### ISSUE TITLE
请问你的项目可以实现在android端实现rtsp转rtmp吗

### ISSUE THREAD

**Issue by guoqinbo1218g** [xiongziliang/ZLMediaKit#1]
你好，看你项目写的可以实现rtsp转rtmp，且用个android，请问你的项目可以实现在android端实现rtsp转rtmp吗？

**Comment by xiongziliang** [comment]
可以的 有android编译脚本

**Comment by xiongziliang** [comment]
有什么问题可以直接在群里面问我

**Comment by guoqinbo1218g** [comment]
好的，多谢

**Comment by guoqinbo1218g** [comment]
以前尝试过，参考的https://github.com/jinlong0813/EasyRTMP_RTSP
不过收费的。

夏楚 <notifications@github.com> 于 2018年6月21日周四 15:51写道：

**Comment by xiongziliang** [comment]
rtsp 转rtmp [test_rtmpPusher.cpp](https://github.com/xiongziliang/ZLMediaKit/blob/master/tests/test_rtmpPusher.cpp);这个还是拉流rtsp/rtmp后再以rtmp方式推流;

还可以参考[test_server.cpp](https://github.com/xiongziliang/ZLMediaKit/blob/master/tests/test_server.cpp)；这个是拉流rtsp/rtmp后再转换成rtsp/rtmp/hls/http-flv直播；

编译android工程也是比较简单的,如果你要实例工程 我可以发给你

**Comment by guoqinbo1218g** [comment]
谢谢，之前那个项目后来不做了，如果以后需要再联系您，多谢

夏楚 <notifications@github.com> 于 2018年6月22日周五 14:48写道：

**Comment by microsoftBoy** [comment]
请问  想再Android端实现拉流rtsp/rtmp后再以rtmp方式推流，这个有demo可以参考吗，库上的Android项目编译出来只是做了一个rtmp的播放
