### ISSUE TITLE
请问有遇到过如下复位场景吗？

### ISSUE THREAD

**Issue by neuskb** [xiongziliang/ZLMediaKit#103]
core 如下：
Core was generated by `./rtspPusher rtsp://10.11.173.132:554/videos264/subway4.264 rtmp://127.0.0.1/Ne'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000007fcd88 in toolkit::MutexWrapper<std::recursive_mutex>::lock() ()
[Current thread is 1 (Thread 0x7f777ff1e0 (LWP 13653))]
(gdb) bt
#0  0x00000000007fcd88 in toolkit::MutexWrapper<std::recursive_mutex>::lock() ()
#1  0x00000000007fb6a0 in std::lock_guard<toolkit::MutexWrapper<std::recursive_mutex> >::lock_guard(toolkit::MutexWrapper<std::recursive_mutex>&) ()
#2  0x00000000007f2844 in toolkit::Socket::setSendPeerAddr(sockaddr const*) ()
#3  0x00000000007685fc in mediakit::RtspPlayer::handleResSETUP(mediakit::Parser const&, unsigned int) ()
#4  0x000000000076ffa4 in void std::_Mem_fn_base<void (mediakit::RtspPlayer::*)(mediakit::Parser const&, unsigned int), true>::operator()<mediakit::Parser const&, unsigned int&, void>(mediakit::RtspPlayer*, mediakit::Parser const&, unsigned int&) const ()
#5  0x000000000076fbe0 in void std::_Bind<std::_Mem_fn<void (mediakit::RtspPlayer::*)(mediakit::Parser const&, unsigned int)> (mediakit::RtspPlayer*, std::_Placeholder<1>, unsigned int)>::__call<void, mediakit::Parser const&, 0ul, 1ul, 2ul>(std::tuple<mediakit::Parser const&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) ()
#6  0x000000000076f678 in void std::_Bind<std::_Mem_fn<void (mediakit::RtspPlayer::*)(mediakit::Parser const&, unsigned int)> (mediakit::RtspPlayer*, std::_Placeholder<1>, unsigned int)>::operator()<mediakit::Parser const&, void>(mediakit::Parser const&) ()
#7  0x000000000076f09c in std::_Function_handler<void (mediakit::Parser const&), std::_Bind<std::_Mem_fn<void (mediakit::RtspPlayer::*)(mediakit::Parser const&, unsigned int)> (mediakit::RtspPlayer*, std::_Placeholder<1>, unsigned int)> >::_M_invoke(std::_Any_data const&, mediakit::Parser const&) ()
#8  0x0000000000750800 in std::function<void (mediakit::Parser const&)>::operator()(mediakit::Parser const&) const ()
#9  0x0000000000769748 in mediakit::RtspPlayer::onWholeRtspPacket(mediakit::Parser&) ()
#10 0x000000000075dc5c in mediakit::RtspSplitter::onRecvContent(char const*, unsigned long) ()
#11 0x0000000000700858 in mediakit::HttpRequestSplitter::input(char const*, unsigned long) ()
#12 0x00000000007668ac in mediakit::RtspPlayer::onRecv(std::shared_ptr<toolkit::Buffer> const&) ()
#13 0x000000000080226c in toolkit::TcpClient::onSockRecv(std::shared_ptr<toolkit::Buffer> const&) ()
#14 0x0000000000801e2c in toolkit::TcpClient::onSockConnect(toolkit::SockException const&)::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*)#3}::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*) const ()
#15 0x0000000000802c18 in std::_Function_handler<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*), toolkit::TcpClient::onSockConnect(toolkit::SockException const&)::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*)#3}>::_M_invoke(std::_Any_data const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*&&) ()
#16 0x00000000007fb7b0 in std::function<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*)>::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*) const ()
#17 0x00000000007f03fc in toolkit::Socket::onRead(std::shared_ptr<toolkit::SockFD> const&, bool) ()
#18 0x00000000007efc00 in toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}::operator()(int) const ()
#19 0x00000000007f5b58 in std::_Function_handler<void (int), toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#20 0x000000000080e370 in std::function<void (int)>::operator()(int) const ()
#21 0x0000000000809968 in toolkit::EventPoller::runLoop(bool) ()
#22 0x00000000008164a8 in void std::_Mem_fn_base<void (toolkit::EventPoller::*)(bool), true>::operator()<bool, void>(toolkit::EventPoller*, bool&&) const ()
#23 0x0000000000816408 in void std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool)> (toolkit::EventPoller*, bool)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
#24 0x0000000000816218 in std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool)> (toolkit::EventPoller*, bool)>::operator()() ()
#25 0x00000000008160d4 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool)> (toolkit::EventPoller*, bool)> >::_M_run() ()
#26 0x0000007f7d346280 in ?? () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#27 0x0000007f7d423fc4 in start_thread (arg=0x7f7d346260) at pthread_create.c:335
#28 0x0000007f7d1ec2e0 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

**Comment by xiongziliang** [comment]
这个错误非常诡异，定位的代码如下：
![image](https://user-images.githubusercontent.com/11495632/66444713-dc9fa000-ea76-11e9-9042-5d1aa0d93c0e.png)

从core提示来看，应该是rtp或rtcp socket对象为空，但是从这里的代码分析，不可能为空的，你是不是在其他线程也在操作该RtspPlayer对象？

**Comment by neuskb** [comment]
我用的就是test_push的那个示例，直接给test_push起了个进程，应该没有其他线程操作，new socket的时候默认不是有锁的吗？即便并发访问 应该也没问题吧。

**Comment by neuskb** [comment]
今天又看了下，test_push用的是tcp的方式，但是代码竟然走到udp的地方了，就是如上你圈红框的应该是udp的流程吧

**Comment by xiongziliang** [comment]
嗯 是的 可能设备不支持tcp方式 但是我代码截图中 socket也不肯为空啊

**Comment by neuskb** [comment]
噢  我用的老版本，可能真的是socket为空。我看修改记录 当时做了这个保护
![image](https://user-images.githubusercontent.com/55521963/66564211-0c8f9600-eb92-11e9-9d79-9e866ff336ee.png)

**Comment by neuskb** [comment]
嗯 大致清楚了，rtsppush默认走tcp，但是发完setup后，收到相机的200ok中只支持udp，所以老代码中未创建socket，所以空指针访问就复位，新代码里加了上面的保护。

**Comment by xiongziliang** [comment]
是的 我之前也遇到这个问题 所以修复了
