### ISSUE TITLE
播放延时

### ISSUE THREAD

**Issue by xiongziliang** [xiongziliang/ZLMediaKit#105]
此issue专门用于交流代码相关的问题

**Comment by Sidamor** [comment]
rtsp转rtmp推流播放，延迟较高。  请问有优化的方法吗？ 针对实时性要求较高的转码场景。

**Comment by Sidamor** [comment]
> 延时主要是体现在播放器，服务器本身延时很低(不会超过500毫秒)。
> 你直观的延时体验是播放器给你的错觉，你可以使用低延时播放器测试延时。
> 请使用ZLMediaKit提供的播放器（test_player）测试.

使用了test_pusher推送到nginx-rtmp的流媒体服务器，延迟很高。 会不会nginx-rtmp本身性能上的问题？   因为用你们的test_server确实延迟很低。

**Comment by xiongziliang** [comment]
你最好使用test_player播放测试延时，你所说的延时说实话我并不敢相信，很多人拿VLC测直观延时是极其错误的。

**Comment by xiongziliang** [comment]
ZLMediaKit提供一整套推拉流、服务器、播放器工具，基于ZLMediaKit可以实现极低的延时、秒开等极致体验，对比SRS、NGINX体验更好。
