### ISSUE TITLE
MediaServer可以开启录像吗？怎么开启？

### ISSUE THREAD

**Issue by Sidamor** [xiongziliang/ZLMediaKit#107]
看到代码注释中写了 
//录像地址为(当然vlc不支持这么多级的rtmp url，可以用test_player测试rtmp点播):
        //http://127.0.0.1/record/live/0/2017-04-11/11-09-38.mp4
        //rtsp://127.0.0.1/record/live/0/2017-04-11/11-09-38.mp4
        //rtmp://127.0.0.1/record/live/0/2017-04-11/11-09-38.mp4

请问可以像注释中一样，开启相应的录像功能吗？

**Comment by xiongziliang** [comment]
你是拉流录像还是推流录像？

**Comment by Sidamor** [comment]
PlayerProxy 拉流的录像

**Comment by xiongziliang** [comment]
http api有参数控制，请查看[wiki](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API)
