### ISSUE TITLE
ffmpeg拉流代理失败

### ISSUE THREAD

**Issue by aiweed** [xiongziliang/ZLMediaKit#108]
curl "http://127.0.0.1/index/api/addFFmpegSource?src_url=rtsp%3a%2f%2fadmin%3aadmin%40192.168.1.82%3a554%2fcam%2frealmonitor%3fchannel%3d1%26subtype%3d0%26unicast%3dtrue%26proto%3dOnvif&dst_url=rtmp%3a%2f%2f127.0.0.1%3a1935%2flive%2faaabbb&timeout_ms=10000"

MediaServer(891) /opt/zlkmedia/ZLMediaKit/server/FFmpegSource.cpp 68
2019-10-12 16:31:07.329 I | play  -i rtsp://admin:admin@192.168.1.82:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif -vcodec copy -an -f flv -y rtmp://127.0.0.1:1935/live/aaabbb
MediaServer(891) /opt/zlkmedia/ZLMediaKit/server/Process.cpp 153
2019-10-12 16:31:17.329 I | wait process terminated, pid=22033, exit code=255
MediaServer(891) /opt/zlkmedia/ZLMediaKit/server/WebApi.cpp 189
2019-10-12 16:31:17.330 D | operator() 
# request:
GET /index/api/addFFmpegSource?src_url=rtsp%3a%2f%2fadmin%3aadmin%40192.168.1.82%3a554%2fcam%2frealmonitor%3fchannel%3d1%26subtype%3d0%26unicast%3dtrue%26proto%3dOnvif&dst_url=rtmp%3a%2f%2f127.0.0.1%3a1935%2flive%2faaabbb&timeout_ms=10000
# content:

# args:
dst_url : rtmp://127.0.0.1:1935/live/aaabbb
src_url : rtsp://admin:admin@192.168.1.82:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
timeout_ms : 10000
# response:
{
   "code" : -1,
   "msg" : "ffmpeg已经退出,exit code = 255"
}

MediaServer(891) /opt/zlkmedia/ZLMediaKit/server/FFmpegSource.cpp 52
2019-10-12 16:31:17.330 D | ~FFmpegSource 
MediaServer(891) /opt/zlkmedia/ZLMediaKit/server/Process.cpp 117
2019-10-12 16:31:17.330 W | kill kill process 22033 falied,err:no such process
MediaServer(891) /opt/zlkmedia/ZLMediaKit/src/Http/HttpSession.cpp 175
2019-10-12 16:31:17.331 W | onError 0x7fa8700015e0(127.0.0.1:51600) end of file
MediaServer(891) /opt/zlkmedia/ZLMediaKit/src/Http/HttpSession.cpp 115
2019-10-12 16:31:17.331 T | ~HttpSession 0x7fa8700015e0(127.0.0.1:51600)

**Comment by xiongziliang** [comment]
这个问题可以看看FFmpeg的日志
FFmpeg日志默认打开：
```ini
[ffmpeg]
#FFmpeg可执行程序路径
bin=/usr/local/bin/ffmpeg
#FFmpeg拉流再推流的命令模板，通过该模板可以设置再编码的一些参数
cmd=%s -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
#FFmpeg日志的路径，如果置空则不生成FFmpeg日志
log=/Users/xzl/git/ZLMediaKit/release/mac/Release/ffmpeg/ffmpeg.log
```

**Comment by aiweed** [comment]
ffpeg 日志
#### pid=15684,cmd= -i rtsp://admin:admin@192.168.1.82:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif -vcodec copy -an -f flv -y rtmp://127.0.0.1:1935/live/aaabbb #####
fork process failed, errno=2(No such file or directory

但是用手动推流正确
root@A9300:/opt/zlkmedia/ZLMediaKit/release/linux/Debug/ffmpeg# /usr/local/bin/ffmpeg -i "rtsp://admin:admin@192.168.1.82:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif" -vcodec copy -an -f flv -y "rtmp://127.0.0.1:1935/live/aaabbb"
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, rtsp, from 'rtsp://admin:admin@192.168.1.82:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.360000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Data: none
[flv @ 0xc4eaa0] Codec for stream 0 does not use global headers but container format requires global headers
Output #0, flv, to 'rtmp://127.0.0.1:1935/live/aaabbb':
  Metadata:
    title           : Media Server
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuvj420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn, 90k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[flv @ 0xc4eaa0] Non-monotonous DTS in output stream 0:0; previous: 0, current: -200; changing to 0. This may result in incorrect timestamps in the output file.
[flv @ 0xc4eaa0] Non-monotonous DTS in output stream 0:0; previous: 0, current: -160; changing to 0. This may result in incorrect timestamps in the output file.
[flv @ 0xc4eaa0] Non-monotonous DTS in output stream 0:0; previous: 0, current: -120; changing to 0. This may result in incorrect timestamps in the output file.
[flv @ 0xc4eaa0] Non-monotonous DTS in output stream 0:0; previous: 0, current: -80; changing to 0. This may result in incorrect timestamps in the output file.
[flv @ 0xc4eaa0] Non-monotonous DTS in output stream 0:0; previous: 0, current: -40; changing to 0. This may result in incorrect timestamps in the output file.

**Comment by xiongziliang** [comment]
从日志中应该可以看出是配置文件指定的FFmpeg可执行文件路径不对，你看看配置文件`config.ini`中ffmpeg.bin选项是多少

**Comment by aiweed** [comment]
rtmp://127.0.0.1:1935/live/aaabbb 用VLC播放这个地址不成功

服务端的日志
> MediaServer(28230) /opt/zlkmedia/ZLMediaKit/src/Rtmp/RtmpSession.cpp 35
2019-10-12 17:42:33.737 D | RtmpSession 0x7f55bc0017b0(192.168.1.105:59427) 
MediaServer(28230) /opt/zlkmedia/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp 378
2019-10-12 17:42:33.738 W | handle_C1_complex try rtmp complex schema0 failed:digest mismatched
MediaServer(28230) /opt/zlkmedia/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp 431
2019-10-12 17:42:33.738 I | check_C1_Digest check rtmp complex handshark success!
MediaServer(28230) /opt/zlkmedia/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp 392
2019-10-12 17:42:33.738 I | handle_C1_complex schema1
MediaServer(28230) /opt/zlkmedia/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp 703
2019-10-12 17:42:33.779 T | handle_rtmpChunk MSG_WIN_SIZE:5000000
MediaServer(28230) /opt/zlkmedia/ZLMediaKit/src/Rtmp/RtmpSession.cpp 454
2019-10-12 17:42:33.779 T | onProcessCmd 0x7f55bc0017b0(192.168.1.105:59427) can not support cmd:_checkbw
MediaServer(28230) /opt/zlkmedia/ZLMediaKit/src/Rtmp/RtmpSession.cpp 454
2019-10-12 17:42:33.819 T | onProcessCmd 0x7f55bc0017b0(192.168.1.105:59427) can not support cmd:getStreamLength
不支持VLC播放吗？

**Comment by xiongziliang** [comment]
为什么说不支持呢?
不出画面吗？
你解决FFmpeg拉流的问题了吗？什么原因？

**Comment by aiweed** [comment]
谢谢，拉流问题应该是已经正常了
root@A9300:/opt/zlkmedia/ZLMediaKit/release/linux/Debug# curl "http://127.0.0.1/index/api/addFFmpegSource?src_url=rtsp%3a%2f%2fadmin%3aadmin%40192.168.1.82%3a554%2fcam%2frealmonitor%3fchannel%3d1%26subtype%3d0%26unicast%3dtrue%26proto%3dOnvif&dst_url=rtmp%3a%2f%2f127.0.0.1%3a1935%2flive%2faaabbb&timeout_ms=10000"
{
   "code" : 0,
   "data" : {
      "key" : "c79d42c540d8ba12b2e17b0248ca4db5"
   }
}
vlc 播放是报错
您的输入无法被打开:
VLC 无法打开 MRL「rtmp://192.168.1.152:1935/live/aaabbb」。详情请检查日志。

**Comment by xiongziliang** [comment]
MediaServer默认在无人观看10秒后会移除拉流代理 ，所以你要在10秒内打开VLC播放。

请务必详细观察MediaServer的日志

**Comment by aiweed** [comment]
谢谢，可以了
