### ISSUE TITLE
辅码拉取解析错误

### ISSUE THREAD

**Issue by tqcenglish** [xiongziliang/ZLMediaKit#109]
dahua 摄像头通过 rtsp url 添加 ?subtype=0 获取辅码，但是getSystemDomainIP 解析识别
```
test_pusher_new(15400) /home/pi/ZLMediaKit/3rdpart/ZLToolKit/src/Network/sockutil.cpp 213
2019-10-12 09:25:38.955 W | getSystemDomainIP 域名解析失败:192.168.11.65?subtype=0
```

**Comment by xiongziliang** [comment]
你的rtsp url是多少？

**Comment by tqcenglish** [comment]
rtsp://admin:admin@192.168.11.65 大华设备

**Comment by xiongziliang** [comment]
你要提供完整的url，看日志应该是url解析异常导致的

**Comment by tqcenglish** [comment]
ZLToolKit/src/Network/sockutil.cpp 213 行得到的 host 格式为 **ip?subtype=0**， 我再看看其他的设备

**Comment by thaibienbac** [comment]
Full rtsp url of Dahua IP camera is:
rtsp://admin:admin@192.168.11.65/cam/realmonitor?channel=1&subtype=0

**Comment by xiongziliang** [comment]
> ZLToolKit/src/Network/sockutil.cpp 213 行得到的 host 格式为 **ip?subtype=0**， 我再看看其他的设备

你的url是不是这种？rtsp://admin:admin@192.168.11.65?channel=1&subtype=0
