### ISSUE TITLE
test_rtmpPusher如何只推视频，不推音频

### ISSUE THREAD

**Issue by airx** [xiongziliang/ZLMediaKit#11]
使用方法：
test_rtmpPusher.cpp，拉流rtsp，转成rtmp推出去：domain(rtsp_url, rtmp_url);
问题：
如何只推视频，不要音频呢？

**Comment by xiongziliang** [comment]
你可以修改[PlayerProxy.cpp](https://github.com/xiongziliang/ZLMediaKit/blob/master/src/Device/PlayerProxy.cpp)代码；注释掉setOnAudioCB相关代码；然后注释掉makeMuteAudio代码；随后注释掉PlayerProxy::initMedia中initAudio相关代码。
其实你没必要屏蔽音频功能，ZLMediaKit在拉流时如果发现是纯视频流，那么会加上静音的音频流；因为包括FFmpeg在内的播放器在打开纯音频流的rtmp(可能不限于rtmp)时会延迟几秒(最差情况有10秒)没有画面；所以我不建议你去掉音频
