### ISSUE TITLE
rtsp推流rtmp转发卡顿

### ISSUE THREAD

**Issue by neuskb** [xiongziliang/ZLMediaKit#110]
linux下，直接用test_push 和 test_server 这两个可执行文件
服务器和相机都在局域网内，
然后用vlc rtsp到test_server取流，播放一点都不卡顿，而且时延很小

但是用vlc rtmp到test_serve取流，播放就会卡顿，而且有时延，卡顿还挺频繁的。

这种有遇到过吗？

**Comment by xiongziliang** [comment]
采用的是什么推流方式？rtsp还是rtmp？
拉的源流是什么流？
代码什么版本的？

**Comment by xiongziliang** [comment]
rtsp推流和rtmp推流默认打开了时间戳覆盖，也就是ZLMediaKit在接收推流时会自动根据接收时间生成一个较平滑的时间戳。
你可以在配置文件中关闭该特性，配置文件选项分别是：
`rtsp.modifyStamp`、`rtmp.modifyStamp`

**Comment by neuskb** [comment]
使用test_push 先通过rtsp拉取相机流，源流是真实相机的流，然后推流也是rtsp，

发给test_server后，用vlc再通过rtmp或者rtsp取流。

**Comment by neuskb** [comment]
好的 我先试下

**Comment by xiongziliang** [comment]
还有 rtsp/rtmp拉流，如果没有音频，会默认添加静音音频，这个也可能会有一定的影响。
最新的代码加了一个配置选项，叫`general.addMuteAudio`,你置0试试。

**Comment by neuskb** [comment]
测试了下 vlc用rtmp方式  拉去server的流 还是卡顿
是不是推流改成rtmp？

**Comment by xiongziliang** [comment]
最新代码已经修改该bug

**Comment by neuskb** [comment]
嗯呢 测试了下  不卡顿了，多谢~
