### ISSUE TITLE
HTTP HLS does not auto stop on VLC

### ISSUE THREAD

**Issue by thaibienbac** [xiongziliang/ZLMediaKit#111]
Hi,

I am using VLC to play HLS stream proxy by MediaServer.
"http://127.0.0.1:10248/proxy/cam111/hls.m3u8"
it's work fine but when close MediaServer, video on VLC does not auto stop (as RTMP or RTSP stream) and in log file i found a error: "onError 013232A8(127.0.0.1:4381) read file eof"
How to avoid this?
[2019-10-13.log](https://github.com/xiongziliang/ZLMediaKit/files/3721860/2019-10-13.log)

**Comment by xiongziliang** [comment]
The log `onError 013232A8(127.0.0.1:4381) read file eof` means that ,the http server had sent file completed, and then disconnect from the player.

When you close MediaServer, VLC have a few seconds of caching, and it will continue to play.

**Comment by thaibienbac** [comment]
The log "onError 013232A8(127.0.0.1:4381) read file eof" occurs while MediaServer and VLC are running.
after close MediaServer (VLC not close) and open MediaServer again, the error still continue although VLC does not play (freeze frame when MediaServer closed).

**Comment by xiongziliang** [comment]
> The log "onError 013232A8(127.0.0.1:4381) read file eof" occurs while MediaServer and VLC are running.
> after close MediaServer (VLC not close) and open MediaServer again, the error still continue although VLC does not play (freeze frame when MediaServer closed).

This is ok, when you close MediaServer,the hls segment file will be removed, then vlc will try download it always。

**Comment by thaibienbac** [comment]
Thanks
