### ISSUE TITLE
关闭时间戳重写，Flash播放rtmp推流卡住

### ISSUE THREAD

**Issue by neuskb** [xiongziliang/ZLMediaKit#113]
推流方式 rtsp 和 rtmp 都尝试过

刷新下网页 就会更新下，不刷新 就一直卡在第一帧的画面上。

**Comment by xiongziliang** [comment]
请更新最新代码，推荐采用rtmp推流方式。
rtmp推流默认覆盖时间戳，经过本人测试在flash中可以流畅播放。

你可以采用我提供的这个[播放器](https://github.com/xiongziliang/ZLMediaKit/files/3723265/rtmp_sample_player_adobe.zip)测试。

**Comment by neuskb** [comment]
嗯呢 升级最新版本后  flash播放流畅
