### ISSUE TITLE
怎么在flv.js中降低http-flv/websocket-flv直播延时？

### ISSUE THREAD

**Issue by Sidamor** [xiongziliang/ZLMediaKit#114]
拉流之后，测试用播放器播放rtmp，基本达到500ms以内延迟。

但是，在网页上播放（chome无插件），延迟比较高，5s左右。

这个有办法优化吗？

网页播放当前采用的videojs&videojs-flash

**Comment by xiongziliang** [comment]
无插件播放推荐http-flv,websocket-flv直播协议，
播放器可以采用bilibili的flv.js。
可以这样控制直播延时：
![image](https://user-images.githubusercontent.com/11495632/66733293-a5275e00-ee91-11e9-9b05-bf47d2917af1.png)
经反复测试，flv延迟500毫秒内，有时候甚至同步
