### ISSUE TITLE
请问一下ZLMediaKit支持rtmp_H265推流？

### ISSUE THREAD

**Issue by bigbao9494** [xiongziliang/ZLMediaKit#117]

**Comment by xiongziliang** [comment]
抱歉 由于rtmp本身不支持265，国内对这个的支持都不是非标准的，vlc ，ffmpeg，浏览器都不支持。你可以推265的rtmp流给zlmediakit,zlmediakit也rtmp可以转发.只是不能转换成其他协议而已。

**Comment by bigbao9494** [comment]
推265的rtmp流给zlmediakit,zlmediakit也可以rtmp转发
我使用VLC播放zlmediakit转发的RTMP流，能播放？

**Comment by xiongziliang** [comment]
vlc、FFmpeg肯定不行啊，又不是标准全球通用的，只是国内对rtmp的扩展，并未收到世界的广泛认可。要播放265的rtmp，只能自研播放器，而且rtmp协议还要自己实现、解码也要自己实现。
