### ISSUE TITLE
hls支持265的问题

### ISSUE THREAD

**Issue by SherDick** [xiongziliang/ZLMediaKit#118]
我现在通过ffmpeg将一个265编码的mkv视频推到了rtsp服务器上，并且通过该项目的测试代码test_server.cpp将rtsp转成了hls，并且该hls可以成功播放（这里感谢大佬的贡献，很好用），在本地生成了对应的m3u8文件和ts文件。问题是，[苹果官方的](https://developer.apple.com/streaming/examples/)说法是hls的hevc/h265必须使用fmp4容器，我就不太明白，这里使用ts做容器，为什么也可以播放，难道这个要求不是硬性的吗？我是用vlc播的。请问项目里hls的容器可以换成fmp4吗？

**Comment by xiongziliang** [comment]
目前ZLMediaKit还不支持fmp4的hls，我也没试过 ios是否支持H265 ts的hls，不过能确定是，VLC是支持的

**Comment by SherDick** [comment]
谢谢大佬
