### ISSUE TITLE
hls文件生成

### ISSUE THREAD

**Issue by bestneymarjr** [xiongziliang/ZLMediaKit#119]
我有264/265的视频数据和音频数据，怎么通过ZLMediaKit生成相应的ts文件和m3u8文件。

**Comment by xiongziliang** [comment]
请使用[DevChannel](https://github.com/xiongziliang/ZLMediaKit/blob/master/src/Common/Device.h)接口

**Comment by bestneymarjr** [comment]
这个接口里面只有264的描述，支持265吗？

**Comment by xiongziliang** [comment]
> 这个接口里面只有264的描述，支持265吗？

这个接口虽然不支持H265,但是你如果仔细看下这个类的代码，要支持H265也很容易。
 我本来推荐大家用DevChannel的基类：MultiMediaSourceMuxer
但是发现很多人不会用，所以才推荐用DevChannel。

**Comment by xiongziliang** [comment]
我刚刚添加了H265的接口，你看下。
使用initH265Video初始化，并且inputH265输入数据

**Comment by bestneymarjr** [comment]
谢谢啦，想大佬学习。
