### ISSUE TITLE
你好，WINDOWS下有哪些依赖第三方库

### ISSUE THREAD

**Issue by gergul** [xiongziliang/ZLMediaKit#12]
感谢开源，请问有哪些依赖的第三方库呢？

**Comment by xiongziliang** [comment]
ZLToolKit可选依赖openssl、mysqlclient；但是都是非必须；
ZLMediaKit可选依赖mp4v2,openssl,x264,faac,也是非必须；
ZLMediaKit的测试程序`test_player`依赖sdl2，ffmpeg;如果没安装的话将忽略编译
以上依赖项在cmake构建时会自动检测；如果没有安装，相应特性将关闭；主体功能都是可以使用的。
需要指出的是，ZLMediaKit的rtmp服务器功能在不依赖openssl时将导致flash player播放失败(vlc可以正常播放，因为flash player使用的是rtmp复杂握手)

上述第三方依赖项你都可以不安装，ZLMediaKit的绝大部分功能都是都可以使用的

**Comment by gergul** [comment]
好的，感谢。
