### ISSUE TITLE
问题咨询：RTP Server如何启动并且进行测试

### ISSUE THREAD

**Issue by leaflower** [xiongziliang/ZLMediaKit#120]
大佬你好，我目前在实践一个VoIP的应用场景，由信令和流传输组成，其中流媒体传输使用的是RTP/RTCP协议，我准备用ZLMediaKit实现流媒体这块，也即VoIP设备会向ZLMediaKit进行RTP/RTCP的推流。
我的问题如下：
1，目前我只看到了RTMP和RTSP侦听的端口，但是没有看到RTP服务的启动，请问项目中包含RTP Server吗？如何启动？
2，如果支持的话，请问如何配置RTP是使用UDP还是TCP？
3，如果支持的话，如果要把RTP的流在服务端存储为ts文件，应该如何配置？

谢谢。

**Comment by xiongziliang** [comment]
rtp严格来说并不能作为单独的一种服务，它必须寄生在其他控制信令服务之下，譬如rtsp、sip等。
所以自然的ZLMediaKit也不会有所谓的rtp服务，ZLMediaKit提供rtsp服务器，流媒体的传输通过rtp实现，但是rtp端口以及必要的信息协商都是通过rtsp协议实现的。

我并不建议你用ZLMediaKit来实现你的VOIP应用，这两者是完全不一样的东西，
如果你要实践voip服务，那么有两种方式：
- 私有协议
- sip、webrtc之类的协议。

voip这种应用对延时很敏感，要踩很多坑，不过大体总结的经验有：

-  不要用TCP，你可以采用kcp、srt、quic这种可靠udp协议。
- 不要用AAC，aac的编码延时很高，对丢包也很敏感，不适合VOIP，建议用自动fec的编码格式，批量opus。
- 如果是私有协议，不要用恶心的RTP格式，纯粹是浪费时间，我始终认为，分包应该是可靠传输协议的事情，不应该放在应用层做，我们用kcp、srt就够了。

- 回声消除是个大问题，就算你用webrtc的库，也很难完全消除，而且double talk情况下会丢声音。


我的这些建议已经很全面了，希望对你有用。

**Comment by leaflower** [comment]
多谢大佬的解释！受益良多。不过我要做的场景没那么复杂。。。
我的应用场景只是像VoIP，但却很简单的，前期只需要将门禁上的语音/摄像头设备接到服务器上。我之前的实践过程如下：
1，（因为很早之前我用SIP做过一些东西），因此我选择用SIP做信令控制；
2，当某个时刻，服务端向门禁设备发送SIP命令，请求门禁设备将语音视频流以RTP/RTCP协议推送到我的服务上（SIP命令会告诉门禁设备所有相关的地址、媒体格式等信息）；
3，服务端收RTP流，我从网上找了个简单的hello world级的程序实践后可以存成ps文件；
4，这个时候我发现了ZLMediaKit项目，觉得使用这个项目来接收RTP流，要有价值的多：用的人多、性能、各种格式转换、客户端播放等，并且可以省很多时间；
5，因此我就开始尝试这个项目，于是提出了刚开始的问题；
-------------------------
因此，基于目前的需求，我不担心上述任何延时、可靠性方面的问题。
所以想再次请教下，如果只是想用ZLMediaKit实现上述第三步中的接收RTP/RTCP流，存成PS文件，或者转成hls/http-flv流让浏览器可以播放，那么我应该在ZLMediaKit项目中的哪个类开始进行修改呢？或者有个大概的修改思路就行。
多谢！

**Comment by xiongziliang** [comment]
你其实可以让设备用rtsp推流的方式推上来，ZLMediaKit支持推流服务器和客户端。
代码在RtspSession.cpp这个文件中。
建议你还是用rtsp推流，可以省去很多事。

**Comment by leaflower** [comment]
多谢你的建议。只是当初觉得SIP已经是信令控制了，所以传输就是裸的RTP了，不再加RTSP控制。目前方案已经定了，我现在只能硬着头皮做RTP接收了。。。

**Comment by xiongziliang** [comment]
你不沿用RTSP那套东西 你后面转其他协议也得自己搞了

**Comment by leaflower** [comment]
谢谢大佬。
我太难了

**Comment by leaflower** [comment]
大佬，抱歉问一句，如果让RTP做到目前RTSP的水平（功能包含推流接入，播放时转其它协议），一个平均水平的developer需要大约多少天可以做到？如果付费做这个，有没有意愿以及价格是多少呢？

**Comment by xiongziliang** [comment]
> 大佬，抱歉问一句，如果让RTP做到目前RTSP的水平（功能包含推流接入，播放时转其它协议），一个平均水平的developer需要大约多少天可以做到？如果付费做这个，有没有意愿以及价格是多少呢？

这个可以发邮件给我哦😂

**Comment by leaflower** [comment]
大佬，已经邮件了哈。需求就是：让RTP做到接近目前RTSP、RTMP的水平（功能包含推流接入，播放时转hls、http-flv，可以存储为ps或mp4文件）。
