### ISSUE TITLE
No automatic connection retry?

### ISSUE THREAD

**Issue by lucaszanella** [xiongziliang/ZLMediaKit#121]
I've been looking at the documentation and looks like there's no way to automaticlly retry RTSP connections. Am I rigth?

**Comment by xiongziliang** [comment]
Yes, if you are using the `MediaPlayer`  or `RtspPlayerImp` interface, it will not retry RTSP connections. 

If you want to automaticlly retry RTSP connections, you can refer the [code](https://github.com/xiongziliang/ZLMediaKit/blob/master/src/Player/PlayerProxy.cpp) of `PlayerProxy`.
