### ISSUE TITLE
播放端到test_server取流后，动态修改相机分辨率，出现花屏不恢复。

### ISSUE THREAD

**Issue by neuskb** [xiongziliang/ZLMediaKit#122]
test_pusher到相机取流 然后通过rtsp推流给test_server
web通过rtmp到server取流播放，
这时候修改相机帧率，播放端直接黑屏，
然后重新取流推流还是一样。

请问大佬 有遇到这种情况吗？

**Comment by neuskb** [comment]
木有问题，是相机问题。

**Comment by xiongziliang** [comment]
重启相机即可
