### ISSUE TITLE
（rtsps/https-flv/https-hls 等）播放一段时间后 ssl 出错

### ISSUE THREAD

**Issue by xiongguangjie** [xiongziliang/ZLMediaKit#125]
commit : ccbd1d4a831433d88c31757067793b1c714c17a2
system: centos7 
gcc: 5.3

应该是ZLToolKit 中的SSLBox出问题了
SSL_Box::onRecv 中 BIO_write 未判断返回值
SSL_Box::flush() 中 SSL_write 判断返回值 只判断了 > 0 ；必须保证 内存都写入了

**Comment by xiongziliang** [comment]
服务器什么异常日志？
onRecv是用于解密数据的，既然作为https-flv服务器，那么后面只发不收，所以这个错误不是onRecv导致的。
应该是 SSL_write 返回错误了

**Comment by xiongguangjie** [comment]
客户端 
rtsp_client(43409) /home/xiong/code/ZLMediaKit/src/Rtsp/RtspPlayer.cpp 756
2019-11-11 15:03:50.286 W | onPlayResult_l 2 recv rtp timeout
rtsp_client(43409) rtsp_client.cpp 114
2019-11-11 15:03:50.286 E | operator() OnShutdown:recv rtp timeout
rtsp_client(43409) /home/xiong/code/ZLMediaKit/src/Rtsp/RtspPlayer.cpp 756
2019-11-11 15:03:50.286 W | onPlayResult_l 5 teardown

服务器端：
2019-11-11 15:03:50.286 W | onError 0x7f35f012d1a0(127.0.0.1:38166) 播放器(__defaultVhost__/live/test)断开:rtsp player send teardown request


测试代码
`#include <signal.h>
#include <unistd.h>
#include <stdio.h>
#include "Util/util.h"
#include "Util/logger.h"
#include <iostream>
#include "Poller/EventPoller.h"
#include "Rtsp/UDPServer.h"
#include "Player/MediaPlayer.h"
#include "Util/onceToken.h"
#include "Network/sockutil.h"


using namespace std;
using namespace toolkit;
using namespace mediakit;


/**
 * 合并一些时间戳相同的frame
 */
class FrameMerger {
public:
    FrameMerger() = default;
    virtual ~FrameMerger() = default;

    void inputFrame(const Frame::Ptr &frame,const function<void(uint32_t dts,uint32_t pts,const Buffer::Ptr &buffer)> &cb){
        if (!_frameCached.empty() && _frameCached.back()->dts() != frame->dts()) {
            Frame::Ptr back = _frameCached.back();
            Buffer::Ptr merged_frame = back;
            if(_frameCached.size() != 1){
                string merged;
                _frameCached.for_each([&](const Frame::Ptr &frame){
                    if(frame->prefixSize()){
                        merged.append(frame->data(),frame->size());
                    } else{
                        merged.append("\x00\x00\x00\x01",4);
                        merged.append(frame->data(),frame->size());
                    }
                });
                merged_frame = std::make_shared<BufferString>(std::move(merged));
            }
            cb(back->dts(),back->pts(),merged_frame);
            _frameCached.clear();
        }
        _frameCached.emplace_back(Frame::getCacheAbleFrame(frame));
    }
private:
    List<Frame::Ptr> _frameCached;
};
int main(int argc, char *argv[]) {


    FILE* fd = NULL;

    static semaphore sem;
    //设置退出信号处理函数
    signal(SIGINT, [](int){
            InfoL << "SIGINT:exit";
            signal(SIGINT, SIG_IGN);// 设置退出信号
            sem.post();});
    //设置日志
    Logger::Instance().add(std::make_shared<ConsoleChannel>());
    Logger::Instance().setWriter(std::make_shared<AsyncLogWriter>());

    if (argc != 4) {
        ErrorL << "\r\n测试方法：./test_player rtxp_url rtp_type out_file\r\n"
               << "例如：./test_player rtsp://admin:123456@127.0.0.1/live/0 0 test.h264\r\n"
               << endl;
        return 0;

    }

    fd = fopen(argv[3],"wb");


    

    MediaPlayer::Ptr player(new MediaPlayer());
    weak_ptr<MediaPlayer> weakPlayer = player;
    player->setOnPlayResult([weakPlayer,&fd](const SockException &ex) {
        InfoL << "OnPlayResult:" << ex.what();
        auto strongPlayer = weakPlayer.lock();
        if (ex || !strongPlayer) {
            return;
        }

        auto viedoTrack = strongPlayer->getTrack(TrackVideo);
        if (!viedoTrack || viedoTrack->getCodecId() != CodecH264) {
            WarnL << "没有视频或者视频不是264编码!";
            return;
        }

        AnyStorage::Ptr storage(new AnyStorage);
        viedoTrack->addDelegate(std::make_shared<FrameWriterInterfaceHelper>([storage,&fd](const Frame::Ptr &frame) {
            EventPollerPool::Instance().getExecutor()->async([frame,storage,&fd]() {
                auto &merger = (*storage)["merger"];
                if(!merger){
                    merger.set<FrameMerger>();
                };

                merger.get<FrameMerger>().inputFrame(frame,[&](uint32_t dts,uint32_t pts,const Buffer::Ptr &buffer){

                    InfoL << "dts = "<<dts<<" pts = "<<pts<<" size = "<<buffer->size();
                    fwrite(buffer->data(),buffer->size(),1,fd);
                });
                return true;
            });
        }));
    });


    player->setOnShutdown([](const SockException &ex) {
        ErrorL << "OnShutdown:" << ex.what();
    });
    (*player)[kRtpType] = atoi(argv[2]);
    player->play(argv[1]);
    sem.wait();
    fclose(fd);
    return 0;
}
`

**Comment by xiongguangjie** [comment]
客户端：
rtsp_client(43409) /home/xiong/code/ZLMediaKit/src/Rtsp/RtspPlayer.cpp 756
2019-11-11 15:03:50.286 W | onPlayResult_l 2 recv rtp timeout
rtsp_client(43409) rtsp_client.cpp 114
2019-11-11 15:03:50.286 E | operator() OnShutdown:recv rtp timeout
rtsp_client(43409) /home/xiong/code/ZLMediaKit/src/Rtsp/RtspPlayer.cpp 756
2019-11-11 15:03:50.286 W | onPlayResult_l 5 teardown
服务器端：
2019-11-11 15:03:50.286 W | onError 0x7f35f012d1a0(127.0.0.1:38166) 播放器(__defaultVhost__/live/test)断开:rtsp player send teardown request

**Comment by xiongguangjie** [comment]
vlc 播放 https-flv 出错（可以出图）
gnutls error: Certificate verification failure: The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected. 
gnutls error: Decryption has failed.
direct3d9 error: SetThumbNailClip failed: 0x800706f4
avcodec info: Using DXVA2 (NVIDIA GeForce GT 720, vendor NVIDIA(10de), device 1288, revision a1) for hardware decoding
gnutls error: The specified session has been invalidated for some reason.
direct3d9 error: SetThumbNailClip failed: 0x800706f4

**Comment by xiongguangjie** [comment]
[rtsp_client.zip](https://github.com/xiongziliang/ZLMediaKit/files/3830036/rtsp_client.zip)
rtsp 客户端测试代码（根据 test_player 修改 保存h264 裸流）

**Comment by xiongguangjie** [comment]
ffplay 播放 rtsps (可以出图） 但是ssl 会报错

[tls @ 0092e680] The specified session has been invalidated for some reason.
    Last message repeated 2 times
[tls @ 0092e680] The specified session has been invalidated for some reason.
    Last message repeated 2 times
[tls @ 0092e680] The specified session has been invalidated for some reason.
    Last message repeated 2 times
[tls @ 0092e680] The specified session has been invalidated for some reason.
    Last message repeated 2 times
[tls @ 0092e680] The specified session has been invalidated for some reason.
    Last message repeated 2 times
[tls @ 0092e680] The fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
 specified session has been invalidated for some reason.
    Last message repeated 2 times
[tls @ 0092e680] The specified session has been invalidated for some reason.
    Last message repeated 2 times
[tls @ 0092e680] The specified session has been invalidated for some reason.
    Last message repeated 11 times

**Comment by xiongguangjie** [comment]
ffplay播放rtsps 时抓的包
[rtsptls.zip](https://github.com/xiongziliang/ZLMediaKit/files/3830100/rtsptls.zip)

**Comment by xiongziliang** [comment]
服务器日志还是不全，你要把这句日志找到：
![image](https://user-images.githubusercontent.com/11495632/68569292-b8c9e280-0498-11ea-9158-5e1fe32e8f38.png)

**Comment by xiongguangjie** [comment]
没有打印这个日志，我认为 SSL_Write 返回 > 0 ，有可能是只把一部分内存加密了

**Comment by xiongguangjie** [comment]
返回值是写入ssl 的大小，不一定表示全部写入了
![图片20191111154014](https://user-images.githubusercontent.com/19631632/68569651-97b5c180-0499-11ea-96a4-43607d271f22.png)

**Comment by xiongziliang** [comment]
你再试试吧

**Comment by xiongguangjie** [comment]
vlc 播放 https-flv 还是有ssl 出错的地方，出现的几率比以前少了
ffplay 播放 rtsps 也会出现错误必现
但是用rtsp_client(上传的测试代码） 本地回环 好像没有问题

**Comment by xiongguangjie** [comment]
服务器没有ssl 出错的日志，与以前一样

**Comment by xiongziliang** [comment]
你有更新zltookit吗？我用ffplay测试了一段时间 本地网路 好像ok



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiongguangjie <notifications@github.com&gt;
发送时间: 2019年11月11日 17:25
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] （rtsps/https-flv/https-hls 等）播放一段时间后 ssl 出错 (#125)

**Comment by xiongguangjie** [comment]
更新了，ffplay 我不是在本地测试的

**Comment by xiongguangjie** [comment]
本地回环 rtsps 还是有问题只是几率比其他情况很少

**Comment by xiongziliang** [comment]
不错意外完全修复了，测试方法：
建议用OBS推流高清视频，用test_player在其他机器播放rtsps，如果全程播放正常，那么应该没问题了

**Comment by xiongguangjie** [comment]
服务器没有任何关于ssl 的错误打印
ZLToolKit 与 ZLMediaKit 都更新了
vlc 播放 https-flv ，播放一段时间后，还是会出问题 （非本地）
ffplay 播放 rtsps 可以出图，但是会出错（非本地）
rtsp_client 本地播放 rtsps 还在测试跑了20 分钟没有问题

**Comment by xiongziliang** [comment]
播放rtsps要指定tcp方式 ，我在局域网不同电脑上用ffplay测试https-flv播放有一段时间是正常的.我在localhost情况下用test_player播放rtsps也正常。


你可以把不能播放情况下的错误提示信息截图出来



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiongguangjie <notifications@github.com&gt;
发送时间: 2019年11月11日 20:11
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] （rtsps/https-flv/https-hls 等）播放一段时间后 ssl 出错 (#125)




服务器没有任何关于ssl 的错误打印
 ZLToolKit 与 ZLMediaKit 都更新了
 vlc 播放 https-flv ，播放一段时间后，还是会出问题 （非本地）
 ffplay 播放 rtsps 可以出图，但是会出错（非本地）
 rtsp_client 本地播放 rtsps 还在测试跑了20 分钟没有问题

**Comment by xiongguangjie** [comment]
![vlc-https-flv](https://user-images.githubusercontent.com/19631632/68586915-b67b7e80-04c0-11ea-84eb-52564387b3ae.png)

这个也是tcp
![rtsps_client](https://user-images.githubusercontent.com/19631632/68586991-e7f44a00-04c0-11ea-8e64-c339d5a054aa.png)

ffmpeg rtsps 默认是tcp
![ffplay_rtsps](https://user-images.githubusercontent.com/19631632/68587032-00fcfb00-04c1-11ea-8056-6c5b14ec9032.png)

**Comment by xiongguangjie** [comment]
vlc 播放了大概 10 多分钟出现
rtsp_client 本地播放 大概 20-30 分钟后出错
ffplay rtsps 播放 马上出现

**Comment by xiongziliang** [comment]
你更新最新代码（包括ZLToolKit的），这个bug修复了。
bug原因是ssl发送缓冲区是复用的，在未发送出去时可能会被后续的数据覆盖，现在已经改成循环池解决这个问题了

**Comment by xiongguangjie** [comment]
谢谢

**Comment by fengmao31** [comment]
recv teardown request

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/188308097-2d41b558-9680-49de-877a-09760dcedd24.png)
In vmware, use two vlc. one is rtsps. It is easy appear. In another pc, it is hard to appear.

**Comment by fengmao31** [comment]
I prepare to check it for more information.
