### ISSUE TITLE
record中拷贝一个MP4点播文件到record目录下 点播无法播放

### ISSUE THREAD

**Issue by zywu31** [xiongziliang/ZLMediaKit#127]
record中拷贝一个MP4点播文件到record目录下 点播无法播放.
让拷贝进去的MP4和录制的MP4都可以点播

或者 额外开放VOD配置 这样点播用户自定义的TS MP4 FLV等等
因为http hls直播都会放到/dev/shm 内存映射目录中 这样性能会提升。。

**Comment by xiongziliang** [comment]
现在hls保存目录和record点播目录其实跟http根目录完全没有关系。

如果你要用ZLMediaKit自带的http服务器完成http-hls/http-mp4点播，
那么，hls根目录或record根目录肯定要在http的根目录内。

这样设计的目的其实是两种完全不同的业务解耦，
你可以用ZLMediaKit实现hls、MP4的录制，
但是却用诸如 NGINX的http服务器。

其实你说白了需要的是不同的http端口访问不同的http根目录，或者不同的http url访问不同的http根目录。这样就要实现一个HTTP GET请求的拦截器，在获取http根目录前拦截并覆盖下。

目前ZLMediaKit并不支持这个机制，但是你的建议我考虑采纳，我计划后面实现这个拦截器功能，请静等佳音！

**Comment by xiongziliang** [comment]
你可以监听kBroadcastHttpBeforeAccess事件，然后拦截修改文件路径。

要通过修改代码的方式实现，配置文件目前不足以支撑这么复杂的配置
