### ISSUE TITLE
 close_stream无法关闭addFFmpegSource,addStreamProxy拉的流及restful统一化易用化建议

### ISSUE THREAD

**Issue by amhoho** [xiongziliang/ZLMediaKit#128]
问题:
close_stream无法关闭addFFmpegSource,addStreamProxy拉的流,返回success后并未实际关闭.

建议目的:
以下建议最终目的,实现大部分接口仅需`schema/vhost/app/stream`这种统一的参数完成.无需出现下查key或id再操作的情况(如delFFmpegSource,delStreamProxy).并且精简接口,易于调用.

建议:
1.medialist的data流数据带上各个流的附加信息如session,来源:push/ffmepg,key/proxy,key[易于统计,观察等]
上面实现后,即可精简接口.如:
2.加流:addStream,如type:push/ffmpeg/proxy,即可完成各类推拉流的添加.
3.删流:仅需closeStream按来源即可关闭相应schema/vhost/app/stream(即无需delFFmpegSource,delStreamProxy).
4.将session归于各流的附加信息即方便统计,又方便操作,如某个stream下推流/播放流所有session.而`kick_session`此可以按统一参数加上 id/peer_id/local_port/tyeid即可方便断开.

from @战国策

**Comment by amhoho** [comment]
再加一个建议
5.各个流加上addTime,然后按addTime排序,MediaList再按这个排序根据页码与单页数量进行分页,否则如果存在很多stream的话一次性给出也是有点鸡肋.
这种分页在管理界面化()接入到直播后台),对直播流进行管理时十分方便.否则上千个stream一次给全也不人性化.

**Comment by xiongziliang** [comment]
close_stream接口确实不能断开FFmpeg拉流代理，这个是个遗漏，我刚才已经修复了，请你验证下！

**Comment by xiongziliang** [comment]
针对你的建议，我一一答复：
- 1、getMediaList接口做不到你要求的功能，因为生成MediaSource的方式五花八门，既不统一，也不能准确获取源头信息。

- 2、添加拉流代理目前包含addFFmpegSource和addStreamProxy两种方式，其中addFFmpegSource也可以推流到其他服务器，所以这个接口不是纯粹的拉流代理接口，他们的参数也完全不一样。所以他们做不到统一，况且这个东西前端做个switch case也很简单，没必要统一。

- 3、现在close_stream/close_streams接口可以关闭所有类型的拉流和推流，能满足你的需求，所以delFFmpegSource和delStreamProxy接口其实没什么用了。

- 4、getAllSession接口提供参数可以筛选出你感兴趣的tcp客户端，配合kick_session接口可以踢除你想要关闭的客户端，现在我新增了kick_sessions批量踢人接口，你可以查看wiki了解详情。

- 5、分页没你想得那么简单，这个不是数据库，也随时是浮动的，光排序都是个难题。

**Comment by xiongziliang** [comment]
你使用ZLMediaKit的restful接口存在误区，误区就是，一切的业务都想由ZLMediaKit的restful接口实现，这显然是不显示的，因为ZLMediaKit不依赖数据库，业务能力是通过web hook和restful api有机结合实现的。

你要实现复杂的业务逻辑，应该在web hook接口中对接你的数据库，把必要的数据更新到数据库，然后你自己查数据库，这才是完全之策。别想着ZLMediaKit什么都帮你解决了，那还要web hook接口干嘛？

**Comment by amhoho** [comment]
@xiongziliang 知道了,多谢指教.
