### ISSUE TITLE
/release/linux/Debug中的test_server录制视频，如何设置每个视频片段长

### ISSUE THREAD

**Issue by woshiwoyali** [xiongziliang/ZLMediaKit#129]
项目 /ZLMediaKit/tests/test_server.cpp 中
//监听rtsp、rtmp源注册或注销事件；此处用于测试rtmp保存为flv录像，保存在http根目录下
        NoticeCenter::Instance().addListener(nullptr, Broadcast::kBroadcastMediaChanged, [](BroadcastMediaChangedArgs) {
            if (schema == RTMP_SCHEMA && app == "live") {
                lock_guard<mutex> lck(s_mtxFlvRecorder);
                std::string strTime = GetNowTime();
                if (bRegist) {
                    std::string strhourmin = GetTime();
                    DebugL << "开始录制RTMP：" << schema << " " << vhost << " " << app << " " << stream;
                    GET_CONFIG(string, http_root, Http::kRootPath);
                    auto path =
                            http_root + "/" + strTime + "/" + biaoqian + "/" + app + "/" + strhourmin + ".flv";
                        FlvRecorder::Ptr recorder(new FlvRecorder);
                    try {
                        recorder->startRecord(EventPollerPool::Instance().getPoller(),
                                              dynamic_pointer_cast<RtmpMediaSource>(sender.shared_from_this()), path);
                        s_mapFlvRecorder[vhost + "/" + app + "/" + stream] = recorder;
                    } catch (std::exception &ex) {
                        WarnL << ex.what();
                    }
                } else {
                    s_mapFlvRecorder.erase(vhost + "/" + app + "/" + stream);
                }
            }
        });

我需要在自定义目录下生成.flv录屏文件，例如每一分钟产生一个文件，配置文件应该在哪里修改呢？

**Comment by woshiwoyali** [comment]
[record]
#mp4录制或mp4点播的应用名，通过限制应用名，可以防止随意点播
#点播的文件必须放置在此文件夹下
appName=record
#mp4录制写文件缓存，单位BYTE,调整参数可以提高文件io性能
fileBufSize=65536
#mp4录制保存、mp4点播根路径
#可以为相对(相对于本可执行程序目录)或绝对路径
filePath=./httpRoot
#mp4录制切片时间，单位秒
fileSecond=60
#mp4点播每次流化数据量，单位毫秒，
#减少该值可以让点播数据发送量更平滑，增大该值则更节省cpu资源
sampleMS=500
#mp4录制完成后是否进行二次关键帧索引写入头部
fastStart=0
#MP4点播(rtsp/rtmp/http-flv/ws-flv)是否循环播放文件
fileRepeat=0

这个适用于flv吗？其中的record应该如何理解呀！
感谢大神解答！

**Comment by xiongziliang** [comment]
不建议采用flv方式实现视频录制，建议采用mp4方式实现视频录制！
现在flv录制在ZLMediaKit是个孤立的功能，现在支持很有限。



> [record]
> #mp4录制或mp4点播的应用名，通过限制应用名，可以防止随意点播
> #点播的文件必须放置在此文件夹下
> appName=record
> #mp4录制写文件缓存，单位BYTE,调整参数可以提高文件io性能
> fileBufSize=65536
> #mp4录制保存、mp4点播根路径
> #可以为相对(相对于本可执行程序目录)或绝对路径
> filePath=./httpRoot
> #mp4录制切片时间，单位秒
> fileSecond=60
> #mp4点播每次流化数据量，单位毫秒，
> #减少该值可以让点播数据发送量更平滑，增大该值则更节省cpu资源
> sampleMS=500
> #mp4录制完成后是否进行二次关键帧索引写入头部
> fastStart=0
> #MP4点播(rtsp/rtmp/http-flv/ws-flv)是否循环播放文件
> fileRepeat=0
> 
> 这个适用于flv吗？其中的record应该如何理解呀！
> 感谢大神解答！

这里描述的mp4文件录制相关的配置

**Comment by woshiwoyali** [comment]
感谢您的回复，在您的项目中 build_for_linux.sh之后，生成的目录为release/linux/Debug 也就是在/ZLMediaKit/tests/test_server.cpp中写的是flv，这个我需要如何修改呢？并且我需要没一分钟生成一个录屏文件，我查看了您的配置文件，其中涉及到了record，但是在我的视频保存路径中，不存在该路径，我尝试修改了一下，Common/config.cpp 设置成60s但是不起作用

**Comment by xiongziliang** [comment]
- 1、请使用MediaServer进程进行完整的测试
- 2、请仔细阅读wiki关于 配置文件相关的文档
- 3、flv目前不建议使用，推荐使用mp4录制功能

**Comment by woshiwoyali** [comment]
您好：
录制的视频路径为：record/live/obs/2019-09-20/15-53-02.mp4
如果我想修改 2019-09-20/15-53-02.mp4 命名，需要修改哪个文件呢？
期待您的回复！
