### ISSUE TITLE
With QT Creator

### ISSUE THREAD

**Issue by manik005** [xiongziliang/ZLMediaKit#13]
Hi,
Thanks for the great package. I would like to use it along with QT. Is it possible to add it to QT creator? If so any idea on how can I add it to QT?

**Comment by xiongziliang** [comment]
Of course you can integrate into QT, and many people have already done so.
CMake seems to be able to directly produce QT projects. You can look up more information on google.

**Comment by manik005** [comment]
ok, thanks for the quick response. Will take a look. But I would like to add this as library to my existing QT application. It would be possible right ? Sorry if the question is silly, just getting started with C++ and QT.

**Comment by xiongziliang** [comment]
Of course, you can use C++ header files directly on non-Windows platforms. It is recommended that you use C interface to encapsulate them on windows platforms.
You can see the c_wrapper folder, which is the encapsulation of the C interface, but this code only adapts to the 2.0 branch. You need to switch to the 2.0 branch to use it.

**Comment by manik005** [comment]
Oh OK. Thanks for the information. Will try it out and let you know, thanks
again.
