### ISSUE TITLE
如果想要实现其他协议代理，要怎么实现

### ISSUE THREAD

**Issue by lixinhan2019** [xiongziliang/ZLMediaKit#131]
现在需要rtsp或rtmp拉流用MediaServer未实现的其他协议推给别人，H264裸流进行PS封装推出去。

**Comment by xiongziliang** [comment]
你可以先提取出H264和AAC，然后剩下的事情就是ps封装推流了。
至于怎么提取H264和AAC,你可以参考这些issue:
#58 
#50 
#46

**Comment by lixinhan2019** [comment]
可能问题问的不太对，你说的这些都已经验证通过可行，我只是想问下想集成到MediaServer中，从什么地方新加一个功能模块，对MediaServer整体框架修改达到最小，尽量不要更改MediaServer原有的其他功能的代码

**Comment by xiongziliang** [comment]
改动确实会比较大，因为这种推给别的服务器，有可能是`拉流再推流`,也可能是`推流再推流`。
所以建议从`MediaSource`对象入手，因为ZLMediaKit里面，`MediaSource`是所有直播流的源头

**Comment by lixinhan2019** [comment]
非常感谢，我先沿着这个方向尝试添加新的GB28181MediaSource，支持协议转发
