### ISSUE TITLE
librtmp推流到mediaserver，flash无法播放问题

### ISSUE THREAD

**Issue by jiuaiwo1314** [xiongziliang/ZLMediaKit#132]
前提：
1.海康264视频流，704*576， 1Mbps 15fps
2.librtmp推到mediaserver
3.windows平台，局域网
4.开启了时间戳覆盖
现象：
1.flash无法播放 ，flash设置了50000ms超时
2.ffplay可以播放，有延迟（ffpaly参数设置问题）
3.使用EasyPlayerPro，基本秒开
4.也尝试了开启和关闭时间戳覆盖，结果一样

**Comment by xiongziliang** [comment]
不出意外是你编译zlmediakit没开启openssl.flash 播放需要采用所谓的复杂握手，而这个需要openssl的支持

**Comment by jiuaiwo1314** [comment]
编译openssl了。 flash 必须要用https://ip:port嘛？

**Comment by xiongziliang** [comment]
不用，启用了openssl并不是用了https，二是完成了rtmp所谓的复杂握手。
你可以把flash播放失败时服务器的日志截图出来并粘贴出来，这样才好分析你到底有没有真的启用openssl。

**Comment by jiuaiwo1314** [comment]
确认了， 我把ssl编译关了，稍后再测试下，给回复

**Comment by jiuaiwo1314** [comment]
@xiongziliang 已解决，是未编译ssl导致的。
