### ISSUE TITLE
addFFmpegSource拉的流在flv/hls均存在卡帧跳帧的情况.

### ISSUE THREAD

**Issue by amhoho** [xiongziliang/ZLMediaKit#133]
拉流方式:
addFFmpegSource

视频源:(该源本身稳定无异常)
http://ali.m.l.cztv.com/channels/lantian/channel01/360p.m3u8

播放情况:
flv:画面卡帧,声音正常.
hls:画面卡帧或跳帧或迅速播放.或音画不同步.

播放工具: 
ffplay,vlc

服务器配置:
4核/8G/5M(仅测试播放专用,无其它在线)

**Comment by xiongziliang** [comment]
请先确保 配置文件中的`rtmp.modifyStamp`选项改成0，目的是关闭rtmp推流的时间戳覆盖功能。

如果还是无效，你可以用FFmpeg推流测试：
```
ffmpeg -i http://ali.m.l.cztv.com/channels/lantian/channel01/360p.m3u8 -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv rtmp://127.0.0.1/live/test
```

如果这样还是卡顿，再试试：
```
ffmpeg -re -i http://ali.m.l.cztv.com/channels/lantian/channel01/360p.m3u8 -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv rtmp://127.0.0.1/live/test
```

加了`-re`后如果有效果，那么配置文件中请把`ffmpeg.cmd`改成如下即可：
```
%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
```

**Comment by xiongziliang** [comment]
经过测试 确实是这个问题
