### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by jiuaiwo1314** [xiongziliang/ZLMediaKit#134]
在浏览器中播放hls存在跨域问题，请问下怎么设置

**Comment by xiongziliang** [comment]
http请求中的http头要设置Origin字段才行。

**Comment by jiuaiwo1314** [comment]
不会考虑从服务端解决此问题吧

**Comment by jiuaiwo1314** [comment]
修改了HttpSession.cpp =>HttpSession::sendResponse
`    if(!_origin.empty()){
        //设置跨域
        headerOut.emplace("Access-Control-Allow-Origin",_origin);
        headerOut.emplace("Access-Control-Allow-Credentials", "true");
	}
	else
	{
		headerOut.emplace("Access-Control-Allow-Origin", "*");
		headerOut.emplace("Access-Control-Allow-Credentials", "true");
	}`

全部允许跨域拉。 
然后httproot下面放了一个crossdomain.xml文件

**Comment by xiongziliang** [comment]
你这样做感觉不是太好 也就说所有请求都能跨域了

**Comment by jiuaiwo1314** [comment]
恩 去掉代码修改了， 改为用 crossdomain.xml了
`<cross-domain-policy>
  <allow-access-from domain="*"/>
</cross-domain-policy>
`
