### ISSUE TITLE
使用MediaServer作为服务器，用ffmpeg推h265流服务器会提示警告

### ISSUE THREAD

**Issue by lippg** [xiongziliang/ZLMediaKit#135]
MediaServer(11448) /home/ZLMediaKit/src/Extension/H265Rtp.cpp 96
2019-11-15 14:16:55.404 W | decodeRtp 不支持该类型的265 RTP包48
MediaServer(11448) /home/ZLMediaKit/src/Common/MediaSource.cpp 157
2019-11-15 14:16:55.404 I | regist rtsp __defaultVhost__ live 
MediaServer(11448) /home/ZLMediaKit/src/Extension/Factory.cpp 209
2019-11-15 14:16:57.405 W | getRtmpCodecByTrack 暂不支持该CodecId:1
MediaServer(11448) /home/ZLMediaKit/src/Common/MediaSource.cpp 246
2019-11-15 14:17:00.405 W | onNoneReader rtsp/__defaultVhost__/live/

请问是服务器不支持吗？

**Comment by xiongziliang** [comment]
### 1、支持任意格式代理转发
ZLMediaKit支持`推流代理转发`、`拉流代理转发`。
因为是纯粹转发，不需要做rtp/rtmp包的解复用，
所以ZLMediaKit支持任意格式的rtmp/rtsp推拉流转发代理。

### 2、支持有限格式的协议转换
ZLMediaKit默认支持rtsp、rtmp的推拉流代理，
同时能转换成rtmp/rtsp/hls/mp4/http-flv/ws-flv协议并转发。
这就意味则，ZLMediaKit要支持rtp/rtmp包的解复用，要转换成H264/H265/AAC等帧数据。
目前转协议支持如下编码：

 |          功能/编码格式           | H264 | H265 | AAC  | other |
 | :------------------------------: | :--: | :--: | :--: | :---: |
 | RTSP[S] --> RTMP/HTTP[S]-FLV/FLV |  Y   |  N   |  Y   |   N   |
 |         RTMP --> RTSP[S]         |  Y   |  N   |  Y   |   N   |
 |         RTSP[S] --> HLS          |  Y   |  Y   |  Y   |   N   |
 |           RTMP --> HLS           |  Y   |  N   |  Y   |   N   |
 |         RTSP[S] --> MP4          |  Y   |  Y   |  Y   |   N   |
 |           RTMP --> MP4           |  Y   |  N   |  Y   |   N   |
 |         MP4 --> RTSP[S]          |  Y   |  N   |  Y   |   N   |
 |           MP4 --> RTMP           |  Y   |  N   |  Y   |   N   |


也就是说，除了rtmp，其他都支持H265、H264、AAC的**协议转换**。

### 3、怎么选择编码格式？

如果你只是推rtsp并且只播放rtsp(不要求rtmp播放)，那么你可以采用H265推流，
如果你要用到rtmp/http-flv/ws-flv播放，建议还是只用264推流。

从你的错误日志可以看出，你应该是用RTSP的方式推流H265,这样的话除了不能转换成RTMP，其他没问题。

**Comment by lippg** [comment]
我只是用RTSP的方式推流H265，功能是可以实现的，感谢您的回复
