### ISSUE TITLE
播放时间稍长后,音画不同步,重新播放也会不同步.

### ISSUE THREAD

**Issue by imfuding** [xiongziliang/ZLMediaKit#136]
我推流工具是obs,系统win7,推流来源是浏览器(播放任意正常音画同步的视频),播放工具为ffplay和vlc,暴风影音(这些工具正常播放其它hls).
在推流给ZLMediaKit后,多次尝试http-flv/http-hls均出现几分钟后音画不同步的情形,断开重新打开也是同样情形.
后来将时间戳覆盖关闭后也是同样多次出现.
我把推流工具改为ffmpeg,视频源是个正常的mp4,也会出现http-flv/http-hls音画不同步.

**Comment by xiongziliang** [comment]
如果你把时间戳覆盖关闭还是不同步，那说明源数据是真的是不同步😂

**Comment by imfuding** [comment]
> 如果你把时间戳覆盖关闭还是不同步，那说明源数据是真的是不同步

感谢回复,确定源是可以保证同步的,因为我用了很多观看过的视频,且还用了摄像头测试过.

**Comment by xiongziliang** [comment]
再不覆盖时间戳的情况下 是纯粹转发的 所以肯定是发送端就失步了。

你可以换个电脑推流，或者用FFmpeg推流测试

**Comment by imfuding** [comment]
> 在不覆盖时间戳的情况下 是纯粹转发的 所以肯定是发送端就失步了。
> 
> 你可以换个电脑推流，或者用FFmpeg推流测试

这个我也想过,我用同事两个电脑也试过,装的最新obs和linux编译的ZLMediaKit,也出现.所以我才觉得很奇怪来提问.出现的时间是播放几分钟或十来分钟后.刚开始都很正常

**Comment by imfuding** [comment]
为方便还原问题,我刚刚又用了蘑菇街的视频源来测试.
obs中添加vlc视频源:https://tliveplay.mogujielive.com/live/359166625_11428209.flv
对比的蘑菇街播放页面:https://h5.mogu.com/live-mona/live.html?roomId=11428209&actorId=1bvodiy&acm=3.ms.0_14_1dlw62.0.80056-98274-98278-68958.7GDRzrHSutrWV.sd_117-xid_26-na_1-t_7GDRzrHSutrWV-xm_1dlw62-cxk_100028-x_1bvodiy-ban_20-dm1_1000&ptp=32.aabyWb.0.0.qY2XZ7E6
播放了5分钟后出现了音画不同步,但蘑菇街播放页面上的音画仍然是同步的.
您试试?

**Comment by xiongziliang** [comment]
你obs推流建议你采集桌面和或扬声器、或者采集mp4文件，或者你用FFmpeg推流。
反正你多试试不同的方式，我不认为ZLMediaKit时间戳处理机制有问题，毕竟我们已经有很多使用案例了。




> 为方便还原问题,我刚刚又用了蘑菇街的视频源来测试.
> obs中添加vlc视频源:https://tliveplay.mogujielive.com/live/359166625_11428209.flv
> 对比的蘑菇街播放页面:https://h5.mogu.com/live-mona/live.html?roomId=11428209&actorId=1bvodiy&acm=3.ms.0_14_1dlw62.0.80056-98274-98278-68958.7GDRzrHSutrWV.sd_117-xid_26-na_1-t_7GDRzrHSutrWV-xm_1dlw62-cxk_100028-x_1bvodiy-ban_20-dm1_1000&ptp=32.aabyWb.0.0.qY2XZ7E6
> 播放了5分钟后出现了音画不同步,但蘑菇街播放页面上的音画仍然是同步的.
> 您试试?

我用FFmpeg推流的 你看看：https://tliveplay.mogujielive.com/live/359166625_11428209.flv

**Comment by xiongziliang** [comment]
确实不同步了

**Comment by xiongziliang** [comment]
改成这样既可：

```
ffmpeg -re  -i https://tliveplay.mogujielive.com/live/359166625_11428209.flv -c:a copy -c:v copy -f flv rtmp://120.77.206.70/live/test?token=1677193e-1244-49f2-8868-13b3fcc31b17
```

**Comment by imfuding** [comment]
经过多个设备(不同电脑/网络)多个环境(win/linux),多种源(摄像头,别人的流,mp4文件,桌面)多种方式(obs/app等)均在不同时间(hls多半小时内,rtmp/flv1小时内)均存在音画不同步的情形,您上文`"毕竟我们已经有很多使用案例了"`,估计有许多用于无声/弱声环境如监控,在直播方面,音画不同步现象尤为突出,期望能从zl中解决问题.非常关注,谢谢.

**Comment by xiongziliang** [comment]
好 &nbsp;我跟踪下 有可能是有次更新导致的 之前开始从没有这个反馈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: imfuding <notifications@github.com&gt;
发送时间: 2019年11月16日 16:26
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 播放时间稍长后,音画不同步,重新播放也会不同步. (#136)




经过多个设备(不同电脑/网络)多个环境(win/linux),多种源(摄像头,别人的流,mp4文件,桌面)多种方式(obs/app等)均在不同时间(hls多半小时内,rtmp/flv1小时内)均存在音画不同步的情形,您上文"毕竟我们已经有很多使用案例了",估计有许多用于无声/弱声环境如监控,在直播方面,音画不同步现象尤为突出,期望能从zl中解决问题.非常关注,谢谢.

**Comment by xiongziliang** [comment]
我加了点调试代码，目的是打印播放器获取到的时间戳：
![image](https://user-images.githubusercontent.com/11495632/69018709-89f7c300-09e8-11ea-8b15-a93da8ab7cd8.png)

这个代码每一秒会打印一次音视频的时间戳(现在是开始播放时的时间戳打印)：
![image](https://user-images.githubusercontent.com/11495632/69018747-a693fb00-09e8-11ea-9be0-0d069659a62f.png)

如果绝对时间戳与相对时间戳的差值(也就是代码中的`pkt->timeStamp - dts_out`)变化了，那说明我生成的相对时间戳有问题。否则可以把相对时间戳当做绝对时间戳看待。

我现在正在观察等待(等待时间戳不同步的那一刻)......

经过漫长的等待（35分钟左右），发现有很轻微的音视频不同步现象，大概声音比视频延后几百毫秒(感觉500ms以内)
![image](https://user-images.githubusercontent.com/11495632/69019857-6edb8200-09ed-11ea-812c-9f4074552ae4.png)

从开始和结尾的日志可以看出，绝对时间戳与相对时间戳的差值并没有发生变化，说明时间戳的源头就不同步了,也就是推流时间戳就不同步了，但是并不严重。

本次测试是在开启时间戳覆盖功能时测试的，所谓的时间戳覆盖是指根据数据包接收时间戳平滑化后的结果覆盖原先的时间戳。

**Comment by xiongziliang** [comment]
我会以相同的技术手段再测试关闭时间戳覆盖时的同步问题

**Comment by xiongziliang** [comment]
现在我已经关闭了时间戳覆盖功能，这是开始时的打印：
![image](https://user-images.githubusercontent.com/11495632/69020188-a39c0900-09ee-11ea-86ec-4e6530725478.png)

经过大概20分钟的测试，目前音视频还完全同步，以下是日志打印：
![image](https://user-images.githubusercontent.com/11495632/69021133-c7ad1980-09f1-11ea-8f11-d0df32a8c286.png)


我全程用obs捕获摄像头和麦克风推流测试的，你之前的那次测试，我认为很可能是那个视频源的问题，obs或FFmpeg在解码那个视频源时，可能遇到了某种问题导致音视频不同步了，你一定要原汁原味的推流，也就是不要转码，命令类似为：
```
ffmpeg -re  -i https://tliveplay.mogujielive.com/live/359166625_11428209.flv -c:a copy -c:v copy -f flv rtmp://120.77.206.70/live/test?token=1677193e-1244-49f2-8868-13b3fcc31b17
```

**Comment by xiongziliang** [comment]
我现在测试了1个多小时了，还是同步的
![image](https://user-images.githubusercontent.com/11495632/69022923-deef0580-09f7-11ea-8a01-96863f54fdd0.png)

**Comment by imfuding** [comment]
暂时保留疑问,留待以后线上应用,引入了更多推拉流用户后更多人反馈.
