### ISSUE TITLE
[期望功能]能按schema/vhost/app/stream任选其一或多个的比较弹性的断流方式

### ISSUE THREAD

**Issue by imfuding** [xiongziliang/ZLMediaKit#138]
当前按四项参数全部匹配才能断实在太硬性了.若是想断某个vhost或某类app就只能getMediaList遍历逐个提交close_stream.
场景如多家网站(vhost)共用视频服务器,当期望断开某个vhost(例如网站重启时顺便断开相关流),以目前要么restartServer,要么getMediaList遍历逐个提交close_stream.

**Comment by xiongziliang** [comment]
已经添加了close_streams接口了，wiki文档也更新了，你看下

**Comment by imfuding** [comment]
谢谢大佬

**Comment by imfuding** [comment]
好像wiki里的close_streams参数是否可选写错了,成了都必须的了.

**Comment by xiongziliang** [comment]
> 好像wiki里的close_streams参数是否可选写错了,成了都必须的了.

都改成非必须了

**Comment by amhoho** [comment]
这样是正确的吗?
```
http://127.0.0.1/index/api/close_streams?vhost=__defaultVhost__&force=1
或者vhost=任意一个当前存在着流的vhost
---------
http://127.0.0.1/index/api/close_streams?vhost=__defaultVhost__&schema=rtsp&force=1
或者加上协议等参数
```
其效果均等于`restartServer`重启了.而不是只是关了这个vhost的流了.

**Comment by xiongziliang** [comment]
只会关这个对应的流 其他的不会关



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: amhoho <notifications@github.com&gt;
发送时间: 2019年11月18日 21:37
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] [期望功能]能按schema/vhost/app/stream任选其一或多个的比较弹性的断流方式 (#138)




这样是正确的吗?
 http://127.0.0.1/index/api/close_streams?vhost=__defaultVhost__&amp;force=1 或者vhost=任意一个当前存在着流的vhost --------- http://127.0.0.1/index/api/close_streams?vhost=__defaultVhost__&amp;schema=rtsp&amp;force=1 或者加上协议等参数  
其效果均等于restartServer重启了.而不是只是关了这个vhost的流了.
