### ISSUE TITLE
hls的按需拉流，及rtsp回放的问题

### ISSUE THREAD

**Issue by newtalk** [xiongziliang/ZLMediaKit#139]
目前是什么原因不支持HLS的按需拉流呢？是没功夫写哈，还是因为HLS本身的技术上限制不容易实现呢？
因为hls 目前我测试下来，只发on_play ，没有on_stream_not_found ,同时主的 flv 或rtsp 取流停止后，虽然hls没关还在播放，但也往应用服务器发了 on_stream_none_reader

另外测试设备是海康NVR设备的情况下，按需拉流中，rtsp地址如果写成rtsp://admin:xxx@10.1.1.188:554/Streaming/tracks/901?starttime=20191116t120000z&endtime=20191116t120030z，类型这种回放地址的话，基本不能成功，看日志至少重试3-4次后能连上，稳定连上后，基本上包也全部不符合要求被丢了(handleOneRtp 无有效负载的rtp包:104 <= 108)，这时通过接口查获取流列表也是空的没有建立。 实时也有不少这种日志，但可以正常播放， 基本就表现在回放上。

另外请教一个问题，这种回放型的RTSP流的话，是否可能在生成FLV或HLS时就让播放器知道整个片段时长？或者说可以允许videojs 类的播放器，进行进度条播放，速率操作。

**Comment by xiongziliang** [comment]
历史回放进度条拉动是个很困难的事情，因为作为拉流代理，在接收到播放器的seek请求时，还要再向NVR发送seek请求，你那么就会存在一个回复延时和同步的问题，还会存在一个时间戳转换的问题，再者拉流代理出去可能被N个人同时观看，其中一个人seek，其他人也会被跟着seek，况且有些协议在这种场景下还不可能支持seek(譬如http-flv/hls直播)。

现在这种录像流代理，有那么点可能性实现seek操作，但是很难，做出来了效果也很难让人满意。

> 另外请教一个问题，这种回放型的RTSP流的话，是否可能在生成FLV或HLS时就让播放器知道整个片段时长？或者说可以允许videojs 类的播放器，进行进度条播放，速率操作。

回放型的RTSP流转http-flv/hls后不可能让播放器知道整个片段时长。因为在回放结束前不可能知道模拟点播的整个http-flv文件大小以及hls切片个数和市场，也就是说你不可能判断一件未来的事情。

**Comment by newtalk** [comment]
感谢回复， 今天详细试了下， 回放seek确实存在你说大家共用的问题。

昨天海康的设备回放抓了下包研究了下，不知道为什么海康的设备Play返回200后，没有及时发RTP包，导致平台超时重试，用VLC什么的倒是秒开的，对比后初步怀疑vlc碰到不支持的音频，直接不setup了，而ZLMediaKit还是setup的，实际海康的设备没有音频的，不知道搞什么SDP里放了个音频描述。  怀疑是这个原因导致的不发包，回头我改下程序看看，是不是这个原因，今天换了个NVR测试是好的。

rtsp回放流转flv在videojs下进度条及时长显示是有的也是对的，但不能拉，或者说拉了，也要等到flv顺序下载，并缓存到这个片断后，才能跳。

**Comment by xiongziliang** [comment]
> rtsp回放流转flv在videojs下进度条及时长显示是有的也是对的，但不能拉，或者说拉了，也要等到flv顺序下载，并缓存到这个片断后，才能跳。

videojs能播放http-flv直播也能播放http-flv点播，通过拉rtsp回放流的方式转http-flv,只能转成直播，因为http协议只能通过bytes offset拖动进度条，而http-flv直播是没有content-length字段的，这个也是没法生成的。

hls也是同理，你整个文件都没下载完成，怎么生成完整的m3u8和ts文件？这些东西不可能凭空生成。

**Comment by xiongziliang** [comment]
如果要代理点播流，那么基本只能模拟成直播(特别是转成http协议)，这个是没办法的事情。
rtsp的seek是根据时间戳来seek的，
http-flv/hls是通过bytes offset来seek的，
http-flv协议要seek后才能知道总文件时间长度，
hls要获取完整的ts文件列表才能知道总文件时间长度，
所以注定不能你想想的那么简单。

**Comment by xiongziliang** [comment]
拉rtsp回放流勉强能代理成点播rtsp流，但是也很麻烦，里面的坑跟你也讲不完，讲了你也很难能体会，只有你自己把rtsp协议实现遍才能体会。

**Comment by xiongziliang** [comment]
现在ZLMediaKit的mp4点播在多次seek后都可能时间轴紊乱，更不要说代理后的rtsp点播流了。

**Comment by xiongziliang** [comment]
点播这种东西 除了http ,其他(rtsp/rtmp)基本都没啥价值

**Comment by xiongziliang** [comment]
hls的按需拉流价值也不大，因为hls生成的时间太长了，生成了，黄花菜都凉了，播放器哪里会等你那么长时间啊？

况且http服务器本来就应该跟你hls文件是切割开的，两种又不是一回事，现在ZLMediaKit的http服务器加了太多的业务了，这不是种好的设计。按道理，一般hls由ZLMediaKit生成，http服务器由NGINX实现，所谓术业有专攻就是这个道理。而hls按需拉流是深度与http服务器逻辑绑定的，这样会污染http文件服务器的纯粹性。

**Comment by newtalk** [comment]
嗯，打算页面放个时间轴，用JS换videojs src的方式，更换取回放流地址的时间偏移值来实现了。

**Comment by xiongziliang** [comment]
现在ZLMediaKit实现了hls的按需拉流了
