### ISSUE TITLE
illegal rtsp url，播放失败不会触发setOnPlayResult

### ISSUE THREAD

**Issue by JerryLinGd** [xiongziliang/ZLMediaKit#143]
非法的rtsp url，解析出来的ip为空，播放失败，直接触发setOnShutdown，不会触发setOnPlayResult，导致MediaServer没有把这个url从点播列表里面删除，导致反复使用非法的rtsp重试拉流操作。如果客户端再次用这个非法rtsp url去点播，会因为点播列表中存在这个key，直接认为播放成功。

**Comment by xiongziliang** [comment]
你说的这个确实是个bug，我修复下

**Comment by JerryLinGd** [comment]
非常感谢~~
