### ISSUE TITLE
想请问一下为什么ZLMediaKit对RTSP的支持感觉是最完善的

### ISSUE THREAD

**Issue by bigbao9494** [xiongziliang/ZLMediaKit#145]
为什么ZLMediaKit对RTSP的支持感觉是最完善的，而不是RTMP呢？
其实主流的商用流媒体还是RTMP用得最多吧？

**Comment by xiongziliang** [comment]
因为最开始ZLMediaKit就支持rtsp，这还是2013年就支持了
在2016~2017年添加了RTMP的支持。

不过现在ZLMediaKit的rtmp商用的比较多，很稳定了，
RTSP稳定性应该还可以，但是我没有大规模商用这个，
不过在一个IPTV项目中商用了，也表现很稳定。
