### ISSUE TITLE
[期望功能]hls能像flv一样长连接的实现on_play和on_flow_report等

### ISSUE THREAD

**Issue by imfuding** [xiongziliang/ZLMediaKit#147]
现状:受限于hls不是长连接,所以很多功能无法实现,例如hook中的一些常用项.
期望:大佬能解决.

**Comment by tsingeye** [comment]
同求

**Comment by xiongziliang** [comment]
我也同求，同求志同道合者一起实现(帮我实现最好🤣)！


玩笑话，这个建议的优先级其实挺高的，我之前计划录像改造完了(已经完成)就做这个，
但是由于目前手上有很多事情中断了该进程，计划手上事情忙完了优先实现这个。

**Comment by xiongziliang** [comment]
hls直播目前实现了一下hook事件
- on_play：播放鉴权
- on_stream_changed：流注册注销事件
- on_stream_none_reader：无人观看事件
- on_stream_not_found：未找到流事件

目前正在实现：
- on_flow_report：播放器断开消耗流量事件

现在hls直播基本与长连接类型的直播功能完全一致

**Comment by xiongziliang** [comment]
目前hls能完整实现按需推流流功能
