### ISSUE TITLE
你好,请问线程负载和工作线程负载是什么意思,hook中所反馈的data具体是什么意思呢?

### ISSUE THREAD

**Issue by 649789249** [xiongziliang/ZLMediaKit#149]
对c++不了解,不明白wiki中所述的线程负载和工作线程负载的具体作用,获得参数中的延时和负载又具体什么意思,大小代表着什么意义?请具体的释疑一下,谢谢.

**Comment by 649789249** [comment]
目前是否对hls支持不足,测试时发现hls不能触发许多东西,更像是纯粹的http.(也许我的测试有问题吗?)

**Comment by 649789249** [comment]
再咨询一个问题,截止目前,有已上线的采用ZLMediaKit的成熟案例吗?

**Comment by xiongziliang** [comment]
> 对c++不了解,不明白wiki中所述的线程负载和工作线程负载的具体作用,获得参数中的延时和负载又具体什么意思,大小代表着什么意义?请具体的释疑一下,谢谢.

zlmediakit里面主要线程大概分为两种，
一类是网络线程，处理非阻塞的网络io事件，
另外一类是后台任务线程，一般处理阻塞式任务，比如说dns解析以及mp4点播

这个两个接口分别返回这两类线程的负载情况，用于监控zlmediakit的整体运行负载情况.

**Comment by xiongziliang** [comment]
> 目前是否对hls支持不足,测试时发现hls不能触发许多东西,更像是纯粹的http.(也许我的测试有问题吗?)

严格的讲，hls只用负责生成hls文件切片即可，怎么把文件传输给播放器是http服务器的事情，
所以从设计上来讲，hls跟http文件服务器是解耦的，也就是说http文件服务器其实不管是不是hls文件，它才不管客户端访问的是什么文件。所以你可以用zlmediakit生成hls文件，NGINX作为http文件服务器。

而且hls作为短链接方式实现的播放协议，根本做不到判断本次播放访问是否是第二次播放还是第二次获取m3u8文件，所以很多长连接类型协议中容易实现的逻辑，在hls里面要实现很难或者根本实现不了。
况且，http文件服务器，跟hls文件本来是两个独立的分割的逻辑，如果hls的业务逻辑强行放在http文件服务器里面实现，那么就会很深的耦合，这样的话不利于http服务器的独立发展和演进。

**Comment by xiongziliang** [comment]
> 再咨询一个问题,截止目前,有已上线的采用ZLMediaKit的成熟案例吗?

ZLMediaKit目前有很多公司在用，不过还未听说有cdn类型的应用案例，目前更多的是一些嵌入式应用或小规模的商用服务器场景。
不过可以透露的是，目前ZLMediaKit已经得到了一些行业翘楚公司的认可，这些公司在细分领域是领头羊的存在。

**Comment by 649789249** [comment]
> 而且hls作为短链接方式实现的播放协议，根本做不到判断本次播放访问是否是第二次播放还是第二次获取m3u8文件，所以很多长连接类型协议中容易实现的逻辑，在hls里面要实现很难或者根本实现不了。

大致明白了,后期是否会修补hls这个局限性呢?或者说,以曲线救国的方式解决这个局限,毕竟大部分移动端都以hls播放为主.

**Comment by xiongziliang** [comment]
hls播放这块如果要做成像长连接那么复杂，那么需要改的东西会比较复杂，工作量会比较大。这个看后续时间允不允许，现在暂时没那么多时间和精力处理这个事情
