### ISSUE TITLE
用librtmp推流时提示握手失败

### ISSUE THREAD

**Issue by kqbi** [xiongziliang/ZLMediaKit#150]
用librtmp推流时有时候失败，MediaServer出现can not support cmd: FCUnpublish

**Comment by xiongziliang** [comment]
> 用librtmp推流时有时候失败，MediaServer出现can not support cmd: FCUnpublish

失败不是这个原因导致的，ZLMediaKit实现了rtmp协议的必备的命令，也就是大家公认的命令，有些命令不起作用(用重复相似的命令替代功能)。

你可以抓个包给我看下。
