### ISSUE TITLE
关于hls问题

### ISSUE THREAD

**Issue by yuhu-fei11** [xiongziliang/ZLMediaKit#154]
我想基于zlmediakit做一个hls协议的demo，实现hls协议，在输入码流的时候遇到了一些问题，我在本地有一个H264的视频文件该怎么将其跟zlmediakit连接在一起呢，找了好几天的代码，总有些不明白，希望您能给梳理一下，最好能把hls内部实现的结构讲解一下就更完美了，谢谢

**Comment by xiongziliang** [comment]
你应该从H264文件中提取出一帧一帧的数据(根据 0x00  00 01来split)，
然后按照一定的频率一帧一帧的输入到ZLMediaKit的DevChannel对象。
剩下的要做的你可以参考这个 #19 #55

**Comment by xiongziliang** [comment]
如果你只是想生成HLS切片文件，那么你可以看看MediaRecorder、HlsRecorder对象

**Comment by xiongziliang** [comment]
HLS相对来说很简单了 只是生成m3u8索引文件以及ts切片

**Comment by yuhu-fei11** [comment]
好的，实际上我是想基于您的zlmediakit 做一个视频直播的简单服务器，感谢您的答复。

**Comment by yuhu-fei11** [comment]
我还想问下，生成之后的ts切片，在zlmediakit内部有http分发支持吗？

**Comment by xiongziliang** [comment]
> 我还想问下，生成之后的ts切片，在zlmediakit内部有http分发支持吗？

zlmedaikit内置http服务器，该服务器不仅可以为hls提供服务，
同时还支持 restful api、文件服务器、http-flv、websocket-flv、websocket服务器
