### ISSUE TITLE
关于DNS的问题

### ISSUE THREAD

**Issue by neuskb** [xiongziliang/ZLMediaKit#155]
大佬请教下，我在DNS服务器上做了 域名client.example.com 和 某个ip的映射，
然后用test_pusher 去 用url rtsp://admin:admin123@client.example.com:554拉流
并没有拉成功，zlmedia侧针对dns还有什么配置吗？

**Comment by neuskb** [comment]
![image](https://user-images.githubusercontent.com/55521963/69725347-e9787000-1158-11ea-84f9-8528b34fba65.png)

**Comment by xiongziliang** [comment]
zlmedaikit基于zltoolkit网络库，里面通过线程池的方式实现了dns的异步解析。
dns解析成功后会缓存(默认60秒超时)解析结果在内存中。
按道理，如果你在你本机ping 你的域名能解析出ip的话，那么zltoolkit肯定能解析成功的。

建议你调试下代码，或者在关键地方添加调试日志。从你的截图来看，应该是rtsp握手超时导致的，并不像是tcp网络链接的问题。

**Comment by xiongziliang** [comment]
另外你也可以wireshark抓包分析下，我觉得应该是建立了tcp连接并发送了rtsp播放请求，只是你rtsp服务器没响应

**Comment by neuskb** [comment]
![image](https://user-images.githubusercontent.com/55521963/69770979-0f882980-11c6-11ea-8931-d0037053551b.png)
能ping通 我加下调试打印看下

**Comment by neuskb** [comment]
![image](https://user-images.githubusercontent.com/55521963/69773782-bf619500-11ce-11ea-8b8c-0bd4fb1b2843.png)
抓包看了下 是 相机对describe的200ok回复的太慢了，超了10s了，zlmedia就teardown了。
奇怪，直接用ip是不会这么慢的，zlmedia的超时时间在哪里设置的呢？

**Comment by xiongziliang** [comment]
你可以这样设置单个播放器的超时时间：
```c++ 
MediaPlayer::Ptr player(new MediaPlayer());
(*player)[mediakit::Client::kTimeoutMS] = 30 * 1000;
```
也可以设置默认的超时时间:
![image](https://user-images.githubusercontent.com/11495632/69774038-aad1cc80-11cf-11ea-9665-874b8fe78671.png)

现在默认是10秒超时

**Comment by neuskb** [comment]
多谢大佬 改成20s 就可以了，就是好奇怪 用了域名 相机就是针对describe 的200ok回的特别慢。
