### ISSUE TITLE
getMediaList 接口增加rtmp/rtxp完整的url

### ISSUE THREAD

**Issue by machh** [xiongziliang/ZLMediaKit#156]
第三方服务器通过http接口  getMediaList 获取流信息， 直接拿到url字段进行拉流播放

**Comment by xiongziliang** [comment]
这个url还是你自己组装比较好 ，为什么呢？
- 1、因为ZLMediaKit不支持服务器的公网域名(或者ip)和端口，如果通过nat映射的，端口不一定一致。
- 2、访问的url一般要带参数来实现播放鉴权，而播放鉴权的行为是hook第三方服务器决定的，ZLMediaKit不知道hook第三方服务器的url参数规则，生成的rtmp/rtsp完整的url 是没法带鉴权参数的。
