### ISSUE TITLE
关于hls鉴权是否带有缓存

### ISSUE THREAD

**Issue by imfuding** [xiongziliang/ZLMediaKit#157]
hls的缓存是只针对当前stream的还是针对客户端即所有stream的,在切换到其它stream后这个缓存结果会失效吗

**Comment by xiongziliang** [comment]
- 由于hls短链接的特性，所以必须设置一种鉴权结果缓存的机制来避免频繁的鉴权hook事件。

- zlmediakit的hls鉴权是通过cookie来实现用户追踪和鉴权结果缓存的，在cookie有效期内，重复的hls播放将不再触发鉴权hook事件(会直接返回上次的鉴权结果)。

- 如果hls播放器重启了（比如说重启vlc播放器），那么这个时候播放器是不提供cookie字符串的，那么zlmediakit会根据播放url的参数(也就是问号后面的字符串)来定位cookie，如果播放url没有参数，那么会根据ip+端口来定位用户cookie，如果定位到用户cookie就会直接返回上次鉴权结果，否则触发鉴权hook事件。

- hls播放鉴权cookie有效期默认10分钟。

- hls播放鉴权cookie默认只对本目录有效，如果切换其他目录将重新触发鉴权hook事件。


我在代码里面有解释这个鉴权机制，这里粘贴出来：

```c++
  /* 1、根据http请求头查找cookie，找到进入步骤3
     * 2、根据http url参数(如果没有根据ip+端口号)查找cookie，如果还是未找到cookie则进入步骤5
     * 3、cookie标记是否有权限访问文件，如果有权限，直接返回文件
     * 4、cookie中记录的url参数是否跟本次url参数一致，如果一致直接返回客户端错误码
     * 5、触发kBroadcastHttpAccess事件
     */
    //开发者应该通过该事件判定http客户端是否有权限访问http服务器上的特定文件
    //ZLMediaKit会记录本次鉴权的结果至cookie
    //如果鉴权成功，在cookie有效期内，那么下次客户端再访问授权目录时，ZLMediaKit会直接返回文件
    //如果鉴权失败，在cookie有效期内，如果http url参数不变(否则会立即再次触发鉴权事件)，ZLMediaKit会直接返回错误码
    //如果用户客户端不支持cookie，那么ZLMediaKit会根据url参数查找cookie并追踪用户，
    //如果没有url参数，客户端又不支持cookie，那么会根据ip和端口追踪用户
    //追踪用户的目的是为了缓存上次鉴权结果，减少鉴权次数，提高性能
```

**Comment by imfuding** [comment]
懂了
