### ISSUE TITLE
hls生成中产生的问题

### ISSUE THREAD

**Issue by yuhu-fei11** [xiongziliang/ZLMediaKit#159]
我在DevChannel类中输入帧，调用的initVideo和inputH264函数接口，但是输出的结果却是一个空的ts文件并且没有m3u8文件，是为什么呢，使用的ffmpeg读取的帧，还有帧的高度宽度，以及每秒的帧率，用断点调试的时候，可以输出多个ts文件和m3u8文件，但是ts文件都特别小，基本上都是1k的，并且数据也不对，是有哪些地方没有注意到吗？

**Comment by xiongziliang** [comment]
这个问题一般是由于没有初始化视频成功导致的
你在inputH264时务必要一帧一帧的输入，并且要带0x 00 00 01这些的头
而且必须在10秒内输入sps pps帧 ，否则H264不会被初始化成功

**Comment by yuhu-fei11** [comment]
好的，谢谢大佬的回复，我再仔细的检查一下。
