### ISSUE TITLE
生成的hls在vlc上可以正常播放,但是在网页上用各种播放器都播放不了,一直在转圈,用ffmpeg生成的hls可以播放..

### ISSUE THREAD

**Issue by wanghouting123** [xiongziliang/ZLMediaKit#16]
生成的hls在vlc上可以正常播放,但是在网页上用各种播放器都播放不了,一直在转圈,用ffmpeg生成的hls可以播放..

**Comment by xiongziliang** [comment]
你是推流还是拉流之后生成的hls文件？能否说下你的应用场景

**Comment by wanghouting123** [comment]
我是拉取监控摄像头的rtsp流然后转成hls。前端用的vue+video.js播放，也尝试用了ckplayer网页播放器，都是播放不了

**Comment by xiongziliang** [comment]
你看下是否是跨域的问题？加入说你hls的服务器地址跟你播放页面的地址不一样 就可能存在跨域问题

**Comment by wanghouting123** [comment]
跨域的话js有提示的，浏览器上没有任何报错，用本地的绝对路径也不行的

**Comment by xiongziliang** [comment]
经过实测，使用以下代码可以在chrome浏览器播放ZLMediaKit生成的hls视频：
```

<head>
  <link href="https://vjs.zencdn.net/7.3.0/video-js.css" rel="stylesheet">

  <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
  <script src="https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js"></script>
</head>

<body>
  <video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
  poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
    <source src="http://127.0.0.1/live/0/hls.m3u8" type='application/vnd.apple.mpegurl'>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>

  <script src="https://vjs.zencdn.net/7.3.0/video.js"></script>
</body>

```

**Comment by media1984** [comment]
> 经过实测，使用以下代码可以在chrome浏览器播放ZLMediaKit生成的hls视频：
> 
> ```
> 
> <head>
>   <link href="https://vjs.zencdn.net/7.3.0/video-js.css" rel="stylesheet">
> 
>   
>   <script src="https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js"></script>
> </head>
> 
> <body>
>   <video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
>   poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
>     <source src="http://127.0.0.1/live/0/hls.m3u8" type='application/vnd.apple.mpegurl'>
>     <p class="vjs-no-js">
>       To view this video please enable JavaScript, and consider upgrading to a web browser that
>       <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
>     </p>
>   </video>
> 
>   <script src="https://vjs.zencdn.net/7.3.0/video.js"></script>
> </body>
> ```

好用 这个测试了
