### ISSUE TITLE
無法進行rtp multicast拉流

### ISSUE THREAD

**Issue by taiwancek** [xiongziliang/ZLMediaKit#160]
透過指令ffmpeg.... -rtsp_transport udp -f rtsp rtsp://10.10.10.117:554/live/2.sdp可以成功推流，
並使用vlc player可以成功拉流rtsp://10.10.10.117:554/live/2，但無法透過RTP mulitcast拉流(rtp://@10.10.10.117:554).

**Comment by xiongziliang** [comment]
因为你在同一台主机上 不能两个进程同时使用一个组播端口啊
你可以服务器和客户端在两台主机上测试

**Comment by taiwancek** [comment]
非常感謝回覆！ 目前我嘗試在手機上用vlc播放rtp://@10.10.10.117:554還是拉不到流，會是我哪邊設定的問題？(rtsp://10.10.10.117:554/live/2是可以在手機上成功拉流)

**Comment by xiongziliang** [comment]
> 非常感謝回覆！ 目前我嘗試在手機上用vlc播放rtp://@10.10.10.117:554還是拉不到流，會是我哪邊設定的問題？(rtsp://10.10.10.117:554/live/2是可以在手機上成功拉流)

rtp组播跟rtsp组播是两回事，rtsp组播需要先协商组播端口号才能开始组播
你可以在其他电脑这样播放：
```
ffplay rtsp://10.10.10.117:554/live/2 -rtsp_transport udp_multicast
```

**Comment by taiwancek** [comment]
可以了。但看起來udp_multicast會比udp卡頓許多，我在研究看，非常感謝您的協助，目前看起來ZLMediaKit與其他RTSP開源完整許多!!
