### ISSUE TITLE
RTSP Stream C++ byte array from android

### ISSUE THREAD

**Issue by idonov** [xiongziliang/ZLMediaKit#162]
Hi,

I am looking in to your rtsp library, and want to use it to stream a byte array pointer obtained from Unity on android with native C++. I want to stream this I guess over HTTP to Facebook live.
It would nice if I can add on top audio from the android microphone, and/or maybe the camera.

Would this be possible, I want to compile to an .so library for android?

Thanks,
Igor

**Comment by xiongziliang** [comment]
Hi , you can read this [wiki](https://github.com/xiongziliang/ZLMediaKit/wiki/How-to-create-a-live-steam) i just finished.
