### ISSUE TITLE
rtp代理的几个问题

### ISSUE THREAD

**Issue by zhang2349** [xiongziliang/ZLMediaKit#164]
https://github.com/xiongziliang/ZLToolKit/blob/628d3b2527f63b54a5eb38b9e9973254d4a2192b/src/Network/Socket.cpp#L252
UDP的缓存1600太小，我测试会收到1900大小的包，百度说最大65535？

https://github.com/xiongziliang/media-server/blob/4325386be318889b7815cdd86a2e83f05a059c81/librtp/payload/rtp-ts-unpack.c#L28
这里判断逻辑有问题
pkt.rtp.m是代表一帧结束，这里直接把前面rtp包缓存的给丢掉了？rtp组完包的处理在rtp_payload_check(helper, &pkt)里，
if (pkt->rtp.timestamp != helper->timestamp)
这个判断是不是应该也有点问题？

最近加的rtp代理推流，就是以SSRC区分的？这个不会重复的吗？

**Comment by xiongziliang** [comment]
局域网中，你能收到1600个字节的udp包吗？貌似不能吧？
ZLMediaKit默认udp的socket读缓存是1600，这个其实也有api可以改的嘛。
ZLMediaKit支持最大10K的rtp包，不过这种只针对tcp情况下。

后面第三方库media-server的实现逻辑我没细看，但是这个rtp代理的功能我实测过，没发现什么问题啊，我能正常观看转换后的rtsp/rtmp。

rtp推流都是通过ssrc来区分源的，如果一次推流中ssrc多次变化，相比推流代码是极有问题的。
不过如果是tcp推流，可以变更ssrc，tcp没限定ssrc。

**Comment by zhang2349** [comment]
我打印显示nread最大值有1900，win32环境
抓包显示都是小于1600的  而且nread的值 跟 抓包软件里显示的长度 都对不上  有点奇怪

好像就rtp_decode_ts这里看起来有点问题， 其他比如rtp_h264_decode的是的

**Comment by xiongziliang** [comment]
那行代码nread最大值有1900？你把代码文件、行数位置贴出来。

**Comment by zhang2349** [comment]
哦 不好意思 我以为贴了 是这行的nread
https://github.com/xiongziliang/ZLToolKit/blob/628d3b2527f63b54a5eb38b9e9973254d4a2192b/src/Network/Socket.cpp#L299

**Comment by xiongziliang** [comment]
不出意外你断点触发时是tcp包。
你不行的话可以打印出内容或者本地端口。

**Comment by zhang2349** [comment]
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.795 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.795 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.795 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.796 D | toolkit::Socket::onRead recvfrom:1932  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.796 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.796 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.796 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.796 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.796 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.796 D | toolkit::Socket::onRead recvfrom:671  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.796 D | toolkit::Socket::onRead recvfrom:26  192.168.3.152  12838
MediaServer.exe(6580) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 15:58:23.834 D | toolkit::Socket::onRead recvfrom:26  192.168.3.152  12838

DebugL << "recvfrom:" << nread << "  " << inet_ntoa(peerAddr.sin_addr) << "  " << peerAddr.sin_port;
这是我打印的日志，来自同一ip的同一端口

你说打印本地端口是什么意思  本地端口就是10000把

**Comment by xiongziliang** [comment]
```cpp
DebugL << "recvfrom:" << nread << " " << pSock->get_local_port() << " " << pSock->type();
```

**Comment by zhang2349** [comment]
get_local_port()是this的， 显示type都是1

DebugL << "recvfrom:" << nread << "  " << inet_ntoa(peerAddr.sin_addr) << "  " << peerAddr.sin_port << " " << get_local_port() << " " << pSock->type();

MediaServer.exe(13552) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 16:48:29.531 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  13862 10000 1
MediaServer.exe(13552) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 16:48:29.531 D | toolkit::Socket::onRead recvfrom:1932  192.168.3.152  13862 10000 1
MediaServer.exe(13552) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 16:48:29.531 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  13862 10000 1
MediaServer.exe(13552) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 16:48:29.532 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  13862 10000 1
MediaServer.exe(13552) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 16:48:29.532 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  13862 10000 1
MediaServer.exe(13552) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 16:48:29.532 D | toolkit::Socket::onRead recvfrom:1312  192.168.3.152  13862 10000 1
MediaServer.exe(13552) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 16:48:29.532 D | toolkit::Socket::onRead recvfrom:997  192.168.3.152  13862 10000 1
MediaServer.exe(13552) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 16:48:29.532 D | toolkit::Socket::onRead recvfrom:26  192.168.3.152  13862 10000 1
MediaServer.exe(13552) D:\repos\ZLMediaKit\3rdpart\ZLToolKit\src\Network\Socket.cpp 302
2019-12-12 16:48:29.571 D | toolkit::Socket::onRead recvfrom:26  192.168.3.152  13862 10000 1

**Comment by xiongziliang** [comment]
我忘记我修改buffer大小了：
```C++
bool UdpRecver::initSock(uint16_t local_port,const char *local_ip) {
    _sock.reset(new Socket(nullptr, false));
    onceToken token(nullptr,[&](){
        SockUtil::setRecvBuf(_sock->rawFD(),4 * 1024 * 1024);
    });

    auto &ref = RtpSelector::Instance();
    _sock->setOnRead([&ref](const Buffer::Ptr &buf, struct sockaddr *addr, int ){
        ref.inputRtp(buf->data(),buf->size(),addr);
    });
    return _sock->bindUdpSock(local_port,local_ip);
}

```

**Comment by xiongziliang** [comment]
udp socket缓存设置为4MB了

**Comment by zhang2349** [comment]
test_rtp是MP2P的时候真没有问题？

rtp_decode_mp4v_es 和 rtp_decode_ts
对pkt.rtp.m的处理逻辑明显不一样

**Comment by xiongziliang** [comment]
你目前要自己选择MP4V-ES和MP2P

**Comment by zhang2349** [comment]
我是说 MP2P情况下 rtp_decode_ts里对rtp的解析有问题

**Comment by ireader** [comment]
> https://github.com/xiongziliang/ZLToolKit/blob/628d3b2527f63b54a5eb38b9e9973254d4a2192b/src/Network/Socket.cpp#L252
> UDP的缓存1600太小，我测试会收到1900大小的包，百度说最大65535？
> 
> https://github.com/xiongziliang/media-server/blob/4325386be318889b7815cdd86a2e83f05a059c81/librtp/payload/rtp-ts-unpack.c#L28
> 这里判断逻辑有问题
> pkt.rtp.m是代表一帧结束，这里直接把前面rtp包缓存的给丢掉了？rtp组完包的处理在rtp_payload_check(helper, &pkt)里，
> if (pkt->rtp.timestamp != helper->timestamp)
> 这个判断是不是应该也有点问题？
> 
> 最近加的rtp代理推流，就是以SSRC区分的？这个不会重复的吗？

RFC2250 
2. Encapsulation of MPEG System and Transport Streams
2.1 RTP header usage(p4)
M bit: Set to 1 whenever the timestamp is discontinuous.
注意看rfc规范，MPEG-TS中M设置为1表示新的流开始，such as might happen when a sender switches from one data source to another。

RFC6416 RTP Payload Format for MPEG-4 Audio/Visual Streams
5.1. Use of RTP Header Fields for MPEG-4 Visual (p9)
Marker (M) bit: The marker bit is set to 1 to indicate the last RTP packet(or only RTP packet) of a VOP
MPEG4-ES中M表示一帧结束，这两者是完全不同的。

**Comment by zhang2349** [comment]
> > https://github.com/xiongziliang/ZLToolKit/blob/628d3b2527f63b54a5eb38b9e9973254d4a2192b/src/Network/Socket.cpp#L252
> > UDP的缓存1600太小，我测试会收到1900大小的包，百度说最大65535？
> > https://github.com/xiongziliang/media-server/blob/4325386be318889b7815cdd86a2e83f05a059c81/librtp/payload/rtp-ts-unpack.c#L28
> > 这里判断逻辑有问题
> > pkt.rtp.m是代表一帧结束，这里直接把前面rtp包缓存的给丢掉了？rtp组完包的处理在rtp_payload_check(helper, &pkt)里，
> > if (pkt->rtp.timestamp != helper->timestamp)
> > 这个判断是不是应该也有点问题？
> > 最近加的rtp代理推流，就是以SSRC区分的？这个不会重复的吗？
> 
> RFC2250
> 2. Encapsulation of MPEG System and Transport Streams
> 2.1 RTP header usage(p4)
> M bit: Set to 1 whenever the timestamp is discontinuous.
> 注意看rfc规范，MPEG-TS中M设置为1表示新的流开始，such as might happen when a sender switches from one data source to another。
> 
> RFC6416 RTP Payload Format for MPEG-4 Audio/Visual Streams
> 5.1. Use of RTP Header Fields for MPEG-4 Visual (p9)
> Marker (M) bit: The marker bit is set to 1 to indicate the last RTP packet(or only RTP packet) of a VOP
> MPEG4-ES中M表示一帧结束，这两者是完全不同的。

额 这样啊  那是设备发过来的PS流不标准呀。。
