### ISSUE TITLE
expose streaming codecs to Web Hook and RESTful API 

### ISSUE THREAD

**Issue by c1ngular** [xiongziliang/ZLMediaKit#166]
it is critical for certain use cases to know the streaming codecs ,  so they could transcode/remux accordingly , do you agree ? 
Regards

**Comment by xiongziliang** [comment]
You can refer to these APIs:
[getMediaInfo](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#20indexapigetmediainfo)
[getMediaList](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#6indexapigetmedialist)

This is the codecs information:
```json
"tracks" : [    # 音视频轨道
        {
           "codec_id" : 0,  # H264 = 0, H265 = 1, AAC = 2
           "codec_type" : 0, # Video = 0, Audio = 1
           "ready" : true # 轨道是否准备就绪
        },
        {
           "codec_id" : 2,
           "codec_type" : 1,
           "ready" : true
        }
     ]
```

**Comment by c1ngular** [comment]
@xiongziliang sorry , i missed that part ,  i just scanned wiki ，**on_play and on_publish**  hooks to be specific , did not find codec info there .   i will close this issue .
thank you again for your reply .

**Comment by xiongziliang** [comment]
I just finished this feature that I didn't support before🙂🤣
