### ISSUE TITLE
关于rtsp取视频流问题

### ISSUE THREAD

**Issue by MrDiudiu** [xiongziliang/ZLMediaKit#169]
rtsp连接建立之后，是否是监听kBroadcastMediaChanged(注册或反注册MediaSource广播)事件，注册之后我就可以获取相应视频流了，还有假如我想使用mp4Recoder，他需要获取frame，不知道这个frame如何获取，希望作者能帮我解答一下，谢谢

**Comment by xiongziliang** [comment]
MediaSource对象有个 getTracks的方案，可以获取音视频轨道，获取到这些轨道了就能获取Frame了：
```C++
auto viedoTrack = MediaSource->getTrack(TrackVideo);
if(viedoTrack){
    viedoTrack->addDelegate(std::make_shared<FrameWriterInterfaceHelper>([](const Frame::Ptr &frame) {
       //这里获取到视频了
    }));
}}

auto audioTrack = MediaSource->getTrack(TrackAudio);
if(audioTrack){
    audioTrack->addDelegate(std::make_shared<FrameWriterInterfaceHelper>([](const Frame::Ptr &frame) {
        //这里获取音频了
    }));
}}
````

**Comment by MrDiudiu** [comment]
谢谢



---原始邮件---
发件人: "夏楚"<notifications@github.com&gt;
发送时间: 2019年12月13日(周五) 下午3:00
收件人: "xiongziliang/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
抄送: "MrDiudiu"<610915369@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xiongziliang/ZLMediaKit] 关于rtsp取视频流问题 (#169)



MediaSource对象有个 getTracks的方案，可以获取音视频轨道，获取到这些轨道了就能获取Frame了：
 auto viedoTrack = MediaSource-&gt;getTrack(TrackVideo); if(viedoTrack){     viedoTrack-&gt;addDelegate(std::make_shared<FrameWriterInterfaceHelper&gt;([](const Frame::Ptr &amp;frame) {        //这里获取到视频了     })); }} auto audioTrack = MediaSource-&gt;getTrack(TrackAudio); if(audioTrack){     audioTrack-&gt;addDelegate(std::make_shared<FrameWriterInterfaceHelper&gt;([](const Frame::Ptr &amp;frame) {         //这里获取音频了     })); }}
