### ISSUE TITLE
关于rtsp取流

### ISSUE THREAD

**Issue by MrDiudiu** [xiongziliang/ZLMediaKit#170]
![image](https://user-images.githubusercontent.com/25821958/70786712-38b0d880-1dc8-11ea-9f15-68393d7cb20e.png)
通过这样的方式，我获取到的videoTrack一直是empty，是我代码写法有问题还是rtsp流有问题？

**Comment by MrDiudiu** [comment]
应该如何修改 才能正确的将rtsp流保存为mp4格式

**Comment by xiongziliang** [comment]
本来就支持 你为什么还用弄一道？
[startRecord](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#17indexapistartrecord)

**Comment by MrDiudiu** [comment]
这不是要通过web请求吗

**Comment by MrDiudiu** [comment]
我是需要拿到frame，同时也需要MP4录制

**Comment by xiongziliang** [comment]
那你拿到frame又录制成mp4? 
本来就有mp4录制的功能啊。
你截图中已经获取到frame了。
