### ISSUE TITLE
Error when build project for iOS on XCode 11

### ISSUE THREAD

**Issue by thachonline** [xiongziliang/ZLMediaKit#174]
I am implementing a project to create an hls server on an iOS device, but when building a framework to use for the project, an error occurs and it cannot be built.

Can you show me how to build the framework to use in the xcode project?

**Comment by xiongziliang** [comment]
You can read the chapter in `readme`：

### Build on iOS

  This build method is no longer recommended.It is recommended that make Xcode project by yourself.

- My environment

  Same with Build on macOS

  
- You can generate Xcode projects and recompile them , [learn more](https://github.com/leetal/ios-cmake):

  ```
  cd ZLMediaKit
  mkdir -p build
  cd build
  # Generate Xcode project, project file is in build directory
  cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../cmake/ios.toolchain.cmake  -DPLATFORM=OS64COMBINED
  ```

**Comment by thachonline** [comment]
I have built a library for iOS, but after research about ZLMediaKit I found no examples of how to create an hls server on iOS devices or an rtsp example then convert into hls.
Can you help me on how to create a hls server on iOS?
On the iOS side, I already have frames corresponding to CMSampleBuffer, can I apply CMSampleBuffer with ZLMediaKit?
