### ISSUE TITLE
关于Tracks

### ISSUE THREAD

**Issue by MrDiudiu** [xiongziliang/ZLMediaKit#175]
我使用getTracks获取到的tracks列表为空，应该在何时添加tracks，以及如何添加呢

**Comment by xiongziliang** [comment]
你的描述不够精准 信息不够完善 不知道你说的获取哪个对象的tracks

**Comment by MrDiudiu** [comment]
![image](https://user-images.githubusercontent.com/25821958/70895779-79a82780-202a-11ea-99b8-64c977289a30.png)
z在这一步获取的tracks为empty

**Comment by MrDiudiu** [comment]
![image](https://user-images.githubusercontent.com/25821958/70895926-be33c300-202a-11ea-9bdb-796ecc7ffe90.png)
在红线处获取的tracks为empty，这里想再拉取rtsp流的同时 获取视频帧

**Comment by xiongziliang** [comment]
推流还是拉流？

**Comment by MrDiudiu** [comment]
拉流

**Comment by xiongziliang** [comment]
刚修复这个问题了
