### ISSUE TITLE
mp4 push and play

### ISSUE THREAD

**Issue by ganhx** [xiongziliang/ZLMediaKit#176]
MP4文件在push的同时进行播放，怎样做比较好？

**Comment by xiongziliang** [comment]
现在MediaPusher对象在推流时要绑定MediaSource，
而MediaSource可以通过getTrack(TrackVideo)获取H264视频。

你用MP4Reader生成MediaSource，然后用MediaPusher推流，参考test_pusherMp4.cpp
找到MediaSource对象后，通过getTrack(TrackVideo)获取H264视频并解码播放，参考test_player.cpp
