### ISSUE TITLE
关于MP4Recoder

### ISSUE THREAD

**Issue by MrDiudiu** [xiongziliang/ZLMediaKit#177]
在MP4Recoder.cpp中
![image](https://user-images.githubusercontent.com/25821958/70972748-0ca29980-20df-11ea-84d6-8a58a0639b4d.png)
这里红色区域中的/.是否应该改为/

**Comment by xiongziliang** [comment]
不应该 ，在录制途中，会隐藏文件 ，录制结束了会rename文件为可见
