### ISSUE TITLE
How to create HLS server or convert RTSP to HLS with ZLMediaKit on iOS Project

### ISSUE THREAD

**Issue by thachonline** [xiongziliang/ZLMediaKit#178]
I have built a library for iOS, but after research about ZLMediaKit I not found an example of how to create an hls server on iOS devices or an RTSP example then convert into hls.
Can you help me on how to create a hls server on iOS?
On the iOS side, I already have frames corresponding to CMSampleBuffer, can I apply CMSampleBuffer with ZLMediaKit?
Any answers that support me are grateful.

**Comment by xiongziliang** [comment]
You need create a `http server` and then create `hls files` like [this](https://github.com/xiongziliang/ZLMediaKit/wiki/How-to-create-a-live-steam).

Then you can play the hls live steam by url like this: `http://ip:port/app/stream/hls.m3u8`.

You need to encodec the `CMSampleBuffer ` to H264 first, and then input into `DevChannel`.

**Comment by xiongziliang** [comment]
This is a sample for create http server:
```c++
TcpServer::Ptr httpsSrv(new TcpServer());
httpSrv->start<HttpSession>(80);
// You need retain the object of httpsSrv when this function exited
// If the httpsSrv object destroyed, the http server will be closed
```

**Comment by xiongziliang** [comment]
And you need setup the hls root path and http server root path for IOS:
```C++
mINI::Instance()["http.rootPath"] = "/path/can/be/accessed/on/ios";
mINI::Instance()["hls.filePath"] = "/path/can/be/accessed/on/ios";
```

**Comment by xiongziliang** [comment]
This [project](https://gitee.com/xiahcu/IOSMedia) may be helpful for you.
You need download zlmediakit(please rename it to ZLMediaKit) with branch `3.0` or older and place it in the same path of this project(IOSMedia).
