### ISSUE TITLE
/index/api/addStreamProxy失败

### ISSUE THREAD

**Issue by tsingeye** [xiongziliang/ZLMediaKit#179]
url：
http://127.0.0.1/index/api/addStreamProxy?app=proxy&stream=test&enable_rtsp=1&enable_rtmp=1&enable_mp4=1&url=rtsp://admin:admin123@192.168.1.64:554/cam/realmonitor?channel=1&subtype=1

返回值：
{
   "code": -300,
   "msg": "ȱ�ٱ�Ҫ����:\"vhost\",\"app\",\"stream\",\"params\",\"url\",\"enable_rtsp\",\"enable_rtmp\""
}

不是rtsp的url 后面导致的问题呢， 有&符号

**Comment by tsingeye** [comment]
此错误码未 非法参数，应该是rtsp后面有&导致的了。

**Comment by xiongziliang** [comment]
你参数值中有？&，所以要转义

**Comment by tsingeye** [comment]
url中转么？  
http://127.0.0.1/index/api/addStreamProxy?app=proxy&stream=test&enable_rtmp=1&enable_mp4=1&url=rtsp://admin:admin123@192.168.1.64:554/cam/realmonitor%3Fchannel=1%26subtype=1 

这样？

**Comment by tsingeye** [comment]
http://127.0.0.1/index/api/addStreamProxy?vhost=__defaultVhost__&app=proxy&stream=test&enable_rtsp=1&enable_rtmp=1&enable_mp4=1&url=rtsp://admin:admin123@192.168.1.64:554/cam/realmonitor?channel=1%26subtype=1

url中的？不用转， &符号要转。。。
