### ISSUE TITLE
Clone your project not complete

### ISSUE THREAD

**Issue by lenhatvu** [xiongziliang/ZLMediaKit#180]
Hi,

I am ussing git desktiop to clone your project, but there is error as bellow:
![image](https://user-images.githubusercontent.com/59004953/71060774-f8bb6e00-2198-11ea-95a6-37355a48e2ae.png)

**Comment by xiongziliang** [comment]
You can try like this:
```
git clone --depth 1 https://gitee.com/xiahcu/ZLMediaKit
cd ZLMediaKit
git submodule update --init
```
