### ISSUE TITLE
还是addStreamProxy发现的问题

### ISSUE THREAD

**Issue by tsingeye** [xiongziliang/ZLMediaKit#181]
http://127.0.0.1/index/api/addStreamProxy?vhost=__defaultVhost__&app=proxy&stream=test1&enable_rtsp=0&enable_rtmp=1&enable_mp4=1&url=rtsp://admin:admin123@192.168.1.64:554/cam/realmonitor?channel=1%26subtype=1

以上拉流成功， 然后崩溃在：
`uint8_t mpeg4_h264_read_ue(const uint8_t* data, size_t bytes, size_t* offset)
{
	int bit, i;
	int leadingZeroBits = -1;

	for (bit = 0; !bit && *offset / 8 < bytes; ++leadingZeroBits)
	{
		bit = (data[*offset / 8] >> (7 - (*offset % 8))) & 0x01;   //这行
		++*offset;
	}`
ps: win环境，视频为264，音频为aac，是拉取的新代码

**Comment by tsingeye** [comment]
`static int h264_sps_copy(struct h264_annexbtomp4_handle_t* mp4, const uint8_t* nalu, size_t bytes)
{
	int i;
	uint8_t spsid;
	size_t offset;

	if (bytes < 4 + 1)
	{
		assert(0);
		mp4->errcode = -1;
		return -1; // invalid length
	}

	offset = 4 * 8; // 1-NALU + 3-profile+flags+level
	spsid = mpeg4_h264_read_ue(nalu, bytes, &offset);

	for (i = 0; i < mp4->avc->nb_sps; i++)
	{
		offset = 4 * 8; // reset offset
		if (spsid == mpeg4_h264_read_ue(mp4->avc->sps[i].data, mp4->avc->sps[i].bytes, &offset))    //这里第进去，然后接上一条
		{
			if (bytes == mp4->avc->sps[i].bytes && 0 == memcmp(nalu, mp4->avc->sps[i].data, bytes))
				return 0; // do nothing

			if (bytes > mp4->avc->sps[i].bytes && mp4->avcptr + (bytes - mp4->avc->sps[i].bytes) > mp4->avc->data + sizeof(mp4->avc->data))
			{
				assert(0);
				mp4->errcode = -1;
				return -1; // too big
			}`

**Comment by tsingeye** [comment]
mp4->avc->sps[i].data 内存出错了。

**Comment by xiongziliang** [comment]
这个应该是mp4录制的代码出错了 ，应该是sps或者pps获取未成功导致的，我刚提交了，你更新试试。
如果还崩溃，有可能是获取到的sps/pps异常导致，如果不再崩溃，但是打印了`Track未就绪`的日志也再反馈给我

**Comment by tsingeye** [comment]
依然崩溃，未打印Track，同样位置

**Comment by tsingeye** [comment]
{
	"vhost":"__defaultVhost__",
	"app":"proxy",
	"stream":"test1",
	"enable_rtsp":0,
	"enable_mp4":1,
	"enable_rtmp":0,
	"url":"rtsp://admin:admin123@192.168.1.64:554/cam/realmonitor?channel=1&subtype=1"
}

关闭rtsp rtmp时 不触发异常， 但是录像分段大小为0

**Comment by tsingeye** [comment]
另外 11月13号之前的版本 无异常，但是会打印：
2019-12-18 16:32:55.654 W | mediakit::HttpSession::onError 000001D8AFA9BF60(127.0.0.1:54024) session timeouted
iSMS.exe(16440) D:\work\projects\ictt\ZLMediaKit\src\Http\HttpSession.cpp 204
2019-12-18 16:32:55.654 T | mediakit::HttpSession::~HttpSession 000001D8AFA9BF60(127.0.0.1:54024)
iSMS.exe(16440) D:\work\projects\ictt\ZLMediaKit\src\Http\HttpSession.cpp 196
2019-12-18 16:33:13.869 T | mediakit::HttpSession::HttpSession 000001D8AFA9DC60(127.0.0.1:54034)
iSMS.exe(16440) D:\work\projects\ictt\ZLMediaKit\src\Rtsp\RtspPlayer.cpp 108
2019-12-18 16:33:13.871 D | mediakit::RtspPlayer::play rtsp://192.168.1.64:554/cam/realmonitor?channel=1&subtype=1
 admin123 0
"D:\work\projects\ictt\ZLMediaKit\src\Extension\SPSParser.c" line 687 [err]: **iCpbCount 109374 invalid**

iSMS.exe(16440) D:\work\projects\ictt\ZLMediaKit\src\Rtsp\RtspPlayer.cpp 756
2019-12-18 16:33:13.987 W | mediakit::RtspPlayer::onPlayResult_l 0 rtsp play success
iSMS.exe(16440) D:\work\projects\ictt\ZLMediaKit\src\Http\HttpSession.cpp 285
2019-12-18 16:33:29.668 W | mediakit::HttpSession::onError 000001D8AFA9DC60(127.0.0.1:54034) session timeouted
iSMS.exe(16440) D:\work\projects\ictt\ZLMediaKit\src\Http\HttpSession.cpp 204
2019-12-18 16:33:29.668 T | mediakit::HttpSession::~HttpSession 000001D8AFA9DC60(127.0.0.1:54034)

**Comment by xiongziliang** [comment]
从这个看 应该是pps sps异常导致的

**Comment by xiongziliang** [comment]
我本机也无法复现 很难定位

**Comment by xiongziliang** [comment]
也有可能是media-server这个项目更新导致的

**Comment by tsingeye** [comment]
> 我本机也无法复现 很难定位

整个vs 试试。
