### ISSUE TITLE
noneReader关闭推流然后立马重新推流出现推流失败

### ISSUE THREAD

**Issue by kqbi** [xiongziliang/ZLMediaKit#182]
![图片](https://user-images.githubusercontent.com/40823194/71155382-85892900-2278-11ea-918b-a4a907f83040.png)
noneReader后我关闭推流，然后立马重新推流出现推流失败，要等一小会才能重新推流成功是怎么回事

**Comment by xiongziliang** [comment]
都是异步的 异步就是说执行的顺序可能不确定 你关闭推流了，服务器可能还不知道。一般而言，这种临界状态很短，最大几秒钟而已。你说的一小会是多久？

**Comment by kqbi** [comment]
大概重推个3-4次都没成功，明天我再试试吧，谢谢了
