### ISSUE TITLE
vs 2019 compile error,thanks

### ISSUE THREAD

**Issue by qiri07** [xiongziliang/ZLMediaKit#185]
1严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C3861	“getTimeStr”: 找不到标识符	zlmediakit	D:\Github\ZLMediaKit\src\Record\HlsMakerImp.cpp	60	
2严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2660	“h264_annexbtomp4”: 函数不接受 7 个参数	zlmediakit	D:\Github\ZLMediaKit\src\Record\MP4Muxer.cpp	163	
3严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2672	“std::make_shared”: 未找到匹配的重载函数	zlmediakit	D:\Github\ZLMediaKit\src\Record\MP4Recorder.cpp	72	
4严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C3536	“strFileTmp”: 初始化之前无法使用	zlmediakit	D:\Github\ZLMediaKit\src\Record\MP4Recorder.cpp	72	
5严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C3536	“strFile”: 初始化之前无法使用	zlmediakit	D:\Github\ZLMediaKit\src\Record\MP4Recorder.cpp	63	
6严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2676	二进制“+”:“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”不定义该运算符或到预定义运算符可接收的类型的转换	zlmediakit	D:\Github\ZLMediaKit\src\Record\MP4Recorder.cpp	68	
7严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2676	二进制“+”:“std::string”不定义该运算符或到预定义运算符可接收的类型的转换	zlmediakit	D:\Github\ZLMediaKit\src\Record\MP4Recorder.cpp	57

**Comment by xiongziliang** [comment]
先更新子模块zltoolkit源码吧



发自我的iPhone


------------------ Original ------------------
