### ISSUE TITLE
Support HTTP JPEG and HTTP MJPEG source

### ISSUE THREAD

**Issue by thaibienbac** [xiongziliang/ZLMediaKit#186]
Hi,

Can I add HTTP JPEG stream or HTTP MJPEG stream to MediaServer ?
If you want to test JPEG stream, you can paste URL bellow to Internet Browse:
JPEG stream:http://118.70.125.33:21700/cgi-bin/camera
and paste URL bellow to Video Lan Player
MJPEG stream: http://118.70.125.33:21700/cgi-bin/mjpeg?

**Comment by xiongziliang** [comment]
Do you mean to support HTTP MJPEG streaming agent？
like this:
```
Camera  --mjpeg--> zlmediakit ----> rtsp/rtmp ?
```

**Comment by thaibienbac** [comment]
Yes, 

Some cameras only support HTTP MJPEG stream.

**Comment by xiongziliang** [comment]
So you need a HTTP MJPEG client ,and a HTTP MJPEG agent server.
This implementation is not very difficult，but this has nothing to do with zlmediakit's system .
Even if this is realized, it is also a very independent thing，So I'm not going to do this. Sorry

**Comment by xiongziliang** [comment]
But you can use the restful api（[addFFmpegSource](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#14indexapiaddffmpegsource%E7%9B%AE%E5%89%8Dwindows%E4%B8%8B%E6%97%A0%E6%95%88)） to supported this characteristic.

**Comment by thaibienbac** [comment]
But this api addFFmpegSource is invalid under windows

**Comment by xiongziliang** [comment]
> But this api addFFmpegSource is invalid under windows

@thaibienbac Now supported  under windows

**Comment by thaibienbac** [comment]
Thanks,

I will try it

**Comment by thaibienbac** [comment]
I was successfull to add MJPEG stream to MediaServer by api addFFmpegSource, but:
- the output stream only support rtmp ? how to support rtsp ?
- ffmpeg using more CPU to encode video from MJPEG to H264, can i restreaming this mjpeg source without encoding ?

**Comment by xiongziliang** [comment]
The addFFmpegSource api is a mechanism that start a ffmpeg process and then push a rtmp stream to zlmediakit which pulled from another one.


And zlmediakit will transform a rtmp(which pushed from ffmpeg) to rtsp/hls.

**Comment by thaibienbac** [comment]
Hi,

Today I am test again with "addFFmpegSource" and still get previous issue:
- by using "getMediaList" I am only see 1 RTMP stream, does not has rtsp/hls.
- when add a ffmpeg source, the console window will be show, how to hide it ?
