### ISSUE TITLE
资源回收问题

### ISSUE THREAD

**Issue by MrDiudiu** [xiongziliang/ZLMediaKit#187]
我用ZLMediaKit写了一个多线程读取关键帧的小项目，但是发现库的源码里面有资源回收上的bug
![image](https://user-images.githubusercontent.com/25821958/71344009-68b46480-259c-11ea-8751-465dbc137cb7.png)
![image](https://user-images.githubusercontent.com/25821958/71344028-77028080-259c-11ea-873b-a8fd3b96d2c7.png)
程序会在rtp 接收回调那里崩溃。崩溃的原因是已经调用的shutdown函数关闭了回调函数置空了，但是rtp接收回调依然会调用回调函数解析数据
![image](https://user-images.githubusercontent.com/25821958/71344072-8c77aa80-259c-11ea-9f2c-67ef6a355c28.png)
![image](https://user-images.githubusercontent.com/25821958/71344086-95687c00-259c-11ea-9999-b4407c465fd3.png)
![image](https://user-images.githubusercontent.com/25821958/71344096-9a2d3000-259c-11ea-9fc6-ce644848e2d3.png)
_aTrackInfo这个vector的size已经是0了

请问是什么问题导致这样的错误啊

**Comment by xiongziliang** [comment]
你这个不是rtsp 播放器的代码吗？你是怎么用的？播放的rtsp url是多少？能否暴露公网？

**Comment by MrDiudiu** [comment]
就是代码里的使用方法，play播放，在videotrack的delegate里完整读一帧关键帧，然后shutdown，循环几次就崩溃了。不能暴露公网

**Comment by MrDiudiu** [comment]
我用了大华的摄像头和一个捷高的摄像头，都有这个问题

**Comment by xiongziliang** [comment]
哪有你这样用的，你为什么要对一个RtspPlayer对象执行多种play操作？
RtspPlayer对象不是线程安全的，所以存在两个线程同时操作的可能性，分别是网络线程和你调用play函数的线程.

你这样的用法是莫名其妙且无意义的，我不知道你写这个代码的初衷和目的。
而且ZLMediaKit的几乎所有api都是非阻塞的，你知道你while(true)会执行多少次吗？

如果你想在其他线程多次控制一个player对象，建议切换到他的poller线程再操作，你可以参考这个代码：
https://github.com/xiongziliang/ZLMediaKit/blob/master/api/source/player.cpp#L57

**Comment by MrDiudiu** [comment]
![image](https://user-images.githubusercontent.com/25821958/71387226-d9579180-262d-11ea-9dc2-d8b9d5cbd3f8.png)
![image](https://user-images.githubusercontent.com/25821958/71387231-e1afcc80-262d-11ea-8547-a29e5b0e877d.png)
每次我都是new了一个新的MediaPlayer啊

**Comment by xiongziliang** [comment]
你这个player对象是成员变量吗？我看看声明。

**Comment by xiongziliang** [comment]
老实讲，你这个代码质量堪忧，
我很怀疑是你代码没用对。
