### ISSUE TITLE
api使用问题

### ISSUE THREAD

**Issue by kqbi** [xiongziliang/ZLMediaKit#188]
_media = mk_media_create("__defaultVhost__", "app", _outputDeviceInfo._deviceSSRC.c_str(), 0, 0, 0); 
  _pusher = mk_pusher_create("rtsp", "__defaultVhost__", "app", outputDeviceInfo._deviceSSRC.c_str()); if (_pusher) {
        mk_pusher_set_option(_pusher, "media_timeout_ms", "10000");
        mk_pusher_set_on_result(_pusher, mk_push_event, this);
        mk_pusher_publish(_pusher, url.c_str());
}

然后后边调用：
mk_media_init_h264(_media, (int) _metaData.nWidth, (int) _metaData.nHeight,
                                               _metaData.nFrameRate);
mk_media_input_h264(_media, (void *) data.data(), data.length(), _timeStamp, _timeStamp);
然后回调函数mk_push_event就会出现：
errorCode = 255, err_msg = the media source was released
正常传入h264然后推流是这样一个流程吗，我这样是那边有错误？

**Comment by xiongziliang** [comment]
不出意外是你在推流时，调用mk_media_release删除了MediaSource对象。
或者没有删除MediaSource对象，但是MediaSource对象却未注册。
你一定要看到日志中出现了 `regist`开头的日志才能调用mk_pusher_create。
因为mk_media_create是创建MediaSource，而mk_pusher_create要绑定一个已经注册的MediaSource。

你刚创建MediaSource如果还未输入数据，可能还未来得及注册。
你可以先输入sps pps来触发MediaSource的注册。

**Comment by kqbi** [comment]
char frame_start_code[4] = {0x00, 0x00, 0x00, 0x01};
    std::string data;
    data.append(frame_start_code, 4);
    data.append(spsData);
    data.clear();
    mk_media_input_h264(_media, (void *) data.data(), data.length(), _timeStamp, _timeStamp);
    data.append(frame_start_code, 4);
    data.append(ppsData);
    mk_media_input_h264(_media, (void *) data.data(), data.length(), _timeStamp, _timeStamp);
sps pps是输入了的，怎么开打印，没看到任何打印除了回调里自己加的打印

**Comment by kqbi** [comment]
我是在发sps和pps之前创建的push我放到后边试试

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/71392202-41b06e00-2642-11ea-803f-147782141ca6.png)
这是什么问题

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/71392555-60633480-2643-11ea-9735-748c1f8909c5.png)
还是不行，我并没有调用mk_media_release

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/71392879-cac8a480-2644-11ea-8ecb-6a29ea69cb90.png)
大佬麻烦指导下，我之前用librtmp推过流是没问题的，现在是想换成ZL的

**Comment by xiongziliang** [comment]
你在main函数中首先调用：
```C++
mk_env_init1(0, 0, 1, nullptr, 0, nullptr, nullptr);
```
然后把日志粘贴到issue，我分析下

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/71406950-9ec51780-2674-11ea-9ebd-2b16f4e8878d.png)
打印都差不多，好像没有太多有用的东西，之前收流解析都是自己写的，不行就都换成ZL的试试吧

**Comment by xiongziliang** [comment]
我就搞不懂 你绑定的还是rtsp的MediaSource，但是你为什么推rtmp的url?

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/71408153-1d6f8400-2678-11ea-95f2-6f39c3c63537.png)
你应该改成这样：
```
_pusher = mk_pusher_create("rtmp", "__defaultVhost__", "app", outputDeviceInfo._deviceSSRC.c_str());
//你的url不应该跟绑定的MediaSource协议一致吗?!
mk_pusher_publish(_pusher, url.c_str());

```

**Comment by xiongziliang** [comment]
如果你不知道你创建的流什么时候能注册上，那么你可以在确保输入sps pps后再mk_pusher_create创建对象。

或者监听on_mk_media_changed事件。

**Comment by kqbi** [comment]
好的，谢谢，我再试下，之前是这样：我传了sps和sps后会出现一个regist rtsp和一个regist rtmp，出现了两个source，然后推流push的url确实是rtmp的，我以为随便选一个源就可以，就选了每次先出现的rtsp的

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/71427324-6f54f000-26f2-11ea-9710-425be0900054.png)
成功了，太感谢大佬了！！！

**Comment by kqbi** [comment]
我创建push都放到发送关键帧之后了，还是有时候在rtmp注册之前创建push导致失败，估计是异步的关系，还是希望on_mk_media_changed能给出用户指针或者其他方式通知用户，能在真正注册后在创建push
