### ISSUE TITLE
海康IPC通过mediaserver由rtsp协议转成rtmp协议，vlc播放rtmp不时花屏

### ISSUE THREAD

**Issue by BeatTime** [xiongziliang/ZLMediaKit#189]
[rtmp_vlc播放花屏.zip](https://github.com/xiongziliang/ZLMediaKit/files/3997737/rtmp_vlc.zip)

附件是花屏时过滤1935端口的抓包

花屏时通过mediaserver录像，录像出来的MP4文件是正常的。

**Comment by xiongziliang** [comment]
你要tcp方式拉流

**Comment by BeatTime** [comment]
> 你要tcp方式拉流

tcp方式拉流，是指mediaserver从海康IPC上拉流要用RTP over RTSP吗？

**Comment by xiongziliang** [comment]
> > 你要tcp方式拉流
> 
> tcp方式拉流，是指mediaserver从海康IPC上拉流要用RTP over RTSP吗？

对

**Comment by BeatTime** [comment]
> > > 你要tcp方式拉流
> > 
> > 
> > tcp方式拉流，是指mediaserver从海康IPC上拉流要用RTP over RTSP吗？
> 
> 对

看了下海康ipc的网页设置，上面也没有这个设置。mediaserver能设置吗？
之前的抓包看，海康ipc那边过来的是
m=video 0 RTP/AVP 96

**Comment by xiongziliang** [comment]
你用什么接口拉流的？restful api?

**Comment by BeatTime** [comment]
是的，/index/api/addStreamProxy

**Comment by BeatTime** [comment]
主要它也不是一直都花屏不能看，只是有时会这样

**Comment by xiongziliang** [comment]
> 主要它也不是一直都花屏不能看，只是有时会这样

你可以把你的请求参数拷贝到这里。
另外你可以关注日志的黄色部分，看看有没有异常

**Comment by BeatTime** [comment]
请求参数：
http://127.0.0.1/index/api/addStreamProxy?vhost=__defaultVhost__&app=live&stream=stream_1&enable_rtsp=0&enable_rtmp=1&url=rtsp://admin:a1234567@192.168.10.92:554/h264/ch33/main/av_stream

日志:
目前就看到一个没有enable ssl的警告
![image](https://user-images.githubusercontent.com/16471634/71406850-573e8b80-2674-11ea-8567-80afd530fdbb.png)

**Comment by BeatTime** [comment]
![image](https://user-images.githubusercontent.com/16471634/71406890-72110000-2674-11ea-802c-435152db345f.png)

**Comment by xiongziliang** [comment]
你拉流方式是tcp。
你可以试试另外一个摄像头。
理论上讲，花屏不太可能是ZLMediaKit代码的问题。

你可以试试不同播放器或不同摄像头，看看花屏是普遍现象还是特例。

**Comment by xiongziliang** [comment]
前段时间，我把过滤不常见帧的代码删除了，这个有很小的可能性会导致花屏。
你可以把你这个花屏的rtsp url暴露到公网，可以通过这个软件实现：https://github.com/fatedier/frp

这样我才能本地测试，否则没法判断为什么花屏。

**Comment by BeatTime** [comment]
我先看下为什么这个摄像头变成了tcp拉流了，另一个摄像头是走的udp的。

**Comment by BeatTime** [comment]
> 我先看下为什么这个摄像头变成了tcp拉流了，另一个摄像头是走的udp的。

额，是我自己搞混了。我用vlc直接拉ipc是走的udp，mediaserver默认是tcp来拉。

**Comment by BeatTime** [comment]
夏总，frp这个工具我看了下，需要一台具有公网ip的服务器，目前我这边还没有。
另外我再测试会花屏的ipc，转发成rtsp和rtmp。rtsp可以正常播放，rtmp就会出现花屏。
![image](https://user-images.githubusercontent.com/16471634/71411516-8bba4380-2684-11ea-8c2e-f190e0caef77.png)

**Comment by xiongziliang** [comment]
如果你不能暴露公网，那么是没法做测试的和下结论的。
你可以看看hls/mp4/http-flv是否花屏

**Comment by BeatTime** [comment]
测试了http-flv、hls、rtmp。
rtmp和http-flv都会花屏，hls正常、录像MP4正常
![image](https://user-images.githubusercontent.com/16471634/71464087-6dbf2100-27f3-11ea-953e-6d3e22248190.png)

另外找了海康ipc，并没有花屏的情况，可能还是ipc出的码流问题

**Comment by xiongziliang** [comment]
你用最新代码试试

**Comment by BeatTime** [comment]
目前用了最新的代码，暂时没发现花屏了。感谢
