### ISSUE TITLE
你好, 我想用这个作为 rtsp server, streaming  监控录制的flv (h264 aac)

### ISSUE THREAD

**Issue by xfirefly** [xiongziliang/ZLMediaKit#19]
或者raw h264, raw aac流, 请问该从哪里开始, 没看到完善的example, 感谢

**Comment by xiongziliang** [comment]
你可以查看这个类的代码[Device](https://github.com/xiongziliang/ZLMediaKit/blob/master/src/Common/Device.h)，这个类输入264、AAC能生成rtsp/rtmp/hls流。
或者可以查看这个类[MediaReader](https://github.com/xiongziliang/ZLMediaKit/blob/master/src/MediaFile/MediaReader.h)，这个类可以把mp4文件转换成rtsp/rtmp/hls流。
