### ISSUE TITLE
onPipeEvent take time:14ms

### ISSUE THREAD

**Issue by woshiwoyali** [xiongziliang/ZLMediaKit#192]
![image](https://user-images.githubusercontent.com/22191779/71437837-44888d00-272e-11ea-885a-da16a3d57ec0.png)
请问，标红的地方如何理解呀！

**Comment by xiongziliang** [comment]
debug模式下性能分析相关代码
如果某个函数执行时间太长 就会打印这个代码



发自我的iPhone


------------------ Original ------------------

**Comment by woshiwoyali** [comment]
您好，函数执行时间太长，是否会影响到视频加载的时间？函数执行时间过长的可能原因有哪些呀？

**Comment by xiongziliang** [comment]
不会 只要不是频繁打印 就没关系



发自我的iPhone


------------------ Original ------------------

**Comment by woshiwoyali** [comment]
好的 ，感谢您的回复
