### ISSUE TITLE
调用 /index/api/addStreamProxy，到成功拉流显示，大概需要多久时间？

### ISSUE THREAD

**Issue by woshiwoyali** [xiongziliang/ZLMediaKit#193]
当服务开启后，在网页上调用/index/api/addStreamProxy接口，大约需要多久才可以使用ffplay 播放此流？

**Comment by xiongziliang** [comment]
可以立即播放，实际上，在这个接口调用前10秒也可以播放。
ZLMediaKit如果未找到流，会让播放器最多等待10秒左右
