### ISSUE TITLE
web hook问题

### ISSUE THREAD

**Issue by tsingeye** [xiongziliang/ZLMediaKit#195]
1.开启hook，on_http_access=http://127.0.0.1/index/hook/on_http_access
2.使用H5播放器播放HLS 视频流时，会触发几次hook呢？我实际测试中发现 第一步获取hls.m3u8会触发，后续再获取ts文件也会触发。是设计如此吗？

**Comment by xiongziliang** [comment]
这个是http文件服务器做鉴权用的，
hls鉴权我做了特殊处理，你用on_play事件即可

**Comment by tsingeye** [comment]
on_http_access 我还用了作为下载mp4文件的鉴权，如果这个打开了，好像是会影响hls吧。

**Comment by xiongziliang** [comment]
只要你设置的鉴权目录不互相覆盖，那么就不会冲突的。

**Comment by xiongziliang** [comment]
建议你这么实现文件下载：
```C++
 API_REGIST_INVOKER(api,downloadBin,{
        CHECK_SECRET();
        invoker.responseFile(headerIn,StrCaseMap(),exePath());
    });
```

**Comment by xiongziliang** [comment]
现在ZLMediaKit支持http api方式下载文件

**Comment by xiongziliang** [comment]
这样有个好处，就是在下载时可以做一些人的逻辑，譬如查询数据库。
而且下载地址跟文件路径也无关。

**Comment by tsingeye** [comment]
我来试试

**Comment by tsingeye** [comment]
> 只要你设置的鉴权目录不互相重叠，那么就不会冲突的。

鉴权目录是怎么设置呢？ hls流还是存放在 httpRoot 里面， 是改掉这个吗？

**Comment by tsingeye** [comment]
另外，如果按默认设置的话，我开启保存hls了，同时开启on_http_access， 用ffplay可以播放，但是用H5播放器就不能播放。还是触发on_http_access没有回复问题，

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/71508592-46378980-28c3-11ea-9ab7-90f85b474d0a.png)

![image](https://user-images.githubusercontent.com/11495632/71508605-50f21e80-28c3-11ea-96c1-294e55e66efd.png)

**Comment by tsingeye** [comment]
谢谢大佬

**Comment by xiongziliang** [comment]
http鉴权的逻辑是，
- 1、先判断是否为hls.m3u8文件后缀，是的话触发kBroadcastMediaPlayed事件（on_play）。
- 2、如果返回播放鉴权成功，那么设置cookie，并设置cookie有效作用路径是 hls.m3u8所在目录。
- 3、下次播放器以该cookie访问同目录下的所有文件都有权限(不会再触发获取)。
- 4、hls 的cookie的有效期是60秒，每次访问该cookie会刷新过期时间。

如果不是hls.m3u8文件，那么走http文件鉴权事件kBroadcastHttpAccess（on_http_access）。

**Comment by xiongziliang** [comment]
假定你的其他文件放在hls.m3u8文件所在目录以及子目录下，那么用hls鉴权的cookie同样可以有权限访问该文件(而不会触发kBroadcastHttpAccess/on_http_access事件)。
但是ZLMediaKit的hls文件夹是临时文件夹，一般不会有其他文件存在。

**Comment by xiongziliang** [comment]
所以文件下载鉴权事件，例如上是不会跟hls播放鉴权事件冲突的

**Comment by tsingeye** [comment]
好的。我业务服务之前都是靠on_http_access，看来用错了， 改on_play试试

**Comment by tsingeye** [comment]
> 所以文件下载鉴权事件，理论上是不会跟hls播放鉴权事件冲突的。而我实测也是不会。

downloadBin的wiki还没更新哈。

**Comment by xiongziliang** [comment]
那个是个范例 懂得人自然懂 其实还有些api没写上去 因为一般的人用不到



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tsingeye <notifications@github.com&gt;
发送时间: 2019年12月27日 16:30
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] web hook问题 (#195)



 
所以文件下载鉴权事件，理论上是不会跟hls播放鉴权事件冲突的。而我实测也是不会。
  
downloadBin的wiki还没更新哈。

**Comment by tsingeye** [comment]
> 那个是个范例 懂得人自然懂 其实还有些api没写上去 因为一般的人用不到 发自我的iPhone


好的。，

**Comment by huyji-000** [comment]
vlc等播放器可以根据响应头保持同一个cookie，所以后续的下载m3u8和ts都没有问题
但是web播放器每次请求都是一个新的cookie，因此导致，每次下载m3u8会调用on_play,每次下载ts会调用on_http_access

这种情况下，考虑使用参数形式保持会话,m3u8链接后面追加参数后，可以实现会话保持
但是m3u8文件中存的ts文件没有加参数，所以每次下载ts还是在根据cookie判断会话，仍然频繁调用on_http_access

请问能否在响应m3u8时，在ts文件后面加上hls链接同样的鉴权参数，这个容易实现吗

**Comment by xia-chu** [comment]
hls的cookie鉴权基本已经废了 这个需要播放器的配合 跨域了就GG了，有些播放器也不支持cookie(例如vlc)。
hls鉴权有通过url跳转加参数的方法来实现鉴权，但是我没时间搞这个，而且我觉得hls在直播中也不是很重要，这个功能没有也不太影响，所以没去做

**Comment by huyji-000** [comment]
确实hls延迟大，不太好用
但是ios的h5页面只能播放hls

**Comment by huyji-000** [comment]
m3u8是直接将磁盘文件返回了吗
如果能在响应m3u8时ts后面追加参数，问题就解决了

**Comment by xia-chu** [comment]
> 确实hls延迟大，不太好用 但是ios的h5页面只能播放hls

可以webrtc了

**Comment by huyji-000** [comment]
webrtc也试过，ios原生浏览器是可以的，钉钉里面h5就不行了

**Comment by xia-chu** [comment]
> m3u8是直接将磁盘文件返回了吗 如果能在响应m3u8时ts后面追加参数，问题就解决了

那没用啊 难道m3u8每人都生成一个？hls的设计 本身就是依赖http的基础设施，应该跟http是解耦的，现在zlm把hls的业务带进http服务器 我就很不乐意了 现在更不想继续破坏http服务器纯粹性了

**Comment by huyji-000** [comment]
好吧，那就算了，我临时把ts鉴权给过滤掉了

```
if(start_with(path,"/rtp/") && end_with(path,".ts")){
        callback("", nullptr);
        return;
    }
```

有点low....
