### ISSUE TITLE
RTSP 双向视频对讲 and  pull -then - push

### ISSUE THREAD

**Issue by hug2008** [xiongziliang/ZLMediaKit#198]
1. 是否支持RTSP 双向视频对讲，如何实现？
2. 如何 先拉流PULL 后 推流PUSH呢？

**Comment by xiongziliang** [comment]
rtsp你要做双向对讲也不是不可以，虽然比较挫，但是好在简单。

**Comment by xiongziliang** [comment]
你可以先让对方pull 再push上去也行
ZLMediaKit再未找到流时会让播放器最多等待10秒(可配置)左右，只要你在这个时间内推流上去，那么播放器就能播放成功

**Comment by hug2008** [comment]
https://github.com/xiongziliang/ZLMediaKit/blob/84de9720b5c517da4229dd46ba27e554998a9af0/conf/config.ini#L189
配置
#rtsp必须在此时间内完成握手，否则服务器会断开链接，单位秒
handshakeSecond=15
#rtsp超时时间，如果该时间内未收到客户端的数据，
#或者tcp发送缓存超过这个时间，则会断开连接，单位秒
keepAliveSecond=15

？

1. 双向对讲性能会很差吗？
2. tests/test_server.cpp 的RTSP demo 就可以实现双向？

**Comment by xiongziliang** [comment]
不会啊 除了延时大点 其他没啥问题。
你说的双向对讲不知道指不指两人同时说话？两人同时说话会有回声。

你用MediaServer进程测试吧，这个才是主进程。

**Comment by hug2008** [comment]
"两人同时说话会有回声"
有没有解决的途径呢？

**Comment by xiongziliang** [comment]
用webrtc 的aec消回声
但是在延时抖动比较的情况下 效果也不是很好

**Comment by GLIUYANG** [comment]
请问解决了此问题吗，我也有相同的需求

**Comment by xia-chu** [comment]
建议用webrtc做双向对讲
