### ISSUE TITLE
这个有在项目中实际使用过吗，没有几个issues 

### ISSUE THREAD

**Issue by martin-huang** [xiongziliang/ZLMediaKit#2]

**Comment by xiongziliang** [comment]
这个项目经过几个月的高强度烤机测试，代码也通过长时间的valgrind的跟踪调试，如果你的业务不是海量级别的，完全够你用了

**Comment by xiongziliang** [comment]
这套代码在ios linux 嵌入式平台都长时间测试过，我们也应用到了实际的产品，其他平台我也全部做过功能测试。

**Comment by gzsll** [comment]
@xiongziliang 有没有android使用rtsp server 使用说明

**Comment by xiongziliang** [comment]
android我跑过测试程序，没有问题，已经有群里面的朋友拿去做生产电子后视镜用了，他们反馈的结果是非常稳定

**Comment by xiongziliang** [comment]
rapidvms这个商业项目也用我的项目构建rtsp hls rtmp服务器了

**Comment by gzsll** [comment]
有没有推h264到rtsp server的例子

**Comment by xiongziliang** [comment]
没有 暂时不支持rtsp推流
