### ISSUE TITLE
addTrack总是有问题是为什么？

### ISSUE THREAD

**Issue by yuhu-fei11** [xiongziliang/ZLMediaKit#200]
我是先调用的addTrack，然后在调用inputFrame函数，但是inputFrame内会将track清除，每次都会都是这样，就会导致初始化不成功。是我addTrack没有成功吗，还是调用的顺序有问题呢？

**Comment by xiongziliang** [comment]
你直接用DevChannel类吧，这个简单点。

**Comment by xiongziliang** [comment]
- 1、你往哪个对象addTrack、inputFrame？
- 2、什么叫清除？是忽略了吗？
- 3、MediaSink类会忽略10秒后还未初始化成功的Track。
- 4、初始化H264 Track成功需要inputFrame  sps/pps，你传入了吗？

**Comment by yuhu-fei11** [comment]
上面描述的不是太清楚，我是用的DevChannel中initVideo和inputH264，这两个函数，因为调用以后总生成不了ts文件，所有就走断点调试了一下，结果发现在MediaSink::inputFrame时，第一次输入帧的时候就会走_track_map.erase这个语句移除未准备好的Track，每次第一次输入帧都会是这样的结果，然后if (it == _track_map.end()) {return;} 帧就会输入不进去了。

**Comment by xiongziliang** [comment]
> * 1、你往哪个对象addTrack、inputFrame？
> * 2、什么叫清除？是忽略了吗？
> * 3、MediaSink类会忽略10秒后还未初始化成功的Track。
> * 4、初始化H264 Track成功需要inputFrame  sps/pps，你传入了吗？



> 上面描述的不是太清楚，我是用的DevChannel中initVideo和inputH264，这两个函数，因为调用以后总生成不了ts文件，所有就走断点调试了一下，结果发现在MediaSink::inputFrame时，第一次输入帧的时候就会走_track_map.erase这个语句移除未准备好的Track，每次第一次输入帧都会是这样的结果，然后if (it == _track_map.end()) {return;} 帧就会输入不进去了。

说明你未在10秒内输入sps pps

**Comment by yuhu-fei11** [comment]
同样的码流在旧版本的ZLMediaKit输入就能生成ts切片，为什么到新的版本中就不行了呢，而且我将码流输出到文件中看了一下，sps和pps到来的时间大概是在2-4秒内。所以肯定会在10秒内输入啊。

**Comment by xiongziliang** [comment]
新版本如果还能正常把rtmp/rtsp转换成hls，那么hls生成就应该没问题。
DevChannel也是调用MultiMediaSourceMuxer对象生成的hls，代码都是相同的。

**Comment by yuhu-fei11** [comment]
嗯嗯，好的，感谢大佬的解惑，我再试试。
