### ISSUE TITLE
/index/api/addStreamProxy接口，并发执行会出现什么问题？

### ISSUE THREAD

**Issue by woshiwoyali** [xiongziliang/ZLMediaKit#201]
您好，如果当启动web界面的时候，并发调用多次/index/api/addStreamProxy即可，把外网rtsp流转发成本地的rtsp流，并发执行的话，会出现什么问题吗？

**Comment by xiongziliang** [comment]
只要流的4元组不相同，那么就不会有问题。
如果4元组相同，那么就会存在竞争注册的问题。

**Comment by xiongziliang** [comment]
这里讲了什么叫4元组：
https://github.com/xiongziliang/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99
