### ISSUE TITLE
[Feature Request] ]add srt support

### ISSUE THREAD

**Issue by syklevin** [xiongziliang/ZLMediaKit#202]
你好，請問有考慮添加對srt的支持嗎？相比rtpm/rstp，在移動網絡應該能有更穩定和低延遲的播放體驗

**Comment by xiongziliang** [comment]
你好，目前这个并未划入ZLMediaKit的规划，不过我目前正在着手kcp协议的整合，跟srt类似，也是可靠的udp协议。

如果后续我有时间，可能会考虑实现srt，但是目前手上事情很多，暂时不太可能展开这个工作。
