### ISSUE TITLE
大佬，通过DevChannel::inputH264 插入数据指针char* pcData，需要自己释放吗？

### ISSUE THREAD

**Issue by neuskb** [xiongziliang/ZLMediaKit#203]

**Comment by xiongziliang** [comment]
要自己释放啊 ，如果你想避免内存拷贝，建议你还是自己生成H264Fame。
ZLMediaKit在里面生成rtmp/hls/mp4 会拷贝你的内存的。

**Comment by neuskb** [comment]
传入的pcData zlmedia会copy一份？

**Comment by xiongziliang** [comment]
嗯 我改下接口吧 之前的老接口会导致内存多次拷贝 本来可以一次拷贝都不用
现在回变成多次拷贝了 也是无奈

**Comment by neuskb** [comment]
噢 会copy一份也没问题，因为一个frame 我自己外部代码用了一次，然后又给zlmedia传了一次。
zlmedia会copy一次，那我外部自己使用的先释放 也没关系了。

**Comment by xiongziliang** [comment]
现在在DevChannel里面会拷贝一次，在合并相同SPS PPS IDR帧时也会拷贝一次，基本只会拷贝一次了。

**Comment by xiongziliang** [comment]
mp4/hls/rtmp要求时间戳相同的帧要在一起，rtsp就没这个要求
