### ISSUE TITLE
调用 /index/api/addStreamProxy,流中断一段时间后会发生什么事情？

### ISSUE THREAD

**Issue by woshiwoyali** [xiongziliang/ZLMediaKit#204]
您好，调用 /index/api/addStreamProxy接口，将外网rtsp流转发到本地，如果出现流间歇性的中断或者是卡顿（网络原因），那么转发到本地的流会发生什么？中断后是否还可以转发？

**Comment by xiongziliang** [comment]
源都断了 那肯定也断了啊

**Comment by woshiwoyali** [comment]
您好，在咨询一个问题，如果硬件条件允许的话，我是不是可以理解为 可以无上线的去调用/index/api/addStreamProxy接口来转发rtsp流？
我将调用哪个接口，来查看服务中转发的所有流的地址呢？

**Comment by xiongziliang** [comment]
对 只要你机器跟得上 是没限制的。
另外一个问题你可以查看wiki关于restful api的篇章

**Comment by woshiwoyali** [comment]
好的，感谢您的回答。

**Comment by woshiwoyali** [comment]
您好，当我调用/index/api/getMediaList接口时，返回的列表中包含
app： 
schema：
vhost：
stream：
这些参数，如果我想把客户端的IP也获取到，我需要在代码中添加什么？

**Comment by xiongziliang** [comment]
不能，因为生成流不仅仅是通过推流，还有其他方式。

你可以对接hook接口，在hook接口中会汇报推流ip给你

**Comment by woshiwoyali** [comment]
好的！感谢您的回答！
