### ISSUE TITLE
如何关闭转发的rtsp流？

### ISSUE THREAD

**Issue by woshiwoyali** [xiongziliang/ZLMediaKit#205]
您好，当我启动服务时，在局域网内的另外两台电脑，依次去调用/index/api/addStreamProxy接口将不同的rtsp流转发到本地，我将如何操作才可以实现，将其中一台电脑上转发的流全部结束掉，另外一台电脑转发的流保存不变？

**Comment by xiongziliang** [comment]
/index/api/addStreamProxy接口有返回值，你用这个返回值用/index/api/delStreamProxy删除即可
