### ISSUE TITLE
通过rtsp向server取流，过一会中断

### ISSUE THREAD

**Issue by neuskb** [xiongziliang/ZLMediaKit#206]
大佬有遇到过这个问题吗？ 之前一直用rtmp，播放没有问题
最近改成vlc用rtsp取流，过一会就中断了。

抓包看 推流中断了，用的zlmedia版本是19年10月份左右的。

**Comment by neuskb** [comment]
用vlc rtmp方式  播放没问题

**Comment by neuskb** [comment]
![微信截图_20200109171020](https://user-images.githubusercontent.com/55521963/72053919-f3b68e00-3302-11ea-902a-91e8959822f5.png)

**Comment by xiongziliang** [comment]
不要vlc 因为vlc默认udp方式拉流，但是有时却不发rtcp包，导致ZLMediaKit判断播放器已经离线了。
你可以采用tcp方式播放或者用ffplay播放rtsp

**Comment by neuskb** [comment]
大佬  vlc改成tcp 确实不断开了， 问下改成tcp zlmedia就不会判断rr报文了吗？

**Comment by xiongziliang** [comment]
tcp 不用rr包保活，tcp接收端消费数据后会发送ack包，发送端根据发送缓存长度可以判断接收端是否存活

**Comment by neuskb** [comment]
多谢大佬~
