### ISSUE TITLE
编译报internal compiler error错

### ISSUE THREAD

**Issue by cuijinquan** [xiongziliang/ZLMediaKit#207]
/ZLMediaKit/api/source/mk_tcp.cpp:271:1:   required from here
/ZLMediaKit/src/Http/WebSocketClient.h:306:78: internal compiler error: in build_base_path, at cp/class.c:278
                 WebSocketSplitter::decode((uint8_t*)pBuf->data(),pBuf->size());

test_wsClient.cpp已删除了,还是报这个错.

**Comment by xiongziliang** [comment]
这个是GCC4.85的bug导致的，应该是不支持某项C++的特性导致编译器出错。
相关的文件是src/Http/WebSocketClient.h

## 方法一
解决方法有两个步骤:
- 1、删除tests/test_wsClient.cpp
- 2、打开CMakeList.txt，定位约第196行，注释之：
```cmake
#add_subdirectory(api)
```

然后重新cmake即可编译通过。
这样做有个缺点，就是不能再生成 c api库了。

## 方法二
- 1、你可以升级你的gcc至高版本
- 2、使用clang编译
