### ISSUE TITLE
/index/api/getMediaInfo 无法调用？

### ISSUE THREAD

**Issue by woshiwoyali** [xiongziliang/ZLMediaKit#208]

**Comment by woshiwoyali** [comment]
http://192.168.1.107:8010/index/api/addStreamProxy?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost__&app=live&stream=ABCD&enable_rtsp=1&enable_rtmp=0&url=rtsp:xxxxxxxx/h265/ch1/sub/av_stream
成功将rtsp流转到了本地。
code 
data 
key "__defaultVhost__/live/ABCD"
当我在调用接口http://192.168.1.107:8010/index/api/getMediaInfo?schema=rtsp&vhost=__defaultVhost__&app=live&stream=ABCD
发现不能访问，显示404：

您访问的资源不存在！
ZLMediaKit-4.0

**Comment by xiongziliang** [comment]
我猜是你的代码版本比较老的原因，因为这个接口是后面加的。
你可以访问这个接口：http://127.0.0.1/index/api/getApiList
获取支持的api

**Comment by woshiwoyali** [comment]
好的，我更新一下代码，感谢您的回复！
