### ISSUE TITLE
使用api推流问题

### ISSUE THREAD

**Issue by kqbi** [xiongziliang/ZLMediaKit#209]
我用api里的push推送一路rtmp流到ZL的流媒体server（ssl是编译了的），使用flash播rtmp不出来（http-flv和hls可以播放），同样的数据我用librtmp推送到同一个ZL的server，rtmp可以播放是什么原因

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/72140661-2bd5d380-33cc-11ea-8995-86eb93b10c46.png)
这个的videocodecid是AVC1，是用api的push推送的rtmp的流点播时出现的，无法播放
![图片](https://user-images.githubusercontent.com/40823194/72140756-6c355180-33cc-11ea-9d3b-734c97adb625.png)
这个是ffpmeg推送的rtmp的流播放时的videocodecid是7，能正常播放

**Comment by xiongziliang** [comment]
因为android系统对flv的文件只支持avc1,所以我才在metedata设置为avc1。
播放器和服务器都应该同时支持7和avc1,如果不支持，这说明兼容性不行。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kqbi <notifications@github.com&gt;
发送时间: 2020年1月10日 17:14
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 使用api推流问题 (#209)





 这个的videocodecid是AVC1，是用api的push推送的rtmp的流点播时出现的，无法播放
 
 这个是ffpmeg推送的rtmp的流播放时的videocodecid是7，能正常播放

**Comment by xiongziliang** [comment]
这个问题已经修复，请更新最新代码！
