### ISSUE TITLE
咨询下pusher使用问题

### ISSUE THREAD

**Issue by neuskb** [xiongziliang/ZLMediaKit#211]
大佬，我这边通过往devchannel塞h264数据，然后是在自己线程中通过make_shared 创建一个MediaPusher， 通过这个往zlmediaserver 推数据，这个mediapusher 在上层代码析构的时候 会强制放掉，这个时候有几率程序会崩溃，是不是zlmedia内部还在用MediaPusher？

**Comment by neuskb** [comment]
停止推流的时候 需要先调用下teardown吗？然后再清理MediaPusher？

**Comment by xiongziliang** [comment]
把你的代码粘贴出来看看?

**Comment by neuskb** [comment]
typedef void* ProcPusher;

	class PusherContext
	{
	public:
		MediaPusher::Ptr _pusher;
		DevChannel::Ptr _dev_channel;
		Timer::Ptr _timer;
	};

	// 前向引用声明
	void rePushDelay(PusherContext* pc, const EventPoller::Ptr& poller, const string& schema, const string& vhost, const string& app, const string& stream, const string& url);

	// 创建推流器并开始推流
	void createPusher(PusherContext* pc, const EventPoller::Ptr& poller, const string& schema, const string& vhost, const string& app, const string& stream, const string& url) {
		// 创建推流器并绑定一个MediaSource
		pc->_pusher = std::make_shared<MediaPusher>(schema, vhost, app, stream, poller);
		// 可以指定rtsp推流方式，支持tcp和udp方式，默认tcp
		// (*pusher)[Client::kRtpType] = Rtsp::RTP_UDP;
		// 设置推流中断处理逻辑
		pc->_pusher->setOnShutdown([pc, poller, schema, vhost, app, stream, url](const SockException& ex) {
			WarnL << "Server connection is closed:" << ex.getErrCode() << " " << ex.what();
			rePushDelay(pc, poller, schema, vhost, app, stream, url); // 重试
			});
		// 设置发布结果处理逻辑
		pc->_pusher->setOnPublished([pc, poller, schema, vhost, app, stream, url](const SockException& ex) {
			if (ex) {
				WarnL << "Publish fail:" << ex.getErrCode() << " " << ex.what();
				// 如果发布失败，就重试
				rePushDelay(pc, poller, schema, vhost, app, stream, url);
			}
			else {
				InfoL << "Publish success,Please play with player:" << url;
			}
			});
		pc->_pusher->publish(url);
	}

	// 推流失败或断开延迟10秒后重试推流
	void rePushDelay(PusherContext* pc, const EventPoller::Ptr& poller, const string& schema, const string& vhost, const string& app, const string& stream, const string& url) {
		pc->_timer = std::make_shared<Timer>(10, [pc, poller, schema, vhost, app, stream, url]() {
			InfoL << "Re-Publishing...";
			//重新推流
			createPusher(pc, poller, schema, vhost, app, stream, url);
			//此任务不重复
			return false;
			}, poller);
	}

	ProcPusher create_inproc_pusher(const InitParam& init_param)
	{
		EventPoller::Ptr poller = EventPollerPool::Instance().getPoller();
		std::string pushUrl = init_param.url;

		PusherContext* pc = new PusherContext();
		pc->_dev_channel = std::make_shared<DevChannel>(init_param.vhost, init_param.app, init_param.stream, 0, true, true, false, false);

		// 监听RtmpMediaSource注册事件,在PlayerProxy播放成功后触发
		NoticeCenter::Instance().addListener(nullptr, Broadcast::kBroadcastMediaChanged,
			[pushUrl, poller, pc](BroadcastMediaChangedArgs) {
				// 媒体源"app/stream"已经注册，这时方可新建一个RtmpPusher对象并绑定该媒体源
				if (bRegist && pushUrl.find(schema) == 0) {
					createPusher(pc, poller, schema, vhost, app, stream, pushUrl);
				}
			});
		return pc;
	}

	void init_h264_video(ProcPusher pusher, const VideoInfo& video_info)
	{
		PusherContext* pc = (PusherContext*)pusher;
		mediakit::VideoInfo vi;
		vi.iWidth = video_info.width;
		vi.iHeight = video_info.height;
		vi.iFrameRate = video_info.fps;
		pc->_dev_channel->initVideo(vi);
	}

	void input_h264_video(ProcPusher pusher, const char* pcData, int iDataLen, uint32_t dts, uint32_t pts)
	{
		PusherContext* pc = (PusherContext*)pusher;
		pc->_dev_channel->inputH264(pcData, iDataLen, dts, pts);
	}

	void destroy_inproc_pusher(ProcPusher pusher)
	{
		delete (PusherContext*)pusher;
	}

以上是代码

下面是core信息：
#0  0x000000000049cdfc in __gnu_cxx::__exchange_and_add (__mem=0x420400187048, __val=-1) at /opt/hisi-linux/x86-arm/aarch64-himix100-linux/aarch64-linux-gnu/include/c++/6.3.0/ext/atomicity.h:49
49	/opt/hisi-linux/x86-arm/aarch64-himix100-linux/aarch64-linux-gnu/include/c++/6.3.0/ext/atomicity.h: No such file or directory.
[Current thread is 1 (LWP 20658)]
(gdb) bt
#0  0x000000000049cdfc in __gnu_cxx::__exchange_and_add (__mem=0x420400187048, __val=-1) at /opt/hisi-linux/x86-arm/aarch64-himix100-linux/aarch64-linux-gnu/include/c++/6.3.0/ext/atomicity.h:49
#1  0x000000000049cee8 in __gnu_cxx::__exchange_and_add_dispatch (__mem=0x420400187048, __val=-1) at /opt/hisi-linux/x86-arm/aarch64-himix100-linux/aarch64-linux-gnu/include/c++/6.3.0/ext/atomicity.h:82
#2  0x00000000004ac840 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x420400187040) at /opt/hisi-linux/x86-arm/aarch64-himix100-linux/aarch64-linux-gnu/include/c++/6.3.0/bits/shared_ptr_base.h:147
#3  0x00000000004ab994 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7efe24db68, __in_chrg=<optimized out>)
    at /opt/hisi-linux/x86-arm/aarch64-himix100-linux/aarch64-linux-gnu/include/c++/6.3.0/bits/shared_ptr_base.h:662
#4  0x0000007fa51fd7f8 in std::__shared_ptr<mediakit::MediaPusher, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#5  0x0000007fa51fdf4c in std::__shared_ptr<mediakit::MediaPusher, (__gnu_cxx::_Lock_policy)2>::operator=(std::__shared_ptr<mediakit::MediaPusher, (__gnu_cxx::_Lock_policy)2>&&) ()
   from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#6  0x0000007fa51fda7c in std::shared_ptr<mediakit::MediaPusher>::operator=(std::shared_ptr<mediakit::MediaPusher>&&) () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#7  0x0000007fa51fadf4 in InProcPusher::createPusher(InProcPusher::CInProcessPusherContext*, std::shared_ptr<toolkit::EventPoller> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#8  0x0000007fa51fb28c in InProcPusher::create_inproc_pusher(InProcPusher::InitParam const&)::{lambda(bool const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mediakit::MediaSource&)#1}::operator()(bool const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mediakit::MediaSource&) const ()
   from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#9  0x0000007fa51fc3b4 in std::_Function_handler<void (bool const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mediakit::MediaSource&), InProcPusher::create_inproc_pusher(InProcPusher::InitParam const&)::{lambda(bool const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mediakit::MediaSource&)#1}>::_M_invoke(std::_Any_data const&, bool const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mediakit::MediaSource&) () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#10 0x0000007fa5144928 in std::function<void (bool&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, mediakit::MediaSource&)>::operator()(bool&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, mediakit::MediaSource&) const () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#11 0x0000007fa5142e18 in bool toolkit::NoticeCenter::emitEvent<bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, mediakit::MediaSource&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, mediakit::MediaSource&) () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#12 0x0000007fa513af24 in mediakit::MediaSource::regist() () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#13 0x0000007fa5108134 in mediakit::RtspMediaSource::onGetSDP(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#14 0x0000007fa5108bb8 in mediakit::RtspMediaSourceMuxer::onAllTrackReady() () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#15 0x0000007fa5134748 in mediakit::MediaSink::inputFrame(std::shared_ptr<mediakit::Frame> const&) () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#16 0x0000007fa510aca4 in MultiMediaSourceMuxer::inputFrame(std::shared_ptr<mediakit::Frame> const&) () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so
#17 0x0000007fa51050e4 in mediakit::DevChannel::inputH264(char const*, int, unsigned int, unsigned int) () from /home/rundir/sensetime/third_party/zlmediakit/lib/libzlmediakit.so

**Comment by xiongziliang** [comment]
你这句代码崩溃了：
![image](https://user-images.githubusercontent.com/11495632/72312350-d3038500-36c2-11ea-99b5-6800890bcc45.png)
原因不出意外是你这个PusherContext对象已经被你delete掉了。

你在异步线程里面访问一个裸指针，你怎么确保这个弱指针事件触发时没被你delete掉？
你为什么不用weak_ptr来包装下你的裸指针？跨线程异步回调最忌讳的就是裸指针。


重申一遍，不要用裸指针！

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/72312490-45746500-36c3-11ea-9a9c-7692d5b892af.png)
这里不要创建裸指针，不要捕获裸指针，不要使用裸指针，一定要转变你的传统思维！

**Comment by neuskb** [comment]
多谢大佬 我再看下

**Comment by neuskb** [comment]
大佬我还有个疑问， 在停止推流时候，我还需要做额外的清理操作吗？除了删除mediapusher

**Comment by xiongziliang** [comment]
你要删除mediapusher，以便端口rtmp推流的tcp连接。
还有删除DevChannel对象。
其他没有额外的操作了

**Comment by neuskb** [comment]
好的  多谢大佬
