### ISSUE TITLE
general.addMuteAudio no effect 

### ISSUE THREAD

**Issue by xiongguangjie** [xiongziliang/ZLMediaKit#212]
commit:b55db11de314b2321213275b2d01cf1900b7f5f0
OS:ubuntu 19.10
gcc:9.2.1
rtmp 推流 （仅仅是视频流，无音频）
flv.js 播放 ws-flv,发现输出的流没有加上静音的音频（可以只播放视频）
我记得以前是可以的。

**Comment by xiongziliang** [comment]
zlmediakit只会对拉流代理添加静音音频，推流不会增加的
