### ISSUE TITLE
Customize recording path with /index/api/startRecord

### ISSUE THREAD

**Issue by thaibienbac** [xiongziliang/ZLMediaKit#213]
Hi,

Can I customize recording path as "D:\\Video" or "E:\\Video" instead of a folder inside www folder when setting "customized_path" parrameter ?

**Comment by xiongziliang** [comment]
No, the customized_path is a relative path in hls file root path.
Absolute path cannot be specified due to security considerations.

**Comment by thaibienbac** [comment]
Thanks
