### ISSUE TITLE
rtsp转rtmp问题？

### ISSUE THREAD

**Issue by lookforit** [xiongziliang/ZLMediaKit#214]
请问有rtsp地址转rtmp的示例吗？资源消耗怎么样，延时如何？

**Comment by xiongziliang** [comment]
你推流到 rtmp://zlmediakit.com/live/test吧，
会自动转换成rtsp://zlmediakit.com/live/test

资源消耗很低，具体多低，你自己测试吧，你不测试，我说的你也不信
