### ISSUE TITLE
wsServer使用问题

### ISSUE THREAD

**Issue by JerryLinGd** [xiongziliang/ZLMediaKit#216]
我想使用wsServer做一个设备网关，管理多个厂家的设备（设备都采用ws，但是协议完全不一样）。我想使用注册地址来区分不同厂家的设备，比如ws://域名（或ip：端口）/dev/ADev，ws://域名（或ip：端口）/dev/BDev，这样我可以通过地址来区分设备类型，请问可以做得到吗？

**Comment by xiongziliang** [comment]
刚实现了这个功能，请参考test_wsServer.cpp

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/72413067-e50c2300-37a9-11ea-8481-71598463144f.png)

**Comment by JerryLinGd** [comment]
> 刚实现了这个功能，请参考test_wsServer.cpp

非常感谢，太给力了。
