### ISSUE TITLE
互斥锁bug

### ISSUE THREAD

**Issue by TheDeaf** [xiongziliang/ZLMediaKit#217]
有个隐藏bug调试了半天，pusher的时候，开始推流后，会出现卡死的情况。跟踪了半天大概知道是MediaSink::getTracks 中互斥锁的问题。流程是 MediaSink::inputFrame的过程中，首先锁住_mtx，后面又会到NoticeCenter.h里面去addListener等待锁_mtxListener，此时_mtxListener已经锁住，并且锁住的线程又去调用去MediaSink::getTracks，此时发现 _mtx已经锁住。两个线程互相锁死。

**Comment by xiongziliang** [comment]
你的代码是很早之前的吧？你试试新代码，应该不再存在这个问题了

**Comment by xiongziliang** [comment]
大佬，你说的对，这个确实有死锁的bug。这个死锁的bug推流时竟然不会触发，我在使用DevChannel时才发现，这个是两个线程交叉互锁导致的。我已经修复这个bug了。非常抱歉！没认真排查你反馈的问题！
