### ISSUE TITLE
on_flow_report播放可以正常hook，推流停止的不能

### ISSUE THREAD

**Issue by tsingeye** [xiongziliang/ZLMediaKit#218]
RT，
通过代码跟踪，发现 
`        if(!hook_enable || args._param_strs == hook_adminparams || hook_flowreport.empty()){
            return; //这里直接返回了，args._param_strs == hook_adminparams 导致
        }`

没明白这个原理。

**Comment by xiongziliang** [comment]
就是说，如果你未启用hook，或者设置的on_flow_report地址为空，或者你用超级管理员身份推流或播放，那么就不计入流量统计。
超级管理员用于开发者自己测试用，相当于一个后门，这个肯定不能参与业务统计啊

**Comment by tsingeye** [comment]
哦 这个道理， 我现在是想实时统计 推流的流量，然后形成rest接口
