### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by imxxiv** [xiongziliang/ZLMediaKit#220]
ZLMediaKit真的是一个非常优秀的项目。
开始接触ZLMediaKit时，以为ZLMediaKit是srs的nginx方式实现的版本，仔细看过手册后，发现核心理念是不同的。以我的理解，srs是以rtmp为核心的功能扩展，ZLMediaKit是以核心编码（H264/H265/aac）为核心的功能扩展。
ZLMediaKit以核心编码为基础，在ffmpeg的扩展下，以主动拉或者客户端推的方式，支持多种网络协议、多种封装格式的视频数据的输入，并可以指定一种或多种网络协议或封装格式的输出，我个人觉得这种核心理念使得ZLMediaKit非常具有兼容性和生命力。
ZLMediaKit的拉流功能真的真的很实用，这样可以大大拓展ZLMediaKit的部署平台，因为在核心编码的支持下，ZLMediaKit无需ffmpeg，本身已经可以高效的支持大部分的视频流，即使在算力比较低的平台上，只需要ZLMediaKit就可以满足很多项目的需求。

下面是我个人对ZLMediaKit的一点建议，如果建议不具有可行性，请无视。
1. 核心编码增加mp3
既然是媒体服务程序，建议对已经全平台支持的hls协议实现充分的支持，hls目前的核心编码为H264/H265/aac/mp3，所以建议ZLMediaKit也增加对mp3的核心编码支持。虽然现在hls基本都是aac的音频编码，偶尔还是会遇到mp3音频编码的流。

2. addStreamProxy 拉流代理在核心编码（H264/H265/aac/mp3）的基础上，支持更多的网络协议
在现有rtsp/rtmp拉流协议上，建议增加 http-flv 、MPEG-TS over http 和 MPEG-TS over UDP 的拉流支持。
特别是以http为网络协议的流，在很多网络环境下可能是唯一的选择，udp网络协议也可以做很好的补充。

3. 增加 MPEG-TS over http 和 MPEG-TS over UDP 的输出服务或者推流
MPEG-TS over http 和 MPEG-TS over UDP 的输出服务或者推流主要考虑给边缘ZLMediaKit进行流的下发和传输。基于http的通用性和udp的支持，可以更好的匹配源ZLMediaKit和边缘ZLMediaKit之间的网络，并且可以多一种支持h265的网络协议的选择。

4. addFFmpegSource 增加ffmpeg命令模块参数提交
ZLMediaKit的拉流功能是非常有特色的，至少我现在还没有找到像ZLMediaKit拉流做的这么好的项目，srs需要通过配置调用ffmpeg来拉流，如果拉取数量很多，只能借助其他程序来管理拉流。但ZLMediaKit通过api和web hook就可以很好的对拉流进行统一管理。
配置文件中的ffmpeg命令模块可以作为默认，对于有些情况下的拉流，需要不同的ffmpeg命令，所以建议在addFFmpegSource接口中增加此拉流的ffmpeg命令模板为参数进行提交，这样可以更灵活的进行拉流。如果ffmpeg日志能区分就更好了。

5. 增加对lhls的支持
[lhls](https://blog.csdn.net/weixin_39970103/article/details/90047813)
这种低延迟hls方案只需要服务器端支持，1提前增加切片（增加数量可以自定）；2服务器以chunked形式实现服务器端每有一帧数据封装到segment，就向客户端发送这一帧的数据（ZLMediaKit可以选择以帧为单位，用chunked的形式发送，nginx是无法做到的）。
在我的理解，这其实就是http-ts了，和http-flv类似，只是支持h265了。

6. 增强并专注核心功能
建议增加通过api提交ip黑白名单功能，这个在源边缘架构，或者分发下级源时更直接和方便；
建议api接口和http服务使用不同的tcp端口，分割管理和服务；
建议配置中增加选项，可以关闭除127.0.0.1以外的api接口访问，提高安全性；
建议可以指定hls的hls.m3u8的文件名，例如play.m3u8；
建议可以通过hook报告抓流的状态，因为有的流确实不稳定；

ZLMediaKit专注于媒体数据服务，业务逻辑通过api和hook和ZLMediaKit进行信息交互。点播需要的http静态文件发布完全可以其他专门的程序来做。例如go+sqlite就可以配合ZLMediaKit做业务逻辑和静态资源发布。

---------
最后预祝夏楚高工新年快乐！star越来越多！

**Comment by xiongziliang** [comment]
您提的这些建议都非常好，很多跟我的规划是一致的：
### 1、支持更多类型的编码格式
这点其实是一个很重要的扩展方向，不仅仅mp3,像g711也很有必要。将来如果要对接webrtc,vp8/vp9这些也有必要，实现rtmp对265的支持也有必要。目前ZLMediaKit要扩展支持更多类型的编码格式也比较容易，只是工作量比较大。

### 2、支持更多类型的拉流协议
其实不仅仅是http-ts拉流，我还想支持http-flv拉流、hls拉流。我之前在其他私有项目实现过hls、mpeg-ts udp拉流，现在还来不及整合，如果要实现这些设想，并且和目前的整理为一体，那么其实还是有很多工作要做。

### 3、支持更多协议类型的输出
其实跟第二条是一致的。

### 4、addFFmpegSource支持自定义FFmpeg参数
目前限定这个FFmpeg拉流的FFmpeg参数，目的还是为了安全，因为这个api的本质是让ZLMediaKit执行一条命令，这个如果做得太自由了会不会有安全隐患？

### 5、支持低延时hls
这个其实不难，工作量也不算大，会考虑择机实现这个的。

### 6、增强并专注核心功能
除了`建议可以指定hls的hls.m3u8的文件名，例如play.m3u8`不能妥协，其他都可以。
因为现在hls是做了很多鉴权相关业务的，如果url不按照统一格式来做，那么这些东西都将紊乱。
其他建议，其实很细末，我认为这些功能应该是需要开发者自己定制开发的，这些不是一个项目的核心功能。而且说实话，我不想花费太多精力做这些事情，如果把这些精力做上面5条岂不是更好？

ZLMediaKit目前提供了C/C++ 的api，也提供了完整的流媒体服务器解决方案，既可以作为其他程序的sdk调用，也能在无开发下作为一个完整的流媒体服务器运行。基于restful api和web hook机制的灵活度也能满足绝大多数的业务需求。

您上面的那些建议都非常具有建设性，也跟我的规范契合度很高，但是由于您也知道，个人开源这种模式有多困难：
- 第一，基本上所有开发都是我一人完成，开发工作繁重，
- 第二，我还要维护issue、qq群等，要分散并不少精力。
- 第三，我有全职的工作，不能全身心投入开源事业。
- 第四，我有孩子(两个，就我夫妻两人带)，要承担养家糊口，养育培养孩子的责任。

可以说为了这个项目我付出了很多精力和时间，在这里也收获了很多，结识了很多友好热心的朋友。
但是我觉得目前这些还远远不够：现在ZLMediaKit虽然有点影响力，但是目前除了我开发代码，几乎没收到多少pr，项目参与度很低，我感觉挺孤独，跟我之前想象中的开源模式不一样。而且目前项目开源也有2年半了，但是目前感觉发展还是挺慢的，用户也基本没法统计，也不知道到底有谁在使用，你知道一个项目还是要有大公司做背书的，如果没有，很多人会觉得这是个野项目，如果别人问我ZLMediaKit有没有实际项目中使用过、性能咋样、稳定性咋样，说实话我会挺生气的。

一个项目成功与否，无非以下几点：
- 1、具有影响力，很多用户。
- 2、开源社区活跃，很多人一起贡献代码。
- 3、商业上的成功，开发者能有现实收入。

除了第一点，有点影响力，ZLMediaKit其他都不具备，我作为一个全职的工作者，并不能全身心投入这个项目，而又没有其他人贡献代码，您觉得能有多快的开发进度？

不管怎样，您提的这些意见我都很感谢，我也会有条不紊的按照规划来逐步添加这些特性，
也不管这个项目最终发展如何，我还是会一如既往的维护这个项目，非常感谢您对本项目的关注和支持。

**Comment by imxxiv** [comment]
在某个年龄阶段，对生活产生忧虑是很正常的心理状态。其实在我看来，夏高工是非常厉害的，熟悉视频编码协议等方面的专业知识，掌握了C++11这种高级技能，还能写出高效稳定的服务器程序，这就是大佬。
目前随着网络宽带的提升，视频类数据占比越来越大，各个领域的视频服务器需求只会越来越大，av1，avs3等新编码方案，超分等等都需要视频类专业人员的加入，后面的应用只会越来越多，按自己的节奏逐步推进，机会肯定会有的。

个人觉得，以具体使用场景和人群为目标，将ZLMediaKit产品化，应该更容易推广。
就以非互动直播为例，这种场景中要抓取的源可能有各种网络协议和封装，但在边缘给客户端获取的，一般是hls。这种场景对延迟一般要不不高，但希望有最大的兼容性。所以一个可以自主抓取多种协议并输出hls的服务程序，对硬件的要求是最低的，适应性最强，成本也最低。
综上所述，这种需求下，最合适的媒体服务器应该以hls的编码为核心（H264/H265/aac/mp3），对各种此编码的协议和封装做适配，并能输出hls，就是最合适的。

当然还有互动直播，或者其他应用场景的需求，对媒体服务程序的核心编码及侧重要求应该是有不同的。ZLMediaKit是准备做一个通用型的还是演变为多个侧重点不同的媒体服务程序，这个就需要你来思考和决定了。选择不同，开发的主次就有不同。

> 4、addFFmpegSource支持自定义FFmpeg参数
目前限定这个FFmpeg拉流的FFmpeg参数，目的还是为了安全，因为这个api的本质是让ZLMediaKit执行一条命令，这个如果做得太自由了会不会有安全隐患？

现在的addFFmpegSource会根据参数拼接为ffmpeg命令行，提交的参数中如果包含有其他命令(dst_url=;ls /root)，应该也是有风险的。如果这样提交可以过滤掉，按道理提交ffmpeg模板也可以保证安全。
而且addFFmpegSource和addStreamProxy中，enable_hls=1时，建议增加filePath=./sss&segDur=2&segNum=3&segRetain=1

 其实，在我看来，媒体服务程序的hls完全可以做的更彻底，对于直播的hls，不需要保存为文件，就放到内存中，做好分段起点和长度记录即可，有m3u8请求时，根据内存中视频数据和对应的分段标识动态生成返回m3u8文件内容，请求视频分片时，根据名称从内存视频流的起始位置和长度返回内容即可。这样的效率应该更高些，而且无需自己建立内存盘来存放直播切片。

**Comment by xiongziliang** [comment]
### 1、hls还是会继续放置在文件系统
HLS放内存中这个特性在srs中都已经删除了，我也很赞成srs作者关于删除这个特性的解释。因为HLS切片放内存中会跟HTTP服务器深度绑定，耦合度提高了，但是性能相对于内存虚拟文件系统不会有提高。而且HLS只会存在边沿节点上，基本上都建议用成熟的HTTP服务器来分发HLS，所以HLS切片放文件系统是最合理的，这样可以只负责产生HLS文件即可，专业的事情交给专业的HTTP服务器来做即可。

### 2、FFmpeg拉流可以新增接口指定参数
可以新增一个restful api来实现这个定制化FFmpeg参数的功能。

### 3、新增编码和新增协议是一个长期的任务和规划
这个是将来主要的关注点。

###4、hls录制相关参数的定制化
hls保存路径跟http根目录相关的，如果错乱了外面访问不了。而且这个接口参数已经很多了，再添加参数会导致混乱，而且其实切片时长，切片个数这些参数其实不需要定制化，全程序一个就行的。触发是录制为点播，否则各个流不需要定制化这些参数，而且startRecord接口也设计到hls录制，不一定要在这个接口里面实现这些很细末的功能。

**Comment by alongL** [comment]
addFFmpegSource  这种简单功能就交给一般程序实现吧。 https://github.com/alongL/srs_ingest_helper

**Comment by xia-chu** [comment]
厉害了老哥 在群里面推广下啊
