### ISSUE TITLE
用FFMPEG推流画面是卡顿的

### ISSUE THREAD

**Issue by zhang2349** [xiongziliang/ZLMediaKit#222]
我用srs-librtmp简单写了个测试程序，从摄像头获取码流，解析出裸h264，然后推送rtmp://xxx.xxx.xxx.xxx/live/livestream。这路用vlc播放正常。

然后我用ffmpeg -i rtmp://xxx.xxx.xxx.xxx/live/livestream -vcodec copy -acodec copy -f flv rtmp://xxx.xxx.xxx.xxx/live/livestream2。这路用vlc播放就会很卡顿。画面基本就是停止的。

但是 用obs推流测试的话，两路都是正常的。

然后用srs服务器测试了下，都是正常的。

这问题会出在哪里呢？

**Comment by xiongziliang** [comment]
改成这个试试：
ffmpeg -re -i rtmp://xxx.xxx.xxx.xxx/live/livestream -vcodec copy -acodec copy -f flv rtmp://xxx.xxx.xxx.xxx/live/livestream2

**Comment by zhang2349** [comment]
我也试过 也是一样的

**Comment by zhang2349** [comment]
我把obs的fps调成25，就会出现类似现象

**Comment by xiongziliang** [comment]
你把时间戳覆盖关闭试试，配置文件是：
rtmp.modfyStamp=0

**Comment by zhang2349** [comment]
改成0后 我用obs推一个视频文件  效果好了很多  只有很偶尔会卡下丢帧 但是3 4分钟后还是会卡死

我用obs推一个黑屏 只有一小块显示时间   是一播放画面就会卡死的

**Comment by xiongziliang** [comment]
我给你一个公网地址：
rtmp://zlmediakit.com/live/test

你推流测试下，看看能否好点

**Comment by zhang2349** [comment]
同样的问题

**Comment by zhang2349** [comment]
你再给我个rtmp地址 我两个都给你推

**Comment by zhang2349** [comment]
都给你推了 
obs推rtmp://zlmediakit.com/live/livestream  
然后 ffmpeg -re -i rtmp://zlmediakit.com/live/livestream -vcodec copy -acodec copy -f flv rtmp://zlmediakit.com/live/test

**Comment by xiongziliang** [comment]
没啥问题啊 播放流畅啊

**Comment by zhang2349** [comment]
rtmp://zlmediakit.com/live/test 播放流畅？
难道我vlc的问题？
我用http flvjs 播放也是会卡住的

**Comment by xiongziliang** [comment]
我播放这个很流畅啊：
![image](https://user-images.githubusercontent.com/11495632/72716325-f8096380-3bac-11ea-9a01-76a9c5017d79.png)
rtmp://zlmediakit.com/live/test 后面你都没推流啊

**Comment by xiongziliang** [comment]
我推得效果也不错啊:ffmpeg -re -i rtmp://zlmediakit.com/live/livestream -vcodec copy -acodec copy -f flv rtmp://zlmediakit.com/live/ffmpeg


![image](https://user-images.githubusercontent.com/11495632/72716493-3dc62c00-3bad-11ea-9ef9-a0343cfef2d9.png)

**Comment by xiongziliang** [comment]
你看我录制的文件：
[QQ20200120-175240-HD.mp4.zip](https://github.com/xiongziliang/ZLMediaKit/files/4085531/QQ20200120-175240-HD.mp4.zip)

命令是：
```
ffmpeg -re -i rtmp://zlmediakit.com/live/livestream -vcodec copy -acodec copy -f flv rtmp://zlmediakit.com/live/ffmpeg
```

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/72717380-de691b80-3bae-11ea-828c-bb47f0c1b114.png)
![image](https://user-images.githubusercontent.com/11495632/72717405-e88b1a00-3bae-11ea-906d-8ff2f79d3607.png)

后来网速不济，服务器掐断FFmpeg了

你要确保你网速稳定，否则会卡一下，然后延时增加，如果卡太久了，ZLMediaKit会直接掐断播放器或推流器的

**Comment by zhang2349** [comment]
用ffplay 播放好像真的没问题，用vlc播放rtmp还是rtsp都是会卡住画面的，但是进度条的时间在走。但是用SRS测试vlc都是正常的。
你http-flv的端口是多少，我也测试下看

**Comment by xiongziliang** [comment]
http/hls/http-flv/ws-flv地址: http://zlmediakit.com:8880/
https地址： https://zlmediakit.com:8443/
rtsp地址： zlmediakit.com:554
rtmp地址： zlmediakit.com:1935
rtsps地址: zlmediakit.com:322

**Comment by zhang2349** [comment]
用http://bilibili.github.io/flv.js/demo/ 播放 http://zlmediakit.com:8880/live/test.flv 也是卡住的
表现跟vlc一样

**Comment by zhang2349** [comment]
而且我用ffmpeg推着推着就断开了  4500码率 推到4分多钟就会断了  用2000码率 推到7分多就断了

**Comment by zhang2349** [comment]
我收回上面说ffplay正常的说法   只要时间够久 延时会越来越大 最后会卡住  我用127.0.0.1测试的 应该跟网速没关系吧

**Comment by zhang2349** [comment]
用最新的代码编译测试，貌似没有问题了

**Comment by vocanotan** [comment]
> 用最新的代码编译测试，貌似没有问题了

你好，您能给我你的最新编译解决方式吗？，我这边srs ffmpeg推流给apk客户端也是播放一段时间后就会越来越卡

**Comment by zhang2349** [comment]
> > 用最新的代码编译测试，貌似没有问题了
> 
> 你好，您能给我你的最新编译解决方式吗？，我这边srs ffmpeg推流给apk客户端也是播放一段时间后就会越来越卡

额 建议还是自己下载源码编译 编译方式还是很简单的  源码也经常有更新 修复bug 提升性能之类的


 @xia-chu  建议把Release里的删掉 看到很多人下载 老旧版本 然后说有问题的
