### ISSUE TITLE
hls在5个web播放器中均测试失败

### ISSUE THREAD

**Issue by imfuding** [xiongziliang/ZLMediaKit#226]
from Q群_天涯海角.
所有github中热门播放器

#播放器1.xgplayer 
地址 http://h5player.bytedance.com/examples/
选择 直播 hls  hls.js

#播放器2.aliplayer 
地址 http://player.alicdn.com/aliplayer/setting/setting.html
填入播放地址

#播放器3 clappr
地址 https://github.com/clappr/clappr/

#播放器4.金山ksplayer 该播放器直接在线测试更方便
http://ksplayer.video.ksyun.com/v1/index.html

#播放器4.chimee 该播放器直接在线测试更方便
http://chimee.org/#demo

测试方法:
反复刷新页面,确保播放后.有音有画的正常播放.

测试结果:
以上播放器的结果:别的地址正常,ZLM的地址失败

正常播放的非ZLM直播源地址(反复刷新均有音有画):
http://101.72.196.41/r/baiducdnct.inter.iqiyi.com/tslive/c16_lb_heibangdianying_1080p_t10/c16_lb_heibangdianying_1080p_t10.m3u8
http://101.72.196.41/r/baiducdnct.inter.iqiyi.com/tslive/c15_lb_reboju_1080p_t10/c15_lb_reboju_1080p_t10.m3u8
http://101.72.196.41/r/baiducdnct.inter.iqiyi.com/tslive/c20_lb_songzhongji_1080p_t10/c20_lb_songzhongji_1080p_t10.m3u8

ZLM地址:
最新代码OBS推流.或任意推流器均可,测试失败

问题:
用最新代码本地http://127.0.0.1的hls地址播放后,出现的问题,刷新十次,有七八次都是播放后有音无画.所有播放器都是一样的

观察发现:
正常源的ts下载后均是在vlc中有音有画的播放,ZLM的10片中有时候只有1-2片是有画面,其它都只有声音.

**Comment by xiongziliang** [comment]
大年30还在开发 我容易吗？🤣

**Comment by xiongziliang** [comment]
这个问题其实也谈不上bug，主要原因是你切片时间太短导致的

**Comment by imfuding** [comment]
老大辛苦了,播放的问题是解决了,但也导致了另一个问题:延迟从原来稳定的7-9s,如今40s,而且直播中反复刷新后会重复播放缓存过的上几帧例如00:30这个位置,继续刷新可能又瞬间跳到了01:00这样的位置了.这两个问题的图片和录屏我在群里提交了.
