### ISSUE TITLE
iOs Build: Undefined symbols for architecture arm64:   "_kCFStreamPropertyShouldCloseNativeSocket", referenced from: .....

### ISSUE THREAD

**Issue by chapayGhub** [xiongziliang/ZLMediaKit#227]
Hello

My build environment is:

- MacOs Mojave 10.14.6
- Xcode 11.2.1

I have next error during linking

Could you give me advise how fix this issue?

<img width="775" alt="Screenshot 2020-01-30 at 11 11 08" src="https://user-images.githubusercontent.com/878464/73431419-70141e00-4351-11ea-8d4b-2188e498fed6.png">

Thank you

**Comment by xiongziliang** [comment]
You need to add the framework of `Core Foundation` in Xcode  project.
I am sorry that i do not know how to add framework of ios in cmake!

**Comment by chapayGhub** [comment]
Shared libraries on iOs uses as [frameworks](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/WhatAreFrameworks.html), 

For now I changed lib type to STATIC for iOs in cmake

I found another issues in build process: test apps have not linked with Foundation, CFNetwork
To fix this issue I added manually in xcode (may be you can fix this by cmake):
**Other linker flags**: `-framework CFNetwork -framework Foundation` 


```
 ﻿include_directories(include source)
 file(GLOB api_src_list include/*.h source/*.cpp source/*.h source/*.c)

if(NOT IOS)
	add_library(mk_api SHARED ${api_src_list})
else()
	add_library(mk_api STATIC ${api_src_list})
endif()
 
 if(WIN32)
     add_definitions(-DMediaKitApi_EXPORTS)
```

**Comment by xiongziliang** [comment]
I refer to this [article](https://blog.csdn.net/zhuyunier/article/details/83025615) and have tried many times, but I'm sorry that I didn't succeed.
I've modified cmaklist.txt now, and only static libraries(for c api) will be generated under IOS.
Thank you very much for your advice!
