### ISSUE TITLE
Mpeg2 

### ISSUE THREAD

**Issue by nokiovo79** [xiongziliang/ZLMediaKit#229]
Hi Friend,
I wanted to ask you: What is the best way to integrate video sources sent via udp protocol and encoded in mpeg2 into ZL?

**Comment by xiongziliang** [comment]
Now zlmediakit supports RTP streaming of `PS`, and the encoding format supports H264 / h265 / AAC,the default port is 10000, and the code is in the `src / RTP` directory.
Do you want to push MPEGTS UDP stream to zlmediakit?

**Comment by nokiovo79** [comment]
Yes....

**Comment by nokiovo79** [comment]
??

**Comment by xiongziliang** [comment]
I'm sorry to tell you that zlmediakit doesn't support MPEGTS streaming now.
- If you want to accept the RTP streaming of MPEGTS, you can refer to this [code](https://github.com/xiongziliang/ZLMediaKit/tree/master/src/Rtp), and then modify the code slightly, and change the `PSDecoder` object to `TSDecoder`.

- Please refer the [code](https://github.com/xiongziliang/media-server/blob/master/libmpeg/include/mpeg-ts.h#L58) and change `ps_demuxer_create` to `ts_demuxer_create` ,`ps_demuxer_input` to `ts_demuxer_input` , `ps_demuxer_destroy` to `ts_demuxer_destroy`.


- If you finally generate H264 / h265 / AAC, you can refer to this [code](https://github.com/xiongziliang/ZLMediaKit/blob/master/src/Rtp/RtpProcess.cpp#L184) to complete the integration with zlmediakit.

**Comment by xiongziliang** [comment]
I'm so sorry to reply to you now. I'm still on vacation, there are a lot of things to do....

**Comment by nokiovo79** [comment]
I made the changes indicated but I receive a dump of errors

**Comment by xiongziliang** [comment]
Now supported!

**Comment by xiongziliang** [comment]
Please update the latest code I have implemented mpeg2-ts

**Comment by nokiovo79** [comment]
Wow... i test it... Thank you very much... you are the best... How are you?
