### ISSUE TITLE
HLS切片出现很大的TS文件的BUG

### ISSUE THREAD

**Issue by oujiangping** [xiongziliang/ZLMediaKit#23]
![Jietu20190429-103139](https://user-images.githubusercontent.com/5906374/56874095-084f4080-6a6a-11e9-9221-0a42613b12a1.jpg)
播放rtsp很久就会出现很大的ts的情况，用test_server的代码rtsp转hls，情况如截图所示，图中出现2.5G的ts

**Comment by oujiangping** [comment]
我这里接入的是一个海康的摄像头，rtsp的，我看了一下代码，出现这个问题的一种情况可能是客观上rtsp流错误timestamp不增加了，另外一种情况可能是解码出现了问题pts出错了

**Comment by xiongziliang** [comment]
你好 我刚提交了代码 ，请查看最新master分支代码
这个bug应该是媒体时间戳回环或者不准确导致的
我已经改成了根据系统时间戳来作为hls切片的依据了
