### ISSUE TITLE
Can I use you library to make livestream from ios/android to server?

### ISSUE THREAD

**Issue by chapayGhub** [xiongziliang/ZLMediaKit#230]
Hi 

Can I use you library to create livestream from ios/android to server?
If yes maybe you could provide instructions how ;) ?

I found tests (api/tests and /tests) folders and saw that they uses different approachs 

api/tests - uses c-like api calls
tests  - have access to all ZLMediaKit classes and use it

Which approach is better? 
What aim to provide api in c-style via libmk_api?

Thanks!

**Comment by xiongziliang** [comment]
- If you use zlmediakit as a SDK, I strongly recommend that you use the [C-style API ].(https://github.com/xiongziliang/ZLMediaKit/tree/master/api)

- If you use zlmediakit as a framework, and you will add some features, or use zlmediakit as server mode, you can use the [C++ apis](https://github.com/xiongziliang/ZLMediaKit/tree/master/src).

- If you want to use zlmediakit as a streaming server without any programming, you can use the [MediaServer process](https://github.com/xiongziliang/ZLMediaKit/tree/master/server).

**Comment by chapayGhub** [comment]
Great answer!
Thank you.

But I have another new one:

I want create sdk for conference calls (p2p, group calls) with custom crypt layer (private crypt algoritms)

Can I implement conference calls via zlmediakit?

It is seems possible, but some features like dynamic bitrate I should implement by self. Am I right?

May be you can give some links or advice that helps me.

**Comment by xiongziliang** [comment]
It seems zlmediakit is not suitable for RTC related applications，
because zlmediakit mainly includes RTSP, RTMP, HTTP protocol and network framework.
RTC related applications are quite different from this one. If you are a private protocol, you may need to use RTP，there is a bit of RTP related code in zlmediakit, which you may use.

**Comment by chapayGhub** [comment]
Thank you!
