### ISSUE TITLE
请问rtmp 流怎么落地mp4文件，MediaPlayer类可以么

### ISSUE THREAD

**Issue by GeneralFury** [xiongziliang/ZLMediaKit#231]

**Comment by GeneralFury** [comment]
我已经知晓如何落地文件,还请教个问题，frame这个这个是没解码的数据么，又没有存在一个回调，返回的是解码好的数据，供使用呢，要不然在自己维护解码，很别扭。
如果存在这样的回调，请问怎么去注册呢，返回的是raw数据么

**Comment by xiongziliang** [comment]
- 1、ZLMediaKit是个流媒体框架，所以它不会提供解码的功能。
- 2、MediaPlayer类可以输出h265/h264/aac，你可以通过参考test_player.cpp来参考获取frame以及编码的相关范例。
