### ISSUE TITLE
rtsp播放一会儿就被服务端自动断开

### ISSUE THREAD

**Issue by addriumruss** [xiongziliang/ZLMediaKit#232]
首先真是非常感谢@xiongziliang提供的这个好产品。对于服务端设计理念我是非常认同和佩服的！
今天简单试用了rtsp-server, 环境是阿里云centos7.2, release编译，默认配置未改动. 
结果：720P，推流到播放两端延时大概 1.5秒, 公网上很不错了. 
只是有个小问题，就是用vlc播放一会儿大概十几秒就断了，看日志是服务端主动断开，显示说rtp超时，日志如下：
MediaServer(13894) /home/russ/file/ZLMediaKit/src/Rtsp/RtspSession.cpp 89
2020-02-08 12:11:24.180 W | onError 0x7f3f78001420(117.136.45.145:11365) RTSP播放器(__defaultVhost__/123456/)断开:rtp over udp session timeouted
现在VLC也算是主流播放器，很多自定义播放器都是用的libvlc内核，所以这个问题还是挺有影响的。  
请问具体要怎么配置呢  不知道是否是配置的问题

**Comment by xiongziliang** [comment]
有两种可能的情况 ，一是可能rtcp包被防火墙或nat过滤了，zlmediakit一直收不到rtcp，认为播放器挂掉了，


二是可能vlc可能扎根就没发rtcp包。我实测会存在这种情况。


联系你采用rtsp over tcp的方式播放，这样就不会出现这种情况了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: russ <notifications@github.com&gt;
发送时间: 2020年2月8日 12:22
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] rtsp播放一会儿就被服务端自动断开 (#232)




首先真是非常感谢@xiongziliang提供的这个好产品。对于服务端设计理念我是非常认同和佩服的！
 今天简单试用了rtsp-server, 环境是阿里云centos7.2, release编译，默认配置未改动.
 结果：720P，推流到播放两端延时大概 1.5秒, 公网上很不错了.
 只是有个小问题，就是用vlc播放一会儿大概十几秒就断了，看日志是服务端主动断开，显示说rtp超时，日志如下：
 MediaServer(13894) /home/russ/file/ZLMediaKit/src/Rtsp/RtspSession.cpp 89
 2020-02-08 12:11:24.180 W | onError 0x7f3f78001420(117.136.45.145:11365) RTSP播放器(defaultVhost/123456/)断开:rtp over udp session timeouted
 现在VLC也算是主流播放器，很多自定义播放器都是用的libvlc内核，所以这个问题还是挺有影响的。
 请问具体要怎么配置呢  不知道是否是配置的问题

**Comment by addriumruss** [comment]
感谢及时解答！
刚才重新在本地虚拟机测了一下，发现本地虚拟机没问题没有断，可能vlc还是发了rtcp. 
但是阿里云那里554端口确实是放开的，rtcp是否不在554这个信道？好像是同一个端口吧?
对vlc播放器添加了rtsp-tcp选项，总"编辑选项"值是" :network-caching=100 rtsp-tcp"，这个设置方式不知道是否有问题，结果还是被服务端说rtp超时。是不是我设置错了？纠结

**Comment by addriumruss** [comment]
确实是vlc没设置好，编辑选项应该设置为" :network-caching=100 :rtsp-tcp"这样就可以了
非常感谢厦工的慷慨分享和及时解答！
rtmp服务器之前已经有nginx和srs两个不错的选择，现在又多了zlm, 但是高性能rtsp服务器就很难找, 不管zlm当前性能如何，单从设计理念看就是目前最领先最优的。
我先花点时间熟悉代码，后续找时间也尽快加入开发组，希望能做点微薄贡献。

**Comment by xiongziliang** [comment]
> 我先花点时间熟悉代码，后续找时间也尽快加入开发组，希望能做点微薄贡献。
谢谢！
