### ISSUE TITLE
How to enable websocket in MediaServer and test client

### ISSUE THREAD

**Issue by lenhatvu** [xiongziliang/ZLMediaKit#233]
Hi,

How to enable websocket in mediaserver and using client to get live stream from media server ?

**Comment by xiongziliang** [comment]
This  issue may help you : https://github.com/xiongziliang/ZLMediaKit/issues/78

**Comment by lenhatvu** [comment]
Thanks,

It's work fine with H264 stream but seem with H265 still not work ?

**Comment by xiongziliang** [comment]
Flv does not support h265, and most browsers do not support h265,so now playing 265 on the browser basically doesn't work

**Comment by lenhatvu** [comment]
Is any way to support H265 on browsers ?

**Comment by xiongziliang** [comment]
WebAssembly

**Comment by lenhatvu** [comment]
Thank, but seem rtsp does not support H265 ? websocket still ok ?
![image](https://user-images.githubusercontent.com/59004953/74644937-ac48da80-51a9-11ea-8fe8-c8abd983bb11.png)

**Comment by xiongziliang** [comment]
The general way to use web WebAssembly is to compile ffmpeg into JavaScript code, which supports TCP type protocols and various encoding formats (software decoding).
You can play the RTSP protocol in WebAssembly, and zlmediakit supports h265 on rtsp.

**Comment by lenhatvu** [comment]
Thank you for supported
