### ISSUE TITLE
config reload 的线程安全问题

### ISSUE THREAD

**Issue by bluestn** [xiongziliang/ZLMediaKit#234]
从代码里面看到config是用SIGHUP触发进行 mediakit::loadIniConfig来进行读取的。
而在程序当中实际用到配置变量是用 类似 GET_CONFIG(string,ffmpeg_bin,FFmpeg::kBin);来得到的。

 GET_CONFIG 本身定义了一个静态变量，通过注册一个配置更改监听器以便在配置被重新加载的时候进行目标静态变量的更新。

那么有没有可能signal的处理线程存在正好进行对目标变量进行更改的时候，其他worker线程正好使用这个变量，是不是可能导致线程安全的问题，引发不可预知的异常行为。

**Comment by xiongziliang** [comment]
嗯 确实存在线程安全的问题 特别是非基础类型的数据 ，如非必要 不要领导热更新配置文件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: stone <notifications@github.com&gt;
发送时间: 2020年2月14日 13:21
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] config reload 的线程安全问题 (#234)
