### ISSUE TITLE
H264或H265视频流转RTMP

### ISSUE THREAD

**Issue by Rey1023** [xiongziliang/ZLMediaKit#236]
您好，刚刚开始接触这个项目，功能太强大了，项目已经编译成功，我现在有个应用场景，我有自己的流媒体服务器（C++编写，H264和H265视频编码），流媒体服务器走自己的私有协议，视频和回放都是走自己的私有协议，现在需要将视频流转成rtmp，客户端可以通过rtmp点播实时音视频和录像回放，我看了项目介绍，可以通过输入H264和AAC实现，现在有点疑惑，我想在我的流媒体服务器上集成该项目的SDK，可以把我们自己的私有协议转成rtmp，不知道可以从什么地方入手，对该项目的SDK不熟悉，wiki上的介绍相对也比较简单，希望能得到指点或者有没有关于这方面的介绍，万分感谢！

**Comment by xiongziliang** [comment]
你可以使用该api生成Rtmp的数据流：

https://github.com/xiongziliang/ZLMediaKit/blob/master/api/include/mk_media.h#L100

然后通过该api启动rtmp服务器：

https://github.com/xiongziliang/ZLMediaKit/blob/master/api/include/mk_common.h#L126

ZLMediaKit里面直播协议和数据流是分开的，Rtmp服务器会去查找这个生成的数据流并发送给客户端。
