### ISSUE TITLE
使用api推送rtmp流到ZLMeida在点播，前几帧发绿

### ISSUE THREAD

**Issue by kqbi** [xiongziliang/ZLMediaKit#237]
打开MP4文件使用api推送rtmp流到ZLMeida,用vlc点播rtmp（是vlc先点播再推流，或者source注册成功后，立马播放出现的），前几帧发绿（rtsp没有这个现象），然后用ffplay播放，ffplay是直接跳过了发绿的那几帧，感觉是前几帧丢弃了。不知道是什么问题

**Comment by kqbi** [comment]
![无标题](https://user-images.githubusercontent.com/40823194/75205880-f5072180-57af-11ea-9137-d0f8ffc3f59c.png)

**Comment by kqbi** [comment]
对了，api推送rtsp流到ZLMeida,用vlc点播rtsp，没发绿也是跳过了前几帧

**Comment by kqbi** [comment]
视频源
![图片](https://user-images.githubusercontent.com/40823194/75206427-5da2ce00-57b1-11ea-9fc4-1a21b622bbb1.png)

**Comment by kqbi** [comment]
仔细看了下，采用rtsp模式，不发绿，是从MP4文件本地播放的第3秒的画面开始播放的，也就是丢了大概3秒的视频

**Comment by xiongziliang** [comment]
等待3秒是因为你的mp4文件是单视频或单音频的。
这个问题我刚优化了下，你拉下最新代码试试

**Comment by kqbi** [comment]
我先试试吧，音视频都有的

**Comment by kqbi** [comment]
刚试了新版，对于我这种场景，貌似没什么改善，我是音视频都有的推送的

**Comment by xiongziliang** [comment]
你能不能提供你的测试mp4? 我本地测试试试

**Comment by xiongziliang** [comment]
这个问题我优化了 你更新代码一下 测试反馈给我

**Comment by kqbi** [comment]
用新的试了，没有改善哦，我用的C的api的mk_media和mk_pusher

**Comment by kqbi** [comment]
![4GG3ZSZG`H@)7YE_W@YJ$1R](https://user-images.githubusercontent.com/40823194/75417567-5378ff00-596c-11ea-9629-adeced375281.png)
![H`Z{WG6_I4M{ML)3%)UFB(F](https://user-images.githubusercontent.com/40823194/75417572-5673ef80-596c-11ea-93bc-d59c1021b301.png)
在这两个地方保存的h264文件开始的部分帧就已经有问题了

**Comment by kqbi** [comment]
![4GG3ZSZG`H@)7YE_W@YJ$1R](https://user-images.githubusercontent.com/40823194/75417686-a18e0280-596c-11ea-8aed-7f2984cb5693.png)

**Comment by kqbi** [comment]
![TTX9_ }0%K_LY KW3GJC$Y](https://user-images.githubusercontent.com/40823194/75418958-b0c27f80-596f-11ea-9c7b-4b90b4a63e1f.png)
在Frame.h这里保存的流，没有问题

**Comment by kqbi** [comment]
![5 12)%WC9UP6_M }VG`X ZR](https://user-images.githubusercontent.com/40823194/75419082-00a14680-5970-11ea-9102-a7f606c8c593.png)
在Frame.h的inputFrame保存的流是正常的，在H264RtpEncoder和H264RtmpEncoder那里不能的流不正常，保存的文件大小，也有差异

**Comment by xiongziliang** [comment]
你调用下这个接口：
![image](https://user-images.githubusercontent.com/11495632/75420511-1feda300-5973-11ea-920a-7fd09855473a.png)

**Comment by kqbi** [comment]
mk_media_init_complete是有用的，我自己这边只推送视频，已经没问题了，应该是我这边音频初始化有问题，影响到了视频，后边的我自己搞定吧，感谢大神

**Comment by kqbi** [comment]
已经完美解决

**Comment by xiongziliang** [comment]
怎么解决的？修改了ZLMediaKit的代码吗？是什么bug？
