### ISSUE TITLE
新接入的 _RingReader 一开始读取到非关键帧

### ISSUE THREAD

**Issue by bluestn** [xiongziliang/ZLMediaKit#238]
在_RingReader里面，新创建的_RingReader 调用setReadCB设置回调的时候，直接向新链接的客户端发送帧数据，但是从代码里面看到，发送的数据不是从关键帧开始的，可能会导致播放器解码出来花屏的现象发生。

    void setReadCB(const function<void(const T &)> &cb) {
        if (!cb) {
            _read_cb = [](const T &) {};
        } else {
            _read_cb = cb;
            flushGop();             // 新接入的播放器马上给他发一个关键帧?
        }
    }

    void flushGop() {
        if (!_use_cache) {
            return;
        }
        auto &cache = _storage->getCache();
        for (auto &pr : cache) {
            onRead(pr.second, pr.first);
        }
    }

**Comment by xiongziliang** [comment]
曾经 我按照别人提的建议 加了个逻辑，就是确保第一帧是关键帧。
但是我实测发现，有时候，很久都等不到关键帧，这个时候播放器就主动断开了，因为超时了。

然后我又改成了目前这样的逻辑了。

目前这样的逻辑有可能会开播花屏，但是这个原因还是没有及时生成关键帧，这个服务器是控制不了的。

这个GOP缓存其实我改过很多次，目前这种方式是最优的。
强行等待关键帧的逻辑不可取。花屏总比播放失败强点吧？
如果上流数据迟迟不产生关键帧，那么花屏就让他花屏，责任又不在我

**Comment by bluestn** [comment]
理解！ 确实是一个两难的选择。
是不是可以做成可配置项，对于大部分直播推流是会按时生成关键帧的。
我们之前也发现，部分录屏软件可能基于减少码率的考虑，很久很久才会产生一个关键帧。
所以我们是不是可以根据实际的应用，通过配置来决定是不是从关键帧开始发送视频流，这样子是不是更好一些了。

**Comment by xiongziliang** [comment]
不建议这么做 如果别人配置了必须从关键帧开始 导致的问题 一波又一波 你到时要怎么解决 要怎么回答？我觉得那种情况可以不考虑了，确保生成流时，第一帧为关键帧这个问题应该是上游源的问题，不应该我们去帮它们强行解决
