### ISSUE TITLE
Android设备场景下，开启热点组成局域网，如何搭流媒体服务器，并让客户端同步播放？

### ISSUE THREAD

**Issue by jyvvip** [xiongziliang/ZLMediaKit#24]
Android设备场景下，开启热点组成局域网，如何搭流媒体服务器，并让客户端同步播放？
因为使用场景是多个Android设备共用一个声音输出口（扬声器），观看不同设备的用户，看到的画面需要同步，画面与声音输出也需要同步；

**Comment by xiongziliang** [comment]
如果你要同步的效果比较好，建议采用UDP组播的方式来实现，RTSP协议是支持rtp组播的，这样在局域网中的所有设备，收到数据的时间点是一致的，如果后面解码和渲染能做到同步， 那么效果就能做到不错。
你提到的同步，其实有两个层面的意思：
1、不同设备间图像的同步
2、图像与音频的同步

一般而言，播放器要实现音视频同步，基本都是声音驱动视频；因为音频播放速度是不可调的，而视频是可调节的；如果网络抖动导致音频缓存累积，可能还要进行丢包消肿来降低延时。

所以我的建议是这样的，音频播放设备播放音频时定时广播时间戳同步信号，画面显示设备收到同步信号后再调节渲染缓存大小，这样既能保证音视频的同步，又能保证不同设备间画面的同步

**Comment by xiongziliang** [comment]
这个是我之前做的一个[项目](https://v.youku.com/v_show/id_XMjgwNzg0NzcyNA==.html?sharefrom=iphone&sharekey=afb9772ff95adf23f430568dfc6595031)，是一个视频矩阵系统，使用的就是RTP组播+同步信号机制实现的 ，效果很不错

**Comment by jyvvip** [comment]
现在的方案就是用的UDP组播的形式，对于高码率高清的视频，可能带宽跟不上，会出现卡顿、花屏等现象，进而导致不同步，这个有解决方法吗？
另外，你项目的视频的分辨率是多少啊？

**Comment by xiongziliang** [comment]
我们是有线网络，支持1080P。
你这个用WIFI来实现感觉会留坑

**Comment by xiongziliang** [comment]
WIFI抗干扰比较差 可能不是很稳定 有可能丢包 特别是UDP组播 感觉很可能丢包

**Comment by xiongziliang** [comment]
WIFI抗干扰比较差 可能不是很稳定 有可能丢包 特别是UDP组播 感觉很可能丢包

**Comment by jyvvip** [comment]
所以，基于WiFi场景，可能没法很好的满足这个场景的需求吗？

**Comment by xiongziliang** [comment]
> 所以，基于WiFi场景，可能没法很好的满足这个场景的需求吗？

如果你是高清节目，那么rtp组播可能会丢包，具体还要你自己测试才好。
你可以用ijkplayer播放器测试下，它是基于FFmpeg的，支持rtsp组播

**Comment by TaoHanny** [comment]
> > 所以，基于WiFi场景，可能没法很好的满足这个场景的需求吗？
> 
> 如果你是高清节目，那么rtp组播可能会丢包，具体还要你自己测试才好。 你可以用ijkplayer播放器测试下，它是基于FFmpeg的，支持rtsp组播

夏大，您好，首先要感谢您开源了这么优秀的项目供我们使用。针对你在上面回复的，使用ijkPlayer通过UDP_组播的方式拉取RTSP流，我目前遇到一个问题。   

我知道在PC上使用ffplay 播放RTSP流，只需要设置`-rtsp_transport udp_multicast`参数就行了。

但是在ijkPlayer_Android项目中使用`-rtsp_transport`这个参数时，只能指定使用’TCP‘或者‘UDP’,并没有‘udp_multicast’这个选项，而且ijkPlayer0.8.8的协议列表中，我也没看到这个相关协议，协议列表如下：

![image](https://user-images.githubusercontent.com/30739724/182031675-e04be590-3b08-4d64-8219-36c61fe9f29c.png)

请问这个RTSP流在ijkplayer中需要如何处理才能实现UDP多播呢？我在ijkplayer下查了一圈，没找到相关的信息。

**Comment by xia-chu** [comment]
@TaoHanny 如果你指定 udp_multicast没效果；那么ijkplayer应该会有打印警告日志的。你既然能设置udp/tcp方式，那设置udp_multicast也是同一方式。

**Comment by xia-chu** [comment]
ijkplayer依赖的ffmpeg版本是支持组播的

https://github.com/ZLMediaKit/FFmpeg/blob/ijkplayer/libavformat/rtsp.c#L88

**Comment by TaoHanny** [comment]
多谢夏大的详细解答，我之前对这块ffmpeg的RTSP协议理解有问题，我正在debug中。我看您的项目也同步到了Gitee，在gitee上请你喝了杯咖啡。
