### ISSUE TITLE
如何添加一个AAC的静音音频到rtsp

### ISSUE THREAD

**Issue by hh-kai** [xiongziliang/ZLMediaKit#240]
我在使用MuteAudioMaker给rtsp流 添加静音的时候 提示 为找到该类 我查看了文件PlayerProxy里面有MuteAudioMaker 但是好像没有暴露出来
我是参考这个代码使用的 
```c++

	auto audioTrack = getTrack(TrackAudio, false);
	if(audioTrack){
		//添加音频
		_mediaMuxer->addTrack(audioTrack);
		//音频数据写入_mediaMuxer
        audioTrack->addDelegate(_mediaMuxer);
    }else if(addMuteAudio && videoTrack){
		//没有音频信息，产生一个静音音频
		MuteAudioMaker::Ptr audioMaker = std::make_shared<MuteAudioMaker>();
		//videoTrack把数据写入MuteAudioMaker
		videoTrack->addDelegate(audioMaker);
		//添加一个静音Track至_mediaMuxer
		_mediaMuxer->addTrack(std::make_shared<AACTrack>());
		//MuteAudioMaker生成静音音频然后写入_mediaMuxer；
		audioMaker->addDelegate(_mediaMuxer);
	}
```

**Comment by xiongziliang** [comment]
你这代码没问题啊 说白了还是头文件引用关系的问题

**Comment by hh-kai** [comment]
我在main.cpp 里面还额外 添加了 
`
#include "Extension/AAC.h"
#include "Extension/H264.h"

#include "Player/PlayerProxy.h"
`
除了这些 还需要那些头文件

**Comment by xiongziliang** [comment]
请问你把MuteAudioMaker类放在哪里了？把这个文件上传 上来

**Comment by hh-kai** [comment]
这个类在PlayerProxy.cpp 文件里面

![无标题](https://user-images.githubusercontent.com/19390025/76729429-1eeeab00-6794-11ea-992f-c78f59e122a8.png)

**Comment by xiongziliang** [comment]
你觉得你
#include "Player/PlayerProxy.h"
能访问 PlayerProxy.cpp里面的私有类吗

**Comment by xiongziliang** [comment]
你是C++半道出家吧？C语法都不熟悉吧？

**Comment by hh-kai** [comment]
是啊 还在学习 想拿这个项目来入门

**Comment by hh-kai** [comment]
我查了一下 看到有内部类、嵌套类  私有类该怎么用？这个类只是在它的cpp文件中 应该不属于任何类吧 可以简单说一点吗？

**Comment by xiongziliang** [comment]
算了 我觉得你这种水平我教不会

**Comment by xiongziliang** [comment]
这个是基本的操作 你先多学习下相关语法吧
