### ISSUE TITLE
windows下编译的二进制文件接收rtp流的时候一直丢包，linux下正常

### ISSUE THREAD

**Issue by wujincheng2333** [xiongziliang/ZLMediaKit#241]
windows下接收rtp流（海康\大华）控制台一直打印丢包，而且每次相差的都是1或2个数据包。linux下没有这种现象。。。丢包的时候视频播放就会卡住或者循环播放前几秒。。。

windows编译环境: win10,vs2017,cmake-gui 3.10
linux编译环境：centos7

**Comment by xiongziliang** [comment]
建议你改成TCP推流，udp不仅仅可能丢包，还性能受限。
我这里没测试环境，我没法调试。
