### ISSUE TITLE
hls播放url格式

### ISSUE THREAD

**Issue by zhangjs** [xiongziliang/ZLMediaKit#243]
常见的播放URL格式是
https://somedomain.com/live/0/playlist.m3u8
https://somedomain.com/live/0.m3u8

建议两种都支持

**Comment by xiongziliang** [comment]
设计多一层目录的原因是删除可以直接删除文件夹，不用记录每个生成的文件路径
其实改成这种格式我认为意义不大 毕竟你只有测试时才会手输url

**Comment by zhangjs** [comment]
url这个跟程序内部实现关系不大，主要看业界实际是什么样的

**Comment by xiongziliang** [comment]
https://somedomain.com/live/0/playlist.m3u8
跟
https://somedomain.com/live/0/hls.m3u8
没本质上的区别，我不认为这个是所谓约定成熟的规定，就算是，不遵循也不会有什么不好的后果
