### ISSUE TITLE
配置文件格式

### ISSUE THREAD

**Issue by zhangjs** [xiongziliang/ZLMediaKit#244]
建议采用类似nginx、srs那种的层次格式，可以支持类似按vhost、app级别的配置

**Comment by xiongziliang** [comment]
我也想搞成srs和NGINX那样啊
那样代价比较大，而且比较重，后面又事件可以弄下，目前主要的精力我觉得不应该用于锦上添花，支持一种新的编码或者协议不是更香吗？
