### ISSUE TITLE
对接海康平台录像取流回放报500错误

### ISSUE THREAD

**Issue by yuyuxp** [xiongziliang/ZLMediaKit#245]
对接海康平台录像取rtsp流回放，报500错误。
发现zlmediakit发play命令的时候，必须带上"Range: npt=0.000-"
否则海康平台报错
RTSP/1.0 500 Internal Server Error
CSeq: 5
Server: Media
ExtErrInfo: errcode=0;description=fail

**Comment by xiongziliang** [comment]
你试试最新代码
