### ISSUE TITLE
使用FFMPEG将MP3文件以RTSP推流方式推送到MediaServer,报暂不支持该sdp

### ISSUE THREAD

**Issue by heyingjie** [xiongziliang/ZLMediaKit#247]
如题所示，使用FFMPEG将MP3文件以RTSP推流方式推送到MediaServer,报暂不支持该sdp。
FFMPEG推送指令如下:
ffmpeg.exe -re -stream_loop -1 -i test.mp3 -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:554/live/rtsp_test

**Comment by xiongziliang** [comment]
没事 只是不能转成其他协议 rtsp完全正常的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Seth <notifications@github.com&gt;
发送时间: 2020年3月26日 10:05
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 使用FFMPEG将MP3文件以RTSP推流方式推送到MediaServer,报暂不支持该sdp (#247)





 
如题所示，使用FFMPEG将MP3文件以RTSP推流方式推送到MediaServer,报暂不支持该sdp。
 FFMPEG推送指令如下:
 ffmpeg.exe -re -stream_loop -1 -i test.mp3 -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:554/live/rtsp_test

**Comment by heyingjie** [comment]
> 没事 只是不能转成其他协议 rtsp完全正常的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Seth <notifications@github.com&gt; 发送时间: 2020年3月26日 10:05 收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[xiongziliang/ZLMediaKit] 使用FFMPEG将MP3文件以RTSP推流方式推送到MediaServer,报暂不支持该sdp (#247) 如题所示，使用FFMPEG将MP3文件以RTSP推流方式推送到MediaServer,报暂不支持该sdp。 FFMPEG推送指令如下: ffmpeg.exe -re -stream_loop -1 -i test.mp3 -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:554/live/rtsp_test — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢回复，但是目前按照上述指令将RTSP推送到MediaServer后，使用VLC播放rtsp://127.0.0.1:554/live/rtsp_test 链接，无法打开。

**Comment by xiongziliang** [comment]
这个bug修复了 谢谢您的反馈！

**Comment by heyingjie** [comment]
验证了，已经OK

**Comment by CococoloSimida** [comment]
![image](https://user-images.githubusercontent.com/37428412/126310723-bad05232-af20-44a8-b956-f48e4f9a6e3a.png)
请问 Audio: aac (LC) (mp4a / 0x6134706D) 这个音频格式也不支持吗

**Comment by xia-chu** [comment]
> ![image](https://user-images.githubusercontent.com/37428412/126310723-bad05232-af20-44a8-b956-f48e4f9a6e3a.png)
> 请问 Audio: aac (LC) (mp4a / 0x6134706D) 这个音频格式也不支持吗

支持 只是不能转协议

**Comment by CococoloSimida** [comment]
> > ![image](https://user-images.githubusercontent.com/37428412/126310723-bad05232-af20-44a8-b956-f48e4f9a6e3a.png)
> > 请问 Audio: aac (LC) (mp4a / 0x6134706D) 这个音频格式也不支持吗
> 
> 支持 只是不能转协议

不能转协议是指源流也必须是rtsp的吗，可我的源流就是rtsp的啊，通过addStreamProxy代理的方式会报这个错，直接用ffmpeg拉这个rtsp流再推到mideaServer上是可以的~

**Comment by xia-chu** [comment]
播放失败是另外的问题 接收rtp超时 请用tcp方式播放 udp超时了

**Comment by xia-chu** [comment]
播放失败是另外的问题 接收rtp超时 请用tcp方式播放 udp超时了

**Comment by CococoloSimida** [comment]
哦哦 所以这是两个问题：
1.暂不支持sdp报错是因为转协议，（如图，我的拉流地址是rtsp地址，通过addStreamProxy这个api接口代理之后的地址应该是rtsp://192.168.110.167/live/test，还是没太明白您说的转协议指的是哪个地方
![image](https://user-images.githubusercontent.com/37428412/126588448-811c3e02-0be9-434f-8994-cc4688633d86.png)
2.receive rtp timeout这个报错是因为不支持udp吗，您说的用tcp方式播放，是指需要把源流改成tcp传输，还是说在流媒体服务器的那个地方配置tcp？
