### ISSUE TITLE
on_stream_not_found咨询

### ISSUE THREAD

**Issue by zywu31** [xiongziliang/ZLMediaKit#249]
1.如果播放HLS没找到文件能不能也通知on_stream_not_found事件.（HLS切片没有经过服务器）
2.当我推流给服务器时也会通知on_stream_not_found事件,这个能不能做一个区分是推流还是播放请求

**Comment by xiongziliang** [comment]
1、ZLMediaKit自带的http服务器支持hls按需拉流，也就是播放不存在的hls时会触发on_stream_not_found事件。

2、推流不会触发on_stream_not_found事件，你确定不是你搞错了？
