### ISSUE TITLE
ZLMediaKit框架是否支持ipc相机侧端的音视频同步问题

### ISSUE THREAD

**Issue by zhuky888888** [xiongziliang/ZLMediaKit#25]
你好群主，我这边有个服务器推送rtsp流的需求，目的是将ZLMediaKit框架部署在ipc侧，但是如何保证摄像机端和麦克风端过来的音视频数据同步问题，ZLMediaKit框架 上有保证吗？

**Comment by xiongziliang** [comment]
音视频同步是通过时间戳来保证的，你产生音视频原始数据时就应该有时间戳的信息；
你把这些数据输入到ZLMediaKit一般都要提供时间戳的信息的，所以音视频同步这个功能需要使用者保证。
