### ISSUE TITLE
rtsp拉流地址错误，会一直重试无法停止

### ISSUE THREAD

**Issue by yuyuxp** [xiongziliang/ZLMediaKit#250]
如果rtsp拉流地址写错，ZLMediaKit会一直重试（通过抓包发现）。在getMediaList接口上无法看到流，close_streams也找不到流关闭，配置文件也没找到重试次数或者重试时间开关，无法停止。

**Comment by xiongziliang** [comment]
1、通过restful api([addStreamProxy](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#12indexapiaddstreamproxy))添加拉流代理时不会存在你说的问题，默认是第一次启动拉流失败会直接返回失败，不会添加成功。如果第一次成功了，后面才会一直重试，这种机制是没问题的。

2、close_streams只能删除一个已经存在的流，一个不存在的流不能删除，如果拉流代理失败了，那么你应该通过restful api([delStreamProxy](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#13indexapidelstreamproxy))删除。

3、如果你是自己通过代码添加拉流代理的，那么你应该通过PlayerProxy::setPlayCallbackOnce监听启动拉流失败事件，第一次添加拉流结果将触发该事件，如果第一次能添加成功，后面就是断开重连失败也会一直重试。

**Comment by r0n9** [comment]
> 1、通过restful api([addStreamProxy](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#12indexapiaddstreamproxy))添加拉流代理时不会存在你说的问题，默认是第一次启动拉流失败会直接返回失败，不会添加成功。如果第一次成功了，后面才会一直重试，这种机制是没问题的。
> 
> 2、close_streams只能删除一个已经存在的流，一个不存在的流不能删除，如果拉流代理失败了，那么你应该通过restful api([delStreamProxy](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#13indexapidelstreamproxy))删除。
> 
> 3、如果你是自己通过代码添加拉流代理的，那么你应该通过PlayerProxy::setPlayCallbackOnce监听启动拉流失败事件，第一次添加拉流结果将触发该事件，如果第一次能添加成功，后面就是断开重连失败也会一直重试。

原来的rtsp流地址开始可以但后来确实失效了，但还是在一直失败重试，这种场景该如何处理？有没有地方配置重试次数？

**Comment by xia-chu** [comment]
目前是一直重试的 虽然代码可以设置重试次数 但是没暴露上http api.
我好像还没遇到需要制定重试次数的场景，我觉得，你应该不太可能知道这个流重试多少次才能上线，最好让用户自己删除无效的流
