### ISSUE TITLE
MediaServer如何实现test中的 test_pusher功能?

### ISSUE THREAD

**Issue by woshiwoyali** [xiongziliang/ZLMediaKit#252]
启动MediaServer服务后，调用那个接口可以实现test_pusher功能？

**Comment by xiongziliang** [comment]
你说的这个接口其实已经有，那就是[addFFmpegSource](https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#14indexapiaddffmpegsource)接口，只不过这个是借助FFmpeg先拉流后推流。


test_pusher这个demo是基于ZLMediaKit原生代码实现的，性能肯定比FFmpeg好多了，但是由于我现在并没有这样用原生代码实现的拉流再推流restful api，所以建议你先用addFFmpegSource接口实现。

注意这个接口默认会统一 转码H264和aac，如果你拉流的地址是固定为H264,你可以在配置文件中把
`ffmpeg.cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s`
改成
`ffmpeg.cmd=%s -re -i %s -c:a copy -c:v copy -f flv %s`

**Comment by xiongziliang** [comment]
对了 如果你要推rtsp，可以改成：
ffmpeg.cmd=%s -re -i %s -c:a copy -c:v copy -f rtsp -rtsp_transport tcp %s
