### ISSUE TITLE
rtsp流转http-flv流，通过flv.js供chrome浏览器播放。

### ISSUE THREAD

**Issue by jianghongsun** [xiongziliang/ZLMediaKit#253]
首先感谢作者的代码分享，
1 .如何解决rtsp流转http-flv流（类似于本地的插件），并测试转换的http-flv流成功(即转换的流地址http://localhost/my.flv)？
2. 博客https://blog.csdn.net/v6543210/article/details/104847094/ 使用OBS推流测试。可以直接生成http://localhost/my.flv吗？
希望作者有空解答下，提点建议，谢谢！

**Comment by xiongziliang** [comment]
## 1、如果你想把ZLMediaKit当做sdk使用
强烈推荐使用 [c api](https://github.com/xiongziliang/ZLMediaKit/tree/master/api/include),这里是c api的[测试程序](https://github.com/xiongziliang/ZLMediaKit/blob/master/api/tests/server.c)。

## 2、怎么启动rtsp拉流并转化成http-flv?
- 2.1、你需要启动http服务器(为了方便建议同时启动rtsp/rtmp服务器)：
```c++
    char *ini_path = mk_util_get_exe_dir("c_api.ini");
    char *ssl_path = mk_util_get_exe_dir("ssl.p12");

    mk_config config = {
            .ini = ini_path,
            .ini_is_path = 1,
            .log_level = 0,
            .ssl = ssl_path,
            .ssl_is_path = 1,
            .ssl_pwd = NULL,
            .thread_num = 0
    };
    mk_env_init(&config);
    free(ini_path);
    free(ssl_path);

    mk_http_server_start(80, 0);
    mk_rtsp_server_start(554, 0);
    mk_rtmp_server_start(1935, 0);
```

- 2.2、开启rtsp拉流代理并转化成http-flv:
你需要使用[mk_proxyplayer接口](https://github.com/xiongziliang/ZLMediaKit/blob/master/api/include/mk_proxyplayer.h)：
```c++
    //创建拉流代理对象
    mk_proxy_player  ctx = mk_proxy_player_create("__defaultVhost__", "live", "stream", 1 /*开启hls*/, 0 /*关闭mp4*/);
    mk_proxy_player_play(ctx, "rtsp://xxxxxx/xxx/xxx");
```

- 2.3、测试
如果拉流代理成功，你可以在播放器播放这些url：
    - rtsp://127.0.0.1/live/stream
    - rtmp://127.0.0.1/live/stream
    - http://127.0.0.1/live/stream.flv
    - http://127.0.0.1/live/stream/hls.m3u8

具体你可以参考这篇文章了解更多播放方式：[播放url规则](https://github.com/xiongziliang/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99)


### 3、怎么用OBS推流并转化成http-flv?
你可以在obs推流到 rtmp://127.0.0.1/live/stream,然后播放地址对应为以下(其实跟上面一致)：
    - rtsp://127.0.0.1/live/stream
    - rtmp://127.0.0.1/live/stream
    - http://127.0.0.1/live/stream.flv
    - http://127.0.0.1/live/stream/hls.m3u8

**Comment by jianghongsun** [comment]
非常感谢作者的解答
