### ISSUE TITLE
续 rtsp流转http-flv流，通过flv.js供chrome浏览器播放

### ISSUE THREAD

**Issue by jianghongsun** [xiongziliang/ZLMediaKit#254]
作者你好 感谢你对这问题的细心仔细解答
1.  char *ini_path = mk_util_get_exe_dir("c_api.ini");
c_api.ini 麻烦解答一下

**Comment by xiongziliang** [comment]
续#253 

你可以置空（这样就不会加载配置文件了）：
```c++
    char *ini_path = NULL;
```

**Comment by jianghongsun** [comment]
好的  看了config.ini明白了
