### ISSUE TITLE
咨询使用mk_media推流时play和seek后时间戳的处理

### ISSUE THREAD

**Issue by baiyfcu** [xiongziliang/ZLMediaKit#255]
目前处理时间戳时，play传入视频播放累计的时间作为dts，pts等于dts，只增不减，现在遇到问题seek后如果不通过增加SEI帧处理NTP时间，seek后此处的dts，pts如何处理？ 另外mk_media是否缺少seekTo的事件回调

**Comment by xiongziliang** [comment]
1、rtsp客户端调用seekTo方法成功后会触发onResume事件，你可以通过MediaPlayer::setOnResume设置回调。
2、ZLMediaKit中rtsp的时间戳是绝对时间戳，可以增加和减少。
3、mk_media接口确实没有设置onSeek回调事件，后面我加一下，我本来是作为直播用的....

**Comment by baiyfcu** [comment]
直播推流和录像推流差不多的，录像推流dts，我试试传入绝对时间

**Comment by xiongziliang** [comment]
rtmp也支持点播 但是后面改了很多东西 不知道现在seek能否正常 你可以测试下

**Comment by xiongziliang** [comment]
目前我都测试了seek功能，基本都算正常，我在服务器内部做了判断是否为点播，如果是点播，会采用绝对时间戳的。
