### ISSUE TITLE
关于GB28181集成摄像头

### ISSUE THREAD

**Issue by swwheihei** [xiongziliang/ZLMediaKit#256]
大佬，你好！
我计划使用ZLMediaKit作为服务器使用，接收GB28181摄像头发送的RTP视频流，并转为RTSP格式进行播放。
通过查看使用教程，发现可以使用【按需推流】流程，但GB28181中定义视频流使用RTP协议推送，请问如何向ZLMediaKit服务器推送RTP视频流？是向配置文件中定义的[rtp_proxy]-port中的10000端口推送吗？如何获取转换后的RTSP视频流呢？
非常感谢！

**Comment by xiongziliang** [comment]
是啊 往10000端口推rtp流即可，支持udp和tcp方式

**Comment by swwheihei** [comment]
那使用VLC播放 rtsp://ip:554/live/0就可以看到视频了吗？如果有多个摄像头需要预览，都往10000端口推送，如何进行区分呢？

**Comment by xiongziliang** [comment]
一般为 rtsp://ip:554/rtp/ssrc
你可以关注日志

**Comment by swwheihei** [comment]
好的，非常感谢！
