### ISSUE TITLE
findCertificate can not find any certificate of host:default host

### ISSUE THREAD

**Issue by bestneymarjr** [xiongziliang/ZLMediaKit#257]
看到readme里有提到支持echo show这样的设备，正好我现在在做的工作也是在echo show上观看摄像机的视频流，虽然我已经实现这个功能，但看到zlmediakit功能很强大，所以有考虑用它替代现有的服务器。
因为echo show必须是要使用rtsps，我不太清楚的是我应该怎么将证书添加进去，我在可执行程序同目录放了一个ssl.p12文件，显然程序读取了这个证书，但是当我尝试用echo show播放时得到了findCertificate can not find any certificate of host:default host这样的错误。我应该怎么正确的导入证书，证书是只支持p12格式吗？

**Comment by bestneymarjr** [comment]
我并没有开启虚拟主机

**Comment by xiongziliang** [comment]
支持p12和pem格式的证书

**Comment by xiongziliang** [comment]
你没导入正确的证书吧？echo show你播放的不是域名的url吗？

**Comment by bestneymarjr** [comment]
是域名的，我的p12也是根据域名证书用openssl生成的

**Comment by bestneymarjr** [comment]
证书的名称是什么格式的呢？有没有什么要求，是必须ssl.pem ssl.p12吗？

**Comment by xiongziliang** [comment]
你没有加载任何证书成功，否则不会这样的。

**Comment by bestneymarjr** [comment]
希望可以在配置文件里加一下证书的添加说明，或者指定证书路径，zlmediakit真的很好用，也很强大，非常感谢您的贡献

**Comment by xiongziliang** [comment]
./MediaServer -h获取帮助啊

**Comment by xiongziliang** [comment]
通了没？

**Comment by bestneymarjr** [comment]
我有点事，已经下班了，明天再搞，还让您“牵挂”了，
感觉我们可能是同行，不过您是大佬，我是还没入门的菜鸟

**Comment by bestneymarjr** [comment]
> ./MediaServer -h获取帮助啊

之前-h看过，竟然没看到有证书添加的说明，粗心了，已经添加成功了，非常感谢。

**Comment by xiongziliang** [comment]
意思是echo show能正常播放视频了？

**Comment by bestneymarjr** [comment]
只是证书添加成功了

**Comment by bestneymarjr** [comment]
echo show还是不行
这个原因我在找，需要把rtsp 请求日志打出来

**Comment by xiongziliang** [comment]
嗯 之前有人反馈过这个 我也没找到原因 可能echo show真的不支持

**Comment by xiongziliang** [comment]
他的反馈是有些流可以 有些不行

**Comment by bestneymarjr** [comment]
有些流可以，有些流不行这个确实是真的，我还遇到了不同版本的echo show都存在问题，echo show1可以播，echo show8不能播，亚马逊解释说是sps解析出来的一个字段不对，他们不支持，之后会做固件升级，但是一直也没升级，

**Comment by bestneymarjr** [comment]
我在抓包测试，感觉我的tls连接可能有问题，
 findCertificate client does not specify host, select default certificate of host: *.***.com
从日志看证书貌似已经没问题的

**Comment by xiongziliang** [comment]
这个是由于echo show在ssl握手时 没指定选择的域名和证书 服务器这边只能给个默认的证书

**Comment by xiongziliang** [comment]
> 有些流可以，有些流不行这个确实是真的，我还遇到了不同版本的echo show都存在问题，echo show1可以播，echo show8不能播，亚马逊解释说是sps解析出来的一个字段不对，他们不支持，之后会做固件升级，但是一直也没升级，

有文章吗？

**Comment by bestneymarjr** [comment]
> 这个是由于echo show在ssl握手时 没指定选择的域名和证书 服务器这边只能给个默认的证书

我觉得我的证书配置还是不对，我也刚入行不到一年，很多东西都不会
 setContext add certificate of: *.example.com
程序启动确实也是添加成功证书了，
但我用openssl s_client -connect **.example.com:443 -state测tls状态，确实是报错了
SSL3 alert read:fatal:unrecognized name
SSL_connect:error in error
我的证书pem内包含了base64编码的证书和秘钥
不清楚这样子配置到底对不对，如果您发现有什么问题，还请指点

**Comment by bestneymarjr** [comment]
> > 有些流可以，有些流不行这个确实是真的，我还遇到了不同版本的echo show都存在问题，echo show1可以播，echo show8不能播，亚马逊解释说是sps解析出来的一个字段不对，他们不支持，之后会做固件升级，但是一直也没升级，
> 
> 有文章吗？
只有邮件，这是最终亚马逊给的回复，问题是同一个摄像机echo show1可以，echo show8不能播放
Hello there,

We appreciate your patience!

We could able to reproduce the issue from our end and this will be fixed in the next firmware release for Echo show 8 device and our internal team is working on the same. We do not comment on the ETA of features releases. I can only suggest you keep an eye on our blogs for new announcements here: http://alexa.design/blog.

Also, I heard back that you can do few changes in the implementation so that till the fix you can use your skill on Echo show 8:
1. "delta_scale" value should be always positive and the limit is 127.
2. Session description has value for npt range which is not supported. Please change the npt range value to "now-" instead of "0-"

**Comment by xiongziliang** [comment]
> 1. delta_scale
我马上改下

**Comment by xiongziliang** [comment]
> > 这个是由于echo show在ssl握手时 没指定选择的域名和证书 服务器这边只能给个默认的证书
> 
> 我觉得我的证书配置还是不对，我也刚入行不到一年，很多东西都不会
> setContext add certificate of: *.example.com
> 程序启动确实也是添加成功证书了，
> 但我用openssl s_client -connect **.example.com:443 -state测tls状态，确实是报错了
> SSL3 alert read:fatal:unrecognized name
> SSL_connect:error in error
> 我的证书pem内包含了base64编码的证书和秘钥
> 不清楚这样子配置到底对不对，如果您发现有什么问题，还请指点

你看我的https完全正常啊：
![image](https://user-images.githubusercontent.com/11495632/78329323-f2b89400-75b3-11ea-9ecd-258fabba8c22.png)

**Comment by xiongziliang** [comment]
```bash
xzl-mac-pro:~ xzl$ openssl s_client -connect zlmediakit.com:443 -state
CONNECTED(00000003)
SSL_connect:before/connect initialization
SSL_connect:SSLv3 write client hello A
SSL_connect:SSLv3 read server hello A
depth=0 CN = zlmediakit.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = zlmediakit.com
verify error:num=21:unable to verify the first certificate
verify return:1
SSL_connect:SSLv3 read server certificate A
SSL_connect:SSLv3 read server done A
SSL_connect:SSLv3 write client key exchange A
SSL_connect:SSLv3 write change cipher spec A
SSL_connect:SSLv3 write finished A
SSL_connect:SSLv3 flush data
SSL_connect:SSLv3 read server session ticket A
SSL_connect:SSLv3 read finished A
---
Certificate chain
 0 s:/CN=zlmediakit.com
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=Encryption Everywhere DV TLS CA - G1
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFmDCCBICgAwIBAgIQC8Oyl1PJCOfld1qngkWttTANBgkqhkiG9w0BAQsFADBu
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMS0wKwYDVQQDEyRFbmNyeXB0aW9uIEV2ZXJ5d2hlcmUg
RFYgVExTIENBIC0gRzEwHhcNMTkwOTIxMDAwMDAwWhcNMjAwOTIwMTIwMDAwWjAZ
MRcwFQYDVQQDEw56bG1lZGlha2l0LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAIAuX0hD1DKaID26Nzpyn6cVulc9iqxJ+1L41bgpTaNTdhdsHerT
DwJM9pZ5aJ27gwwvJ3952ZJno3PCbBTVXNzKp6z2z4SC35Dkdb2Kh3iE9ef+6ycW
nQCRAMgXpC5PWTWvtOgYOlA7TA3+aS3gC0cjYojeoAshqtWwUX7gVSVLTLpgFtV6
0aICLU8W1ERK8kIVlyCLkV+qCOYKDBwwycfZt3UrvCuT6MVU0+275R919jzc3eIZ
H6oi04U8jxMH82zncLeoLJg2aulImD5CiDfVMSlv9dLwaC434G7tb5y60VeZFCDd
V7flYOelDJOTI38+In3oh1WKur9qJ/a+fjsCAwEAAaOCAoUwggKBMB8GA1UdIwQY
MBaAFFV0T7JyT/VgulDR1+ZRXJoBhxrXMB0GA1UdDgQWBBTrcLnfqb96Q/WCF8A0
DshJ0Nb0vTAtBgNVHREEJjAkgg56bG1lZGlha2l0LmNvbYISd3d3LnpsbWVkaWFr
aXQuY29tMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
BQUHAwIwTAYDVR0gBEUwQzA3BglghkgBhv1sAQIwKjAoBggrBgEFBQcCARYcaHR0
cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAIBgZngQwBAgEwgYAGCCsGAQUFBwEB
BHQwcjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEoGCCsG
AQUFBzAChj5odHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRW5jcnlwdGlvbkV2
ZXJ5d2hlcmVEVlRMU0NBLUcxLmNydDAJBgNVHRMEAjAAMIIBAwYKKwYBBAHWeQIE
AgSB9ASB8QDvAHUApLkJkLQYWBSHuxOizGdwCjw1mAT5G9+443fNDsgN3BAAAAFt
UzFmlgAABAMARjBEAiASivvkjOJI8ZcF+4/WifmeCjMTs43TplTLZYESBME00QIg
JU2ZBp6xQSclZboTGjXSrjS8cv7wULTs4wO1JAxwyO8AdgBep3P531bA57U2SH3Q
SeAyepGaDIShEhKEGHWWgXFFWAAAAW1TMWYvAAAEAwBHMEUCIHEjCgYsPtAMmdnY
MN7vf36wRvtYooumt/sTxrY45fPaAiEAhUGUQ6UkQKKW0aPiH4B47GD4cRXRpeQW
dry0AyPyIsswDQYJKoZIhvcNAQELBQADggEBAAXg1UYPwzWvcjMa8RhEzQI+z04u
CL46zi3Bvi7hB8LyFq13SywkjlXSKt4oBDT7IdPtas1oJns9oqmVvHEDN4C7r4bz
W9sS9ErYxSWidofW0+bdvp+GO59ZIbTPtjVQv7d7PNVRbdqA0SIyAUgehuReX+kq
6FQq6jIrwzxNgNx9JXMAduEcs8KbeENNWjVC/QwyxK/O3x2LjgArHp4ADqod52DH
TmPt5qPvPWTgk+PFsVOzbVVUBGYRLqFzsCA7G6CRcsfLG+IllipdezTtoNGHbzMc
wRSsLDd/+DsEChfv6272ZIKIBclBsqLdvD46Px5nrXVOqCuEA+dRzaMwVto=
-----END CERTIFICATE-----
subject=/CN=zlmediakit.com
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=Encryption Everywhere DV TLS CA - G1
---
No client certificate CA names sent
---
SSL handshake has read 1744 bytes and written 514 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: EC44338EE081ECE0B2F0B9959D756DBE92CCAF73E6D3F65C5C009585A220FE34
    Session-ID-ctx: 
    Master-Key: 90950A72BCF8C2776E69F0987F212CF7CBA43DEF610F2E67E92E82781A811AC7B71BA6D14404AA8C7CF95BC6107C57EC
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - ce b7 97 f9 6c 6b d8 b4-9b a0 61 96 8e 21 8c af   ....lk....a..!..
    0010 - fd 1f e3 bc b9 fa 47 6e-e7 ac 3a 1b 4c 37 82 44   ......Gn..:.L7.D
    0020 - 4b 1f 26 9d e6 45 3c 69-e2 79 4c a8 55 bc b7 65   K.&..E<i.yL.U..e
    0030 - 19 02 88 87 41 1a 97 75-54 ff a6 f2 93 6e 9a f1   ....A..uT....n..
    0040 - 24 a0 d1 d9 23 c5 7d 90-58 9f d5 0d e3 4b d5 56   $...#.}.X....K.V
    0050 - 0b 86 00 e5 21 f2 a5 f0-eb fc e9 ea 71 ca 10 41   ....!.......q..A
    0060 - 08 3f 0d c4 68 e8 15 f3-da 59 1d 9a e8 71 2f ff   .?..h....Y...q/.
    0070 - d3 82 6a af f1 0f 96 dd-45 d3 7f 3f 18 df f5 04   ..j.....E..?....
    0080 - 98 67 6b 7a 66 4f b6 34-21 6a 37 db a3 2b ea c4   .gkzfO.4!j7..+..
    0090 - c7 d3 72 a7 b9 6a b9 e1-6f 53 91 79 7f b2 31 43   ..r..j..oS.y..1C

    Start Time: 1585893881
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
```

**Comment by xiongziliang** [comment]
你再拉下最新代码试试

**Comment by xiongziliang** [comment]
这个issue我关闭了？

**Comment by bestneymarjr** [comment]
谢谢您，可以关闭了

**Comment by xiongziliang** [comment]
你倒是说下结果啊

**Comment by bestneymarjr** [comment]
最近在忙别的，这边没往下进行了，不过我发现证书确实是导入成功了的，我也可以成功的建立tls连接，但是echo show那边还是没播出来，echo show不能播放的问题，我目前还没定位是证书问题还是sdp描述问题，不过我有看zlmediakit sdp格式，应该没问题。之后有时间再解决这个问题。不过不解决应该也可以，部署的时候可能会复用443端口，可能会用nginx代理，这样也就不用在zlmediakit这里配置证书了

**Comment by bestneymarjr** [comment]
之后配合二次开发如果成功在echo show下可以使用，我会在这个issues下留言，还是非常感谢您的贡献

**Comment by xiongziliang** [comment]
好的 那我先关闭了

**Comment by bestneymarjr** [comment]
刚刚试了一下，我用nginx去建立tls连接，已成功在echo show上播放出来，至于为什么直接添加证书不行，因为自己经验不足把，目前还没判断出来，之后有时间在研究一下。不过zlmediakit的延迟确实教我以前的服务器低了一些。

**Comment by bestneymarjr** [comment]
> ```shell
> xzl-mac-pro:~ xzl$ openssl s_client -connect zlmediakit.com:443 -state
> CONNECTED(00000003)
> SSL_connect:before/connect initialization
> SSL_connect:SSLv3 write client hello A
> SSL_connect:SSLv3 read server hello A
> depth=0 CN = zlmediakit.com
> verify error:num=20:unable to get local issuer certificate
> verify return:1
> depth=0 CN = zlmediakit.com
> verify error:num=21:unable to verify the first certificate
> verify return:1
> SSL_connect:SSLv3 read server certificate A
> SSL_connect:SSLv3 read server done A
> SSL_connect:SSLv3 write client key exchange A
> SSL_connect:SSLv3 write change cipher spec A
> SSL_connect:SSLv3 write finished A
> SSL_connect:SSLv3 flush data
> SSL_connect:SSLv3 read server session ticket A
> SSL_connect:SSLv3 read finished A
> ---
> Certificate chain
>  0 s:/CN=zlmediakit.com
>    i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=Encryption Everywhere DV TLS CA - G1
> ---
> Server certificate
> -----BEGIN CERTIFICATE-----
> MIIFmDCCBICgAwIBAgIQC8Oyl1PJCOfld1qngkWttTANBgkqhkiG9w0BAQsFADBu
> MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
> d3cuZGlnaWNlcnQuY29tMS0wKwYDVQQDEyRFbmNyeXB0aW9uIEV2ZXJ5d2hlcmUg
> RFYgVExTIENBIC0gRzEwHhcNMTkwOTIxMDAwMDAwWhcNMjAwOTIwMTIwMDAwWjAZ
> MRcwFQYDVQQDEw56bG1lZGlha2l0LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
> ADCCAQoCggEBAIAuX0hD1DKaID26Nzpyn6cVulc9iqxJ+1L41bgpTaNTdhdsHerT
> DwJM9pZ5aJ27gwwvJ3952ZJno3PCbBTVXNzKp6z2z4SC35Dkdb2Kh3iE9ef+6ycW
> nQCRAMgXpC5PWTWvtOgYOlA7TA3+aS3gC0cjYojeoAshqtWwUX7gVSVLTLpgFtV6
> 0aICLU8W1ERK8kIVlyCLkV+qCOYKDBwwycfZt3UrvCuT6MVU0+275R919jzc3eIZ
> H6oi04U8jxMH82zncLeoLJg2aulImD5CiDfVMSlv9dLwaC434G7tb5y60VeZFCDd
> V7flYOelDJOTI38+In3oh1WKur9qJ/a+fjsCAwEAAaOCAoUwggKBMB8GA1UdIwQY
> MBaAFFV0T7JyT/VgulDR1+ZRXJoBhxrXMB0GA1UdDgQWBBTrcLnfqb96Q/WCF8A0
> DshJ0Nb0vTAtBgNVHREEJjAkgg56bG1lZGlha2l0LmNvbYISd3d3LnpsbWVkaWFr
> aXQuY29tMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
> BQUHAwIwTAYDVR0gBEUwQzA3BglghkgBhv1sAQIwKjAoBggrBgEFBQcCARYcaHR0
> cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAIBgZngQwBAgEwgYAGCCsGAQUFBwEB
> BHQwcjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEoGCCsG
> AQUFBzAChj5odHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRW5jcnlwdGlvbkV2
> ZXJ5d2hlcmVEVlRMU0NBLUcxLmNydDAJBgNVHRMEAjAAMIIBAwYKKwYBBAHWeQIE
> AgSB9ASB8QDvAHUApLkJkLQYWBSHuxOizGdwCjw1mAT5G9+443fNDsgN3BAAAAFt
> UzFmlgAABAMARjBEAiASivvkjOJI8ZcF+4/WifmeCjMTs43TplTLZYESBME00QIg
> JU2ZBp6xQSclZboTGjXSrjS8cv7wULTs4wO1JAxwyO8AdgBep3P531bA57U2SH3Q
> SeAyepGaDIShEhKEGHWWgXFFWAAAAW1TMWYvAAAEAwBHMEUCIHEjCgYsPtAMmdnY
> MN7vf36wRvtYooumt/sTxrY45fPaAiEAhUGUQ6UkQKKW0aPiH4B47GD4cRXRpeQW
> dry0AyPyIsswDQYJKoZIhvcNAQELBQADggEBAAXg1UYPwzWvcjMa8RhEzQI+z04u
> CL46zi3Bvi7hB8LyFq13SywkjlXSKt4oBDT7IdPtas1oJns9oqmVvHEDN4C7r4bz
> W9sS9ErYxSWidofW0+bdvp+GO59ZIbTPtjVQv7d7PNVRbdqA0SIyAUgehuReX+kq
> 6FQq6jIrwzxNgNx9JXMAduEcs8KbeENNWjVC/QwyxK/O3x2LjgArHp4ADqod52DH
> TmPt5qPvPWTgk+PFsVOzbVVUBGYRLqFzsCA7G6CRcsfLG+IllipdezTtoNGHbzMc
> wRSsLDd/+DsEChfv6272ZIKIBclBsqLdvD46Px5nrXVOqCuEA+dRzaMwVto=
> -----END CERTIFICATE-----
> subject=/CN=zlmediakit.com
> issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=Encryption Everywhere DV TLS CA - G1
> ---
> No client certificate CA names sent
> ---
> SSL handshake has read 1744 bytes and written 514 bytes
> ---
> New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
> Server public key is 2048 bit
> Secure Renegotiation IS supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> SSL-Session:
>     Protocol  : TLSv1.2
>     Cipher    : AES256-GCM-SHA384
>     Session-ID: EC44338EE081ECE0B2F0B9959D756DBE92CCAF73E6D3F65C5C009585A220FE34
>     Session-ID-ctx: 
>     Master-Key: 90950A72BCF8C2776E69F0987F212CF7CBA43DEF610F2E67E92E82781A811AC7B71BA6D14404AA8C7CF95BC6107C57EC
>     TLS session ticket lifetime hint: 300 (seconds)
>     TLS session ticket:
>     0000 - ce b7 97 f9 6c 6b d8 b4-9b a0 61 96 8e 21 8c af   ....lk....a..!..
>     0010 - fd 1f e3 bc b9 fa 47 6e-e7 ac 3a 1b 4c 37 82 44   ......Gn..:.L7.D
>     0020 - 4b 1f 26 9d e6 45 3c 69-e2 79 4c a8 55 bc b7 65   K.&..E<i.yL.U..e
>     0030 - 19 02 88 87 41 1a 97 75-54 ff a6 f2 93 6e 9a f1   ....A..uT....n..
>     0040 - 24 a0 d1 d9 23 c5 7d 90-58 9f d5 0d e3 4b d5 56   $...#.}.X....K.V
>     0050 - 0b 86 00 e5 21 f2 a5 f0-eb fc e9 ea 71 ca 10 41   ....!.......q..A
>     0060 - 08 3f 0d c4 68 e8 15 f3-da 59 1d 9a e8 71 2f ff   .?..h....Y...q/.
>     0070 - d3 82 6a af f1 0f 96 dd-45 d3 7f 3f 18 df f5 04   ..j.....E..?....
>     0080 - 98 67 6b 7a 66 4f b6 34-21 6a 37 db a3 2b ea c4   .gkzfO.4!j7..+..
>     0090 - c7 d3 72 a7 b9 6a b9 e1-6f 53 91 79 7f b2 31 43   ..r..j..oS.y..1C
> 
>     Start Time: 1585893881
>     Timeout   : 7200 (sec)
>     Verify return code: 21 (unable to verify the first certificate)
> ---
> ```

zlmediakit ssl连接的证书链是不是有问题？你发的这个连接里面也是有报错的
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = zlmediakit.com
verify error:num=21:unable to verify the first certificate
Verify return code: 21 (unable to verify the first certificate)

给客户端返回的时候没有返回上一级证书，证书验证便通过不了

**Comment by xiongziliang** [comment]
你说的很有道理啊 我试试

**Comment by xiongziliang** [comment]
我改了代码，现在这样了：
```bash
xzl-mac-pro:~ xzl$ openssl s_client -connect zlmediakit.com:443 -state
CONNECTED(00000003)
SSL_connect:before/connect initialization
SSL_connect:SSLv3 write client hello A
SSL_connect:SSLv3 read server hello A
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = Encryption Everywhere DV TLS CA - G1
verify return:1
depth=0 CN = zlmediakit.com
verify return:1
SSL_connect:SSLv3 read server certificate A
SSL_connect:SSLv3 read server done A
SSL_connect:SSLv3 write client key exchange A
SSL_connect:SSLv3 write change cipher spec A
SSL_connect:SSLv3 write finished A
SSL_connect:SSLv3 flush data
SSL_connect:SSLv3 read server session ticket A
SSL_connect:SSLv3 read finished A
---
Certificate chain
 0 s:/CN=zlmediakit.com
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=Encryption Everywhere DV TLS CA - G1
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=Encryption Everywhere DV TLS CA - G1
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFmDCCBICgAwIBAgIQC8Oyl1PJCOfld1qngkWttTANBgkqhkiG9w0BAQsFADBu
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMS0wKwYDVQQDEyRFbmNyeXB0aW9uIEV2ZXJ5d2hlcmUg
RFYgVExTIENBIC0gRzEwHhcNMTkwOTIxMDAwMDAwWhcNMjAwOTIwMTIwMDAwWjAZ
MRcwFQYDVQQDEw56bG1lZGlha2l0LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAIAuX0hD1DKaID26Nzpyn6cVulc9iqxJ+1L41bgpTaNTdhdsHerT
DwJM9pZ5aJ27gwwvJ3952ZJno3PCbBTVXNzKp6z2z4SC35Dkdb2Kh3iE9ef+6ycW
nQCRAMgXpC5PWTWvtOgYOlA7TA3+aS3gC0cjYojeoAshqtWwUX7gVSVLTLpgFtV6
0aICLU8W1ERK8kIVlyCLkV+qCOYKDBwwycfZt3UrvCuT6MVU0+275R919jzc3eIZ
H6oi04U8jxMH82zncLeoLJg2aulImD5CiDfVMSlv9dLwaC434G7tb5y60VeZFCDd
V7flYOelDJOTI38+In3oh1WKur9qJ/a+fjsCAwEAAaOCAoUwggKBMB8GA1UdIwQY
MBaAFFV0T7JyT/VgulDR1+ZRXJoBhxrXMB0GA1UdDgQWBBTrcLnfqb96Q/WCF8A0
DshJ0Nb0vTAtBgNVHREEJjAkgg56bG1lZGlha2l0LmNvbYISd3d3LnpsbWVkaWFr
aXQuY29tMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
BQUHAwIwTAYDVR0gBEUwQzA3BglghkgBhv1sAQIwKjAoBggrBgEFBQcCARYcaHR0
cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAIBgZngQwBAgEwgYAGCCsGAQUFBwEB
BHQwcjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEoGCCsG
AQUFBzAChj5odHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRW5jcnlwdGlvbkV2
ZXJ5d2hlcmVEVlRMU0NBLUcxLmNydDAJBgNVHRMEAjAAMIIBAwYKKwYBBAHWeQIE
AgSB9ASB8QDvAHUApLkJkLQYWBSHuxOizGdwCjw1mAT5G9+443fNDsgN3BAAAAFt
UzFmlgAABAMARjBEAiASivvkjOJI8ZcF+4/WifmeCjMTs43TplTLZYESBME00QIg
JU2ZBp6xQSclZboTGjXSrjS8cv7wULTs4wO1JAxwyO8AdgBep3P531bA57U2SH3Q
SeAyepGaDIShEhKEGHWWgXFFWAAAAW1TMWYvAAAEAwBHMEUCIHEjCgYsPtAMmdnY
MN7vf36wRvtYooumt/sTxrY45fPaAiEAhUGUQ6UkQKKW0aPiH4B47GD4cRXRpeQW
dry0AyPyIsswDQYJKoZIhvcNAQELBQADggEBAAXg1UYPwzWvcjMa8RhEzQI+z04u
CL46zi3Bvi7hB8LyFq13SywkjlXSKt4oBDT7IdPtas1oJns9oqmVvHEDN4C7r4bz
W9sS9ErYxSWidofW0+bdvp+GO59ZIbTPtjVQv7d7PNVRbdqA0SIyAUgehuReX+kq
6FQq6jIrwzxNgNx9JXMAduEcs8KbeENNWjVC/QwyxK/O3x2LjgArHp4ADqod52DH
TmPt5qPvPWTgk+PFsVOzbVVUBGYRLqFzsCA7G6CRcsfLG+IllipdezTtoNGHbzMc
wRSsLDd/+DsEChfv6272ZIKIBclBsqLdvD46Px5nrXVOqCuEA+dRzaMwVto=
-----END CERTIFICATE-----
subject=/CN=zlmediakit.com
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=Encryption Everywhere DV TLS CA - G1
---
No client certificate CA names sent
---
SSL handshake has read 2945 bytes and written 514 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: 375BB57C111535A655C9F5297540ED64A3927FABEB0E3DB5983DE31FB12B1EA4
    Session-ID-ctx: 
    Master-Key: 54D454A4EA4E3A45AA262170EF1731165F8E0161A2FE48C2FE76245C4F7AE7809CA12A8B2725D0BEADFA28B0B289C8D0
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - cd 1a 14 f2 35 4c 36 28-a3 8d 1a f1 2f a1 9a 98   ....5L6(..../...
    0010 - cc 29 55 61 15 2c 34 01-30 47 85 51 5d 7c b8 fe   .)Ua.,4.0G.Q]|..
    0020 - a7 ab f5 b6 a1 00 32 0e-9a 7f 7d a2 5f 8f a8 c2   ......2...}._...
    0030 - eb a5 e1 fb 1e 67 64 9a-a4 c0 c1 ab d1 e5 61 aa   .....gd.......a.
    0040 - a5 2d 56 14 c6 c2 60 7f-eb e9 74 1a e9 96 90 e1   .-V...`...t.....
    0050 - af 67 04 6d 33 73 00 a0-f1 84 3e f0 9f b2 61 d9   .g.m3s....>...a.
    0060 - 3c 25 e8 6a 25 d2 5f 04-51 eb c6 a5 65 ff dd b0   <%.j%._.Q...e...
    0070 - c5 ff 20 20 47 10 06 43-96 39 5a 83 c5 56 06 be   ..  G..C.9Z..V..
    0080 - 9f c3 aa ef 7e f8 b1 eb-fb 47 88 27 56 39 3c 13   ....~....G.'V9<.
    0090 - 2e 06 8e ea cb 28 9d f6-c5 9c 5b f4 e0 ee 07 3d   .....(....[....=

    Start Time: 1586516007
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---


```

**Comment by xiongziliang** [comment]
你更新最新代码吧，主要是更新第三方模块ZLToolKit的，测试后请反馈给我，谢谢！

**Comment by bestneymarjr** [comment]
好的，下周一我更新一下，测试后给您结果

**Comment by bestneymarjr** [comment]
证书导入成功,问题已修复，感谢

**Comment by xiongziliang** [comment]
意思是echo show能直接播放ZLMediaKit提供的rtsps了？

**Comment by bestneymarjr** [comment]
是的

**Comment by xiongziliang** [comment]
非常棒！

**Comment by bestneymarjr** [comment]
还有一个问题需要麻烦您，当我配置了*.example.com的证书，当指定servername:name1.example.com来访问时，目前zlmediakit会findCertificate can not find any certificate of host：name1.example.com。当然，我希望的结果是他可以匹配到*.example.com。

**Comment by xiongziliang** [comment]
嗯 这个我在ZLToolKit没做通配符相关的逻辑(主要是通配符的证书都要钱)，你先将就用着吧。
如果方便的话，你可以生成一个通配符的证书给我测试下，这样我方便测试。。。

**Comment by bestneymarjr** [comment]
你只是要证书吗不需要私钥吧

**Comment by bestneymarjr** [comment]
可以使用 Let’s Encrypt免费申请通配符域名证书

**Comment by xia-chu** [comment]
通配符证书已经支持了
