### ISSUE TITLE
服务器出来的流 VLC播放不成功的问题

### ISSUE THREAD

**Issue by zywu31** [xiongziliang/ZLMediaKit#258]
环境介绍
 1.接收机 Tuner转UDP    >>  2.转码器压缩转码(H264 AAC)2M输出 >> 3.ffmpeg UDP接收转RTMP给服务器 >> 4.服务器RTMP/RTSP/HLS/FLV输出  >> 5.VLC播放

ffmpeg命令
 ffmpeg -re -i 'udp://238.1.1.1:1234?localaddr=192.168.10.89&pkt_size=1316&fifo_size=358000&buffer_size=358000&overrun_nonfatal=1&timeout=5000000'    -c copy -bsf:a aac_adtstoasc -f flv rtmp://192.168.1.89:1935/rtmp/live/rtmp001

测试介绍
ZLToolKit&ZLMediaKit
 1.服务器输出的所有协议使用VLC播放刚开始卡顿  过几分钟无法播放

**Comment by zywu31** [comment]
TS和发流工具在百度网盘
链接：https://pan.baidu.com/s/1ZFjv0RVI8jKeiJy2-vxXtA 
提取码：dt2t

**Comment by xiongziliang** [comment]
你可以尝试打开rtmp时间戳覆盖试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zywu31 <notifications@github.com&gt;
发送时间: 2020年4月2日 19:02
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 服务器出来的流 VLC播放不成功的问题 (#258)





 
环境介绍
 1.接收机 Tuner转UDP    &gt;&gt;  2.转码器压缩转码(H264 AAC)2M输出 &gt;&gt; 3.ffmpeg UDP接收转RTMP给服务器 &gt;&gt; 4.服务器RTMP/RTSP/HLS/FLV输出  &gt;&gt; 5.VLC播放
 
ffmpeg命令
 ffmpeg -re -i 'udp://238.1.1.1:1234?localaddr=192.168.10.89&amp;pkt_size=1316&amp;fifo_size=358000&amp;buffer_size=358000&amp;overrun_nonfatal=1&amp;timeout=5000000'    -c copy -bsf:a aac_adtstoasc -f flv rtmp://192.168.1.89:1935/rtmp/live/rtmp001
 
测试介绍
 ZLToolKit&amp;ZLMediaKit
 1.服务器输出的所有协议使用VLC播放刚开始卡顿  过几分钟无法播放

**Comment by zywu31** [comment]
测试结果
1.打开RTMP时间戳覆盖  输出都无法正常播放
2.关闭RTMP时间戳覆盖  RTMP播放还算正常 但是输出的RTSP FLV VLC播放时间长一点就音视频不同步了

**Comment by xiongziliang** [comment]
不同步的话 应该是源就不同步



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zywu31 <notifications@github.com&gt;
发送时间: 2020年4月2日 19:32
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 服务器出来的流 VLC播放不成功的问题 (#258)





 
测试结果
 1.打开RTMP时间戳覆盖  输出都无法正常播放
 2.关闭RTMP时间戳覆盖  RTMP播放还算正常 但是输出的RTSP FLV VLC播放时间长一点就音视频不同步了

**Comment by zywu31** [comment]
源是正常的  推给SRS 使用VLC播放没有问题

**Comment by xiongziliang** [comment]
hls也正常？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zywu31 <notifications@github.com&gt;
发送时间: 2020年4月2日 20:32
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 服务器出来的流 VLC播放不成功的问题 (#258)





 
源是正常的  推给SRS 使用VLC播放没有问题

**Comment by zywu31** [comment]
是的 
给SRS 出来RTMP/HLS/FLV VLC播放都正常

**Comment by xiongziliang** [comment]
理论上讲 rtmp如果一直同步 那么其他协议也能同步 你上传的工具我要下载安装百度网盘客户端才能下载，然后我要找个windows电脑才能测试 好麻烦啊

**Comment by xiongziliang** [comment]
你用rtp推流试试：
ffmpeg -re -i 'udp://238.1.1.1:1234?localaddr=192.168.10.89&pkt_size=1316&fifo_size=358000&buffer_size=358000&overrun_nonfatal=1&timeout=5000000' -c copy -bsf:a aac_adtstoasc -f mpegts rtp://192.168.1.89:10000

zlm也支持rtsp推流：
ffmpeg -re -i 'udp://238.1.1.1:1234?localaddr=192.168.10.89&pkt_size=1316&fifo_size=358000&buffer_size=358000&overrun_nonfatal=1&timeout=5000000' -c copy -bsf:a aac_adtstoasc -f rtsp rtsp://192.168.1.89/live/test

**Comment by xiongziliang** [comment]
不一定非得用rtmp推流的
