### ISSUE TITLE
支持TS OVER RTSP吗

### ISSUE THREAD

**Issue by heyingjie** [xiongziliang/ZLMediaKit#259]
请问是否支持TS OVER RTSP推流到ZLMediaKit进行RTSP分发吗

**Comment by xiongziliang** [comment]
支持



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Seth <notifications@github.com&gt;
发送时间: 2020年4月5日 10:03
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 支持TS OVER RTSP吗 (#259)





 
请问是否支持TS OVER RTSP推流到ZLMediaKit进行RTSP分发吗
