### ISSUE TITLE
GB28181 RTP 能否出一路RTP原始流

### ISSUE THREAD

**Issue by qinqi** [xiongziliang/ZLMediaKit#260]
请问大佬，由于GB28181需要上级级联，而且上级只接受rtp ps 或者 rtp es的原始流数据 ，请问media列表里能否通过不同的ssrc出一路rtp的原始ps 或 es流数据，这样我直接写个udp或者tcp的proxy，直接转发过去，目前我看好像不支持这样的操作，请问后续是否会支持呢？

**Comment by xiongziliang** [comment]
这个要支持很简单的 后面我做下接口
