### ISSUE TITLE
Docker镜像中无ffmpeg

### ISSUE THREAD

**Issue by qylc** [xiongziliang/ZLMediaKit#261]
作者能否制作一个已经安装好ffmpeg的docker镜像，虽然大家都会做，但是希望官方能看下在镜像中安装好ffmpeg

**Comment by xiongziliang** [comment]
这个镜像不是我做的 我让作者加下吧 谢谢您的反馈！

**Comment by xiongziliang** [comment]
你根据最新的readme下载最新的docker镜像吧 已经加入了FFmpeg了

**Comment by qylc** [comment]
感谢作者大大

**Comment by BigPotato1** [comment]
Dock镜像中ffmpeg安装路径是“/usr/local/ffmpeg”，因此跑ZLMediaKit的Docker镜像时应该调用接口“/index/api/setServerConfig”设置一下配置文件中的ffmpeg安装路径，由原来的“/usr/bin/ffmpeg”变为“/usr/local/ffmpeg”路径。
