### ISSUE TITLE
GB28181推流警告: address dismatch

### ISSUE THREAD

**Issue by xiongziliang** [xiongziliang/ZLMediaKit#267]
## 问题如图：
![image](https://user-images.githubusercontent.com/11495632/78849710-d26f5600-7a47-11ea-926f-876abc3060de.png)

## 解答
**表面原因**：错误是由于在短时间让设备用相同的ssrc推流了两次，这个ssrc如果已经被使用，那么就会绑定一个设备的ip和端口。

**深层原因**：如果让这个设备用相同的ssrc推流，那么设备的端口一般会变化，这边ZLMediaKit发现这个ssrc的源地址发送变化了，不知道到底是原设备离线了还是有两个设备在用相同的ssrc同时推流，如果放任两个设备使用相同的ssrc同时推流，那么服务器会解析码流异常，服务器是根据ssrc来区分是否为一路流的。

**解决办法**：
- 1、每次推流都更换ssrc。
- 2、不换ssrc的情况下确保第二次推流在第一次推流停止后的15秒以后(可以通过配置文件设置)。
- 3、[关闭校验rtp源的功能(有风险)](https://github.com/xiongziliang/ZLMediaKit/blob/master/conf/config.ini#L166)

**Comment by LustFairy** [comment]
如何将GB28181   RTP的包转为 rtmp?

**Comment by xiongziliang** [comment]
你推流到ZLMediaKit的10000端口就行了。
剩下的事情请看文档：https://github.com/xiongziliang/ZLMediaKit/wiki/ZLMediaKit%E6%8E%A8%E6%B5%81%E6%B5%8B%E8%AF%95

**Comment by cxssyl** [comment]
> 你推流到ZLMediaKit的10000端口就行了。
> 剩下的事情请看文档：https://github.com/xiongziliang/ZLMediaKit/wiki/ZLMediaKit%E6%8E%A8%E6%B5%81%E6%B5%8B%E8%AF%95

**Comment by cxssyl** [comment]
ZLMediaKit里面的GB28181的是不是直接与摄像机端直接通信啊，刚刚学这个，想改成ZLMediaKit与信令服务器通信，不知道从哪下手

**Comment by xia-chu** [comment]
> ZLMediaKit里面的GB28181的是不是直接与摄像机端直接通信啊，刚刚学这个，想改成ZLMediaKit与信令服务器通信，不知道从哪下手

请把这篇文章看完，文章最后面的两个推荐文章也看完。

**Comment by cxssyl** [comment]
> > ZLMediaKit里面的GB28181的是不是直接与摄像机端直接通信啊，刚刚学这个，想改成ZLMediaKit与信令服务器通信，不知道从哪下手
> 
> 请把这篇[文章](https://github.com/xia-chu/ZLMediaKit/wiki/GB28181%E6%8E%A8%E6%B5%81)看完，文章最后面的两个推荐文章也看完。

好的，谢谢

**Comment by longqi0505** [comment]
你好,能说一下2和3方案改配置文件的哪个参数吗?

**Comment by longqi0505** [comment]
> ## 问题如下：
> ![图片](https://user-images.githubusercontent.com/11495632/78849710-d26f5600-7a47-11ea-926f-876abc3060de.png)
> 
> ## 解答
> **表面原因**：错误是由于在短时间让设备使用相同的ssrc推流了两次，这个ssrc如果已经被使用，那么就会绑定一个设备的ip和端口。
> 
> **深层原因**：如果让这个设备用相同的ssrc重新推流，那么设备的端口一般会变化，这边ZLMediaKit发现这个ssrc的源地址发送变化了，不知道到底是原设备离线了还是有两个设备在用相同的ssrc同时推流，如果放任两个设备使用相同的ssrc同时推流，那么服务器会解析码流异常，服务器是根据ssrc来区分是否为一路流的。
> 
> **解决方法**：
> 
> * 1，每次推流都更换ssrc。
> * 2，不换ssrc的情况下确保第二次推流在第一次推流停止后的15秒以后（[可以通过配置文件设置](https://github.com/xiongziliang/ZLMediaKit/blob/master/conf/config.ini#L185)）。
> * 3，[关闭验证rtp源的功能（有风险）](https://github.com/xiongziliang/ZLMediaKit/blob/master/conf/config.ini#L179)

你好，能说一下2和3方案改配置文件的哪个参数吗？

**Comment by xia-chu** [comment]
https://github.com/xia-chu/ZLMediaKit/blob/master/conf/config.ini#L204
https://github.com/xia-chu/ZLMediaKit/blob/master/conf/config.ini#L198
不推荐方案3，方案3有线程安全的风险，容易崩溃
