### ISSUE TITLE
功能建议：是否提供MP4文件结束时间或者mp4录像时长

### ISSUE THREAD

**Issue by yuyuxp** [xiongziliang/ZLMediaKit#269]
getMp4RecordFile接口只有文件列表，文件名即开始时间，没有结束时间，做集成的时候还是不太方便

**Comment by xiongziliang** [comment]
getMp4RecordFile只是根据文件系统搜索文件用的，里面并没有解复用mp4文件，这个其实是个最简单的接口，无法实现复杂的业务逻辑，我也不推荐用这个接口检索文件，因为这个接口功能太弱了。


我建议是你的业务系统监听mp4录制hook事件，然后存放数据库，后面根据数据库查找文件
