### ISSUE TITLE
如何开启RTSP/RTMP点播

### ISSUE THREAD

**Issue by zhuky888888** [xiongziliang/ZLMediaKit#27]
ZLMediaKit 点播功能在哪里体现，PlayerProxy是否可做到支持本地文件和V4L2，而不是通过推流的方式 @xiongziliang

**Comment by zhuky888888** [comment]
我测试了下，采用拉流方式，我用vlc rtsp播放，一点都不卡。但是采用test_push或test_pushMp4推流，vlc rtsp播放，就存在卡顿和丢帧现象。

**Comment by xiongziliang** [comment]
ZLMedaiKit支持rtsp/rtmp点播(当然也支持http点播)；但是rtsp/rtmp点播只支持264+AAC负载的MP4文件，并且依赖mp4v2库。
所以假如你想开启点播功能，你需要这样做：
1、先安装mp4v2库，并且重新cmake然后编译ZLMediaKit，这样ZLMediaKit就能开启ENABLE_MP4V2宏，点播相关的代码才会编译。
2、把mp4测试文件放置在ZLMediaKit的点播目录下（默认为./httpRoot/__defaultVhost__/record/）。
3、用VLC或ffplay播放：rtsp://127.0.0.1/record/filename.mp4或rtmp://127.0.0.1/record/filename.mp4

**Comment by xiongziliang** [comment]
> 我测试了下，采用拉流方式，我用vlc rtsp播放，一点都不卡。但是采用test_push或test_pushMp4推流，vlc rtsp播放，就存在卡顿和丢帧现象。

这个问题我无法重现，我这里测试一切正常，没有测试条件测试。
你可以换个推流器，比如说EasyDarwin提供的android端rtsp推流器

**Comment by zhuky888888** [comment]
> httpRoot

谢谢，是httpRoot/__defaultVhost__/record 目录，测试可用。。

**Comment by xiongziliang** [comment]
> ZLMediaKit 点播功能在哪里体现，PlayerProxy是否可做到支持本地文件和V4L2，而不是通过推流的方式 @xiongziliang

ZLMediaKit是一个跨平台的流媒体协议库，所以你说的V4L2录制的功能是没有的，这个需要你自己去实现。
假如你基于ZLMediaKit实现了V4L2相关的功能，你也可以贡献出相关代码，这样这个项目才能充实壮大，可惜目前我几乎没收到其他人的代码贡献

**Comment by amhoho** [comment]
> > ZLMediaKit 点播功能在哪里体现，PlayerProxy是否可做到支持本地文件和V4L2，而不是通过推流的方式 @xiongziliang
> 
> ZLMediaKit是一个跨平台的流媒体协议库，所以你说的V4L2录制的功能是没有的，这个需要你自己去实现。
> 假如你基于ZLMediaKit实现了V4L2相关的功能，你也可以贡献出相关代码，这样这个项目才能充实壮大，可惜目前我几乎没收到其他人的代码贡献

最后一句想回一下,我初看这个项目觉得不错,然而问题在于没有任何wiki,这样导致了必须要本地安装后逐步摸索,调试,研究,这样才能像我一样修修改改最后才可能有贡献,建议学习srs那样对项目及配置有个详细说明,以便更多人熟知项,这样各有需求的修修补补中自然有贡献了

**Comment by xiongziliang** [comment]
老兄，这个项目跟srs没法比，人家是团队，我只有我一个人在弄，你看看issue还有其他人答复吗？wiki有其他人写吗？pull request 有其他人合并吗？ 代码基本也是我一个人写的，真的没法比。
而且我既要上班，也要维护这个项目，有时也要接点外包什么的补贴家用，晚上回去还要带孩子，你说我哪有那么多精力来完善项目？

**Comment by xiongziliang** [comment]
作为独立开发者，请体谅下我的难处，这个项目虽然现在有点影响力了，但是并没有给我带来什么经济上的利益，srs的作者是某公司的CTO，人家工作上也不会有太多事情，我是一线码农，事情还是蛮多的

**Comment by xiongziliang** [comment]
当然 ，我还是会继续完善项目的，但是速度会比较慢，而且最后也不太可能达到srs那种完善的水平

**Comment by amhoho** [comment]
作为独立开发者，请体谅下我的难处，这个项目虽然现在有点影响力了，但是并没有给我带来什么经济上的利益，srs的作者是某公司的CTO，人家工作上也不会有太多事情，我是一线码农，事情还是蛮多的

_Originally posted by @xiongziliang in https://github.com/zlmediakit/ZLMediaKit/issues/27#issuecomment-522311864_

我想说 我昨今都在服务器调试这个项目 客户不想用srs 成功上线后 我会捐助的 呵呵 期待完善.

**Comment by xiongziliang** [comment]
你客户为什么不想用srs ?难道是我这个相对srs 有什么优势吗

**Comment by amhoho** [comment]
@xiongziliang 那倒不是 我们原来也是srs的 只是srs现在的3.0稳定版还有一些时间发布.2.0有许多问题.目前需求也比较简单只要求rtmp推流,hls/flv录制和播放,只要均由api控制即可.

**Comment by alongL** [comment]
> 你客户为什么不想用srs ?难道是我这个相对srs 有什么优势吗

我在使用SRS时，出现过在处理推流时，生成的hls流中ts只有30K，播不了的问题。
