### ISSUE TITLE
GB28181 海康IPC推送RTP流时，提示不支持STREAM_AUDIO_G711

### ISSUE THREAD

**Issue by swwheihei** [xiongziliang/ZLMediaKit#271]
大佬，您好：
我在遵照wiki快速开始，成功编译并运行MeidaServer。
但是在使用GB28181向摄像头请求预览视频后，MeidaServer警告不支持STREAM_AUDIO_G711。
警告： `onDecode unsupported codec type:STREAM_AUDIO_G711`

**Comment by xiongziliang** [comment]
是的 现在确实不支持g711呢，现在我正在等一位老兄对g711支持的pr，你等好消息吧

**Comment by swwheihei** [comment]
大佬，有大约的时间点吗？
顺便问一句，你知道怎么让IPC返回H264而不是G711编码视频吗？

**Comment by xiongziliang** [comment]
G711是音频。
ZLMediaKit里面其实有两套代码，一套是ireader/media-server的代码，实现容器解复用和复用。
ZLMediaKit原生代码主要实现了各种网络协议和各种逻辑。

现在ZLMediaKit的rtmp、rtp的编解码都是自己实现的，但是ps/ts/mp4的解复用和复用是ireader/media-server库实现的，ireader/media-server的库对各种格式支持很完善，但是ZLMediaKit只支持265/264/aac.

所以虽然ireader/media-server解析出G711了，但是这个数据没法给ZLMediaKit使用。
