### ISSUE TITLE
http-flv和ws-flv无法播放

### ISSUE THREAD

**Issue by genouswhy** [xiongziliang/ZLMediaKit#272]
你好，我在10.0.10.102上起了服务，然后用ffmpeg推了一个rtmp流
ffmpeg -re -stream_loop -1 -i "1.mp4" -vcodec h264 -acodec aac -f flv rtmp://10.0.10.102/live/test

然后VLC用以下地址播放rtmp是没有问题的
rtmp://10.0.10.102/live/test

但是VLC用以下地址播放http-flv或者ws-flv都不行
http://10.0.10.102/live/test.flv
ws://10.0.10.102/live/test.flv

请问是什么原因呢，是要在config.ini进行什么配置么，多谢了

**Comment by xiongziliang** [comment]
我这里http-flv能播放啊，你是不是端口搞错了？
![image](https://user-images.githubusercontent.com/11495632/79033278-9111ae80-7bdf-11ea-99c5-0a9598ac4cce.png)

vlc不支持ws-flv，ws-flv要用flv.js播放测试

**Comment by genouswhy** [comment]
哈哈 是我没有填端口号 感谢回复 现在可以了

**Comment by xiongziliang** [comment]
> 哈哈 是我没有填端口号 感谢回复 现在可以了
> 另外请问一下 ws的端口是和http一样的么

一样的
