### ISSUE TITLE
请问streamid的生成规则

### ISSUE THREAD

**Issue by swwheihei** [xiongziliang/ZLMediaKit#273]
大佬，您好！
我使用ZLMediaKit作为GB28181的流媒体服务器，现在基本的推流与播放已经验证成功，正在规划方案。现遇到些疑问，烦请大佬帮忙解答下，关于视频流请求流程。
在GB28181中定义，播放器先请求SIP信令服务，SIP信令服务再依次请求流媒体和摄像头，如下图：
![28181流程](https://user-images.githubusercontent.com/28561901/79039336-1d899480-7c13-11ea-9487-573092b873c4.png)
而在wiki中的按需推流流程中，是播放器先请求流媒体。
但是播放器请求流媒体需要先知道url的streamid，我通过翻看其他wiki，并不知道streamid的生成规则是什么，与ssrc是否有关系？
根据翻看wiki与技术验证，streamid是RTP推流给ZLM后，通过hook给业务应用的，业务应用也无法指定streamid。
现在我不理解如何进行集成，大佬能给个示例吗？

**Comment by xiongziliang** [comment]
streamid就是ssrc

**Comment by xiongziliang** [comment]
ssrc打印成16进制就是streamid

**Comment by swwheihei** [comment]
非常感谢！
