### ISSUE TITLE
h265编码的直播流rtsp协议转rtmp问题

### ISSUE THREAD

**Issue by PeterPan020** [xiongziliang/ZLMediaKit#275]
海康摄像机使用h265编码，MediaServer在代理该RTSP流时，生成的RTMP流在VLC上无法播放画面（黑屏有时间戳，有音频流在播放），提示未知编解码器:VLC 无法判别此音频或视频编解码器。

**Comment by xiongziliang** [comment]
ZLMediaKit做了对RTMP-H265的支持，但是这种是国内的玩法，RTMP协议本身不支持265的，所以VLC不能播放265的RTMP很正常，FFmpeg也不支持的。
你要支持的话，要自己做播放器，或者换RTSP/HLS协议。

**Comment by xiongziliang** [comment]
后续ZLMediaKit应该会新增对http-ts直播协议的支持，换http-ts也不错

**Comment by xiongziliang** [comment]
rtmp/flv已经被判死刑了

**Comment by gengbl** [comment]
我看到说明里面有对http-flv和websocket-flv的支持，但是找不到相关的代码说明怎么做， 能简单解说一下吗？
做这个功能时，我启用了三种服务:rtmp, rtsp, http， 使用的地址是：
rtmp://127.0.0.1:1935/live/push
rtsp://127.0.0.1:1554/live/push
ws://127.0.0.1:8080/live/0.flv
在这种情况下无法访问ws地址， 在代码里面也没看到相关的线索。

**Comment by PeterPan020** [comment]
懂了，谢谢

**Comment by xiongziliang** [comment]
http-ts足够简单 不被某个公司主导 支持编码格式非常丰富 可以随意插播 可以和hls共用大部分代码
