### ISSUE TITLE
关于websocket-flv和http-flv的使用

### ISSUE THREAD

**Issue by gengbl** [xiongziliang/ZLMediaKit#276]
你好，我看到说明里面有对http-flv和websocket-flv的支持，但是找不到相关的代码说明怎么做， 能简单解说一下吗？
做这个功能时，我启用了三种服务:rtmp, rtsp, http， 使用的地址是：
rtmp://127.0.0.1:1935/live/push
rtsp://127.0.0.1:1554/live/push
ws://127.0.0.1:8080/live/0.flv
在这种情况下无法访问ws地址， 在代码里面也没看到相关的线索。

**Comment by xiongziliang** [comment]
代码在HttpSession.cpp里面.
这里是在线ws-flv测试：
http://zlmediakit.com:8880/test-flv/test_16.html

**Comment by gengbl** [comment]
> 代码在HttpSession.cpp里面.
> 这里是在线ws-flv测试：
> http://zlmediakit.com:8880/test-flv/test_16.html

谢谢， 已经找到
