### ISSUE TITLE
如何关闭日志

### ISSUE THREAD

**Issue by genouswhy** [xiongziliang/ZLMediaKit#277]
你好，请问如何关闭日志，Log目录下每天的日志有几十G，前端设备撑不住啊

**Comment by xiongziliang** [comment]
怎么会有这么多日志？我线上服务器都没这么多日志啊。。。。

MediaServer进程可以设置日志级别，可以过来一部分日志，也可以设置日志保存天数，
./MediaServer -h获取帮助

**Comment by genouswhy** [comment]
感谢答复 我们这边网络不好 经常会断流重连 日志保存天数可以设成0么

**Comment by xiongziliang** [comment]
不能设置为0 不过你可以修改代码啊
注释掉这句代码即可：
https://github.com/xiongziliang/ZLMediaKit/blob/master/server/main.cpp#L222

**Comment by xiongziliang** [comment]
加个star吧
