### ISSUE TITLE
怎么输入H264和AAC生成rtsp/rtmp直播流？

### ISSUE THREAD

**Issue by zhuky888888** [xiongziliang/ZLMediaKit#28]
对群主的框架理解还不是很深，我这边主要是想实现嵌入式端 流媒体服务的功能，所以不需要推流，直接能从V4L2 和 ALSA 拉流就行。我看是有个DevChannel类，怎么做到把DevChannel 和 ZLMeidaKit的server关联起来呢 @xiongziliang

**Comment by xiongziliang** [comment]
你往DevChannel类中输入264和AAC，那么这个类会生成RtspMediaSource和RtmpMediaSoure类，这两个媒体源类会自动注册在一个全局的map之中，后面的rtsp/rtmp服务器会去查找这个全局map

**Comment by zhuky888888** [comment]
> 你往DevChannel类中输入264和AAC，那么这个类会生成RtspMediaSource和RtmpMediaSoure类，这两个媒体源类会自动注册在一个全局的map之中，后面的rtsp/rtmp服务器会去查找这个全局map

请问群主，假如我已经实现调用了这个DevChannel， vlc播放器端 我该用什么rtsp/rtmp命令。。

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/58064608-68db2480-7bb5-11e9-9635-3a00bb2d1f31.png)
DevChannel类构造函数前3个参数很重要，指定了url访问方式，访问url格式为：
`rtsp://strVhost/strApp/strId`
`rtmp://strVhost/strApp/strId`

假如`strVhost`定为`__defaultVhost__`，`strApp`为`live`,`strId`为`0`；那么访问url就是 :
`rtsp://127.0.0.1/live/0`
`rtmp://127.0.0.1/live/0`

`strVhost`参数是做虚拟主机用的，不同的域名访问同一台服务器，访问的流是不一样的，
假如`strVhost`为`your.host.com`，那么你只能通过以下url访问：
`rtsp://your.host.com/live/0`
`rtmp://your.host.com/live/0`

用ip方式访问都是命中`__defaultVhost__`虚拟主机

**Comment by zhuky888888** [comment]
> 后面的rtsp/rtmp服务器会去查找这个全局map

请问群主，注册到全局map的函数接口是哪个？

**Comment by xiongziliang** [comment]
https://github.com/xiongziliang/ZLMediaKit/wiki/How-to-create-a-live-steam

**Comment by zhanglinyang1128** [comment]
### C API推264裸流

群里很多人问如何用C API推264裸流，这里贴出我验证时的做法。
- 用live555获取到裸流，ffmpeg或者相机厂家的sdk类似，只要能取到裸流即可
- 在收到流的回调中，创建media_source，推裸流进去
- 在media_changed改变事件中，创建pusher，发布流到MediaServer
- 用自己的客户端，从MediaServer拉流

![微信图片_20200528131805](https://user-images.githubusercontent.com/33457203/83102606-73dd6480-a0e7-11ea-93b4-fe5867ece8dd.png)

### 多路推流
- 创建多个media_source，media_changed中，根据注册成功的url，创建每一路的推流器
- vlc拉MediaServer转发的流时，建议改用tcp

![image](https://user-images.githubusercontent.com/33457203/83103155-beabac00-a0e8-11ea-84b7-2bf7b8566108.png)

![image](https://user-images.githubusercontent.com/33457203/83103298-02061a80-a0e9-11ea-92ed-adf76cdeedfd.png)

### 推流时SPS的提示
zlmediakit根据输入的码流，检测sps，生成sdp，所以推进去的流，一定要保证有sps。有些media server（ffserver），码流中不带sps，需要从sdp中解出来，先于码流推进去。live555在Subsession的fmtp_spropparametersets()中，ffmpeg在extra_data中。

good luck!

**Comment by xiongziliang** [comment]
ZLMediaKit的推流接口设计的需要绑定一个MediaSource对很多人 来说不是很友好；
这样做的目的也是为了复用代码，本质上来说ZLMediaKit主要还是个服务器，那么一切还是以服务器为重心。

一个MediaSource可以主动创建，但是更多的时候是在推流时被动创建的。这个MediaSource不仅可以用于被推流到其他服务器，还能作为数据源，被播放。

其实楼上主要的代码是怎么创建一个MediaSource，这个MediaSource其实不仅仅可以被 用于推流，通过创建Rtsp服务器后，也能被播放。

**Comment by xiongziliang** [comment]
另外 ZLMediaKit播放rtsp时，sdp中可以不存在sps pps, ZLMediaKit也会尝试从rtp中获取的。

**Comment by zhanglinyang1128** [comment]
> 其实楼上主要的代码是怎么创建一个MediaSource，这个MediaSource其实不仅仅可以被 用于推流，通过创建Rtsp服务器后，也能被播放。

是的，其实可以把zlmediakit编进自己的程序，启动rtsp服务器，这样取到裸流以后，创建一个media source，就可以用各种协议拉流了，省去了推流的过程。

media source很精髓啊~

**Comment by xiongziliang** [comment]
@zhanglinyang1128 新增mk_media_set_on_regist接口，可以监听mk_media生成的MediaSource对象注册事件

**Comment by xia-chu** [comment]
rtsp播放你是打算用URL鉴权还是rtsp专属鉴权？

**Comment by flowerlove** [comment]
> rtsp播放你是打算用URL鉴权还是rtsp专属鉴权？

rtsp专属鉴权。我设置默认鉴权模式为不鉴权，即error_msg传入NULL或空字符串

**Comment by flowerlove** [comment]
> rtsp播放你是打算用URL鉴权还是rtsp专属鉴权？

目前已经解决了。原因是因为我设置的app为live，但是输入播放地址时没有添加/live/,导致解析报错了。

**Comment by xia-chu** [comment]
rtsp鉴权有两个回调的 你都看看回调函数注释啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: flowerlove <notifications@github.com&gt;
发送时间: 2021年3月10日 16:24
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 怎么输入H264和AAC生成rtsp/rtmp直播流？ (#28)





  
rtsp播放你是打算用URL鉴权还是rtsp专属鉴权？
  
rtsp专属鉴权。我设置默认鉴权模式为不鉴权，即error_msg传入NULL或空字符串
