### ISSUE TITLE
RTP推流

### ISSUE THREAD

**Issue by Danielwuhy** [xiongziliang/ZLMediaKit#281]
大佬，你好，我用本地视频和大华摄像机推RTP流，推送到10000端口，会出现
![image](https://user-images.githubusercontent.com/27725749/80169961-6846db80-8619-11ea-8f86-0cd3acd1c3ef.png)这个情况。但是我用海康摄像机推RTP流，没有出现这种情况。

**Comment by xiongziliang** [comment]
自己编译最新代码就ok了

**Comment by zjxKayle** [comment]
> 自己编译最新代码就ok了
我也遇到了相似的问题，可以发布一个新的exe版本吗？C的编译我们不太会，麻烦了

**Comment by xiongziliang** [comment]
我现在没windows开发环境了 更新操作系统后 我虚拟机就崩溃打不开了
发布一个二进制包 要编译各种版本 太蛋疼了

**Comment by zjxKayle** [comment]
好的。我能请问一下，为什么我拿ZLMedia解海康的国标rtp流能解出来，解大华的国标rtp，会出现上述情况（这种情况好像也是在解流，但是没有在httpRoot文件夹里生成文件呢?海康的就会在httpRoot里生成_defaulthost_文件）？

**Comment by xiongziliang** [comment]
> 好的。我能请问一下，为什么我拿ZLMedia解海康的国标rtp流能解出来，解大华的国标rtp，会出现上述情况（这种情况好像也是在解流，但是没有在httpRoot文件夹里生成文件呢?海康的就会在httpRoot里生成_defaulthost_文件）？

你是说老版本还是新版本代码？

**Comment by zjxKayle** [comment]
我是用的exe的程序直接跑的。r2

**Comment by zjxKayle** [comment]
![image](https://user-images.githubusercontent.com/40660829/80187278-f1720880-8641-11ea-962e-30126ba58b58.png)

**Comment by xiongziliang** [comment]
你要自己编译最新代码，老版本exe由于第三方库的问题 ，又点bug

**Comment by zjxKayle** [comment]
好的，谢谢拉

**Comment by zjxKayle** [comment]
我试试看

**Comment by zjxKayle** [comment]
![f2559f1c63cfc592290107264959a35](https://user-images.githubusercontent.com/40660829/80198277-69e0c580-8652-11ea-853e-07bfd60d524f.png)
好像少这三个文件

**Comment by xiongziliang** [comment]
你编译不看wiki吗？
