### ISSUE TITLE
H265转换成H264

### ISSUE THREAD

**Issue by woshiwoyali** [xiongziliang/ZLMediaKit#283]
是否提供了方法，可以将H265的视频转换成H264

**Comment by xiongziliang** [comment]
ZLMediaKit能提供hook接口通知你的业务服务器，收到了推流。

这个时候，你的业务服务器，可以调用 restful api(addFFmpegSource)从ZLMediaKit拉流，然后再推给ZLMediaKit。你修改配置文件中FFmpeg相关参数，就能转码啊。

**Comment by xiongziliang** [comment]
这个接口控制FFmpeg拉流代理：
https://github.com/xiongziliang/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#14indexapiaddffmpegsource

这个配置文件参数控制FFmpeg拉流转码参数：
https://github.com/xiongziliang/ZLMediaKit/blob/master/conf/config.ini#L12

**Comment by xiongziliang** [comment]
如果源停止推流了，你还要调用delFFmpegSource接口，关掉FFmpeg拉流代理

**Comment by xiongziliang** [comment]
你可以通过on_stream_changed接口监听推流成功事件，在该事件中，你可以调用FFmpeg拉流代理接口。

**Comment by xiongziliang** [comment]
FFmpeg拉流代理可以做很多事，可以转码，转分辨率，加台标什么的。

**Comment by woshiwoyali** [comment]
好的 谢谢您
