### ISSUE TITLE
海康开放平台录像流rtsp总是断流重连，ffplay能正常播放

### ISSUE THREAD

**Issue by BeatTime** [xiongziliang/ZLMediaKit#284]
版本已经拉了最新代码编译，
![image](https://user-images.githubusercontent.com/16471634/80302140-d5ee3580-87da-11ea-8a5d-63fe5fcbd38a.png)

抓包看是海康开放平台554返回RST，大概每次都是过了24s的样子就会断开
![image](https://user-images.githubusercontent.com/16471634/80302128-cc64cd80-87da-11ea-800b-4f2f7f78270c.png)

![image](https://user-images.githubusercontent.com/16471634/80302157-ea323280-87da-11ea-8cec-a5641472e77b.png)

但ffplay可以正常播放，并且没有出现断流
![image](https://user-images.githubusercontent.com/16471634/80302189-15b51d00-87db-11ea-9903-1b2bf9aee9ac.png)

**Comment by BeatTime** [comment]
接下来我应该怎么排查，夏总给个建议？

**Comment by xiongziliang** [comment]
你改成udp拉流试试，
ZLMediaKit的rtsp播放器是会发rtcp保活包的

**Comment by BeatTime** [comment]
> 你改成udp拉流试试，
> ZLMediaKit的rtsp播放器是会发rtcp保活包的
海康这平台有点坑，udp发的包不完整，没法播

**Comment by BeatTime** [comment]
> 你改成udp拉流试试，
> ZLMediaKit的rtsp播放器是会发rtcp保活包的

海康这平台有点坑，udp发的包不完整，没法播

**Comment by xiongziliang** [comment]
哦哦 我懂你意思了 海康rtp包几十KB大小，不过按道理它不会傻到UDP也按这么大打包吧？

**Comment by xiongziliang** [comment]
我现在这里就有个海康的IPC啊 我用ZLMediaKit的test_player播放rtsp，好好的呢

**Comment by xiongziliang** [comment]
不过这个设备我新买的, 分辨率2K

**Comment by BeatTime** [comment]
> 哦哦 我懂你意思了 海康rtp包几十KB大小，不过按道理它不会傻到UDP也按这么大打包吧？

我现在用ffplay播都是特意指定tcp方式拉流的，否则播出来的画面有缺损
![image](https://user-images.githubusercontent.com/16471634/80302588-7e04fe00-87dd-11ea-998d-8585cecf122c.png)

ffplay不加tcp参数
![image](https://user-images.githubusercontent.com/16471634/80302638-c58b8a00-87dd-11ea-856d-4ff1dff22142.png)

**Comment by BeatTime** [comment]
> 我现在这里就有个海康的IPC啊 我用ZLMediaKit的test_player播放rtsp，好好的呢

不是直接对接海康的ipc，而是它的开放平台

**Comment by xiongziliang** [comment]
哦哦 你可能需要提供下他的开发平台播放url给我测试下才行

**Comment by xiongziliang** [comment]
否则我也无能为力

**Comment by BeatTime** [comment]
> 否则我也无能为力

能快速把rtcp的保活机制去了吗，我这边可以测试一下

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/80302699-3763d380-87de-11ea-81c0-08e0043ea607.png)

注释掉这里

**Comment by BeatTime** [comment]
> ![image](https://user-images.githubusercontent.com/11495632/80302699-3763d380-87de-11ea-81c0-08e0043ea607.png)
> 
> 注释掉这里

注释掉后还是一样断开，时间基本保持在22s的样子

**Comment by BeatTime** [comment]
[海康平台172.16.100.102.zip](https://github.com/xiongziliang/ZLMediaKit/files/4534988/172.16.100.102.zip)

这里有个抓包，夏总你看下有没有用吧

**Comment by BeatTime** [comment]
不过连接断开是海康平台主动断开的，这点比较奇怪

**Comment by BeatTime** [comment]
对比了ffplay和zlmediakit的报文，只发现就是play信令的区别。这个有影响吗
![image](https://user-images.githubusercontent.com/16471634/80303434-e30f2280-87e2-11ea-8c20-138f06092276.png)

**Comment by xiongziliang** [comment]
我不认为有什么影响 你可以咨询下海康的客服

**Comment by BeatTime** [comment]
> 我不认为有什么影响 你可以咨询下海康的客服

我还是想尝试一下，哪里可以硬编码这条信令上去？
如果还不行，我到时候联系海康技术问问

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/80303693-4ea5bf80-87e4-11ea-98b6-cea6a14e65cd.png)

**Comment by xiongziliang** [comment]
ZLMediaKit的代码还是很简单的 你可以看看

**Comment by BeatTime** [comment]
> ZLMediaKit的代码还是很简单的 你可以看看

还是会断开，无解。
zlmediakit的代码我也打算看的，只是c++11功力不够

**Comment by xiongziliang** [comment]
问题还没发解决吗

**Comment by BeatTime** [comment]
> 问题还没发解决吗

还没解决。正在想办法把这个平台透到公网来，让你看看它的流。

**Comment by BeatTime** [comment]
夏总，通过mediaserver日志文件看到，海康平台传过来的rtp包并不标准，断流依然存在。另外我这边已经将海康平台的554端口透到公网了，不过那个rtsp地址是可变的，只有5分钟有效期，方便qq上联系为什么会断流吗
[2020-04-30.zip](https://github.com/xiongziliang/ZLMediaKit/files/4556461/2020-04-30.zip)

**Comment by xiongziliang** [comment]
该问题已经修复了
