### ISSUE TITLE
RTMP 转 HLS ， HLS播放问题

### ISSUE THREAD

**Issue by Luosh** [xiongziliang/ZLMediaKit#288]
使用ffmpeg推一个电影文件mkv (h264/aac), 生成的m3u8, 用ffplay播放端播放会出现音视频不同步。 电影开始的龙标镜头很明显的会重复播放了两次。 如果是VLC播放的话， 同样会有镜头重复播放， 一段时间后声音还会消失。 拉流播放rtmp和http-flv都是同步正常的。hls配置的是默认配置。把m3u8保存下来，修改去掉vhost, 直接播放又是正常的。说明保存的数据是正常的？

**Comment by Luosh** [comment]
另外hls生成的ts时间和配置2秒不符合， 有9秒左右

**Comment by xiongziliang** [comment]
> 另外hls生成的ts时间和配置2秒不符合， 有9秒左右

遇到关键帧并且时间超过2秒才会切片。
如果你GOP是9秒，那么切片大小就是9秒

**Comment by Luosh** [comment]
：q

> > 另外hls生成的ts时间和配置2秒不符合， 有9秒左右
> 
> 遇到关键帧并且时间超过2秒才会切片。
> 如果你GOP是9秒，那么切片大小就是9秒

关键帧间隔是 1一个，存在B帧是否有影响判断？

**Comment by xiongziliang** [comment]
> > > 另外hls生成的ts时间和配置2秒不符合， 有9秒左右
> > 
> > 
> > 遇到关键帧并且时间超过2秒才会切片。
> > 如果你GOP是9秒，那么切片大小就是9秒
> 
> 关键帧间隔是 1s 一个，存在B帧是否有影响判断？

不会 只会遇到关键帧才会切片

**Comment by xiongziliang** [comment]
“电影开始的龙标镜头很明显的会重复播放了两次”
这个是由于m3u8里面的文件还没生成完毕的原因导致的，这个确实是个问题，说明你是按需生成hls

**Comment by xiongziliang** [comment]
@Luosh 这个问题修复了
