### ISSUE TITLE
VS2019编译报错

### ISSUE THREAD

**Issue by chensicheng** [xiongziliang/ZLMediaKit#289]
![image](https://user-images.githubusercontent.com/20574853/80579502-b7877480-8a3c-11ea-9469-7fdf16cb14f9.png)

**Comment by chensicheng** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	 无法打开包括文件: “rfc822-datetime.h”: No such file or directory	librtsp	D:\soft\ZLMediaKit\3rdpart\media-server\librtsp\source\server\rtsp-server.c	3	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	 无法打开包括文件: “http-parser.h”: No such file or directory	librtsp	D:\soft\ZLMediaKit\3rdpart\media-server\librtsp\source\server\rtsp-server-internal.h	5

**Comment by chensicheng** [comment]
http-parser.h  头文件缺失
rfc822-datetime.h头文件缺失

**Comment by xiongziliang** [comment]
你编译不看 wiki吗？
