### ISSUE TITLE
mac 下编译会报错, unknown type name 'my_bool'

### ISSUE THREAD

**Issue by KISSMonX** [xiongziliang/ZLMediaKit#29]
![image](https://user-images.githubusercontent.com/2876745/58075770-17de2700-7bdb-11e9-98cf-8b5c356ae0a2.png)

**Comment by KISSMonX** [comment]
使用的是 master 最新代码: 7431a05811cf9748d54eb74f03b751bf968e957a

**Comment by xiongziliang** [comment]
这个就很诡异了  应该是libmysqlclient库版本的问题导致的 ，建议重新安装libmysqlclient库然后再编译ZLMediaKit，如果还是不行，请注释掉这行代码：
![image](https://user-images.githubusercontent.com/11495632/58078140-9a1d1a00-7be0-11e9-94d9-fc11b5ba376b.png)

**Comment by KISSMonX** [comment]
谢谢, MYSQL false 编译通过, 至于为什么会报错, 我探索一下.

**Comment by xiongziliang** [comment]
> 谢谢, MYSQL false 编译通过, 至于为什么会报错, 我探索一下.

这个原因找到了，是由于mysql把my_bool定义删除了，已经修复这个问题了，pull最新代码即可

参考 ： #32
