### ISSUE TITLE
老大你好 我用test_server 测试两款海康ipc，一台正常一台延时越来越大

### ISSUE THREAD

**Issue by chenxianjie** [xiongziliang/ZLMediaKit#290]
我用test_server  拉rtsp流，分别测试了两台海康ipc，型号不一样，然后用web播放器分别播放 hls，flv，发现一台播放比较正常，另一台刚开始出来的视频正常，随着播放时间越长，延时越大，这种现象是不是说是海康ipc发过来的rtp包时间戳不对引起的

**Comment by xiongziliang** [comment]
是的，时间戳不行就会导致这种问题

**Comment by chenxianjie** [comment]
我用抓包工具看，rtp包里面的时间戳增量也是 3600，跟另一个是一样的，不同的是这个有问题的ipc相同时间戳的rtp包数量多一点，请问下跟这个有关系吗

**Comment by xiongziliang** [comment]
你可以用ffplay播放测试，ZLMediaKit拉流代理rtsp是直接模式，也就是不会有任何篡改

**Comment by chenxianjie** [comment]
好的，谢谢
