### ISSUE TITLE
play  audio only rtsp stream with ffplay for a few time,mediaserver rtsp session timeout 

### ISSUE THREAD

**Issue by ziyaofeng** [xiongziliang/ZLMediaKit#292]
### play  audio only rtsp stream with ffplay for a few time,mediaserver rtsp session timeout 
2020-05-09 18:23:07.987 W | mediakit::RtspSession::onError 000001312E947570(10.10.30.159:56980) 播放器(__defaultVhost__/123456audio/123647999)断开:rtp over udp session timeouted.
### It may cause by ffplay has not send feedback rtcp package to mediaserver.But why is rtcp feedback necessary for mediaserver?

**Comment by xiongziliang** [comment]
如果在播放rtsp时，选择的是rtp over udp，那么服务器是无法知道客户端是否存活的，所以需要客户端发送rtcp包保活；但是不知道为什么，vlc有时发有时候不发。

If RTP over UDP is selected when playing RTSP, the server cannot know whether the client is alive, so the client needs to send RTCP packets to keep alive. But I don't know why. Sometimes VLC sends, sometimes it doesn't。

**Comment by ziyaofeng** [comment]
我使用ffplay播放带视频(h264 aac)不会，但是播放只有aac的rtsp就会

I use ffplay to play video (h264 aac) without this problem, but playing the rtsp stream with only aac

**Comment by xiongziliang** [comment]
你可以换ffplay试试，我很早发现这个问题，vlc确实偶尔存在不发送rtcp的情况，你在用ffplay测试下，如果ffplay还存在这个问题，那么可能是ZLMediaKit的bug(之前跟踪貌似是vlc的bug).
你也可以采用rtp over tcp的方式播放，那样不会有这个问题。

**Comment by ziyaofeng** [comment]
我用的一直是ffplay

**Comment by xiongziliang** [comment]
这个是问题应该是ZLMediaKit之前不能确保rtp端口是偶数，rtcp端口是 rtp端口+ 1导致的。
有些播放器会强制这样约定，否则会按照它自己的规则去发送rtcp包

**Comment by xiongziliang** [comment]
这个问题我已经修复了 你也测试下把
