### ISSUE TITLE
用rtmp推流的时候,只显示注册rtmp,并且使用ffpaly播放rtsp和hls 流链接,现实没有数据

### ISSUE THREAD

**Issue by jinghongzhaoying** [xiongziliang/ZLMediaKit#293]
你好,我使用的是通过ffmpeg 推流到ZLMediaKit 上去,再用ffplay播放对应转化好的的rtsp,hls流,但是发现对应的tsp,hls流没有数据 ,查看日志发现只有注册 regist rtmp __defaultVhost,并由播放测试文档中 regist rtsp __defaultVhost 以及 regist hls __defaultVhost,最后会触发无人观看时间而断开拉流

**Comment by xiongziliang** [comment]
是不是配置文件中没有开启转其他协议？
还是你on_publish hook回复中没开转协议？

**Comment by jinghongzhaoying** [comment]
on_publish hook没开,谢谢你的帮助
