### ISSUE TITLE
bug修改

### ISSUE THREAD

**Issue by Yang-rille** [xiongziliang/ZLMediaKit#295]
您好，我很高兴能够使用这么优秀的项目。但是在我使用的过程中发现了一个问题，我已经配置了hook ：enable=1， on_publish=“我自己的一个鉴权地址”，并且鉴权的地址不是127.0.0.1，当我推rtp的流后，发现流推送成功，未触发hook。

**Comment by xiongziliang** [comment]
rtp推流之前不会做鉴权hook，现在会了。
你需要更新最新代码

**Comment by Yang-rille** [comment]
好的，那可能我是拉去的版本问题，非常感谢！
