### ISSUE TITLE
用途

### ISSUE THREAD

**Issue by hrdzkj** [xiongziliang/ZLMediaKit#296]
3个问题：
1.请问这个是做gb28181的上级还是下级？
2.请问支持国标推流转换成rtsp+flv吗？
3.请问使用到的第三方库有什么呢，能否帮列一下呢？谢谢

**Comment by xiongziliang** [comment]
- zlmediakit目前只能接受GB28181的推流，不能推流GB28181到其他服务器。
- 支持转换成其他任何zlmediakit支持的输出协议(rtsp/rtmp/hls/flv/mp4)
- 第三方库包括`zltoolkit(网络库)`、`ireader/media-server(ts/ps/mp4相关)`、`jsoncpp(核心代码不依赖jsoncpp)`
