### ISSUE TITLE
如何使用ffmpeg推流RTMPS？

### ISSUE THREAD

**Issue by czqmike** [xiongziliang/ZLMediaKit#302]
我尝试使用 `ffmpeg -re -i "filepath" -vcodec h264 -acodec aac -f flv rtmps://192.168.216.3/live/test`
来进行RTMPS的推流。
我已经提前生成了证书，但是在 >release/linux/Debug/config.ini中没有发现配置SSL证书的选项。
理所当然地，我得到了
> [tls @ 0x560ad0af9f00] A TLS fatal alert has been received.
> [rtmps @ 0x560ad0af22a0] Cannot open connection tls://192.168.216.3:443
> rtmps://192.168.216.3/live/test: Input/output error

所以该在哪里配置SSL证书以及推流RTMPS呢？

**Comment by xiongziliang** [comment]
./MediaServer -h 获取帮助

**Comment by xiongziliang** [comment]
rtmps端口是19350

**Comment by czqmike** [comment]
> rtmps端口是19350

你好，我在启动选项后加上了`-s path-to-ssl.pem`，启动没有报错，将端口号修改为了19350，执行
`ffmpeg -re -i "filepath" -vcodec h264 -acodec aac -f flv rtmps://192.168.216.3:19350/live/test`
在Server端得到了
>2020-05-14 17:17:43.959 D MediaServer[7860] RtmpSession.cpp:17 RtmpSession | 139770516739488(192.168.216.3:35630) 
2020-05-14 17:17:43.974 D MediaServer[7860] SSLBox.cpp:161 findCertificate | can not find any certificate of host:default host
2020-05-14 17:17:43.976 W MediaServer[7860] RtmpSession.cpp:31 onError | 139770516739488(192.168.216.3:35630) RTMP播放器(//)断开:end of file,耗时(s):0
2020-05-14 17:17:43.976 D MediaServer[7860] RtmpSession.cpp:25 ~RtmpSession | 139770516739488(192.168.216.3:35630) 

在Client端得到了
> [tls @ 0x5639169f3160] A TLS fatal alert has been received.
[rtmps @ 0x5639169ea2a0] Cannot open connection tls://192.168.216.3:19350
rtmps://192.168.216.3:19350/live/test: Input/output error

请问问题出在哪里呢？

**Comment by czqmike** [comment]
> rtmps端口是19350
> 
> 你好，我在启动选项后加上了-s path-to-ssl.pem，启动没有报错，将端口号修改为了19350，执行
> ffmpeg -re -i "filepath" -vcodec h264 -acodec aac -f flv rtmps://192.168.216.3:19350/live/test
> 在Server端得到了
> 
> 2020-05-14 17:17:43.959 D MediaServer[7860] RtmpSession.cpp:17 RtmpSession | 139770516739488(192.168.216.3:35630)
> 2020-05-14 17:17:43.974 D MediaServer[7860] SSLBox.cpp:161 findCertificate | can not find any certificate of host:default host
> 2020-05-14 17:17:43.976 W MediaServer[7860] RtmpSession.cpp:31 onError | 139770516739488(192.168.216.3:35630) RTMP播放器(//)断开:end of file,耗时(s):0
> 2020-05-14 17:17:43.976 D MediaServer[7860] RtmpSession.cpp:25 ~RtmpSession | 139770516739488(192.168.216.3:35630)
> 
> 在Client端得到了
> 
> [tls @ 0x5639169f3160] A TLS fatal alert has been received.
> [rtmps @ 0x5639169ea2a0] Cannot open connection tls://192.168.216.3:19350
> rtmps://192.168.216.3:19350/live/test: Input/output error
> 
> 请问问题出在哪里呢？

nc显示端口是通的
> nc -v 192.168.216.3 19350
Connection to 192.168.216.3 19350 port [tcp/*] succeeded!

**Comment by xiongziliang** [comment]
你要搞个正儿八经的证书 证书里面要有公钥和私钥
