### ISSUE TITLE
api截图接口有bug

### ISSUE THREAD

**Issue by zuohuaijun** [xiongziliang/ZLMediaKit#304]
接口index/api/getSnap，截图有问题，好像是没有完成截图，就把ffmpeg给关了

**Comment by xiongziliang** [comment]
是不是windows系统？windows下有这个bug，这个问题正在修复中

**Comment by EricHsu001** [comment]
2020年5月19日master 分支代码编译： 

测试调用截图接口时返回结果为空


## 服务器配置
$ config.ini   // 配置文件
[ffmpeg]
bin=/usr/bin/ffmpeg

$ which ffmpeg  // 服务器ffmpeg
/usr/bin/ffmpeg

$ ffmpeg -v // ffmpeg版本
ffmpeg version 3.4.6-0ubuntu0.18.04.1

## 服务日志
```  
2020-05-21 12:33:10.187 T MediaServer[6] HttpSession.cpp:30 HttpSession | 140354365374928(172.16.1x.1x:3237)
2020-05-21 12:33:10.203 W MediaServer[6] HttpBody.cpp:78 init | mmap failed:invalid argument
2020-05-21 12:33:10.203 D MediaServer[6] WebApi.cpp:189 operator() |
# request:
GET /index/api/getSnap?url=rtmp://172.16.1x.1x:1935/live/test&timeout_sec=10&expire_sec=30&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
# content:

# args:
expire_sec : 30
secret : 035c73f7-bb6b-4889-a715-d9eb2d1925cc
timeout_sec : 10
url : rtmp://172.16.1x.1x:1935/live/test
# response size:0
```  
## ffmpeg 日志
调用 /getSnap 接口ffmpeg日志:  （生成目录中的文件大小为0）
```
#### pid=3098,cmd=/usr/bin/ffmpeg
 -i rtmp://172.16.1x.1x:1935/live/test -y -f mjpeg -t 0.001 /opt/media/bin/www/snap/8b766acbbb6f4ebf68479941ecd38387/1590066249.jpeg #####

fork process failed, errno=2(No such file or directory)
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
sh: 1: addr2line: not found
sh: 1: addr2line: not found
sh: 1: addr2line: not found ........
```
## 服务器内命令行调用
命令行调用：（截图大小正常）
```
ffmpeg  -i rtmp://172.16.1x.1x:1935/live/test -y -f mjpeg -t 0.001 /opt/media/bin/www/snap/8b766acbbb6f4ebf68479941ecd38387/1590065735.jpeg
```
## 截图结果
```
$ ls -lh
total 136K
-rw-r--r--. 1 root root 133K May 21 13:07 1590065735.jpeg // 命令行调用
-rw-r--r--. 1 root root    0 May 21 13:04 1590066249.jpeg // API调用
```

**Comment by manhere** [comment]
centos7下同样的问题，使用API截图产生0字节文件，手工复制ffmpeg日志对应 cmd 执行可以正常截图。

**Comment by xiongziliang** [comment]
fork进程启动 FFmpeg进程失败了 原因不明啊

**Comment by xiongziliang** [comment]
这里出问题了：
![image](https://user-images.githubusercontent.com/11495632/83617456-ae4d7280-a5bb-11ea-988f-74347c033cf9.png)

原因是你的FFmpeg路径不对

**Comment by lawrencehj** [comment]
windows截图的问题解决了。原因是在Process.cpp里的s_kill函数，调用的时候设定是2秒强制关闭，但函数里检查完线程是否已经关闭后就直接关闭了线程。修改方法如下：
把Process.cpp里173行至176行注释掉即可。

#ifdef _WIN32
    HANDLE hProcess = NULL;
    hProcess = OpenProcess(PROCESS_TERMINATE, FALSE, pid);	//打开目标进程
    if (hProcess == NULL) {
        WarnL << "\nOpen Process Failed: " << GetLastError();
        return;
    }
    //DWORD ret = TerminateProcess(hProcess, 0);	//结束目标进程
    //if (ret == 0) {
    //    WarnL << GetLastError;
    //}
#else

此外，UI调用截图接口时，程序才启动ffmpeg截图，虽说时间很短，但另外的进程已经返回了一个空文件，要等下一次申请才能更新，所以每次更新过程中都有几秒是没有图片显示的。
解决的办法有两个：
1、在webApi.cpp里，生成空文件后，把预先准备的图片复制复制到这个文件，并在File类中增加一个copyFile函数。

        {
            //生成一个空文件，目的是顺便创建文件夹路径，
            //同时防止在FFmpeg生成截图途中不停的尝试调用该api启动FFmpeg生成相同的截图
            //当然，我们可以拷贝一个"正在截图中"的图来替换这个空图，这需要开发者自己实现
            auto file = File::create_file(snap_path.data(), "wb");
            if(file){
                fclose(file);
                std::string snapIcon = snap_root + "/snap.jpeg";
                File::copyFile(snapIcon.c_str(), snap_path.data());
            }
        }

2、修改UI程序里videoList.vue的getSnap函数，接到服务器返回后判断一下response size是否为0，如果不是就直接返回结果，否则再发一次请求，这时ffmpeg应该截图完成了，这样做的好处是缩略图应该一直都是截图，中间不会被等待的图打断。
这个正在实验

**Comment by xiongziliang** [comment]
大佬 你真是天才！你能不能提交个pr？这样项目里面有你的提交记录，项目也好看点😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lawrencehj <notifications@github.com&gt;
发送时间: 2020年6月5日 09:47
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] api截图接口有bug (#304)





 
windows截图的问题解决了。原因是在Process.cpp里的s_kill函数，调用的时候设定是2秒强制关闭，但函数里检查完线程是否已经关闭后就直接关闭了线程。修改方法如下：
 把Process.cpp里173行至176行注释掉即可。
 
#ifdef _WIN32
 HANDLE hProcess = NULL;
 hProcess = OpenProcess(PROCESS_TERMINATE, FALSE, pid);//打开目标进程
 if (hProcess == NULL) {
 WarnL << "\nOpen Process Failed: " << GetLastError();
 return;
 }
 //DWORD ret = TerminateProcess(hProcess, 0);//结束目标进程
 //if (ret == 0) {
 //    WarnL << GetLastError;
 //}
 #else
 
此外，UI调用截图接口时，程序才启动ffmpeg截图，虽说时间很短，但另外的进程已经返回了一个空文件，要等下一次申请才能更新，所以每次更新过程中都有几秒是没有图片显示的。
 解决的办法有两个：
 1、在webApi.cpp里，生成空文件后，把预先准备的图片复制复制到这个文件，并在File类中增加一个copyFile函数。
     {         //生成一个空文件，目的是顺便创建文件夹路径，         //同时防止在FFmpeg生成截图途中不停的尝试调用该api启动FFmpeg生成相同的截图         //当然，我们可以拷贝一个"正在截图中"的图来替换这个空图，这需要开发者自己实现         auto file = File::create_file(snap_path.data(), "wb");         if(file){             fclose(file);             std::string snapIcon = snap_root + "/snap.jpeg";             File::copyFile(snapIcon.c_str(), snap_path.data());         }     }  
2、修改UI程序里videoList.vue的getSnap函数，接到服务器返回后判断一下response size是否为0，如果不是就直接返回结果，否则再发一次请求，这时ffmpeg应该截图完成了，这样做的好处是缩略图应该一直都是截图，中间不会被等待的图打断。
 这个正在实验

**Comment by lawrencehj** [comment]
提交PR搞了半天没搞掂，总说HTTPS授权不行。
把连续截图的代码再改了一次，现在比较完美了。就是启动ffmpeg后，由于是外部程序，无法知道是否已经完成截图，就用了间接的办法，定时检查生成文件的大小，直到两次检查的大小不变（且不为0），则视为截图完成。这时才提交API的响应（当然也设定了最长的等待时限），这样就可以连续获取截图，不需要中间插入等待的图片了。

		FFmpegSnap::makeSnap(allArgs["url"], snap_path, allArgs["timeout_sec"], [invoker, headerIn, snap_path](bool success) {
			if (!success) {
				//生成截图失败，可能残留空文件
				File::delete_file(snap_path.data());
			}
			struct stat buf;
			clock_t delayStart = clock();
			clock_t timeoutStart = clock();
			long snapFileSize = 0;
			while (clock() < timeoutStart + 4 * CLOCKS_PER_SEC) {
				if (clock() < delayStart + 0.5 * CLOCKS_PER_SEC) {
					continue;
				}
				delayStart = clock();
				stat(snap_path.data(), &buf);
				if (buf.st_size >0) {
					if (buf.st_size == snapFileSize) {
						break;
					}
					else {
						snapFileSize = buf.st_size;
					}
				}
			}
			StrCaseMap headerOut;
			headerOut["Content-Type"] = HttpFileManager::getContentType(".jpeg");
			invoker.responseFile(headerIn, headerOut, snap_path);
			});
		});

**Comment by xiongziliang** [comment]
@lawrencehj 这个方法不用sleep等待吗？这样做不是很优雅，而且非windows系统下，也没必要强行这么做。其实这个windows下截图失败的bug是由于没有等待FFmpeg进程退出导致的，windows下有什么api能等待获取某个进程的退出和返回值吗？如果有，那么这个问题就好解决了

**Comment by lawrencehj** [comment]
不能用sleep，用sleep会造成ffmpeg线程锁死，不能关闭也不能再次打开，也就不能继续截图了。windows的API返回的是所启动的进程是否已经执行的信息，不会返回执行的结果。何况这还有写文件的延时之类的。
实际上原来的程序在非windows环境下也是无法连续截图的，新截的图都会出现一次空的图片，这段编码也是考虑到各种系统，特意用了标准c++的函数，没有用到windows的API（比如获取文件大小）。

**Comment by lawrencehj** [comment]
其实这里解决的是两个问题：
1、windows下ffmpeg被过早关闭，造成windows系统下完全不能截图，或者偶然出现一次截图；
2、接到getSnap申请后，如果图已经过时，就会启动ffmpeg截图，但马上返回文件，所以会返回空文件，延时返回的目的是（尽量）确保ffmpeg已经正常生成截图后再返回。
第二个问题不光是windows系统的问题。
至于为什么sleep会造成ffmpeg不再启动还不太清楚，似乎跟延时的长短关系不大，我试过sleep(200)这样短的（只sleep一次）也不定期会出现。@xiongziliang

**Comment by xiongziliang** [comment]
@lawrencehj @zuohuaijun @manhere @EricHsu001 
该问题已修复，请大家下载最新代码体验。
