### ISSUE TITLE
rtsp能转hls么

### ISSUE THREAD

**Issue by Zhuxydspaccn** [xiongziliang/ZLMediaKit#305]
首先感谢作者的代码分享，如此详尽、如此靠谱！
请问如果我想把IPC的数据转成HLS，做直播和回看，应该如何实现。

**Comment by xiongziliang** [comment]
能支持啊 ，但是录制为HLS时只能选择直播或点播，不能同时录制。
建议录制为MP4文件，ZLMediaKit支持MP4录制和转RTSP/RTMP等。

你看下wiki中 restful api篇中的 addStreamProxy接口。
