### ISSUE TITLE
mpeg-pack-header包头格式问题

### ISSUE THREAD

**Issue by SnowfallDan** [xiongziliang/ZLMediaKit#306]
夏总好:

这个问题可能提到iReader那里更合适,但还是想让您先给看看,分析一下.

我在测试流媒体服务器时,收到了大华的h264+aac的rtp流,流的打包格式应该是PS的.但是在解析PS包头的时候,出现了一些问题:

在文件mpeg-pack-header.c文件解析过程中,经常出现assert的现象.具体的位置如下:

27行的assert和34行的assert.34行的频繁出现:assert((0x03 & data[12]) == 0x03);

我肯定视频的时间戳有问题,因为hls播放时,直播的视频时间出现过跳动,向前和向后都出现过1分钟的情况.

请问夏总,能给一个排查的思路吗?

**Comment by xiongziliang** [comment]
#301
