### ISSUE TITLE
RTP proxy 是否支持 ffmpeg推 rtp_mpegts 类型流

### ISSUE THREAD

**Issue by ziyaofeng** [xiongziliang/ZLMediaKit#308]
RTP proxy 是否支持 ffmpeg推 rtp_mpegts 类型流
我使用ffmpeg 推送rtp_mpegts流一直报一个warn
![image](https://user-images.githubusercontent.com/9034778/82523538-1f723c00-9b5f-11ea-9bbe-8e59b333f22a.png)

![image](https://user-images.githubusercontent.com/9034778/82523502-01a4d700-9b5f-11ea-9ef5-5a2d5dda10b7.png)

**Comment by xiongziliang** [comment]
支持的 不过你要自己编译最新代码 ，Release的二进制文件已经很久没更新了
