### ISSUE TITLE
Ubuntu 下编译, 会报 jsoncpp 不支持 long 的错误

### ISSUE THREAD

**Issue by KISSMonX** [xiongziliang/ZLMediaKit#31]
如题, 请问如何解决比较好?
改成 double 和 int?

![image](https://user-images.githubusercontent.com/2876745/58211887-b83d6400-7d1f-11e9-9d8b-59dbe8e45649.png)

**Comment by xiongziliang** [comment]
已经修复该问题，请更新最新代码
