### ISSUE TITLE
Docker容器重启后, 数据丢失

### ISSUE THREAD

**Issue by qylc** [xiongziliang/ZLMediaKit#310]
你好，我通过容器部署之后，通过restfull api  /index/api/addFFmpegSource 添加流之后一切正常。
但当我重启容器后，发现之前的添加的流不见了。需要客户端再次调用 /index/api/addFFmpegSource

**Comment by xiongziliang** [comment]
是的，ZLMediaKit不打算做数据库持久化相关业务逻辑，你可以自行添加数据库相关逻辑，或者添加批量添加视频源的接口。

另外，addFFmpegSource性能会比较差，如果是rtsp/rtmp/hls的流，那么可以尝试使用 addStreamProxy接口替代。

**Comment by Leiyanzangxiangsi** [comment]
那目前数据是缓存在哪里的呢

**Comment by xia-chu** [comment]
> 算做数据库持久化相关业务逻辑，你可以自行添加数据库相关逻辑，或者添加批量添加视频源的接口。
> 
> 另外，addFFmpegSource性能会比较差，如果是rtsp/rtmp/hls的流，那么可以尝试使用 addStreamProxy接口替代。

内存
