### ISSUE TITLE
websocket client 主动关闭

### ISSUE THREAD

**Issue by xiongguangjie** [xiongziliang/ZLMediaKit#311]
commit:4130910
OS:ubuntu 18.04
写了一个websocket 的benchmark，来测试zlmediakit 的ws-flv 的并发，发现websocket client的代码有问题,抓包发现，client主动向server 发送CLOSE，导致websocket 异常关闭，client 只有在收到CLOSE 才会向server 发送CLOSE,但是抓包没有发现，应该是client 解析websocket 错误了，附件为我所抓的包与代码。
[code_cap.zip](https://github.com/xiongziliang/ZLMediaKit/files/4675093/code_cap.zip)

**Comment by xiongziliang** [comment]
之前没做这个考虑的是客户端掐断socket，服务器也能处理断开事件，没必要再发送一次websocket close信令。新代码已经支持销毁时主动发送close信令了

**Comment by xiongguangjie** [comment]
不是发送CLOSE 的问题，是websocket client 接收 MediaServer 的ws-flv 流时，异常断开。报 onErr | websocket server close the connection 的错误

**Comment by xiongguangjie** [comment]
MediaServer 服务器也报 FLV播放器(__defaultVhost__/live/xiong)断开:end of file,耗时(s):0 的错误

**Comment by xiongziliang** [comment]
没关系 这个是正常的  在发送close信令之前掐断tcp连接其实是正常操作，websocket单独再定义个close信令 其实是多余的

**Comment by xiongguangjie** [comment]
关键是websocket client 不能取 MediaServer 的ws-flv 流，一连上，接收几十个字节后，马上断开

**Comment by xiongziliang** [comment]
然后并不是你说的那样，我能用test_wsClient播放ws-flv啊：
![image](https://user-images.githubusercontent.com/11495632/82856695-4951a700-9f41-11ea-8dc5-32de3d9ca368.png)

**Comment by xiongziliang** [comment]
代码改成这样了：
```c++
/*
 * Copyright (c) 2016 The ZLMediaKit project authors. All Rights Reserved.
 *
 * This file is part of ZLMediaKit(https://github.com/xiongziliang/ZLMediaKit).
 *
 * Use of this source code is governed by MIT license that can be found in the
 * LICENSE file in the root of the source tree. All contributing project authors
 * may be found in the AUTHORS file in the root of the source tree.
 */

#include <signal.h>
#include <string>
#include <iostream>
#include "Util/MD5.h"
#include "Util/logger.h"
#include "Http/WebSocketClient.h"
using namespace std;
using namespace toolkit;
using namespace mediakit;

class EchoTcpClient : public TcpClient {
public:
    EchoTcpClient(const EventPoller::Ptr &poller = nullptr){
        InfoL;
    }
    ~EchoTcpClient() override {
        InfoL;
    }
protected:
    void onRecv(const Buffer::Ptr &pBuf) override {
        DebugL << pBuf->size();
    }
    //被动断开连接回调
    void onErr(const SockException &ex) override {
        WarnL << ex.what();
    }
    //tcp连接成功后每2秒触发一次该事件
    void onManager() override {
//        SockSender::send("echo test!");
//        DebugL << "send echo test";
    }
    //连接服务器结果回调
    void onConnect(const SockException &ex) override{
        DebugL << ex.what();
    }

    //数据全部发送完毕后回调
    void onFlush() override{
        DebugL;
    }
};

int main(int argc, char *argv[]) {
    //设置退出信号处理函数
    static semaphore sem;
    signal(SIGINT, [](int) { sem.post(); });// 设置退出信号

    //设置日志
    Logger::Instance().add(std::make_shared<ConsoleChannel>());
    Logger::Instance().setWriter(std::make_shared<AsyncLogWriter>());

    {
        WebSocketClient<EchoTcpClient>::Ptr client = std::make_shared<WebSocketClient<EchoTcpClient> >();
        client->startWebSocket("ws://zlmediakit.com:8880/proxy/0.flv");
        sem.wait();
    }
    return 0;
}


```

**Comment by xiongguangjie** [comment]
我用"ws://zlmediakit.com:8880/proxy/0.flv" 有时候正常，有时候异常.但是我用ws://127.0.0.1/live/xiong.flv 是必现的，你可以多试几次，或者使用127.0.0.1 的地址测试
`2020-05-26 11:15:13.481 I test_ws_benchmark[12968] EventPoller.cpp:449 EventPollerPool | 创建EventPoller个数:1
2020-05-26 11:15:13.481 I test_ws_benchmark[12968] test_ws_benchmark.cpp:130 EchoTcpClient |
2020-05-26 11:15:13.481 D test_ws_benchmark[12968] util.cpp:303 operator() | Stamp thread started!
2020-05-26 11:15:13.496 D test_ws_benchmark[12968] test_ws_benchmark.cpp:150 onConnect |
2020-05-26 11:15:13.497 D test_ws_benchmark[12968] test_ws_benchmark.cpp:137 onRecv | 0
2020-05-26 11:15:13.497 D test_ws_benchmark[12968] test_ws_benchmark.cpp:137 onRecv | 0
2020-05-26 11:15:13.497 D test_ws_benchmark[12968] test_ws_benchmark.cpp:137 onRecv | 97
2020-05-26 11:15:13.501 W test_ws_benchmark[12968] test_ws_benchmark.cpp:141 onErr | websocket server close the connection
2020-05-26 11:15:13.501 D test_ws_benchmark[12968] test_ws_benchmark.cpp:137 onRecv | 45
2020-05-26 11:15:13.501 D test_ws_benchmark[12968] test_ws_benchmark.cpp:137 onRecv | 4
2020-05-26 11:15:13.501 D test_ws_benchmark[12968] test_ws_benchmark.cpp:137 onRecv | 11
`

**Comment by xiongziliang** [comment]
确实遇到了：
![image](https://user-images.githubusercontent.com/11495632/82857181-dd703e00-9f42-11ea-9286-f5d28a778533.png)

**Comment by xiongziliang** [comment]
bug修复了，原因是有部分数据残余在HttpRequestSplitter对象未参与websocket解析。
