### ISSUE TITLE
关于Rtp tcp Server的疑问

### ISSUE THREAD

**Issue by SnowfallDan** [xiongziliang/ZLMediaKit#312]
夏总好:

RTP接海康PS流的时候,我是否可以把一个NVR上的多个IPC同时通过tcp的方式发到同一个端口上.

我看了tcp的server,启动的时候指定是一个rtpsession模板. 一个rtpsession里有一个rtpprocess进行报文的处理.

相同NVR上的不同IPC通过TCP连接上来会生成多个rtpsession的实例,对应多个不同的rtpprcess,进行分别处理对吧?

不会出现tcp端口只能一路ipc接入的情况是吧

**Comment by xiongziliang** [comment]
> 相同NVR上的不同IPC通过TCP连接上来会生成多个rtpsession的实例,对应多个不同的rtpprcess,进行分别处理对吧?

是的

**Comment by SnowfallDan** [comment]
谢谢夏总
