### ISSUE TITLE
你好，我想在安卓上拉取rtmp流，获取关键帧应该怎么做？

### ISSUE THREAD

**Issue by sss8888** [xiongziliang/ZLMediaKit#313]
我打开你的项目里面的安卓的项目，但是报错了
![image](https://user-images.githubusercontent.com/56373935/82973273-900ad400-a009-11ea-8f7c-4f27d23cf5db.png)，就标题的那个我要调用哪个方法？

**Comment by sss8888** [comment]
我是个新手小白，没做过c和c++的项目，希望大佬给讲解下怎么在安卓端使用，怎么从rtmp流中获得关键帧，非常感谢

**Comment by xiongziliang** [comment]
https://github.com/xiongziliang/ZLMediaKit/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B

**Comment by sss8888** [comment]
> https://github.com/xiongziliang/ZLMediaKit/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B

我不太懂你的意思，我用的windows系统的，我本地要需要安装vs和openssl依赖库吗？还是说我只要用Android studio打开安卓项目就可以了？但是打开了就报的上面图片的错误

**Comment by xiongziliang** [comment]
我的意思是你好好看看这段话：
![image](https://user-images.githubusercontent.com/11495632/82986295-2d750080-a028-11ea-9153-a164dee7a821.png)

**Comment by xiongziliang** [comment]
阅读点文档 按照文档操作很难吗？

**Comment by sss8888** [comment]
> 阅读点文档 按照文档操作很难吗？

好吧，我用的svn下载的，我不知道svn下载会漏掉
