### ISSUE TITLE
关于on_stream_changed的触发机制

### ISSUE THREAD

**Issue by swwheihei** [xiongziliang/ZLMediaKit#314]
大佬，我是群里的Devil。有个关于on_stream_changed问题问一下，因别人可能也会遇到，故在issue中提出。
# 1、on_stream_changed的触发流
看wiki中解释“rtsp/rtmp流注册或注销时触发此事件”，那在RTP推流中会触发吗？

# 2、on_stream_changed的触发机制
ZLM在什么情况下会触发on_stream_changed事件？摄像头在向ZLM推视频流，此时网络波动中断几十秒会触发注销事件吗？如果触发了注销事件，但没有超过摄像头推流的流保活时间后网络又畅通了，此时会触发注册事件吗？

**Comment by xiongziliang** [comment]
## 1、on_stream_changed的触发流
目前所有生成流的方式都会触发该事件，包括rtsp/rtmp/rtp推流, rtsp/rtmp/hls拉流代理，以及DevChannel生成的流。

##2、on_stream_changed的触发机制
在MediaSource注册、注销是触发，也就是InfoL类型的日志打印了  `regist` `unregist`时触发。
RTP推流分为UDP/TCP方式，TCP停止推流能立即发现，UDP不行，UDP只能通过超时的方式发现对方不推流了。

如果在超时时间内重新推流，那么ZLMediaKit发现不了任何异常。

如果超时时间后重新推流，那么ZLMediaKit会先触发注销事件，然后触发注册事件。

**Comment by swwheihei** [comment]
学习了，非常感谢
