### ISSUE TITLE
有计划支持jt1078吗

### ISSUE THREAD

**Issue by leegkon** [xiongziliang/ZLMediaKit#316]
有计划支持jt1078吗

**Comment by zhanjx1314** [comment]
😂这种标准都是生意吧

发自我的iPhone

在 2020年5月29日，上午8:07，leegkon <notifications@github.com> 写道：

﻿

有计划支持jt1078吗

**Comment by xiongziliang** [comment]
没有 有很多事情要做 jt1078对我来说不重要
