### ISSUE TITLE
能否支持openssl的静态编码，方便部署

### ISSUE THREAD

**Issue by 648540858** [xiongziliang/ZLMediaKit#318]
现在的openssl是作为动态库加入，本机编译后可以完美运行，但是部署到服务器可能会因为没有按住openssl而显示缺少so文件，是不是可以支持直接讲openssl的代码打入可执行文件，或者随服务一起发布？
期待您的建议

**Comment by xiongziliang** [comment]
静态库一起 拷贝过去 设置下 LD_LIBRARY_PATH环境变量再运行就行了 。

**Comment by xiongziliang** [comment]
大家都是这么玩的 不存在不方便的 说法

**Comment by 648540858** [comment]
谢谢指导，我是新手。学习了。

**Comment by xiongziliang** [comment]
用ldd MediaServer查看依赖的so库

**Comment by 648540858** [comment]
明白，C++开发还在学习中，多谢指导。
