### ISSUE TITLE
拉流能不能加上浮水印

### ISSUE THREAD

**Issue by a8092947** [xiongziliang/ZLMediaKit#319]
您好，我想詢問推流的同時能不能加上浮水印
目前我們在開發一項業務，是透過RESTful api的addStreamProxy拉影像訊號再轉給使用者
可是我們希望推訊號給使用者的同時，能加上個別的浮水印
例如：某訊號是大樓門口的影像，拉流回來後左下角加個提示，告知這是大樓門口的影像才推出去

我翻過issue好像沒有人討論過浮水印
目前的想法是透過ffmpeg拉流加上浮水印才推給ZLMediaKit
可是這樣的做法似乎有點繞路
不曉得有沒有建議的做法？或者有沒有相關api可以使用呢？

**Comment by zhanjx1314** [comment]
应该不行，水印只能先解码解码编码，服务器压力很大。如果摄像头支持的话最好配置在摄像头里面

发自我的iPhone

在 2020年5月30日，下午11:09，a8092947 <notifications@github.com> 写道：

﻿

您好，我想詢問推流的同時能不能加上浮水印
目前我們在開發一項業務，是透過RESTful api的addStreamProxy拉影像訊號再轉給使用者
可是我們希望推訊號給使用者的同時，能加上個別的浮水印
例如：某訊號是大樓門口的影像，拉流回來後左下角加個提示告知這是大樓門口的影像才推出去

我翻過issue好像沒有人討論過浮水印
目前的想法是透過ffmpeg拉流加上浮水印才推給ZLMediaKit
可是這樣的做法似乎有點繞路
不曉得有沒有建議的做法？或者有沒有相關api可以使用呢？

**Comment by xiongziliang** [comment]
ffmpeg拉流方式可以添加水印 你可以修改FFmpeg拉流命令添加滤镜、台标、水印 等信息

**Comment by xiongziliang** [comment]
配置文件ffmpeg.cmd
