### ISSUE TITLE
mac 10.14编译不通过brew install mysql问题

### ISSUE THREAD

**Issue by zhongdechan** [xiongziliang/ZLMediaKit#32]
新版brew install mysql 安装的是mysql 8.0 编译会不成功。
改为安装5.7版本，编译成功

brew uninstall mysql
brew install mysql@5.7
brew link --force mysql@5.7

**Comment by xiongziliang** [comment]
是的 可能新版本mysql连接器api发生变更了 这个问题已经有人反馈过了 #29 
我先排查下 稍后修复之

**Comment by xiongziliang** [comment]
该问题已经修复了，请pull最新代码

**Comment by KISSMonX** [comment]
Nice
