### ISSUE TITLE
怎么做交叉编译？

### ISSUE THREAD

**Issue by bigbao9494** [xiongziliang/ZLMediaKit#326]
ARM-linux 怎么做交叉编译呢？

**Comment by xiongziliang** [comment]
要修改 cmakelist.txt文件，大概这样修改：
```cmake
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)
SET(TOOLCHAIN_DIR "/opt/hisi-linux-nptl/arm-hisiv100-linux")
SET(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_DIR})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/bin/arm-hisiv100-linux-uclibcgnueabi-gcc)
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/bin/arm-hisiv100-linux-uclibcgnueabi-g++)
```

你可以百度关键词`cmake 交叉编译`

**Comment by bigbao9494** [comment]
交叉编译时编译ZLToolKit时出现错误：
/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Buffer.cpp:142:51: error: ‘malloc’ was not declared in this scope
好像是没有找到malloc函数，尝试在Buffer.h中添加头文件#include <stdlib.h>后错误消失
但是又出现错误：
/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.cpp:589:67: error: ‘to_string’ was not declared in this scope
找不到to_string
不知道交叉编译是哪儿设置没有正确呢，下面是我使用的选项：

创建一个CrossCompile.cmake文件，内容如下(执行cmake -DCMAKE_TOOLCHAIN_FILE=./CrossCompile.cmake ..)：
set(CMAKE_SYSTEM_NAME Linux)
set(TOOLCHAIN_DIR "/opt/hisi-linux/x86-arm/arm-hisiv500-linux")
SET(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_DIR})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/bin/arm-hisiv500-linux-uclibcgnueabi-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/bin/arm-hisiv500-linux-uclibcgnueabi-g++)

**Comment by xiongziliang** [comment]
交叉编译由于libc库各不相同，系统头文件也不一致，有可能遇到这种问题，不过一般来说不多。
这样的问题需要你自己一个一个解决，因为每个人的问题都因人而异。

**Comment by bigbao9494** [comment]
编译问题解决了，我用的arm-hisiv500-linux是UCLIBC，看了一个帖子说由于工具链本身没有使用标准的c++11库,导致编译不了，解决办法：Cmakelists.txt 需要加上以下几个选项
    set(CMAKE_CXX_STANDARD 11)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    add_definitions(-D_GLIBCXX_USE_C99=1)
不过运行会coredump

**Comment by xiongziliang** [comment]
coredump 你可以gdb调试看看什么代码触发的

**Comment by bigbao9494** [comment]
因为是UCLIBC所以无法使用backtrace，那部分我屏蔽了编译的。
我试着运行其它测试程序都有一个错误，暂时不清楚原因
terminate called without an active exception
Aborted

**Comment by xiongziliang** [comment]
海思编译器需要指定这些参数：
g++ -mcpu=generic-armv7-a  -mfloat-abi=softfp  -mfpu=neon-vfpv4

你自己调整

**Comment by bigbao9494** [comment]
MediaServer是CORDUMP，
g++ -mcpu=generic-armv7-a -mfloat-abi=softfp -mfpu=neon-vfpv4
这个我去试试看。

**Comment by bigbao9494** [comment]
刚刚试了arm-hisiv500-linux的选项，还是有问题。空了换个平台再试试吧。

**Comment by xiongziliang** [comment]
> g++ -mcpu=generic-armv7-a -mfloat-abi=softfp -mfpu=neon-vfpv4
这个选项要你自己根据cpu类型调整啊，你的开发板总有个Makefile范例吧？

**Comment by bigbao9494** [comment]
是按照我的CPU来调整了的，SDK中有明确指导的。ZLMediaKit有在哪些平台上用过呢？

**Comment by luqinlive** [comment]
cmake -D CMAKE_BUILD_TYPE=RELEASE  \
        -D OPENSSL_ROOT_DIR=../third-party/hi3559a-libopenssl/  \
        -D CMAKE_C_COMPILER=aarch64-himix100-linux-gcc \
        -D CMAKE_CXX_COMPILER=aarch64-himix100-linux-g++ \
    ..
hi3559a下这样编译没问题

**Comment by bigbao9494** [comment]
我试了一个其它平台，使用的是GLIBC，编译过了且能够正常使用。不知道uclibc海思的arm-hisi500-linux哪儿的问题。

**Comment by bigbao9494** [comment]
> cmake -D CMAKE_BUILD_TYPE=RELEASE
> -D OPENSSL_ROOT_DIR=../third-party/hi3559a-libopenssl/
> -D CMAKE_C_COMPILER=aarch64-himix100-linux-gcc
> -D CMAKE_CXX_COMPILER=aarch64-himix100-linux-g++
> ..
> hi3559a下这样编译没问题

@luqinlive aarch64-himix100-linux-gcc 这个SDK是GLIBC还是UCLIBC的呢？

**Comment by 564398053** [comment]
我这边 cmakelist.txt 添加的 arm a83t 成功编译
```shell
# --- build for arm a83t 

SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)
SET(TOOLCHAIN_DIR "/opt/a83t/CQA83TLinux_Qt5.8.0_bv3/buildroot-2017.02.3/output/host/usr")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/bin/arm-buildroot-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/bin/arm-buildroot-linux-gnueabihf-g++)

# --- end build for arm
```

**Comment by houge101** [comment]
终楼上所述
添加几个可能情况：
1：交叉编译可能会添加外部库，外部头文件，如ffmpeg，openssl，则添加如下代码
include_directories(/home/openssl-3.0.0/include)
link_directories(/home/x264/lib /home/ffmpeg-4.4.1/lib /home/openssl-3.0.0/lib)
link_libraries(avcodec avutil swresample swscale ssl crypto)
上面只是示例，如果出现其它外部依赖库，则根据报错（也有可能是warning）添加。比如，我的依赖libz.so.1，那么我的实际代码如下：(添加libz所在路径及库名称）
include_directories(/home/openssl-3.0.0/include)
link_directories(/usr/lib32/ /home/x264/lib /home/ffmpeg-4.4.1/lib /home/openssl-3.0.0/lib)
link_libraries(z avcodec avutil swresample swscale ssl crypto)
2：添加之后执行  cmake  ..   时候，虽然会有报错，编译工具显示也不匹配，但貌似不影响最终编译结果。
![微信截图_20220817144940](https://user-images.githubusercontent.com/3355923/185069170-7e6af2ce-002e-4a63-935f-43a16422b2c9.png)
