### ISSUE TITLE
Webhook on_publish not triggered from localhost

### ISSUE THREAD

**Issue by PaserSRL** [xiongziliang/ZLMediaKit#327]
Hi,
I'm using webhooks and I found that "on_publish" is not triggered if request starts from localhost.
Obviously is automatically authorized but in this way you cannot know when a third party application starts pushing a stream.

Could you please fix it?

**Comment by xiongziliang** [comment]
No, you should pay attention to `on_stream_changed` hook. 
This hook is used to listen for live stream registration and logoff events.

`on_ publish` and `on_ play` events should only be used for authentication

**Comment by xiongziliang** [comment]
Triggered the `on_publish` event does not mean that the stream will always be pushed successfully.

**Comment by xiongziliang** [comment]
And you can also change to the host ip for publish. 
Can't your third-party application get the local host address?

**Comment by PaserSRL** [comment]
Ok, I misunderstood the meaning.
Thanks
