### ISSUE TITLE
HLS Memory Leak in RAM disk

### ISSUE THREAD

**Issue by PaserSRL** [xiongziliang/ZLMediaKit#330]
> [428267.541588] Out of memory: Kill process 761 (MediaServer) score 308 or sacrifice child
> [428267.557103] Killed process 761 (MediaServer) total-vm:2660984kB, anon-rss:971552kB, file-rss:0kB, shmem-rss:0kB
> [428268.642919] oom_reaper: reaped process 761 (MediaServer), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

Unfortunately your solution didn't worked... :(
Issue persists.

> function flushRam() {
>     exec('sync && sudo sh -c "echo 1 > /proc/sys/vm/drop_caches"');
>     exec('sync && sudo sh -c "echo 2 > /proc/sys/vm/drop_caches"');
>     exec('sync && sudo sh -c "echo 3 > /proc/sys/vm/drop_caches"');
> }

executed every 5 minutes

_Originally posted by @PaserSRL in https://github.com/xiongziliang/ZLMediaKit/issues/317#issuecomment-638139881_

**Comment by xiongziliang** [comment]
> exec('sync && sudo sh -c "echo 1 > /proc/sys/vm/drop_caches"');
> exec('sync && sudo sh -c "echo 2 > /proc/sys/vm/drop_caches"');
> exec('sync && sudo sh -c "echo 3 > /proc/sys/vm/drop_caches"');

I suggest you put the HLS slice on disk.
You can test put hls file on ramdisk on x86,  it work on x86  before;

**Comment by xiongziliang** [comment]
#317

**Comment by PaserSRL** [comment]
It doens't work, I tried using path on NVME disk instead of RAM Disk and result is the same.
I will avoid this feature and I will recreate it using ffmpeg.

**Comment by xiongziliang** [comment]
I don't know why I didn't get this feedback before
