### ISSUE TITLE
Suggestion: http.exposedRootPath

### ISSUE THREAD

**Issue by PaserSRL** [xiongziliang/ZLMediaKit#331]
Hi,
I have a suggestion: you can add another parameter exposedRootPath that is the prefix for all HTTP routes.
In this way is possible to change port to HTTP server and put it behind a proxy (like nginx)

for example:
if I set ZLMediaKit HTTP port to 8000, I can set a path in NGINX like "/mediaserver" in order to proxy all http requests.

127.0.0.1/mediaserver -> 127.0.0.1:8000

but in this way application http routes (like "/index/api/getApiList" are not recognized.

If you change setting in order to set a prefix you could do in this way:

**Default**
exposedRootPath = "/"
"127.0.0.1:8000" + exposedRootPath  + "index/api/getApiList"

**Behind Proxy**
exposedRootPath = "/mediaserver/"
"127.0.0.1" + exposedRootPath  + "index/api/getApiList"

I did the same in my NodeJS Express applications ;)

**Comment by xiongziliang** [comment]
You can proxy these http requests:

127.0.0.1/index/api -> 127.0.0.1:8000

**Comment by PaserSRL** [comment]
I know but is the same to set mediaserver http port to 80.
Anyway I found another way:

Nginx proxy setting:

> location /mediaserver
> {
>         # switch off logging
>         access_log /dev/null;
>         rewrite /mediaserver/(.*) /$1  break;
>         proxy_pass http://127.0.0.1:8000;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
> 
>         proxy_set_header Connection 'Upgrade';
>         proxy_set_header Request-By $proxy_add_x_forwarded_for;
>         proxy_set_header X-Forwarded-Proto $scheme;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_connect_timeout 300;
> 
> 
>         proxy_buffering off;
>         proxy_read_timeout 360000;
>         proxy_send_timeout 360000;
> }
