### ISSUE TITLE
按照教程下载不了子模块

### ISSUE THREAD

**Issue by FrancisFYK** [xiongziliang/ZLMediaKit#335]
![image](https://user-images.githubusercontent.com/20334266/83960850-2c619000-a8c0-11ea-8561-b2d5935028ef.png)

**Comment by lawrencehj** [comment]
估计是网络的问题，我早上刚下载过，没问题的。

**Comment by xiongziliang** [comment]
@FrancisFYK 要不你换个电脑checkout试试？
