### ISSUE TITLE
流媒体已经实现转换，但是对应页面播放无法实现，具体如何实现访问？

### ISSUE THREAD

**Issue by F3112104206** [xiongziliang/ZLMediaKit#337]
1：我使用的是GB28181协议，然后实现对应的转换，现在对应转化后的文件已经生成，在点击页面播放按钮后，本地可见转码文件。

2：对于页面中播放无法是播放，具体的如何是播放，地址是啥？

3：对于是否因为我前端无法实现播放所以导致后端报无人观看视频？
- 

- 
![预览图片](https://user-images.githubusercontent.com/48747817/84136541-0a157100-aa7e-11ea-8e00-98cfa83b5532.png)
![转码后文件](https://user-images.githubusercontent.com/48747817/84136556-0eda2500-aa7e-11ea-9b3a-2c68fb100a6c.png)

**Comment by xiongziliang** [comment]
ws-flv播放端口是80，不是10000。
另外，你这个流是H265+G711的，这个js的播放器不支持，必须要H264+AAC编码才行

**Comment by F3112104206** [comment]
嗯嗯，已经播放成功了，谢谢回复。，真的很感谢哈。倒腾了好久，终于有眉目了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"夏楚"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月10日(星期三) 上午9:34
收件人:&nbsp;"xiongziliang/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
抄送:&nbsp;"冯雷"<2549900982@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiongziliang/ZLMediaKit] 流媒体已经实现转换，但是对应页面播放无法实现，具体如何实现访问？ (#337)





 
ws-flv播放端口是80，不是10000。
 另外，你这个流是H265+G711的，这个js的播放器不支持，必须要H264+AAC编码才行
