### ISSUE TITLE
关于接受推流范围端口而非指定端口的建议

### ISSUE THREAD

**Issue by swwheihei** [xiongziliang/ZLMediaKit#338]
在安防监控领域，GB28181规定每个摄像头推流独占1个端口，而不是ZLM现有的统一10000端口的模式。
随着国标要求越来越，明确，部分摄像头厂商已经不按SDP中定义的SSRC要求进行推流。例如大华摄像头不论SDP中定义的SSRC是什么，统一按照0000000000进行推流，这样在就无法区别推流摄像头了。
建议参考SRS的实现方式，可以接受一定区间的自定义端口推流，以端口而非SSRC作为streamId。
非常感谢。

**Comment by xiongziliang** [comment]
好 后面考虑http api动态创建udp监听端口

**Comment by swwheihei** [comment]
能提供大约的里程碑计划吗？
烦请实现之后再次issue中答复一下。
非常感谢！

**Comment by xiongziliang** [comment]
关了干嘛？开着吧，开着能提醒我做这些事

**Comment by zhang2349** [comment]
期待这个功能，最好可以指定流名称

**Comment by SnowfallDan** [comment]
@swwheihei 您好，我咨询一个问题，如果IPC全部的ssrc都是全0，那么该如何在平台上对摄像头做区分呢？如果是按照端口区分的话，是不是还需要添加端口回收的功能，因为linux上指定的端口也就60000+个。如果ZL指定了范围，那可用个数就更少了。

**Comment by swwheihei** [comment]
问：另外您说的越来越明确的国标中，“部分摄像头厂商已经不按SDP中定义的SSRC要求进行推流”能不能帮忙说一下相关的说明出处
答：大华的部分NVR、IPC不按照SDP的SSRC了，具体的型号没有统计。

问：如果IPC全部的ssrc都是全0，那么该如何在平台上对摄像头做区分呢？
答：按照你所描述的端口区分，国标就是这个规定的。

问：是不是还需要添加端口回收的功能
答：是的，ZLM应该在关闭流时，释放该端口，我认为应该由ZLM进行管理

问：如果ZL指定了范围，那可用个数就更少了。
答：端口是够用的，1台服务器有可用端口上万个，实际上释放及时的话根本用不完，因为带宽会先支撑不住。即使是万兆带宽，在预览1080P的视频时，也仅仅能支持1000-2000的并发。

**Comment by SnowfallDan** [comment]
@swwheihei 多谢回复！棒！

**Comment by xiongziliang** [comment]
> 问：另外您说的越来越明确的国标中，“部分摄像头厂商已经不按SDP中定义的SSRC要求进行推流”能不能帮忙说一下相关的说明出处
> 答：大华的部分NVR、IPC不按照SDP的SSRC了，具体的型号没有统计。
> 
> 问：如果IPC全部的ssrc都是全0，那么该如何在平台上对摄像头做区分呢？
> 答：按照你所描述的端口区分，国标就是这个规定的。
> 
> 问：是不是还需要添加端口回收的功能
> 答：是的，ZLM应该在关闭流时，释放该端口，我认为应该由ZLM进行管理
> 
> 问：如果ZL指定了范围，那可用个数就更少了。
> 答：端口是够用的，1台服务器有可用端口上万个，实际上释放及时的话根本用不完，因为带宽会先支撑不住。即使是万兆带宽，在预览1080P的视频时，也仅仅能支持1000-2000的并发。

支持多端口后，能发挥多线程的优势，性能能提升不少。

**Comment by swwheihei** [comment]
期待实现(*￣︶￣)

**Comment by xiongziliang** [comment]
经过简单测试通过了, 我先关闭issue了，有什么问题直接在这里反馈

**Comment by graphnj** [comment]
@xia-chu  您好，在8 Jul的"完善GB28181推流"中看你重新“使用ssrc为流id”
这么一来对于大华等ssrc（y=000000）的情况继续为流id了，从而造成据此识别的地址dismatch
请问这个基于什么考虑，如何解决大华等y=000000的情况，谢谢
