### ISSUE TITLE
defaultVhost(虚拟主机)是做什么用的？

### ISSUE THREAD

**Issue by machh** [xiongziliang/ZLMediaKit#34]
是不是，推一路流给vhost。  然后多个人去vhost拉同一路流？

**Comment by xiongziliang** [comment]
虚拟主机的本意就是同一台服务器实例可以根据域名在逻辑上切割成不同的逻辑主机。

假如说 我搞了个流媒体云服务器集群，我可以给a、b、c公司使用，
他们都可以用这个服务器  他们用的也是同一个物理的服务器实例；
但是他们通过a.com b.com c.com域名访问这同一个服务器 ，
那么他们彼此都是透明不干扰的 就像他们独占服务器一样。

![image](https://user-images.githubusercontent.com/11495632/58064608-68db2480-7bb5-11e9-9635-3a00bb2d1f31.png)
DevChannel类构造函数前3个参数很重要，指定了url访问方式，访问url格式为：
`rtsp://strVhost/strApp/strId`
`rtmp://strVhost/strApp/strId`

假如`strVhost`定为`__defaultVhost__`，`strApp`为`live`,`strId`为`0`；那么访问url就是 :
`rtsp://127.0.0.1/live/0`
`rtmp://127.0.0.1/live/0`

`strVhost`参数是做虚拟主机用的，不同的域名访问同一台服务器，访问的流是不一样的，
假如`strVhost`为`your.host.com`，那么你只能通过以下url访问：
`rtsp://your.host.com/live/0`
`rtmp://your.host.com/live/0`

用ip方式访问都是命中`__defaultVhost__`虚拟主机

#28
