### ISSUE TITLE
test_pusherMP4 推流用vlc观看黑屏

### ISSUE THREAD

**Issue by yongxiangzheng** [xiongziliang/ZLMediaKit#341]
![image](https://user-images.githubusercontent.com/8653159/84222084-535ed280-ab09-11ea-8a51-3be0b3a4049c.png)
程序输出日志，看起来没啥问题，请问会在哪个环节有问题呢
![image](https://user-images.githubusercontent.com/8653159/84222189-8bfeac00-ab09-11ea-8f64-8c1df52f0023.png)

**Comment by xiongziliang** [comment]
你这样音频怪怪的 只能是6声道？你关闭音频试试。
你的mp4文件能上传下吗？

**Comment by yongxiangzheng** [comment]
刚刚试了用ffmpeg直接推流这个MP4文件，vlc观看也是黑屏。应该跟咱们代码没关系。
不过后面在测试test_pusher, 发现卡顿现象。测试步骤如下：
1.采用ffmpeg推流摄像头视频到nginx-rtmp服务，
![image](https://user-images.githubusercontent.com/8653159/84233315-ae51f300-ab24-11ea-96da-309f3f01d33a.png)

2.修改test_pusher拉流地址为ffmpeg推流的地址，推流地址为改为推流到nginx-rtmp
![image](https://user-images.githubusercontent.com/8653159/84233336-bad64b80-ab24-11ea-849e-fbe4fa5d7258.png)
3.测试发现，用vlc拉取rtmp://192.168.0.222/live/rtsp_push流会卡顿（时间停止，然后跳跃几秒）

![image](https://user-images.githubusercontent.com/8653159/84233258-91b5bb00-ab24-11ea-8c9d-b3effe5c0604.png)

**Comment by xiongziliang** [comment]
卡顿现象跟时间戳有关系，你拉rtmp然后推rtmp，不应该卡顿的，因为都是 原模原样推出的。
你可以换ffplay播放试试。

**Comment by xiongziliang** [comment]
也有可能是相对时间戳的问题，你可以推流给ZLMediaKit试试

**Comment by yongxiangzheng** [comment]
嗯嗯，这两天测试，就没出现过，ffplay也试过，都没问题，我怀疑可能那天我电脑开的东西太多，播放卡顿吧

**Comment by yongxiangzheng** [comment]
现在我想实现采集本地摄像头视频和音频，然后调用ZLMediaKit进行编码推流，请问有没有合适例子可以借鉴的？

**Comment by xiongziliang** [comment]
你可以看看Device.h这个代码，里面可以输入yuv和pcm, 需要依赖第三方库libx264和libfaac。
这些第三方库默认未打开，你可以修改CMakeLists.txt文件打开依赖。

**Comment by yongxiangzheng** [comment]
![image](https://user-images.githubusercontent.com/8653159/85358968-9aa48480-b547-11ea-8da2-2f93568e9b19.png)
你好，目前调用c api 进行推流，提示流已经释放，请问调用步骤不对吗,下图是输出日志
![image](https://user-images.githubusercontent.com/8653159/85359067-dfc8b680-b547-11ea-9903-0f78f7ff4416.png)

**Comment by xiongziliang** [comment]
创建一个mk_media对象后并不会立即注册，这个时候你创建mk_pusher对象绑定它，还找不到它。
你应该在mk_media注册后再创建mk_pusher对象

**Comment by yongxiangzheng** [comment]
在mk_media.h里面没有提供注册成功回调的接口，是要如何判断是否注册成功呢

**Comment by yongxiangzheng** [comment]
你好，后面看了api，对代码逻辑进行调整，将mk_media进行注册，但是注册事件没有返回（没进入OnMediaChange），下图是调整后的代码和日志输出
![image](https://user-images.githubusercontent.com/8653159/85377810-321bce80-b56c-11ea-846f-ddceb21f87a0.png)

![image](https://user-images.githubusercontent.com/8653159/85377687-0862a780-b56c-11ea-929a-179b7e5db8e4.png)
