### ISSUE TITLE
在播放时录像（未播放时正常），结束录像后，录像文件（文件名还有.）还被程序占用

### ISSUE THREAD

**Issue by xiongguangjie** [xiongziliang/ZLMediaKit#342]
os:ubuntu 18.04
coomit:9c646d13168170eda85557ec549ec1c94f0449d1
CPU核：1（是虚拟机）

在播放时录像（未播放时正常），结束录像后，录像文件（文件名还有.）还被程序占用

**Comment by xiongziliang** [comment]
可能文件比较大吧？关闭mp4录像是在后台线程操作的，这个线程可能正在干其他阻塞操作。你看看是不是一直无法释放。

**Comment by xiongguangjie** [comment]
> 可能文件比较大吧？关闭mp4录像是在后台线程操作的，这个线程可能正在干其他阻塞操作。你看看是不是一直无法释放。

好像是重命名失败了，我是虚拟机挂载的windows 文件夹(打开的文件被关闭，好像要蛮久的,HLS 保存文件很耗资源-hls 保存应该配置到内存文件系统里面，要平凡读写，应该是负载太大了，磁盘响应慢，)，我放到虚拟机的磁盘上就没有这个问题了
