### ISSUE TITLE
zltoolkit底层库中的threadpool作用?

### ISSUE THREAD

**Issue by xuhe018** [xiongziliang/ZLMediaKit#343]
夏工好, 拜读了源码,不太理解threadpool.h  和 TaskQueue.h这部分代码的作用,将这部分注释掉后,也不影响test_server中功能.(测试采用test_pushMP4 推流, test_server转发).
1 从服务server端角度 ,   WorkThreadPool 线程池的可以获取到EventPoller ,而threadpool线程池主要作用时什么呢 ?

**Comment by xiongziliang** [comment]
其实没用到了，WorkThreadPool替代了threadpool线程。
之前是有用到threadpool的，后来被我干掉了，因为基于事件循环的线程更好，更灵活。

**Comment by xiongziliang** [comment]
为了保证其他项目的兼容性，保留了threadpool的相关代码

**Comment by xuhe018** [comment]
> 其实没用到了，WorkThreadPool替代了threadpool线程。
> 之前是有用到threadpool的，后来被我干掉了，因为基于事件循环的线程更好，更灵活。

感谢夏工的回复,再请教下,通常情况夏WorkThreadPool创建的线程数量时cpu核心个数,比如我的电脑时8核的,创建8个线程.而每个线程又分别调用了EventPoller ,这样子实际上就运行了 8个Eventpoller, 每个Eventpoller 内部采用epoll 或者select 进行(接入,分发,处理,销毁) 这么理解可以么.

**Comment by xiongziliang** [comment]
程序启动时会默认创建cpu核心数(或线程数)的两种类型的EventPoller。
一种在EventPollerPool里面，线程优先级设置为最高，这个是最重要的线程，用于处理各种网络事件。
另外一种在WorkThreadPool里面，线程优先级设置最低，用于处理文件IO和DNS解析、FFmpeg进程等待等阻塞任务。

**Comment by xuhe018** [comment]
> DNS解析

十分感谢~
