### ISSUE TITLE
HTTP API 接口 startRecord 在没有人拉流的情况下能否也开启录制

### ISSUE THREAD

**Issue by noolder** [xiongziliang/ZLMediaKit#345]
如果没有人拉流，调用startRecord 接口无法开启录制，如果无人观看视频的时候，录制也会停止，能否修改一下，在没人拉流的情况下调用startRecord 也开始录制，无人观看的时候，只要不调用stopRecord接口就一直录制。

**Comment by xiongziliang** [comment]
那你应该应该关闭无人观看断流的功能啊。
你是不是想开启录制了就不断流? 关闭录制且无人观看才断流？

**Comment by noolder** [comment]
我是想实现开启录制了就不断流，关闭录制且无人观看才断流，我们的使用场景是大多数时候是录制，偶尔才会有人观看一下视频。

**Comment by xiongziliang** [comment]
你要自己改代码才能实现

**Comment by noolder** [comment]
好的，我改改试试，谢谢
