### ISSUE TITLE
GB28181对接

### ISSUE THREAD

**Issue by hrdzkj** [xiongziliang/ZLMediaKit#346]
请问使用Docker 镜像，具体如何操作才能与国标对接，能否完善一下wiki的步骤。
谢谢。

**Comment by xiongziliang** [comment]
sip相关你要用第三方库，zlm readme主页有介绍。
zlm只负责接收GB28181的rtp推流，端口的是10000.
你可以看这篇wiki:https://github.com/xiongziliang/ZLMediaKit/wiki/ZLMediaKit%E6%8E%A8%E6%B5%81%E6%B5%8B%E8%AF%95
