### ISSUE TITLE
如何优雅的关闭ZLMediaKit服务

### ISSUE THREAD

**Issue by spiderspiderspider** [xiongziliang/ZLMediaKit#347]
您好，每次关闭服务都需要kill -9杀进程，在文档中看到有api可以重启服务，但是没有找到关闭服务的api，可以指点一下吗

**Comment by xiongziliang** [comment]
killall -2 MediaServer
或
kill -2 pid(父进程id)

**Comment by spiderspiderspider** [comment]
emmm，好吧，多谢啦
