### ISSUE TITLE
ZLMediaKit有推荐的rtmp推流库？

### ISSUE THREAD

**Issue by bigbao9494** [xiongziliang/ZLMediaKit#348]
或者ZLMediaKit中有rtmp推流库？

**Comment by xiongziliang** [comment]
zlm有rtsp/rtmp推流客户端，你可以查看 c api的mk_pusher.h

**Comment by bigbao9494** [comment]
刚刚看了一下mk_pusher.h，似乎需要依赖好多文件，几乎整个ZLMediaKit核心都需要，无法单独出来给推流器使用。

**Comment by xiongziliang** [comment]
> 刚刚看了一下mk_pusher.h，似乎需要依赖好多文件，几乎整个ZLMediaKit核心都需要，无法单独出来给推流器使用。

没关系啊 也就多占用点so库加载内存而已

**Comment by xiongziliang** [comment]
推荐直接使用c sdk的动态库，这样编译简单点，无需裁剪。
多出的一点内存占用忽略不计了。
