### ISSUE TITLE
浏览器无法播放 但是VLC可以正常播放

### ISSUE THREAD

**Issue by Mr-ZhangJie** [xiongziliang/ZLMediaKit#349]
![image](https://user-images.githubusercontent.com/42841916/84843371-4ea29d00-b07a-11ea-8704-964b47ae3565.png)
如图,服务器没有任何日志 
前端使用的 liveplayer 作为播放器的

192.168.1.175 是ZLMediaKit 所在
![](https://user-images.githubusercontent.com/42841916/84843964-e1900700-b07b-11ea-95c9-0e42ef77603b.png)
浏览器抓包

![image](https://user-images.githubusercontent.com/42841916/84843605-ee602b00-b07a-11ea-8c43-320c192c8f72.png)
VLC可以正常播放

![image](https://user-images.githubusercontent.com/42841916/84844116-53685080-b07c-11ea-946c-79216c3010b4.png)
VLC 抓包

**Comment by Mr-ZhangJie** [comment]
服务器没有任何日志,抓包 发现ZLMediaKit 回复503

**Comment by Mr-ZhangJie** [comment]
192.168.1.175 是ZLMediaKit 所在
![image](https://user-images.githubusercontent.com/42841916/84843964-e1900700-b07b-11ea-95c9-0e42ef77603b.png)

**Comment by Mr-ZhangJie** [comment]
页面显示跨域,请问一下 这个问题怎么解啊

**Comment by xiongziliang** [comment]
> ![image](https://user-images.githubusercontent.com/42841916/84843371-4ea29d00-b07a-11ea-8704-964b47ae3565.png)
> 如图,服务器没有任何日志
> 前端使用的 liveplayer 作为播放器的
> 
> 192.168.1.175 是ZLMediaKit 所在
> ![](https://user-images.githubusercontent.com/42841916/84843964-e1900700-b07b-11ea-95c9-0e42ef77603b.png)
> 浏览器抓包
> 
> ![image](https://user-images.githubusercontent.com/42841916/84843605-ee602b00-b07a-11ea-8c43-320c192c8f72.png)
> VLC可以正常播放
> 
> ![image](https://user-images.githubusercontent.com/42841916/84844116-53685080-b07c-11ea-946c-79216c3010b4.png)
> VLC 抓包

你访问的不是ZLMediaKit的http服务器。

**Comment by Mr-ZhangJie** [comment]
我部署的是docker 主机模式 默认 80 端口是给了ZLMediaKit 的 不应该访问的不是ZLMediaKit的http服务器吧

**Comment by xiongziliang** [comment]
Zlmediakit 不会返回这个



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZhangJie <notifications@github.com&gt;
发送时间: 2020年6月17日 09:21
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 浏览器无法播放 但是VLC可以正常播放 (#349)





 
192.168.1.175 是ZLMediaKit 所在

**Comment by Mr-ZhangJie** [comment]
好的  上次也是出现这个问题  但是浏览器与VLC 都不能播放,但是这次不一样  这次是浏览器不能播放VLC 可以播放
上次这个问题是端口呗占用了  所以Zlmediakit  没有骑起来 也没有报错,但是这次 Zlmediakit  是启动了的

**Comment by xiongziliang** [comment]
你估计端口号错了 zlm不会返回那种回复

**Comment by Mr-ZhangJie** [comment]
好的  我使用另外一个镜像  播放成功,估计是端口号占用了 导致 zlm 没有启动成功.
一个建议,如果端口号占用了 给个提示在日志比较友好

**Comment by xiongziliang** [comment]
本来就有日志，你不看日志吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZhangJie <notifications@github.com&gt;
发送时间: 2020年6月17日 11:28
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 浏览器无法播放 但是VLC可以正常播放 (#349)





 
好的  我使用另外一个镜像  播放成功,估计是端口号占用了 导致 zlm 没有启动成功.
 一个建议,如果端口号占用了 给个提示在日志比较友好
