### ISSUE TITLE
在installWebApi增加http api函数，出现session timeouted问题

### ISSUE THREAD

**Issue by athnkk** [xiongziliang/ZLMediaKit#351]
在installWebApi函数增加http api接口，出现session timeouted问题后再调用会出现崩溃问题，麻烦请问下如何解决？

**Comment by xiongziliang** [comment]
有api_regist1注册同步接口，也有api_regist2注册异步接口。
你应该是api_regist2注册异步接口了，所以会session timeouted。
同时你异步执行invoker时，这个对象已经销毁了，所以会崩溃。

你最好把你新增代码粘贴出来。

**Comment by xiongziliang** [comment]
你搞的啥啊？这样就关闭了？

**Comment by athnkk** [comment]
抱歉，是自己代码问题，新增代码处理数据库出现问题。
