### ISSUE TITLE
Build test_player project fail

### ISSUE THREAD

**Issue by lenhatvu** [xiongziliang/ZLMediaKit#354]
Hi,

I want to build test_player project on window but when using CMAKE, i have some errors as bellow:

1. not found SDL2 and AVCODEC
![image](https://user-images.githubusercontent.com/59004953/85096466-93ffcf80-b21e-11ea-8e95-0ed790bdbef2.png)
2. after download SDL2 (https://www.libsdl.org/download-2.0.php) and ffmpeg (https://ffmpeg.zeranoe.com/builds/) 32 bit and specify include folder and lib
![image](https://user-images.githubusercontent.com/59004953/85096620-112b4480-b21f-11ea-82ab-67f25138361d.png)
![image](https://user-images.githubusercontent.com/59004953/85096655-2acc8c00-b21f-11ea-9c5d-9500ca73a51c.png)
test_player project was created but complie error: 
![image](https://user-images.githubusercontent.com/59004953/85097217-08d40900-b221-11ea-8c44-08063298ff32.png)
how to avoid this ?

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/85120225-887bcb00-b255-11ea-86be-56e40653c454.png)
please change to `#include <time.h>`

**Comment by lenhatvu** [comment]
Hi,

I am replace #include <ctime> by #include <time.h> at 2 file: util.h and MP4Recorder.cpp but still has 40 errors:
![image](https://user-images.githubusercontent.com/59004953/85130735-ac440e80-b25f-11ea-996c-075d6d42665a.png)

**Comment by xiongziliang** [comment]
You can add `#include <time.h>` in this file which build failed.
Sorry to replay so late.

**Comment by lenhatvu** [comment]
Sorry for basic question but after add #include <time.h> errors still esxist:
![image](https://user-images.githubusercontent.com/59004953/85367221-0cce9680-b553-11ea-84d9-6499fdc8d1cd.png)
![image](https://user-images.githubusercontent.com/59004953/85367241-1526d180-b553-11ea-9f35-4ab60c8754f5.png)
![image](https://user-images.githubusercontent.com/59004953/85367248-1c4ddf80-b553-11ea-846d-de7f0ce21fae.png)

**Comment by xiongziliang** [comment]
Please change std::strftime to strftime.

**Comment by xiongziliang** [comment]
I'll close the issue first. If you have any questions, you can directly report it here
