### ISSUE TITLE
rtpproxy接收udp丢包处理逻辑咨询

### ISSUE THREAD

**Issue by SnowfallDan** [xiongziliang/ZLMediaKit#358]
夏总好：

咨询一个问题，我将公司的nvr配置国标将流拉到ZL中，但是只能支持udp方式推流。
当udp丢包时，rtpprocess就收不到frame，导致超时。
在之前的commit中，我看到了一个issue是修复udp丢包导致无法解析的提交。但是更新后，问题依然存在。
我看日志丢包的数量不是很多，但是相对比较集中。我自己尝试跟了一下，当数据包进入media-server里rtp-ps-unpack.c里的rtp_decode_ps后，后续就跟丢了。因为服务部署环境没有可调试方法，添加日志的话日志实在海量。
夏总能否给个进一步排查的思路，或者可能出现问题的地方，我可以尝试修复，提交PR。

多谢

**Comment by xiongziliang** [comment]
media-server在解析异常时可能会触发断言，你可以编译Release版本或者注释掉断言相关代码。
如果不是断言导致的，你可以把服务器日志贴在issue

**Comment by SnowfallDan** [comment]
好的，我整理一下。稍后贴出

**Comment by SnowfallDan** [comment]
@xiongziliang 夏总，等我把日志弄好，再把issue打开。我的测试环境现在有点问题，短时间没办法接入设备

**Comment by xiongziliang** [comment]
好的
