### ISSUE TITLE
是否可以支持 hls 推到 rtmp/rtsp

### ISSUE THREAD

**Issue by chenxiaolei** [xiongziliang/ZLMediaKit#36]
某些源只提供了hls方式, 想通过这个推流并录制, 不知道有没有办法

**Comment by xiongziliang** [comment]
目前是不支持的，后续我加个调用FFmpeg拉流的功能 就支持了

**Comment by xiongziliang** [comment]
> 目前是不支持的，后续我加个调用FFmpeg拉流的功能 就支持了

不过这样的话就可能存在转码

**Comment by zhanjx1314** [comment]
这种需求还是用外部的程序做比较好把，万一要转码，还是得分开。

**Comment by chenxiaolei** [comment]
> 这种需求还是用外部的程序做比较好把，万一要转码，还是得分开。

嗯,目前就是通过外部程序做的, 只是想着如果能直接支持就再好不过了

**Comment by xiongziliang** [comment]
> > 这种需求还是用外部的程序做比较好把，万一要转码，还是得分开。
> 
> 嗯,目前就是通过外部程序做的, 只是想着如果能直接支持就再好不过了

直接支持不太好做 ，hls可以直接转换成rtsp，但是转换成rtmp就比较麻烦了，不一定都是264和aac编码

**Comment by xiongziliang** [comment]
目前已经实现使用FFmpeg方式拉hls流转rtsp/rtmp了
