### ISSUE TITLE
Error in last commit on webhook on_play

### ISSUE THREAD

**Issue by PaserSRL** [xiongziliang/ZLMediaKit#362]
Hello,
I'm using webhook in order to check login to stream and in last commit there is an issue.

in fact if I try to open:
rtmp://192.168.0.110/live/camera1?token=cbdebc995d586ec77c9de9b479d670ac4fc1b44d

You can see from log:
2020-06-23 12:32:08.685 W MediaServer[16442] WebHook.cpp:149 operator() | hook http://127.0.0.1/backend/mediaserver/on_play 28ms,failed[parse json failed]:AMF not a number:{
   "app" : "live",
   "id" : "547206185952",
   "ip" : "192.168.1.91",
   "params" : "token=cbdebc995d586ec77c9de9b479d670ac4fc1b44d",
   "port" : 1165,
   "schema" : "rtmp",
   "stream" : "camera1",
   "vhost" : "__defaultVhost__"
}

My webserver (in nodejs) returns:

> output = {
>                     "code": 0,
>                     "msg": "success"
>                 };

> app.post(global.config.webserver_root_path+'/mediaserver/on_play', async function (req, res) {
>         res.setHeader('Content-Type', 'application/json');
>
>         let output = {
>             "code": 401,
>             "msg": "Unauthorized"
>         };
> 
>         switch(req.body.schema) {
>             case 'hls':
>             case 'flv':
>             case 'rtmp':
>                 let request = querystring.parse(req.body.params);
>                 if("token" in request) {
>                     let check = await OdsUser.checkLoginToken(request.token);
> 
>                     if(check)
>                     {
>                         output = {
>                             "code": 0,
>                             "msg": "success"
>                         };
>                     }
>                 }
> 
>             break;
> 
>             case 'rtsp':
>                 output = {
>                     "code": 0,
>                     "msg": "success"
>                 };
>             break;
>         }
> 
>         if(output.code == 0)
>         {
>             logger.info("["+req.body.schema.toUpperCase()+"] Access to stream '"+ req.body.stream +"' - IP: "+ req.body.ip);
>         }
>         else
>         {
>             logger.warn("["+req.body.schema.toUpperCase()+"] Access denied to stream '"+ req.body.stream +"' - IP: "+ req.body.ip);
>         }
> 
>         res.send(JSON.stringify(output));
>         res.end();
>     });

As you can see my reply is correct but media-server return: 
> failed[parse json failed]:AMF not a number:

**Comment by xiongziliang** [comment]
This is a bug, please update the newest code.

**Comment by PaserSRL** [comment]
Solved.
