### ISSUE TITLE
关于支持配置参数关闭浏览目录的建议

### ISSUE THREAD

**Issue by swwheihei** [xiongziliang/ZLMediaKit#367]
老大，我们现在用录像功能，但是在访问ZLM的80端口时，会打开录像存放目录。
这样会把所有的录像列表都公开出去，这个可以关闭吗？

**Comment by xiongziliang** [comment]
可以，这个好做。关闭目录列表时，应该返回错误代码多少？ 403还是404？

**Comment by xiongziliang** [comment]
已实现
