### ISSUE TITLE
RTMP输出音视频严重不同步

### ISSUE THREAD

**Issue by lawrencehj** [xiongziliang/ZLMediaKit#369]
应该是时间戳计算有误，致使输出的流视频严重滞后于音频，而且会越来越严重。

经比较，发现将ZLMediaKit\src\Common\Stamp.cpp这个文件的第178行：
```
                _dts_pts_offset = (pts - _last_max_pts);
```
改为：
```
                _dts_pts_offset = (pts - _last_max_pts) / 2;
```
即恢复正常。

**Comment by xiongziliang** [comment]
你输入的是rtsp吗？输出是rtmp?

**Comment by lawrencehj** [comment]
输入RTSP，输出RTMP

**Comment by xiongziliang** [comment]
rtsp协议 音视频时间戳基准是不一样的，也就是对应的时间戳起点不一样 ，所以可能会不同步

**Comment by lawrencehj** [comment]
我用vlc player看rtsp推出的流，同步是没有问题的。
转出的rtmp流就会出现不同步，而且差距会越来越大，改了上述语句后，连续播放了1:40:00以上，一直精准同步

**Comment by xiongziliang** [comment]
> 我用vlc player看rtsp推出的流，同步是没有问题的。
> 转出的rtmp流就会出现不同步，而且差距会越来越大，改了上述语句后，连续播放了1:40:00以上，一直精准同步

你改的哪句代码其实不会导致同步或不同步。那个代码是根据pts生成dts用的。pts排序后就是dst，但是排序需要缓存列队，这就存在排序缓存时间差，这个值就是_dts_pts_offset。这个值只会改变dts与pts的差值，这个差值并不会扩大。

之前确实是` _dts_pts_offset = (pts - _last_max_pts) / 2`,我后面改成了` _dts_pts_offset = (pts - _last_max_pts) `,理论上不存在你说的这些问题

**Comment by lawrencehj** [comment]
用以前的版本确实没有遇到不同步的问题，最近发现这个问题我还以为是推流端出了问题，做了很多尝试都没改善。今天运行了一个以前编译的版本，发现不同步的问题消失了，就尝试替换有可能的文件，单单改了这一处就解决了。

**Comment by xiongziliang** [comment]
嗯 你先把文件发给我

**Comment by lawrencehj** [comment]
stamp.cpp这个文件吗？

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/85940903-eb561c00-b951-11ea-9f2d-00e03321d352.png)
应该是这个逻辑导致的

**Comment by xiongziliang** [comment]
> stamp.cpp这个文件吗？

mp4那个文件

**Comment by lawrencehj** [comment]
那个文件太大了，之前发过的bhd.mp4也是类似的

**Comment by xiongziliang** [comment]
嗯 那算了 我改回去吧 基本没啥影响

**Comment by xiongziliang** [comment]
你再试试呗

**Comment by xiongziliang** [comment]
我想关闭这个issue了，有反馈你直接在这里回复

**Comment by lawrencehj** [comment]
OK
