### ISSUE TITLE
Rtsp vbr. Config or fixed buffer 

### ISSUE THREAD

**Issue by nokiovo79** [xiongziliang/ZLMediaKit#37]
I wanted information about rtsp pusher.  I noticed that by publishing a video source (camera) with cbr the server behaves well and the player correctly shows everything.  if instead the video source applies the vbr the movement of the camera is freezed on the player. Obviously I tried with different players, all has the same problem.  it appears that the server adjusts its receive buffer based on the first rtsp packet.  There is configuration to be done in the config file for server to also satisfy vbr or is there a problem in the management of buffers variable in time?  Thank you

**Comment by xiongziliang** [comment]
The old version of the code will cache sps pps frame,so it will not be able to decode by player when  use VBR , the latest code has fixed this bug, thank you!

**Comment by nokiovo79** [comment]
Fixed bug in server?I cloned the code 2 days ago.
For player i use vlc or ffplay. Thank you

**Comment by xiongziliang** [comment]
The bug was fixed a few weeks ago when it was discovered that the video of H264 pulled by RTSP could not be decoded. This fix is valid for both client and server of pull-flow and push-flow。

**Comment by nokiovo79** [comment]
Checking with the latest version i don't find the same problem. great !!!
Further advice ... Which javascript library can i use to connect web client to ZlServer?

**Comment by xiongziliang** [comment]
You mean the player on web? You can use video.js or ckplayer or [flv.js](https://github.com/bilibili/flv.js).

**Comment by nokiovo79** [comment]
Ok, thank you. But is it not possible via websocket?

**Comment by xiongziliang** [comment]
If you like, you can use rtsp over websocket or any tcp protocol over websocket.

**Comment by nokiovo79** [comment]
Because I would lighten the client from any h264 decoding, sending only jpeg

**Comment by xiongziliang** [comment]
> Because I would lighten the client from any h264 decoding, sending only jpeg

You mean you want transcode h264 to jpeg and send it by websocket ?

**Comment by nokiovo79** [comment]
Is there a best way? I think the best solution is webrtc!!! I don’t understand the websocket in Zlmediakit....

**Comment by nokiovo79** [comment]
> > Because I would lighten the client from any h264 decoding, sending only jpeg
> 
> You mean you want transcode h264 to jpeg and send it by websocket ?

Yes, if i want the near video realtime. With hls and videojs the video has 5/10 second of delay. Webrtc can be the solution?

**Comment by xiongziliang** [comment]
At present,except webrtc, other technical solutions are not ideal.
RTMP is a fast outdated technology and HLS delay is too high.
But maybe you can try `emscripten`,
It can convert FFmpeg into javascript code

**Comment by nokiovo79** [comment]
Thank you...
