### ISSUE TITLE
GB28181 如何关联设备与输出流？ 

### ISSUE THREAD

**Issue by ikingye** [xiongziliang/ZLMediaKit#371]
/index/api/getMediaList 获取的拉流地址，看不出是哪个 ipc 设备发过来的

**Comment by xiongziliang** [comment]
只能获取到ssrc和发送端地址等信息，因为ipc的id没法通过rtp发给ZLMediaKit ZLMediaKit也无从得知

**Comment by xiongziliang** [comment]
后续我会新增动态创建GB28181 Rtp接收端口的api，到时可以绑定这些信息
