### ISSUE TITLE
[新功能请求] 建议c接口增加三个回调: 1. 码流ready回调 2. 前端(比如RTSP客户端)关闭码流回调 3. 一段时间内无人观看回调

### ISSUE THREAD

**Issue by netjune** [xiongziliang/ZLMediaKit#373]
建议c接口增加以下三个回调: 
1. 码流ready回调. 遇到的问题: 比如创建了一个rtsp流并返回url, 但是码流还没就绪, 导致rtsp客户端马上打开该url时提示找不到流.
2. 前端(比如RTSP客户端)关闭码流回调. 应用场景: 假如一个rtsp的url只允许被访问一次, 那么rtsp客户端关闭的时候, 流就可以关闭了, 此时需要一个回调函数来知道rtsp客户端关闭了.
3. 一段时间内无人观看回调. 看日志有这个信息, 但是没有回调. 增加回调方便处理.

**Comment by xiongziliang** [comment]
1、目前是有码流ready回调的，也就是MediaSource的注册事件，kBroadcastMediaChanged这个广播(C++的)。
    你说的播放一个不存在的rtsp，zlm并不会立即返回404，而且会hold一段时间，如果还是未注册，才会返回404.

2、目前有无人观看事件，不过可以设置触发延时，这个事件是kBroadcastStreamNoneReader。

3、无人观看事件C++和C都有接口的。

**Comment by netjune** [comment]
C接口的回调我只在mk_media.h里看到有两个:
+ mk_media_set_on_close
+ mk_media_set_on_seek

其他的在哪个头文件里? 另外, 如何在C里监听广播事件?

**Comment by xiongziliang** [comment]
用mk_events_listen函数监听，on_mk_media_changed回调

**Comment by netjune** [comment]
看了下 `mk_events_listen`, 里面的对象都是针对`mk_media_source`, 如何转换到`mk_media`, 他们两者之间如何对应?

**Comment by xiongziliang** [comment]
通过流id啊。

**Comment by xiongziliang** [comment]
mk_media会对应多个mk_media_source啊，你想往mk_media设置个回调多次触发mk_media_source注册事件吗？

**Comment by xiongziliang** [comment]
其实也能做到

**Comment by netjune** [comment]
> mk_media会对应多个mk_media_source啊，你想往mk_media设置个回调多次触发mk_media_source注册事件吗？

明白了, 是会有多个media source, 那函数`mk_media_total_reader_count`获取到的是该mk_media对应的所有media source的reader count吗?

**Comment by xiongziliang** [comment]
是的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhanghj <notifications@github.com&gt;
发送时间: 2020年7月2日 09:45
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] [新功能请求] 建议c接口增加三个回调: 1. 码流ready回调 2. 前端(比如RTSP客户端)关闭码流回调 3. 一段时间内无人观看回调 (#373)





  
mk_media会对应多个mk_media_source啊，你想往mk_media设置个回调多次触发mk_media_source注册事件吗？
  
明白了, 是会有多个media source, 那函数mk_media_total_reader_count获取到的是该mk_media对应的所有media source的reader count吗?

**Comment by netjune** [comment]
我这边创建的mk_media大都只有一个media source, 目前的一个需求是如何及时销毁它释放资源, 有两个销毁的逻辑:

1. 创建后, 一直处于空闲状态, 则超过3分钟后销毁
2. 创建后, 有任何一个用户打开过, 然后关闭了, 则马上销毁

现在是无法知道该流被人打开过, 无法实现2的逻辑.

**Comment by xiongziliang** [comment]
我知道你想实现按需生成流。目前zlm的接口完全够你达到这个目的啊。
在触发on_mk_media_not_found事件触发时，你再创建mk_media对象。
在触发on_mk_media_no_reader事件触发时，就销毁这个mk_media对象。

**Comment by xiongziliang** [comment]
你描述的1、2条有点匪夷所思 ，特别是第二条，你知不知道播放器断开后立即关闭流可能会导致一些临界区竞争关系？
延时后再关闭是种比较稳妥的做法。

**Comment by netjune** [comment]
> 我知道你想实现按需生成流。目前zlm的接口完全够你达到这个目的啊。
> 在触发on_mk_media_not_found事件触发时，你再创建mk_media对象。
> 在触发on_mk_media_no_reader事件触发时，就销毁这个mk_media对象。

这个机制挺不错, 不过由于我们这边的需求以及设计问题, 没法使用这个机制.

>你描述的1、2条有点匪夷所思 ，特别是第二条，你知不知道播放器断开后立即关闭流可能会导致一些临界区竞争关系？
延时后再关闭是种比较稳妥的做法。

短暂的延时是可以的, 比如100毫秒.

**Comment by netjune** [comment]
> mk_media会对应多个mk_media_source啊，你想往mk_media设置个回调多次触发mk_media_source注册事件吗？

这个可以实现吗? 回调的用户数据里存放mk_media对象指针, 这样就对应起来了.

**Comment by xiongziliang** [comment]
可以是可以 

> > 我知道你想实现按需生成流。目前zlm的接口完全够你达到这个目的啊。
> > 在触发on_mk_media_not_found事件触发时，你再创建mk_media对象。
> > 在触发on_mk_media_no_reader事件触发时，就销毁这个mk_media对象。
> 
> 这个机制挺不错, 不过由于我们这边的需求以及设计问题, 没法使用这个机制.
> 
> > 你描述的1、2条有点匪夷所思 ，特别是第二条，你知不知道播放器断开后立即关闭流可能会导致一些临界区竞争关系？
> > 延时后再关闭是种比较稳妥的做法。
> 
> 短暂的延时是可以的, 比如100毫秒.

你的需求很奇怪 我很难理解， 你需要自己修改代码

**Comment by xiongziliang** [comment]
> > mk_media会对应多个mk_media_source啊，你想往mk_media设置个回调多次触发mk_media_source注册事件吗？
> 
> 这个可以实现吗? 回调的用户数据里存放mk_media对象指针, 这样就对应起来了. 不过回调好像没有用户数据.

这个可以实现下

**Comment by xiongziliang** [comment]
已经添加新接口：mk_media_set_on_regist
你测试反馈下给我

**Comment by netjune** [comment]
> 可以是可以
> 
> > > 我知道你想实现按需生成流。目前zlm的接口完全够你达到这个目的啊。
> > > 在触发on_mk_media_not_found事件触发时，你再创建mk_media对象。
> > > 在触发on_mk_media_no_reader事件触发时，就销毁这个mk_media对象。
> > 
> > 
> > 这个机制挺不错, 不过由于我们这边的需求以及设计问题, 没法使用这个机制.
> > > 你描述的1、2条有点匪夷所思 ，特别是第二条，你知不知道播放器断开后立即关闭流可能会导致一些临界区竞争关系？
> > > 延时后再关闭是种比较稳妥的做法。
> > 
> > 
> > 短暂的延时是可以的, 比如100毫秒.
> 
> 你的需求很奇怪 我很难理解， 你需要自己修改代码

简单来说就是为了安全, 每个url只能被打开一次, 然后就失效了, 这样省去了认证, 因为认证不是很统一, 有的不支持认证.

**Comment by netjune** [comment]
> 已经添加新接口：mk_media_set_on_regist
> 你测试反馈下给我

这个是media source创建的时候的回调吗? 这个好像我用不上啊, 需要个mk_media中任意一个media source流关闭的回调.

**Comment by xiongziliang** [comment]
对播放器来说 url参数也是url的一部分，所以通过url参数鉴权也能满足你的要求



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhanghj <notifications@github.com&gt;
发送时间: 2020年7月2日 21:45
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] [新功能请求] 建议c接口增加三个回调: 1. 码流ready回调 2. 前端(比如RTSP客户端)关闭码流回调 3. 一段时间内无人观看回调 (#373)





  
可以是可以
   
我知道你想实现按需生成流。目前zlm的接口完全够你达到这个目的啊。
 在触发on_mk_media_not_found事件触发时，你再创建mk_media对象。
 在触发on_mk_media_no_reader事件触发时，就销毁这个mk_media对象。
  
这个机制挺不错, 不过由于我们这边的需求以及设计问题, 没法使用这个机制.
  
你描述的1、2条有点匪夷所思 ，特别是第二条，你知不知道播放器断开后立即关闭流可能会导致一些临界区竞争关系？
 延时后再关闭是种比较稳妥的做法。
  
短暂的延时是可以的, 比如100毫秒.
  
你的需求很奇怪 我很难理解， 你需要自己修改代码
  
简单来说就是为了安全, 每个url只能被打开一次, 然后就失效了, 这样省去了认证, 因为认证不是很统一, 有的不支持认证.

**Comment by netjune** [comment]
> 对播放器来说 url参数也是url的一部分，所以通过url参数鉴权也能满足你的要求 发自我的iPhone
> […](#)

这个信息太容易泄漏, 别人抓个包就看到了. 我现在是在一个安全的传输里创建这个url, 返回给客户端, 然后客户端那边用任意工具打开该url, 每个url只能打开一次, 这样即使url泄漏了也影响不大.

**Comment by xiongziliang** [comment]
你streamid能随机 url参数就不能随机? streamid只是服务器上的概念 对播放器来说没区别啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhanghj <notifications@github.com&gt;
发送时间: 2020年7月3日 08:44
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] [新功能请求] 建议c接口增加三个回调: 1. 码流ready回调 2. 前端(比如RTSP客户端)关闭码流回调 3. 一段时间内无人观看回调 (#373)





  
对播放器来说 url参数也是url的一部分，所以通过url参数鉴权也能满足你的要求 发自我的iPhone
 …
  
这个信息太容易泄漏, 别人抓个包就看到了. 我现在是在一个安全的传输里创建这个url, 返回给客户端, 然后客户端那边用任意工具打开该url, 每个url只能打开一次, 这样即使url泄漏了也影响不大.

**Comment by xiongziliang** [comment]
我先关闭这个issue了 有问题你直接在这里反馈

**Comment by netjune** [comment]
> 你streamid能随机 url参数就不能随机? streamid只是服务器上的概念 对播放器来说没区别啊 发自我的iPhone
> […](#)

你是说所有的流都使用同一个stream id, 然后用url参数来区分不同的流? 我们有很多摄像头, 不是一两个摄像头, 大部分情况下每个流都是来自不同摄像头, 这样的话, 好像没必要共享streamid.

最终需求是想得到流关闭事件的通知, 比如RTSP的.

**Comment by xiongziliang** [comment]
我的意思是 你不同的摄像头 用不同的stream id ，但是同一个摄像头stream id不变，通过url参数来鉴权，而不是通过变换stream id来鉴权。

**Comment by netjune** [comment]
> 我的意思是 你不同的摄像头 用不同的stream id ，但是同一个摄像头stream id不变，通过url参数来鉴权，而不是通过变换stream id来鉴权。

是的, 这种情况也会有. 之前不知道mk_event, 所以在zlmedia内部做了一个url映射层, 底层是一个streamid, 映射层会给它创建多个别名. 底层的streamid不暴露出去, 给出去的只有别名. 也算简单. 

但是有个限制就是HLS. HLS是短连接, 周期请求同一个url, 如果每次请求都需要验证, 担心性能.

**Comment by xiongziliang** [comment]
hls鉴权结果会保存cookie的 不会频繁触发



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhanghj <notifications@github.com&gt;
发送时间: 2020年7月5日 12:40
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] [新功能请求] 建议c接口增加三个回调: 1. 码流ready回调 2. 前端(比如RTSP客户端)关闭码流回调 3. 一段时间内无人观看回调 (#373)





  
我的意思是 你不同的摄像头 用不同的stream id ，但是同一个摄像头stream id不变，通过url参数来鉴权，而不是通过变换stream id来鉴权。
  
是的, 这种情况也会有. 之前不知道mk_event, 所以在zlmedia内部做了一个url映射层, 底层是一个streamid, 映射层会给它创建多个别名. 底层的streamid不暴露出去, 给出去的只有别名. 也算简单.
 
但是有个限制就是HLS. HLS是短连接, 周期请求同一个url, 如果每次请求都需要验证, 担心性能.
