### ISSUE TITLE
ZLMediaKit 目前支持集群部署么

### ISSUE THREAD

**Issue by tsinemperor** [xiongziliang/ZLMediaKit#376]
ZLMediaKit 目前支持集群部署么，如果可以，目前有集群部署文档么？如果还没有，有没有这方面的计划或方向？

**Comment by xiongziliang** [comment]
集群部署是一种业务，需要二次开发的。集群部署基本等同于按需拉流。

**Comment by tsinemperor** [comment]
我的答题思路是：集群部署ZLM集群服务，GB平台通过负载均衡策略下发流媒体任务到ZLM，这样就可以实现集群。ZLM还要加一个keepalive的心跳存活监测功能。兄弟有何其他高见？

**Comment by tsinemperor** [comment]
> 集群部署是一种业务，需要二次开发的。集群部署基本等同于按需拉流，你可以看看wiki，里面有按需拉流的相关描述

我的解决思路是：集群部署ZLM集群服务，GB平台通过负载均衡策略下发流媒体任务到ZLM，这样就可以实现集群。ZLM还要加一个keepalive的心跳存活监测功能。兄弟有何其他高见？

**Comment by xiongziliang** [comment]
你是要心跳存活检测GB流在不在线还是检测ZLM服务器节点在不在线?

**Comment by xiongziliang** [comment]
我先关闭这个issue了 有问题你直接在这里反馈
