### ISSUE TITLE
问题咨询：…如何建立RTSP服务端并直播一段本地流？

### ISSUE THREAD

**Issue by Elvisass** [xiongziliang/ZLMediaKit#377]
我对网络流媒体相关的概念不是很熟，看框架里的东西完全摸不着头脑……

现在我是想试一下，只使用ZLMediaKit，在本地开放一个RTSP服务，对外输出一个本地视频文件（MP4/H.264+AAC）。
我看到test中有`test_server`建立了服务端，并设置了事件处理，同时也有播放的代码（但没有理解播放和Player到底是干什么的，Player与后面的Server之间也没有发现什么关联）。
同时`test_pusherMP4`可以将mp4文件作为数据源（或许是直接推原始数据，不需要做编解码？），然后往一个地址上推送。
尝试运行test_pusherMP4往本地推流（使用默认554端口），同时运行test_server并播放这个流，但两个程序都表示无法连接（`Socket not set errCB`）。

能否讲解一下**建立RTSP服务端并接收本地的流**以及**向一个地址推送流**的正确方法是什么？
我感觉我可能完全误解了这些test……
~~然后为什么issue区只有我一个人跑不通这个基本流程（自闭~~

**Comment by xiongziliang** [comment]
你可以把mp4文件放在www/record目录下,然后启动MediaServer进程。
播放url你参考wiki，url规则篇
