### ISSUE TITLE
是否有计划支持纯音频录制？

### ISSUE THREAD

**Issue by lyg1949** [xiongziliang/ZLMediaKit#378]
对于只有音频流的或者只关心音频数据的情况下，是否考虑支持音频文件的录制？

**Comment by xiongziliang** [comment]
现在本来就支持纯音频的录制啊，不过都是录制为mp4文件，你想录制为aac吗？

**Comment by lyg1949** [comment]
能录成aac文件最好，因为纯音频的mp4文件和aac文件在后续的音频再处理上不知道有没有区别去！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年7月1日 17:59
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: lyg1949 <zh.ghlong@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 是否有计划支持纯音频录制？ (#378)





 
现在本来就支持纯音频的录制啊，不过都是录制为mp4文件，你想录制为aac吗？

**Comment by xiongziliang** [comment]
你这个需求已经是定制化的了。zlm不会限定推流器只能推aac。所以音频可能有各种格式，保存为mp4可以兼容各种编码格式。
你如果需要保存为aac，你可以自己修改下代码

**Comment by lyg1949** [comment]
好的，多谢！
