### ISSUE TITLE
"git submodule update --init" failed

### ISSUE THREAD

**Issue by lenhatvu** [xiongziliang/ZLMediaKit#379]
I am clone your latest code but command "git submodule update --init" failed.
Previous vesion is ok

**Comment by xiongziliang** [comment]
@wasphin  We need help!

@lenhatvu This issue is caused by #375

**Comment by wasphin** [comment]
@lenhatvu Can you post the logs of the command?

I have tried it again, and here is output:
```
git clone --depth 1 --recurse-submodules https://github.com/xiongziliang/ZLMediaKit.git
Cloning into 'ZLMediaKit'...
remote: Enumerating objects: 504, done.
remote: Counting objects: 100% (504/504), done.
remote: Compressing objects: 100% (455/455), done.
remote: Total 504 (delta 66), reused 221 (delta 24), pack-reused 0
Receiving objects: 100% (504/504), 6.73 MiB | 2.14 MiB/s, done.
Resolving deltas: 100% (66/66), done.
Submodule 'ZLToolKit' (https://github.com/xiongziliang/ZLToolKit) registered for path '3rdpart/ZLToolKit'
Submodule '3rdpart/media-server' (https://github.com/xiongziliang/media-server) registered for path '3rdpart/media-server'
Cloning into '/home/wxf/work/opensource/tmp/ZLMediaKit/3rdpart/ZLToolKit'...
remote: Enumerating objects: 355, done.        
remote: Counting objects: 100% (355/355), done.        
remote: Compressing objects: 100% (226/226), done.        
remote: Total 5341 (delta 226), reused 233 (delta 129), pack-reused 4986        
Receiving objects: 100% (5341/5341), 31.34 MiB | 2.71 MiB/s, done.
Resolving deltas: 100% (3898/3898), done.
Cloning into '/home/wxf/work/opensource/tmp/ZLMediaKit/3rdpart/media-server'...
remote: Enumerating objects: 791, done.        
remote: Counting objects: 100% (791/791), done.        
remote: Compressing objects: 100% (520/520), done.        
remote: Total 8952 (delta 438), reused 489 (delta 251), pack-reused 8161        
Receiving objects: 100% (8952/8952), 2.75 MiB | 1.71 MiB/s, done.
Resolving deltas: 100% (6235/6235), done.
Submodule path '3rdpart/ZLToolKit': checked out '5030af90126ea8f01ded6744ae8abdf549d00a81'
Submodule path '3rdpart/media-server': checked out '576216c64bf3bcdc5e787da2adb3e169bdd97118'
```
and this is the output of another try:
```
[wxf@wxf tmp]$ pgit clone --depth 1  https://github.com/xiongziliang/ZLMediaKit.git
Cloning into 'ZLMediaKit'...
remote: Enumerating objects: 504, done.
remote: Counting objects: 100% (504/504), done.
remote: Compressing objects: 100% (455/455), done.
remote: Total 504 (delta 66), reused 221 (delta 24), pack-reused 0
Receiving objects: 100% (504/504), 6.73 MiB | 698.00 KiB/s, done.
Resolving deltas: 100% (66/66), done.
[wxf@wxf tmp]$ cd ZLMediaKit/
[wxf@wxf ZLMediaKit]$ git submodule update --init 
Cloning into '/home/wxf/work/opensource/tmp/ZLMediaKit/3rdpart/ZLToolKit'...
Cloning into '/home/wxf/work/opensource/tmp/ZLMediaKit/3rdpart/media-server'...
Submodule path '3rdpart/ZLToolKit': checked out '5030af90126ea8f01ded6744ae8abdf549d00a81'
Submodule path '3rdpart/media-server': checked out '576216c64bf3bcdc5e787da2adb3e169bdd97118'
```

**Comment by lenhatvu** [comment]
Hi,

Microsoft Windows [Version 10.0.19041.329]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\thaib>e:

E:\>cd E:\ZL\20200701_1784

E:\ZL\20200701_1784>git clone https://github.com/zlmediakit/zlmediakit.git
Cloning into 'zlmediakit'...
remote: Enumerating objects: 109, done.
remote: Counting objects: 100% (109/109), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 13761 (delta 48), reused 54 (delta 27), pack-reused 13652
Receiving objects: 100% (13761/13761), 123.46 MiB | 2.07 MiB/s, done.
Resolving deltas: 100% (10286/10286), done.

E:\ZL\20200701_1784>cd zlmediakit

E:\ZL\20200701_1784\zlmediakit>git submodule update --init
Submodule 'ZLToolKit' (https://github.com/zlmediakit/ZLToolKit) registered for path '3rdpart/ZLToolKit'
Submodule '3rdpart/media-server' (https://github.com/zlmediakit/media-server) registered for path '3rdpart/media-server'
Cloning into 'E:/ZL/20200701_1784/zlmediakit/3rdpart/ZLToolKit'...
Cloning into 'E:/ZL/20200701_1784/zlmediakit/3rdpart/media-server'...
remote: Repository not found.
fatal: repository 'https://github.com/zlmediakit/media-server/' not found
fatal: clone of 'https://github.com/zlmediakit/media-server' into submodule path 'E:/ZL/20200701_1784/zlmediakit/3rdpart/media-server' failed
Failed to clone '3rdpart/media-server'. Retry scheduled
Cloning into 'E:/ZL/20200701_1784/zlmediakit/3rdpart/media-server'...
remote: Repository not found.
fatal: repository 'https://github.com/zlmediakit/media-server/' not found
fatal: clone of 'https://github.com/zlmediakit/media-server' into submodule path 'E:/ZL/20200701_1784/zlmediakit/3rdpart/media-server' failed
Failed to clone '3rdpart/media-server' a second time, aborting

E:\ZL\20200701_1784\zlmediakit>

**Comment by wasphin** [comment]
@lenhatvu I see the problem.

Can you use this command to fix the url of the main repo:
```
git remote set-url origin https://github.com/xiongziliang/ZLMediaKit.git
```
Then sync the submodule url by this:
```
git submodule sync
```
Then update again:
```
git submodule update --init
```

Summary:
```
git remote set-url origin https://github.com/xiongziliang/ZLMediaKit.git
git submodule sync
git submodule update --init
```

**Comment by wasphin** [comment]
This may be the story of this problem:
1. @xiongziliang create the repo at user name/org-name ``ZLMediaKit``;
1. Change his name to ``xiongziliang``;
1. Then fork media-server under new name xiongziliang;

Sorry for the trouble introduced, but this problem cannot be fixed if you use both relative path and the old repo url.

**Comment by lenhatvu** [comment]
Hi,

It's work.  But now can i using "git clone --depth 1 --recurse-submodules https://github.com/xiongziliang/ZLMediaKit.git"
instead of:
git clone https://github.com/zlmediakit/ZLMediaKit.git
cd ZLMediaKit
git remote set-url origin https://github.com/xiongziliang/ZLMediaKit.git
git submodule sync
git submodule update --init

?

**Comment by wasphin** [comment]
@lenhatvu If you use the new url https://github.com/xiongziliang/ZLMediaKit.git, you can just use the same way as before:
```
git clone https://github.com/xiongziliang/ZLMediaKit.git
cd ZLMediaKit
git submodule update --init
```

If you want to update a repo from the previously cloned one, the you can update the url first:
```
git remote set-url origin https://github.com/xiongziliang/ZLMediaKit.git
git submodule sync
```
then update the repo just as before by ``git submodule update --init``

**Comment by lenhatvu** [comment]
Thanks

**Comment by lenhatvu** [comment]
Please update in readme: https://github.com/xiongziliang/ZLMediaKit/blob/master/README_en.md

**Comment by xiongziliang** [comment]
> Please update in readme: https://github.com/xiongziliang/ZLMediaKit/blob/master/README_en.md

Updated, thanks.
