### ISSUE TITLE
后期有对讲功能的计划吗

### ISSUE THREAD

**Issue by dengchaowen-cx** [xiongziliang/ZLMediaKit#380]
可以用http实现吗

**Comment by xiongziliang** [comment]
不会，建议你了解下RTC和直播的区别。
你可以了解下webrtc。

**Comment by dengchaowen-cx** [comment]
还有一个问题想咨询您，推tcp/rtp/ps流到mediaserver，vlc拉rtmp，开始延时是五六秒的样子，第二条早上延时到了十一二秒，我拜读了一下您的代码，里面用了缓冲，是缓冲导致的吗？ 谢谢

**Comment by xiongziliang** [comment]
缓冲只是GOP缓存，目的是为了秒开画面，在播放器打开视频后会一股脑丢给播放器。
所以这个缓存不会导致延时累积。
延时累积是由于播放器网络抖动导致的，或者干脆摄像头的时间戳有问题。

**Comment by xiongziliang** [comment]
你可以看看wiki关于延时的文章

**Comment by dengchaowen-cx** [comment]
好的 谢谢您的解答
