### ISSUE TITLE
部分usb camera 帧率高于25fps时，需要60-120s不等才有画面

### ISSUE THREAD

**Issue by FengChueng** [xiongziliang/ZLMediaKit#381]
首先很感谢作者的贡献精神(早就star了，^_^)
项目背景：使用ZLMediaKit作为摄像机的流媒体服务器，使用的板子是jetson nano，
现在的流程，使用ffmpeg 拉取 usb camera的h264(30fps)流推送至ZLM，web端使用live-player播放摄像头的http-flv
ffmpeg命令：ffmpeg -i "/dev/video1" -vcodec copy -acodec copy -f flv rtmp://localhost:1935/live/test
ffmpeg进程此时cpu占用7%，ZML占用10-20%，前端播放偶尔会出现绿屏的情况，需要等待60s左右恢复正常画面。部分摄像机播放需要等待60-120s才有画面
使用ffmpeg将帧率设置为25，ffmpeg -i "/dev/video1" -vcodec h264 -r25 -b:v 512k -f flv rtmp://localhost/live/test。
ffmpeg进程此时cpu占用183%，ZML占用5%。前端播放立即就有画面。

**Comment by xiongziliang** [comment]
可能你的驱动默认很久才出现关键帧

**Comment by xiongziliang** [comment]
你需要设置下GOP的时长

**Comment by xiongziliang** [comment]
我先关闭这个issue了 有问题你直接在这里反馈

**Comment by FengChueng** [comment]
不好意思太忙了，应该是你说的那个问题，我找了一下控制相机相关参数，没有可以设置I帧间隔和GOP的参数，我再找找看能不能解决吧。

**Comment by xiongziliang** [comment]
要么是GOP时长问题 要么是时间戳问题 肯定不是ZLMediaKit问题

**Comment by FengChueng** [comment]
想请教一下，windows上面可以使用addStreamProxy只能拉取rtsp流推流，我们现在jetson nano上面部署了ZLMediaKit，如果不使用fork ffmpeg的方式来拉取usb Camera的 h264的流来推流，需要改哪部分源码呢？
之前使用的方式：ffmpeg -s 1920*1080 -vcodec h264 -i "/dev/video0" -vcodec copy -f flv rtmp://localhost/supercube/live
