### ISSUE TITLE
rtp丢包后，就解析不出frame了

### ISSUE THREAD

**Issue by zhang2349** [xiongziliang/ZLMediaKit#388]
#358 
跟这个问题应该是同一个问题

每次 https://github.com/xiongziliang/ZLMediaKit/blob/master/src/Rtp/RtpProcess.cpp#L132 这句输出后
https://github.com/xiongziliang/ZLMediaKit/blob/master/src/Rtp/RtpProcess.cpp#L170 这里就没有了
哪怕只输出一次丢包日志

另外我也碰到了 #359  的类似问题，更新了最新代码后 rtp推流有G711音频的时候（不太确定是否真的有音频，保存为文件后，用MediaInfo查看是 没有音频的， 但是用vlc播放 编解码器信息里 有个MPEG Audio layer 1/2 （mpga）） vlc播放rtsp的时候，mediaserver会崩溃，具体没细看，暂时把音频去掉了

**Comment by xiongziliang** [comment]
你是 公网udp推流吗？我觉得不输出frame可能不仅仅是那个丢包日志导致，你需要粘贴更多的日志

**Comment by zhang2349** [comment]
不是公网，没日志 就那一句。。

**Comment by zhang2349** [comment]
丢了一次后 会 大部分进 https://github.com/xiongziliang/media-server/blob/master/librtp/payload/rtp-ps-unpack.c#L27
导致都丢了

**Comment by SnowfallDan** [comment]
和我的问题基本一致...我还苦恼于问题复现...看来这位兄台帮我解决了

**Comment by gcmars** [comment]
同样的问题

**Comment by xiongziliang** [comment]
能不能导出一个rtp包给我测试下？

**Comment by xiongziliang** [comment]
配置文件rtp_proxy.dumpDir设置下导出目录即可

**Comment by bozang** [comment]
rtp-ps-unpack.c这个文件的32行(rtp_payload_onframe(helper);)上面加上这句话试试：
helper->seq = (uint16_t)(pkt.rtp.seq - 1);

**Comment by bozang** [comment]
> 丢了一次后 会 大部分进 https://github.com/xiongziliang/media-server/blob/master/librtp/payload/rtp-ps-unpack.c#L27
> 导致都丢了

我之前丢包环境中也碰到过这个问题，你按照我上面的方法测一下

**Comment by zhang2349** [comment]
> rtp-ps-unpack.c这个文件的32行(rtp_payload_onframe(helper);)上面加上这句话试试：
> helper->seq = (uint16_t)(pkt.rtp.seq - 1);

这个方法可以，大概看了下逻辑是这样的
如果丢包，就开始找mpeg2_packet_start，但是找到后，相关的标志没有恢复初始状态，是不是把helper->flags=-1，会不会好一些，我看他的timestamp也有初始化一下

**Comment by xiongziliang** [comment]
@ireader 大佬 你看看这个issue  是不是你的库有点bug

**Comment by ireader** [comment]
@zhang2349 @bozang 是不是RTP包的timestamp一直没有变？

**Comment by ireader** [comment]
![image](https://user-images.githubusercontent.com/1535445/86870192-80070980-c10a-11ea-9e52-7ae918a81776.png)

这里是判断是否含有起始码，提供一份有问题的数据？ rtpdump或者wireshark抓包文件都可以。

**Comment by zhang2349** [comment]
> ![image](https://user-images.githubusercontent.com/1535445/86870192-80070980-c10a-11ea-9e52-7ae918a81776.png)
> 
> 这里是判断是否含有起始码，提供一份有问题的数据？ rtpdump或者wireshark抓包文件都可以。


判断后 
https://github.com/xiongziliang/media-server/blob/master/librtp/payload/rtp-payload-helper.c#L97
这里只是 去掉了丢包标志

然后到了
https://github.com/xiongziliang/media-server/blob/master/librtp/payload/rtp-payload-helper.c#L44
条件肯定不成立，又判断为丢包了

**Comment by ireader** [comment]
> rtp-ps-unpack.c这个文件的32行(rtp_payload_onframe(helper);)上面加上这句话试试：
> helper->seq = (uint16_t)(pkt.rtp.seq - 1);

@zhang2349 按照这个改吧，回头我更新下。

**Comment by gcmars** [comment]
> rtp-ps-unpack.c这个文件的32行(rtp_payload_onframe(helper);)上面加上这句话试试：
> helper->seq = (uint16_t)(pkt.rtp.seq - 1);

这改了之后还需要手动再把flag置成-1吗？

**Comment by ireader** [comment]
> > rtp-ps-unpack.c这个文件的32行(rtp_payload_onframe(helper);)上面加上这句话试试：
> > helper->seq = (uint16_t)(pkt.rtp.seq - 1);
> 
> 这改了之后还需要手动再把flag置成-1吗？

flags设置为0即可

**Comment by xiongziliang** [comment]
@ireader 麻烦更新了通知我一声 我同步下

**Comment by zhang2349** [comment]
刚更新了源码   第二个问题  也没了 完美

**Comment by xiongziliang** [comment]
> 刚更新了源码 第二个问题 也没了 完美

嗯 第二个问题是由于G711没设置rtp的类型导致的

**Comment by ireader** [comment]
> @ireader 麻烦更新了通知我一声 我同步下

周六更新

**Comment by xiongziliang** [comment]
已经同步代码 诸位有条件的可以测试下是否修复这个问题。
这个issue先关闭了，有问题请请直接在此回复。

**Comment by zhang2349** [comment]
可以

**Comment by xiongziliang** [comment]
@zhang2349 测试没问题吗 群里面又有人反馈这个问题 不知道是不是代码没更新还是没修复

**Comment by ireader** [comment]
什么现象？

**Comment by zhang2349** [comment]
@xiongziliang 暂时没发现问题
另外有个问题   频繁的 openRtpServer closeRtpServer 会奔溃在s_rtpServerMap.erase() 有点奇怪
我断点看 s_rtpServerMap 和 stream_id的值都是正常的 但一执行就崩掉了 s_rtpServerMap就变野值了。。。
