### ISSUE TITLE
Can I seperate HLS filePath dir and record dir on multi disk for load balancing ?

### ISSUE THREAD

**Issue by lenhatvu** [xiongziliang/ZLMediaKit#389]
Hi,

When MediaServer connect to many streams, if enable HLS or RTMP server, the video stream output very lag, if using only rtsp server, the video stream output is normal. I think HLS and RTMP need to write ts file to disk, if disk speed is not good => video stream output lag.

About record dir: maybe 1 disk is not enough for recording, if i can set multi path to recording is very flexible.

**Comment by xiongziliang** [comment]
Yes, writing HLS file may cause network receiving threads to lag.
I don't recommend generating a lot of HLS live stream unless you have a fast disk.

**Comment by xiongziliang** [comment]
You can use ramdisk to verify whether HLS causes the delay increase

**Comment by xiongziliang** [comment]
It is difficult to write HLS to multiple disks, because HLS writing is a configuration and reading it is a other directory.
Strictly speaking, writing HLS files has nothing to do with the HTTP server root directory.

Therefore, if you want to make multiple HLS streams write to multiple disks, the HTTP file server should also support this feature.

**Comment by xiongziliang** [comment]
You should use ramdisk or raid (redundant arrays of Independent Disks) technology to implement your X

**Comment by lenhatvu** [comment]
Yes,

I've tried ramdisk, it's very good and solve this problem. 
How about record dir ?

**Comment by xiongziliang** [comment]
I don't recommend using the zlmediakit alone to solve this problem。

Disk IO performance bottleneck optimization is a big project, not a simple transformation of zlmediakit can be achieved.
Mp4 record files saved by zlmediakit can also be used for RTSP / RTMP on demand。

If you only generate mp4 record files, you can save them to multiple disks, but where to find them when reading them?
 After all, zlmediakit has no database to record the metadata.

**Comment by xiongziliang** [comment]
I think in `fopen`, you can make a unified file directory mapping, and then put the mapping relationship in the database, so the change code is very small, you can try it

**Comment by lenhatvu** [comment]
Thanks,

I think using "on_record_mp4" event to get file path and save to database.
I will try with your advise.
Thank you very much.
