### ISSUE TITLE
FFmpeg按需拉流失败问题

### ISSUE THREAD

**Issue by oujiangping** [xiongziliang/ZLMediaKit#39]
按照现在按需拉流的流程，无人观看断流，如果用户再次打开rtmp会触发，not_found处理成重新打开流addFFmpegSource，但是按照这个逻辑测试发现，当用户再次打开时rtmp服务器先返回错误“No such stream”，紧接着才打开流，所以客户端在打开第一次失败后再打开一次才成功。这是一个bug还是功能上本来就是这样

**Comment by xiongziliang** [comment]
这个不是bug，这个是由于FFmpeg在超时时间内`未拉流并推流成功`的原因导致的。
你可以重启MediaServer进程，多试几次，有时FFmpeg确实不能再规定时间内拉流并推流成功，但是多数情况下能立即成功。不能立即成功的原因可以查看下FFmpeg的日志。

如果要加大这个成功率，可以延长超时时间。
这个超时时间有2个，分别是:
- 1、FFmpeg等待超时时间(默认10 - 0.5秒)，配置项为hook.timeoutSec
- 2、播放器最大等待事件，默认5秒，配置项为general.maxStreamWaitMS
