### ISSUE TITLE
Centos7 make报错

### ISSUE THREAD

**Issue by Allenisme** [xiongziliang/ZLMediaKit#390]
`[ 87%] Linking CXX executable ../../../release/linux/Debug/api_tester_websocket
../../../release/linux/Debug/libmk_api.so: undefined reference to `X509_get0_pubkey'
../../../release/linux/Debug/libmk_api.so: undefined reference to `HMAC_CTX_reset'
../../../release/linux/Debug/libmk_api.so: undefined reference to `HMAC_CTX_free'
../../../release/linux/Debug/libmk_api.so: undefined reference to `OPENSSL_init_crypto'
../../../release/linux/Debug/libmk_api.so: undefined reference to `OPENSSL_init_ssl'
../../../release/linux/Debug/libmk_api.so: undefined reference to `TLS_server_method'
../../../release/linux/Debug/libmk_api.so: undefined reference to `TLS_client_method'
../../../release/linux/Debug/libmk_api.so: undefined reference to `SSL_is_init_finished'
../../../release/linux/Debug/libmk_api.so: undefined reference to `HMAC_CTX_new'
../../../release/linux/Debug/libmk_api.so: undefined reference to `EVP_PKEY_get0_RSA'
collect2: error: ld returned 1 exit status
make[2]: *** [../release/linux/Debug/api_tester_websocket] Error 1
make[1]: *** [api/tests/CMakeFiles/api_tester_websocket.dir/all] Error 2
make: *** [all] Error 2`

请问怎么解决？

**Comment by xiongziliang** [comment]
openssl链接失败，应该指定的ssl库路径不

**Comment by Allenisme** [comment]
谢谢，指定ssl库路径就可以了
