### ISSUE TITLE
on_stream_changed 事件触发后马上播放该视频流时，web 端播放不出来，需要等待几百毫秒

### ISSUE THREAD

**Issue by cakipaul** [xiongziliang/ZLMediaKit#391]
在 config.ini 配置 on_stream_changed 的触发接口：

```ini
#直播流注册或注销事件
on_stream_changed=http://127.0.0.1:8082/hook/zlm/on_stream_changed
```

在某视频设备向 ZLM 推流成功后，ZLM 会触发 hook 事件，向指定接口传入一个带着视频流信息的 json 数据，到此都是正常的。

问题出现在下一步：如果使 WEB 播放器在接收到视频流时，马上播放该 json 中指向的视频流，WEB 视频播放器会显示为黑屏，需要稍等几百毫秒后再次刷新才能播放。大致后端代码如下：

```java
	@ResponseBody
	@PostMapping(value = "/on_stream_changed", produces = "application/json;charset=UTF-8")
	public ResponseEntity<String> onStreamChanged(@RequestBody JSONObject json){

		BigInteger bigint=new BigInteger(json.getString("stream"), 16);
		int numb=bigint.intValue();
		String ssrc = String.format("%010d", numb);
		boolean regist = json.getBoolean("regist");
		if (regist) {
                        //此处获取等待该 ssrc 视频流的 session
			Session session = streamSession.getSession(ssrc);
			if (session != null) {
                                //根据 callId 指向等待该 ssrc 视频流的 session
				String callId = session.getCallId();
				RequestMessage msg = new RequestMessage();
				msg.setCallId(callId);
				//此处省略一些数据处理

				//等待 0.3s 再发送，防止手机推流等情况下 ZLM 尚未就绪，web 端播放不出来
				try {
					Thread.sleep(300);
				} catch(InterruptedException ex) {
					Thread.currentThread().interrupt();
				}
                                //此处实现异步回调响应
				resultHolder.invokeResult(msg);
			} 
		}
		//此处省略一些代码
	}
```

如果移除 `Thread.sleep(300);` 部分代码，则无法播放；添加后播放正常。

初步认为这可能是 hook 和播放就绪的次序出现问题，可能还没播放就绪，就触发hook了。测试发现，100ms 延时有时仍播放不出来，等待 300ms 就可以比较稳定地播放出来。

**Comment by xiongziliang** [comment]
视频注册后能立即播放成功的 因为这个是按需拉流的必要条件。
你看看chrome浏览器调试窗口有什么错误日志输出吗？粘贴出来

**Comment by cakipaul** [comment]
您好，如果不添加延时，播放出来的内容就是黑屏【并没有报错】：

![image](https://user-images.githubusercontent.com/20686421/86987723-49dc8f00-c1c9-11ea-99fb-29661b5f315b.png)

需要再次刷新一下，才能获取到正常视频流，ssrc 保持不变：

![image](https://user-images.githubusercontent.com/20686421/86987874-9d4edd00-c1c9-11ea-9a63-91ebe3daf1d0.png)

如果在后台代码添加少许延时，则不会出现开始的黑屏问题。

视频注册后应该能立即播放成功，实际上确实是黑屏，不知道是不是第一时间调用出现了bug？

使用火狐浏览器仍出现同样问题。不过火狐浏览器**出现报错**：

```js
Exception {
 name: "NS_ERROR_NOT_AVAILABLE", 
 message: "", 
 result: 2147746065,
 filename: "http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js",
 lineNumber: 1,
 columnNumber: 0,
 data: null,
 stack: "drawCanvas@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:541552\nimageCaptureByDom@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:541705\nimageCaptureByIdAndCanvasDom@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:541944\ncaptureFrame/<@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:539170\ncaptureFrame@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:539126\ncreateSnapshot@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:538775\nstart@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:538293\na.prototype.onClick@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:539509\nG/r.dispatcher@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:8042\ninitVideoJS/</<@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:1225177\nG/r.dispatcher@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:8042\nz@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:8832\ntrigger@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:34910\n@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:227007\nG/r.dispatcher@http://127.0.0.1:8080/iot-vmp-vmanage-web/static/video/liveplayer-element.min.js:1:8042\n" 
}
```

**Comment by swwheihei** [comment]
@cakipaul ZLM后台有报错吗？

**Comment by xiongziliang** [comment]
@cakipaul 你更新下ZLMediaKit最新代码试试

**Comment by xiongziliang** [comment]
这个问题不存在的，我刚测试过了，测试流程以下:

- 1、liveplayer开始播放ws://localhost/rtp/test.flv。
- 2、使用openRtpServer创建绑定9990端口以及流id为test的rtp服务。
- 3、使用FFmpeg推流rtp_mpegts
```bash
ffmpeg -re -i ~/git/ZLMediaKit/release/mac/Debug/www/record/robot.mp4 -vcodec h264 -acodec aac -f rtp_mpegts rtp://127.0.0.1:9990
```

- 4、推流成功，__defaultVhost_/rtp/test注册，liveplayer播放成功。

**Comment by xiongziliang** [comment]
在步骤4前是黑屏状态，因为还没有推流上来。

**Comment by xiongziliang** [comment]
黑屏就黑屏 你不要刷新 如果一直黑屏，在看播放器的报错

**Comment by cakipaul** [comment]
@xiongziliang 感谢，我更新 ZLM 重新编译后再次运行测试了一下，火狐浏览器**不再有**这个问题（可以马上播放出来了），但谷歌浏览器却**仍存在**进入播放界面后持续黑屏的问题：

![image](https://user-images.githubusercontent.com/20686421/87105054-72798d00-c28c-11ea-9ec7-432960ab8ce8.png)

>已经进入播放，可以暂停/播放，但是显示一直为黑屏，只能刷新页面重新播放才能正常显示

检查浏览器控制台没有输出异常，ZLM后台也没有异常（与火狐播放时输出相同）。不知道是不是谷歌浏览器问题……

**Comment by xiongziliang** [comment]
我也是chrome浏览器 没你说的问题啊

**Comment by xiongziliang** [comment]
一直黑屏没声音吗？一直黑屏最后不断开吗？

**Comment by cakipaul** [comment]
有可能是发送的流的问题，如果是接入网络摄像头（海康、大华等），立即播放也的确没出现黑屏。

我用的 [yasea](https://github.com/begeekmyfriend/yasea) 进行手机端的推流，看来需要再排查一下是不是这个手机推流软件的问题了…

**Comment by xiongziliang** [comment]
这个推流软件不产生metadata 这个好像不被flv.js支持。zlm会延后生成metadata，但是这个时间可能比较长。所以延后能播放成功



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: cakipaul <notifications@github.com&gt;
发送时间: 2020年7月11日 15:45
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] on_stream_changed 事件触发后马上播放该视频流时，web 端播放不出来，需要等待几百毫秒 (#391)





 
有可能是发送的流的问题，如果是接入网络摄像头（海康、大华等），立即播放也的确没出现黑屏。
 
我用的 yasea 进行手机端的推流，看来需要再排查一下是不是这个手机推流软件的问题了…

**Comment by cakipaul** [comment]
感谢解答，那么如果要解决这个问题，就有三种方式：

1. 先校验 metadata ，如果没有就生成 metadata ，然后在触发 on_stream_changed 事件；
2. 前端先确认获取的流的 metadata 合法性，再播放；
3. 在前端或者后端进行延时后再播放。

第三种方式不够优雅，第二种复杂了些吧，可能还需要改 flv.js 代码？几相比较，第一种方式更合理一些吧

**Comment by xiongziliang** [comment]
其实没有metadata并不是不能播放，大部分播放器播放不依赖metadata。
而且ZLMediaKit不能生成任意格式的metadata，你不能说ZLMediaKit不能生成这个metadata就不让人家播放器播放吧？

rtmp服务器一般情况下只负责纯粹转发rtmp即可，这样不管什么编码，ZLMediaKit都能转发（不用分析码流，不用管什么编码）。
ZLMediaKit只会在发现推流器没metadata时，才会去生成metadata，而且这个新生成的metadata也可能不包含不支持的编码(例如mp3),这样做的目的是为了提高播放器的兼容性。

但是ZLMediaKit给推流器擦屁股解决兼容性的问题，也是有代价的，这样做会引用一些副作用，目前的副作用是如果推流器推得流没metadata且编码不被ZLMediaKit支持，那么ZLMediaKit帮它生成的metadata就没这个Track的codec信息，可能会导致播放器认为这个Track不存在(然后实际上是有数据包的)。

如果再按照你说的做法，等metadata生成了再触发注册事件，那么这个注册事件可能永远都不会触发，因为ZLMediaKit有可能生成metadata失败，而且这个失败事件目前还不支持（也就是生成metadata失败时，这个流永远都不会被注册，永远不能被播放）。

况且，等metadata生成成功后再注册，这个时间可能太久了，也会影响用户体验，有点得不偿失，所以建议你选择一个好点的推流器，你说的这些问题其他服务器都会存在，我相信没有几个服务器体验能跟ZLMediaKit媲美的。

**Comment by cakipaul** [comment]
感谢详细解答！看来这个问题得在 yasea 下提，或者自己解决了 🤣
