### ISSUE TITLE
做视频双向对讲

### ISSUE THREAD

**Issue by dengchaowen-cx** [xiongziliang/ZLMediaKit#398]
大神您好：我看了#198 你是说可以做双向对讲，但是我没太理解里面讨论的，我的疑惑是mediaserver上rtp接收socket是否可以同时接收流和发送流，还是说收流和发流需要两个socket来处理。假设是A<--rtp-->zlmediakit<--->B, 上述是指A侧。同时推流和拉流需要一个socket通道还是两个socket通道。

**Comment by xiongziliang** [comment]
延时太高了 体验不好 建议你了解下webrtc

**Comment by dengchaowen-cx** [comment]
方便告知是什么原因导致延时太高吗 谢谢

**Comment by xiongziliang** [comment]
TCP协议抗网络抖动 抗丢包比较差，如果出现丢包或延时增大或乱序，会导致TCP的带宽剧烈下降，这样会在网络发送端积累大量的缓存，这样播放端只能无米下炊，只能干等，也就是加载中。

而网络情况好转之后，这些缓存数据也不能直接丢掉，而播放速度是恒定的，那么就会导致延时累积

**Comment by xiongziliang** [comment]
如果自己做发送端和播放器，并知道该不该丢包，该不该加快播放速度，TCP其实通常也能做到低延时的

**Comment by dengchaowen-cx** [comment]
您好 我现在是自己做终端 服务器和 web端，实现语音双向对讲。还是最开始的问题，在zl上面同一个socket可以同时收推端的音频和同时往推端发送音频流吗？ 谢谢

**Comment by xiongziliang** [comment]
你既然是TCP，那么就不存在同一个socket的说法

**Comment by dengchaowen-cx** [comment]
您好  那我换一个说法吧 我就建一个tcp通道就可以了吧  我的场景是接一个执法仪进去 在这同一个tcp通道内 我既要往zl推本地语音也要接收zl发送给执法仪的语音数据。谢谢

**Comment by xiongziliang** [comment]
当然可以啊 tcp是全双工的啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dengchaowen-cx <notifications@github.com&gt;
发送时间: 2020年7月9日 15:11
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 做视频双向对讲 (#398)





 
您好  那我换一个说法吧 我就建一个tcp通道就可以了吧  我的场景是接一个执法仪进去 在这同一个tcp通道内 我既要往zl推本地语音也要接收zl发送给执法仪的语音数据。谢谢

**Comment by dengchaowen-cx** [comment]
好的 谢谢您 耽误您宝贵的时间
