### ISSUE TITLE
Android app rtsp push stream

### ISSUE THREAD

**Issue by nokiovo79** [xiongziliang/ZLMediaKit#40]
Hi,
I have a problem with zl server when i push video with this app android https://github.com/pedroSG94/rtmp-rtsp-stream-client-java.
The server receive new connection when i start the streaming, but after connection of vlc/ffplay player on url rtsp, the server stop connection with app. The streaming is not present in “live” on http page.
What is the problem?

**Comment by xiongziliang** [comment]
Are you using `test_server` or `MediaServer`?

MediaServer will close connection between pusher  
when nobody played it(this can be closed by configuration file).

And rtsp server also will close connection between player 
when receive rtcp timeout (if your player on rtp over udp).

You can pusher a rtsp/rtmp stream to `test_server`,and then play it by `ffplay`.

Such as this:

```
ffplay rtsp://127.0.0.1/live/stream -rtsp_transport tcp
```

**Comment by nokiovo79** [comment]
I use test server. In debug i have analyze the flow from RTPReceiver to RTSP Session and the size of pkt is good. But don't have nothing in out for playing. Log error are not present and ffplay have a payload too short.

**Comment by xiongziliang** [comment]
What is the codec of the stream?

**Comment by nokiovo79** [comment]
H264

**Comment by nokiovo79** [comment]
Consider that the same app, publishing in rtmp works great with Zl. Can it be, the reference to the different RFC for RTSP?

**Comment by xiongziliang** [comment]
The bug is fixed now ,please pull the newest code.

**Comment by nokiovo79** [comment]
Thank you very much..... best regard....
