### ISSUE TITLE
RTSP 播放器断开: rtp over udp session timeouted

### ISSUE THREAD

**Issue by ikingye** [xiongziliang/ZLMediaKit#400]
GB28181 推送 RTP 到 ZLMediaKit，在本地调试是正常的，
把 ZLMediaKit 部署到 IDC 后，每次播放十几秒就断开，
可能原因是什么？

```
2020-07-08 10:17:57.627 W | onError 139950905618880(172.18.184.129:51398) RTSP播放器(__defaultVhost__/rtp/05F5E105)断开:rtp over udp session timeouted,耗时(s):15

2020-07-08 10:18:05.626 W | onError 139950906363344(172.18.184.129:51401) RTSP播放器(__defaultVhost__/rtp/05F5E105)断开:rtp over udp session timeouted,耗时(s):17

2020-07-08 10:20:55.640 W | onError 139950908025568(172.18.184.129:51711) RTSP播放器(__defaultVhost__/rtp/05F5E105)断开:rtp over udp session timeouted,耗时(s):15
```

**Comment by xiongziliang** [comment]
你服务器开放下UDP端口。

**Comment by xiongziliang** [comment]
超时时间也 设置长点
![image](https://user-images.githubusercontent.com/11495632/86909318-7dc49f80-c14a-11ea-9dc4-ebbe7ca8e2b0.png)

**Comment by xiongziliang** [comment]
这个issue先关了 有问题直接在此回复

**Comment by ikingye** [comment]
> 你服务器开放下 UDP 端口。

默认使用 RTSP 的 554 端口播放，是 TCP 吧。
这里开放 UDP 端口，是指什么的端口？

**Comment by xiongziliang** [comment]
所有的udp端口 给rtp用的 因为你用的udp方式播放rtsp的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: King Ye <notifications@github.com&gt;
发送时间: 2020年7月10日 11:13
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] RTSP 播放器断开: rtp over udp session timeouted (#400)





  
你服务器开放下 UDP 端口。
  
默认使用 RTSP 的 554 端口播放，是 TCP 吧。
 这里开放 UDP 端口，是指什么的端口？

**Comment by ikingye** [comment]
确实，使用 ffplay 指定 tcp 播放，是正常的
`ffplay -rtsp_transport tcp rtsp://10.xx.xx.xx:554/rtp/xxxx`

docker 部署的 zlm，开放所有 udp 端口，是使用 host network 才行吗

**Comment by xiongziliang** [comment]
udp用的随机端口，你全部打开吧，具体怎么设置docket我不知道，
建议你用TCP方式播放，udp基本很多问题。

**Comment by AkihisaDZX** [comment]
> GB28181 推送 RTP 到 ZLMediaKit，在本地调试是正常的，
> 把 ZLMediaKit 部署到 IDC 后，每次播放十几秒就断开，
> 可能原因是什么？
> 
> ```
> 2020-07-08 10:17:57.627 W | onError 139950905618880(172.18.184.129:51398) RTSP播放器(__defaultVhost__/rtp/05F5E105)断开:rtp over udp session timeouted,耗时(s):15
> 
> 2020-07-08 10:18:05.626 W | onError 139950906363344(172.18.184.129:51401) RTSP播放器(__defaultVhost__/rtp/05F5E105)断开:rtp over udp session timeouted,耗时(s):17
> 
> 2020-07-08 10:20:55.640 W | onError 139950908025568(172.18.184.129:51711) RTSP播放器(__defaultVhost__/rtp/05F5E105)断开:rtp over udp session timeouted,耗时(s):15
> ```

请问这个问题您解决了嘛，我最近使用docker启动zlm时也遇到了这个问题

**Comment by xiongziliang** [comment]
你用tcp方式播放 或者rtsp心跳超时时间设置长点



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: AkihisaDZX <notifications@github.com&gt;
发送时间: 2020年7月23日 16:17
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] RTSP 播放器断开: rtp over udp session timeouted (#400)

**Comment by AkihisaDZX** [comment]
心跳超时放到30秒，也是使用tcp方式播的，只是比心跳超时15秒时多播了一点点😂 下面分别是zlm和ffplay的日志↓

zlm：
```
ediaServer(6) /opt/media/ZLMediaKit/src/Rtp/RtpDecoder.cpp 48
2020-07-23 08:04:09.173 I | decodeRtp rtp type:96
MediaServer(6) /opt/media/ZLMediaKit/src/Rtp/RtpProcess.cpp 170
2020-07-23 08:04:09.173 I | onRtpDecode judged to be PS: 11E1A338
MediaServer(6) /opt/media/ZLMediaKit/src/Rtp/RtpProcess.cpp 214
2020-07-23 08:04:09.173 I | onDecode got video track: H264
MediaServer(6) /opt/media/ZLMediaKit/src/Common/MediaSource.cpp 296
2020-07-23 08:04:12.213 I | regist rtsp __defaultVhost__ rtp 11E1A338
MediaServer(6) /opt/media/ZLMediaKit/src/Common/MediaSource.cpp 296
2020-07-23 08:04:12.242 I | regist rtmp __defaultVhost__ rtp 11E1A338
MediaServer(6) /opt/media/ZLMediaKit/src/Common/MediaSource.cpp 296
2020-07-23 08:04:15.400 I | regist hls __defaultVhost__ rtp 11E1A338
MediaServer(6) /opt/media/ZLMediaKit/src/Rtsp/RtspSession.cpp 60
2020-07-23 08:04:17.069 D | RtspSession 140557570430368(10.0.16.67:7932) 
MediaServer(6) /opt/media/ZLMediaKit/src/Rtsp/RtspSession.cpp 353
2020-07-23 08:04:17.081 T | onAuthSuccess 140557570430368(10.0.16.67:7932) 
MediaServer(6) /opt/media/ZLMediaKit/src/Rtp/RtpProcess.cpp 145
2020-07-23 08:05:11.221 W | onRtpSorted 0 != 65535+1
MediaServer(6) /opt/media/ZLMediaKit/src/Rtsp/RtspSession.cpp 74
2020-07-23 08:05:24.670 W | onError 140557570430368(10.0.16.67:7932) RTSP播放器(__defaultVhost__/rtp/11E1A338)断开:Socket send timeout,耗时(s):67
MediaServer(6) /opt/media/ZLMediaKit/src/Rtsp/RtspSession.cpp 68
2020-07-23 08:05:24.671 D | ~RtspSession 140557570430368(10.0.16.67:7932) 
MediaServer(6) /opt/media/ZLMediaKit/src/Http/HttpSession.cpp 30
2020-07-23 08:05:24.671 T | HttpSession 140557770822480(127.0.0.1:42499) 
MediaServer(6) /opt/media/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp 171
2020-07-23 08:05:24.680 D | findCertificate can not find any certificate of host:default host
```
ffplay
  ```
Metadata:
    title           : Streamed by ZLMediaKit-5.0(build in Apr  6 2020 15:11:02)
  Duration: N/A, start: 6.560000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn, 50 tbc
[swscaler @ 00000267534e97c0] deprecated pixel format used, make sure you did set range correctly
[h264 @ 00000267521be500] error while decoding MB 88 43, bytestream -9
[h264 @ 00000267521be500] concealing 2961 DC, 2961 AC, 2961 MV errors in P frame
 411.38 M-V:-40.456 fd=  29 aq=    0KB vq=    0KB sq=    0B f=1/1

```

**Comment by GamerLee6** [comment]
我在使用的过程中遇到了如下的问题，使用ffpmeg，在rtsp协议下通过udp进行推流时，ZLMediakit能够接收到rtspsession的请求，但是并没有进行对应的媒体注册，导致到达keepAliveSecond后推流终端ffmpeg报错broken pipe。在到达keepAliveSecond之前查看服务器端口，在udp端口建立了对应的连接。ffmpeg推流命令中加入rtsp_transport tcp后媒体成功注册。想询问一下可能的原因。

**Comment by xia-chu** [comment]
udp端口不通的问题

**Comment by GamerLee6** [comment]
感谢提醒，使用了port_range配置，并且针对udp端口进行了抓包，在keepAliveSecond前能够在zlm分配的端口捕获到udp报文，但是依然没有媒体注册的log显示，问题依然存在。

**Comment by xia-chu** [comment]
我认为zlm压根就没收到udp推流

**Comment by GamerLee6** [comment]
最近粗略看了一下代码，RtspSession.cpp文件中714行和721行中会将绑定推流端的rtp与rtcp的udp端口，请问绑定端口的意义是什么？测试中发现，服务器接收端口收到的数据包需要是以上两个绑定端口发出的udp数据包才能够被zlm接收。在阿里云服务器中会因为发送端口不对应导致zlm无法收到udp推流。

**Comment by xia-chu** [comment]
@GamerLee6 如果zlm在nat内，zlm需要发udp数据给播放器用于打洞，这样播放器才能发数据给zlm

**Comment by xia-chu** [comment]
设置客户端地址后 这样发送udp数据包时 直接调用send即可 而不用调用sendto了
