### ISSUE TITLE
请问怎么获取一路流对应所有palyer列表

### ISSUE THREAD

**Issue by 648540858** [xiongziliang/ZLMediaKit#401]
我查看RESTful 接口和Web Hook 接口，似乎只有再on_play的hook接口中进行统计，但是遇到不知道播放鉴权的播放器就不能用on_play了，会导致播放端播放失败；另外流量统计似乎也可以用来实现这个统计，但是不够实时。
所以想了解下还有什么其他方式获取到Player列表。

**Comment by xiongziliang** [comment]
目前没有的 也就是目前知道有多少人正在播放这个流，但是没法知道都是谁

**Comment by xiongziliang** [comment]
web hook,能知道，谁开始播放这个流了，但是结束播放没单独的事件。
只有结束播放时的流量汇报功能，不过要超过阈值才能触发这个事件，默认1024KB

**Comment by 648540858** [comment]
这个考虑加一下吗，

**Comment by chatop2020** [comment]
on_play,on_stop，如果没有技术难度还是需要加一下的。

**Comment by xiongziliang** [comment]
你把触发on_flow_report事件触发阈值改成0，就是播放(推流)停止事件了。

**Comment by 648540858** [comment]
> 你把触发on_flow_report事件触发阈值改成0，就是播放(推流)停止事件了。

确实这样设置可以马上收到播放/推流的停止，那我应该如何获取播放的开始呢

**Comment by xiongziliang** [comment]
on_play你可以认为就是播放的开始，而且on_flow_report也会 统计流量和耗时。

**Comment by 648540858** [comment]
on_play必须是支持鉴权的播放器才可以使用，现在没有一种更通用的办法。因为有的播放器在收到401后就直接播放失败了，而不是等待。

**Comment by xiongziliang** [comment]
on_play鉴权期间 客户端是没感知的 不会回401啊&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 648540858 <notifications@github.com&gt;
发送时间: 2020年7月12日 08:43
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 请问怎么获取一路流对应所有palyer列表 (#401)





 
on_play必须是支持鉴权的播放器才可以使用，现在没有一种更通用的办法。因为有的播放器在收到401后就直接播放失败了，而不是等待。

**Comment by xiongziliang** [comment]
issue 先关闭了 有问题你直接在此回复

**Comment by 648540858** [comment]
我使用vlc播放会提示需要输入用户名密码，
使用ffplay会直接报401错误而导致无法播放，
可以收到on_play事件，也回复了
```
{
   "code" : 0,
   "msg" : "success"
}
```
但是没有什么效果
抓包看到
```
OPTIONS rtsp://192.168.1.141:30554/1000/111111 RTSP/1.0
CSeq: 1
User-Agent: Lavf57.83.100

RTSP/1.0 200 OK
CSeq: 1
Date: Mon, Jul 13 2020 01:14:27 GMT
Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, ANNOUNCE, RECORD, SET_PARAMETER, GET_PARAMETER
Server: ZLMediaKit-5.0(build in Jul  3 2020 13:04:18)

DESCRIBE rtsp://192.168.1.141:30554/1000/111111 RTSP/1.0
Accept: application/sdp
CSeq: 2
User-Agent: Lavf57.83.100

RTSP/1.0 401 Unauthorized
Content-Length: 26
Content-Type: text/plain
CSeq: 2
Date: Mon, Jul 13 2020 01:14:27 GMT
Server: ZLMediaKit-5.0(build in Jul  3 2020 13:04:18)
```
最后确实是回复了401的

**Comment by xiongziliang** [comment]
你开的不是on_play鉴权 而是rtsp鉴权。

开启rtsp鉴权后，on_play鉴权会被忽略。

**Comment by xiongziliang** [comment]
请参考这个 #405

**Comment by 648540858** [comment]
rtsp的鉴权我是置空的，只开启了on_play
```
[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
enable=1
on_flow_report=http://192.168.1.20:10880/index/hook/on_flow_report
on_http_access=
on_play=http://192.168.1.20:10880/index/hook/on_play
on_publish=
on_record_mp4=http://192.168.1.20:10880/index/hook/on_record_mp4
on_rtsp_auth=
on_rtsp_realm=
on_server_started=http://192.168.1.20:10880/index/hook/on_server_started
on_shell_login=http://192.168.1.20:10880/index/hook/on_shell_login
on_stream_changed=http://192.168.1.20:10880/index/hook/on_stream_changed
on_stream_none_reader=http://192.168.1.20:10880/index/hook/on_stream_none_reader
on_stream_not_found=http://192.168.1.20:10880/index/hook/on_stream_not_found
timeoutSec=10
```
是不是还需要配置哪里

**Comment by jiechengyang** [comment]
@648540858 请问兄弟 现在解决了吗这个问题
