### ISSUE TITLE
rtsp 拉流录制不同步

### ISSUE THREAD

**Issue by Luosh** [xiongziliang/ZLMediaKit#403]
1. 用rtsp 拉流 h264(High) , 存在B帧的情况, dts会有乱序情况, 导致录像不同步. 
2. 对rtp时间戳的概念我有点模糊,  我的理解是, 这个时间戳是按 编码时间打的对应的是dts. 代码里是当pts处理, 然后重新计算dts.不知道我的理解是不是错的
3. 大佬有没有考虑下 rtsp 拉流支持下 ts流格式(MP2T)?

万分感谢

**Comment by xiongziliang** [comment]
> 1.用rtsp 拉流 h264(High) , 存在B帧的情况, dts会有乱序情况, 导致录像不同步.

rtsp里面的rtp传的pts，不是dts，你按接收顺序解码，解码后yuv按pts排序渲染。

> 3.大佬有没有考虑下 rtsp 拉流支持下 ts流格式(MP2T)?

目前没这个需求，所以不考虑

**Comment by Luosh** [comment]
> > 1.用rtsp 拉流 h264(High) , 存在B帧的情况, dts会有乱序情况, 导致录像不同步.
> 
> rtsp里面的rtp传的pts，不是dts，你按接收顺序解码，解码后yuv按pts排序渲染。
> 
> > 3.大佬有没有考虑下 rtsp 拉流支持下 ts流格式(MP2T)?
> 
> 目前没这个需求，所以不考虑

感谢~
问题原因找到, 有些终端的rtp时间戳不太规范, 导致通过除以 sample_rate 转换后的毫秒数可能与上一帧的一样. 写入MP4的时间戳不递增,造成不同步.

RtpReceiver.cpp

```C++ 
//时间戳转换成毫秒
    rtp.timeStamp = rtp.timeStamp * 1000LL / samplerate;
```
可以在rtpdecode之后 简单判断处理下.

AACRtp.cpp
```C++
      //追加aac数据
        _frame->_buffer.append((char *) ptr, size);
        _frame->_dts = rtppack->timeStamp;
        //add by luosh 确保时间戳递增, 否则可能或导致音频不同步
        if (_last_ts == _frame->_dts) {
            _frame->_dts++;
        } 
        _last_ts = _frame->_dts;

```
仅供参考
