### ISSUE TITLE
关于rtsp认证的疑问

### ISSUE THREAD

**Issue by lyg1949** [xiongziliang/ZLMediaKit#405]
在回调on_mk_rtsp_auth中只能获取到用户的用户名，客户端传过来的密码或者加过密的密码要怎么获取呢？

还有must_no_encrypt这个参数是在那边设置的呢？

谢谢！

**Comment by lyg1949** [comment]
must_no_encrypt这个知道在哪配置了，是在配置文件里面
`
[rtsp]
authBasic=1
`

**Comment by lyg1949** [comment]
on_mk_media_play中也可以进行认证，那么这个认证和on_mk_rtsp_auth之间是什么关系呢？是不是择一使用？

谢谢！

**Comment by xiongziliang** [comment]
on_mk_media_play是url参数鉴权，这个是通用的，支持所有播放协议。
on_mk_rtsp_auth是rtsp专有鉴权，不通用

**Comment by lyg1949** [comment]
多谢回答！
那on_mk_rtsp_auth中如何获取到客户端传过来的密码或者加密的密码呢？




------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年7月10日 11:00
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: lyg1949 <zh.ghlong@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 关于rtsp认证的疑问 (#405)

**Comment by xiongziliang** [comment]
不能 客户端只是把密码的md5签名传过来了，所以没法知道密码。


你只能把密码传给zlmediakit，zlm会把你的密码生成签名，然后比对签名是否一致



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lyg1949 <notifications@github.com&gt;
发送时间: 2020年7月10日 11:20
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 关于rtsp认证的疑问 (#405)





 多谢回答！ 
 那on_mk_rtsp_auth中如何获取到客户端传过来的密码或者加密的密码呢？ 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 夏楚 <notifications@github.com&amp;gt; 
 发送时间: 2020年7月10日 11:00 
 收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&amp;gt; 
 抄送: lyg1949 <zh.ghlong@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[xiongziliang/ZLMediaKit] 关于rtsp认证的疑问 (#405)

**Comment by lyg1949** [comment]
那怎么能够获得客户端发过来的密码md5签名呢？谢谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年7月10日 11:25
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: lyg1949 <zh.ghlong@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 关于rtsp认证的疑问 (#405)





不能 客户端只是把密码的md5签名传过来了，所以没法知道密码。


你只能把密码传给zlmediakit，zlm会把你的密码生成签名，然后比对签名是否一致



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lyg1949 <notifications@github.com&amp;gt;
发送时间: 2020年7月10日 11:20
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&amp;gt;
抄送: 夏楚 <771730766@qq.com&amp;gt;, Comment <comment@noreply.github.com&amp;gt;
主题: 回复：[xiongziliang/ZLMediaKit] 关于rtsp认证的疑问 (#405)





 多谢回答！ 
 那on_mk_rtsp_auth中如何获取到客户端传过来的密码或者加密的密码呢？ 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 夏楚 <notifications@github.com&amp;amp;gt; 
 发送时间: 2020年7月10日 11:00 
 收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&amp;amp;gt; 
 抄送: lyg1949 <zh.ghlong@qq.com&amp;amp;gt;, Author <author@noreply.github.com&amp;amp;gt; 
 主题: 回复：[xiongziliang/ZLMediaKit] 关于rtsp认证的疑问 (#405)

**Comment by lyg1949** [comment]
我了解了，实际上客户端传过来的密码的md5签名zlmediakit有了，需要我传真正的密码给zlmediakit，由zlmediakit做验证，对吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年7月10日 11:25
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: lyg1949 <zh.ghlong@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 关于rtsp认证的疑问 (#405)





不能 客户端只是把密码的md5签名传过来了，所以没法知道密码。


你只能把密码传给zlmediakit，zlm会把你的密码生成签名，然后比对签名是否一致



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lyg1949 <notifications@github.com&amp;gt;
发送时间: 2020年7月10日 11:20
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&amp;gt;
抄送: 夏楚 <771730766@qq.com&amp;gt;, Comment <comment@noreply.github.com&amp;gt;
主题: 回复：[xiongziliang/ZLMediaKit] 关于rtsp认证的疑问 (#405)





 多谢回答！ 
 那on_mk_rtsp_auth中如何获取到客户端传过来的密码或者加密的密码呢？ 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 夏楚 <notifications@github.com&amp;amp;gt; 
 发送时间: 2020年7月10日 11:00 
 收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&amp;amp;gt; 
 抄送: lyg1949 <zh.ghlong@qq.com&amp;amp;gt;, Author <author@noreply.github.com&amp;amp;gt; 
 主题: 回复：[xiongziliang/ZLMediaKit] 关于rtsp认证的疑问 (#405)

**Comment by xiongziliang** [comment]
对，用户名密码签名需要依赖其他好几个参数，这个算法比较复杂，不合适把这些东西hook给开发者去生成签名，所以ZLMediaKit设计的是用户提供密码，让ZLMediaKit生成签名并比对是否一致。

RTSP这种鉴权其实也考虑了明文密码传递给媒体服务器不安全的问题，所以设置了realm机制，也就是你只要提供md5(username:realm:password)即可。如果你在on_rtsp_realm hook中提供随机的realm，在on_rtsp_auth hook中提供md5(username:realm:password)，那么就能做到不泄露你业务系统中的明文密码。

**Comment by xiongziliang** [comment]
rtsp专属鉴权支持md5和base64两种，base64就必须提供明文密码以便比对了。所以hook中才会有must_no_encrypt这个参数，
也就是base64方式鉴权必须你提供明文密码，而md5方式你可以提供明文password或md5(username:realm:password)。

**Comment by xiongziliang** [comment]
这是md5签名生成方式
```c++
 /*
        response计算方法如下：
        RTSP客户端应该使用username + password并计算response如下:
        (1)当password为MD5编码,则
            response = md5( password:nonce:md5(public_method:url)  );
        (2)当password为ANSI字符串,则
            response= md5( md5(username:realm:password):nonce:md5(public_method:url) );
         */
```

**Comment by lyg1949** [comment]
多谢解答！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏楚 <notifications@github.com&gt;
发送时间: 2020年7月11日 22:10
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: lyg1949 <zh.ghlong@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 关于rtsp认证的疑问 (#405)






rtsp专属鉴权支持md5和base64两种，base64就必须提供明文密码以便比对了。所以hook中才会有must_no_encrypt这个参数，
也就是base64方式鉴权必须你提供明文密码，而md5方式你可以提供明文password或md5(username:realm:password)。
