### ISSUE TITLE
最新的代码中getSsrcInfo接口报404

### ISSUE THREAD

**Issue by JonathanHsia** [xiongziliang/ZLMediaKit#408]
![image](https://user-images.githubusercontent.com/10798612/87221502-10f61300-c39f-11ea-8331-0c6db22e3361.png)

**Comment by xiongziliang** [comment]
用法和名称发生了变更 还没更新wiki 你可以先对照下源码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JonathanHsia <notifications@github.com&gt;
发送时间: 2020年7月11日 17:51
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 最新的代码中getSsrcInfo接口报404 (#408)

**Comment by xiongziliang** [comment]
```c++
api_regist1("/index/api/getRtpInfo",[](API_ARGS1){
        CHECK_SECRET();
        CHECK_ARGS("stream_id");

        auto process = RtpSelector::Instance().getProcess(allArgs["stream_id"], false);
        if (!process) {
            val["exist"] = false;
            return;
        }
        val["exist"] = true;
        val["peer_ip"] = process->get_peer_ip();
        val["peer_port"] = process->get_peer_port();
        val["local_port"] = process->get_local_port();
        val["local_ip"] = process->get_local_ip();
    });
```

**Comment by xiongziliang** [comment]
更新wiki了 你看下
