### ISSUE TITLE
设置 SO_LINGER 失败!

### ISSUE THREAD

**Issue by liping17** [xiongziliang/ZLMediaKit#409]
启动正常，但中间有错误信息
2020-07-13 15:57:24.641 I | toolkit::TcpServer::start_l TCP Server listening on 0.0.0.0:9000
MediaServer.exe(13988) Z:\git\ZLMediaKit\3rdpart\ZLToolKit\src\Network\sockutil.cpp 70
**2020-07-13 15:57:24.641 T | toolkit::SockUtil::setCloseWait 设置 SO_LINGER 失败!**
MediaServer.exe(13988) Z:\git\ZLMediaKit\3rdpart\ZLToolKit\src\Network/TcpServer.h 304

**Comment by xiongziliang** [comment]
没关系 不影响
