### ISSUE TITLE
RTMP支持H265并且能够录播吗?

### ISSUE THREAD

**Issue by weller0** [xiongziliang/ZLMediaKit#41]
rtmp官方并不支持h265编码,但是h265带宽上占了很大优势,想问一下需要如何在ZLMediaKit上支持rtmp h265,并录播

**Comment by xiongziliang** [comment]
rtmp可以直接录制成flv,所以如果rtmp支持265，那么录制没什么问题，
但是由于目前Adobe官方不支持265，预计将来也不会支持，
所以目前国内对265的支持还得不到全球的认可，包括vlc、FFmpeg都不支持rtmp 265。

ZLMediaKit目前也不支持rtmp 265，原因主要是上述所说，就算服务器支持rtmp 265,
也意义不大，因为那样只能自己实现包括推流器、服务器、播放器等全链路软件。

ZLMediaKit目前仅rtsp、hls支持rtmp，由于精力也有限，所以近期并不打算支持比较鸡肋的rtmp 265支持
