### ISSUE TITLE
关于SEI包在传入track时直接被抛弃

### ISSUE THREAD

**Issue by baiyfcu** [xiongziliang/ZLMediaKit#411]
`            case H264Frame::NAL_SEI:{
                //忽略SEI,暂加上
                VideoTrack::inputFrame(frame);
                break;
            }
`
好像记得SEI包抛弃是因为转协议时有些不支持才抛弃的，建议在track接收SEI包，转协议时根据各协议情况再决定是否抛

**Comment by xiongziliang** [comment]
除了rtsp,其他(hls/mp4/rtmp)都忽略了SEI

**Comment by xiongziliang** [comment]
除了rtsp,其他(hls/mp4/rtmp)都忽略了SEI
