### ISSUE TITLE
rtsp/rtmp录像文件点播有问题

### ISSUE THREAD

**Issue by lyg1949** [xiongziliang/ZLMediaKit#412]
1.rtmp回放时报错：`createFromMP4 | 打开文件失败`，原因是给文件的后缀名多加了`.mp4`。

如果把rtmp地址中最后的`.mp4`去掉，就不会被加上`.mp4`，从而导致`createFromMP4 | 打开文件失败`。

2.rtsp回放时没有这个错误，但是在seek时或者长时间没有数据过来导致超时，或者返回的不是正确时间的视频数据（播放器上时间的位置不对），但log上看服务端seek到正确的时间了。

**Comment by lyg1949** [comment]
还有一个问题，用vlc回放rtsp（h265编码的mp4文件）时`MediaSink.cpp:128 emitAllTrackReady | track not ready for a long time, ignored: CodecH265`，导致无法播放。vlc单独播放该mp4文件是没有问题的。

**Comment by lyg1949** [comment]
rtsp或者rtmp点播录像文件的思路还是类似与直播一样，当找不到stream时就从mp4文件创建一个，但是当存在多个用户同时点播时就出现问题了（因为他们看的是同一个stream），他们之间会相互干扰（比如进度等）

**Comment by xiongziliang** [comment]
> rtsp或者rtmp点播录像文件的思路还是类似与直播一样，当找不到stream时就从mp4文件创建一个，但是当存在多个用户同时点 > 播时就出现问题了（因为他们看的是同一个stream），他们之间会相互干扰（比如进度等）

是的 rtsp rtmp是共享点播，大家看的是同一个MediaSource，seek时是会互相干扰。这样做的目的是因为这样做可以提高性能，要是每个人看次点播都加载下文件，服务器扛不住的。当然也不是不能这么改(已经有人改成独立点播了)，但是我觉得那样做意义不大，用rtsp/rtmp点播一般是那种嵌入式设备，互联网应用场景不会存在这种需求，互联网建议用http点播。

**Comment by xiongziliang** [comment]
先关闭了 有其他问题请 在此直接回复
