### ISSUE TITLE
咨询下制作一个播放源所需要的步骤

### ISSUE THREAD

**Issue by dravvern** [xiongziliang/ZLMediaKit#42]
目的是想通过这个来扩展支持接收GB28181协议中IPC的推流，然后对外提供rtsp播放源，看了里面是通过 MultiMediaSourceMuxer来进行制作， 都是通过 addTrack来添加音视频数据，但是怎么把IPC推过来的RTP转换成 这个音视频数据呢？ 
不知道我理解有没问题， 或者有没其他思路？谢谢

**Comment by xiongziliang** [comment]
如果你只是要转换成rtsp流，那么相对来说就简单多了。
rtsp流只需要两个元素，一个是sdp，另外就是rtp流。
你可以查看RtspMediaSource的源码，输入sdp和rtp后就能注册为rtsp流了。
