### ISSUE TITLE
时好时坏的传输

### ISSUE THREAD

**Issue by zsinba** [xiongziliang/ZLMediaKit#421]
ZL，你好。
我在Ubuntu 16.04 上面编译，并部署了ZLMediakit，但是他时好时坏的。 这并不是一台服务器这样，我尝试了四台不同的服务器，（它们都是Ubuntu），都是同样的表现。
我是想通过rtmp进入，rtsp播放。
刚开始推的时候，他是好的，过一会，有两个流同时播放的时候（使用rtsp，vlc播放），他就不好了。
流都没有了。
而且当有若干个（不超过10个流）的时候，他的情况变的更糟糕。

请问是我用的不对吗？
我只是编译，然后运行，没有做过修改和调试。

难道是编译出来的是Debug的原因？
是我的服务器配置和带宽问题？ 我想不是，因为这个服务器配置和带宽是相当棒的。

祝一切顺利，静候

**Comment by xiongziliang** [comment]
你说的话怎么有点像机翻？ 😂

播放不了你应该告诉我播放器的日志或ZLMediaKit的日志，否则我没法回答你

**Comment by xiongziliang** [comment]
？？？？？？
没有答复我先关闭了

**Comment by zsinba** [comment]
谢谢，关闭吧。
