### ISSUE TITLE
对接 H265的设备 ，后台一直打印日志

### ISSUE THREAD

**Issue by CatchWish** [xiongziliang/ZLMediaKit#422]
H264 的设备推流可以正常播放，使用H265时会播放异常

打印日志是：

![image](https://user-images.githubusercontent.com/20606372/87849194-2a580b80-c919-11ea-94f0-0ef7dce61532.png)

ps:本人是小白，如果是很低级的问题，大佬不要见怪

**Comment by xiongziliang** [comment]
是不是flv播放器一直播放重试？请把音频设置为aac



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CatchWish <notifications@github.com&gt;
发送时间: 2020年7月18日 17:08
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 对接 H265的设备 ，后台一直打印日志 (#422)





 
H264 的设备推流可以正常播放，使用H265时会播放异常
 
打印日志是：
 

 
ps:本人是小白，如果是很低级的问题，大佬不要见怪

**Comment by xiongziliang** [comment]
不对 flv播放器不支持265



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CatchWish <notifications@github.com&gt;
发送时间: 2020年7月18日 17:08
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 对接 H265的设备 ，后台一直打印日志 (#422)





 
H264 的设备推流可以正常播放，使用H265时会播放异常
 
打印日志是：
 

 
ps:本人是小白，如果是很低级的问题，大佬不要见怪

**Comment by CatchWish** [comment]
用的是H5的播放器

**Comment by xiongziliang** [comment]
那就不支持265



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CatchWish <notifications@github.com&gt;
发送时间: 2020年7月18日 17:34
收件人: xiongziliang/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xiongziliang/ZLMediaKit] 对接 H265的设备 ，后台一直打印日志 (#422)





 
用的是H5的播放器

**Comment by CatchWish** [comment]
好的，知道了，多谢
