### ISSUE TITLE
ffplay播放rtsp流，报错：Too short data for FU-A H.264 RTP packet

### ISSUE THREAD

**Issue by v354412101** [xiongziliang/ZLMediaKit#424]
![fu-a](https://user-images.githubusercontent.com/9720127/87868549-73679880-c9c9-11ea-8530-757d9b4e58d8.png)

**Comment by xiongziliang** [comment]
合并了 谢谢！

**Comment by atv2016** [comment]
@xia-chu what caused this 'too short data RTP' error ?

**Comment by xia-chu** [comment]
> @xia-chu what caused this 'too short data RTP' error ?

This bug should had been fixed
