### ISSUE TITLE
HttpRequester和httpSrv嵌套的疑问

### ISSUE THREAD

**Issue by suisou** [xiongziliang/ZLMediaKit#426]
我参照test_httpclient和test_httpapi想写一个自己的业务服务程序。
需求如下：
第三方访问我的httpSrv服务程序，服务程序去访问MediaServer  APi 和接收其HOOK实现控制。
程序结构如下：
在httpsrv的Listener函数中处理第三方的访问，根据规则，构造链接参数，使用HttpRequester的GET方式访问MediaServer，
现在的故障在MediaServer的LOG是
```bash
2020-07-19 20:14:21.313 W MediaServer[26054] HttpSession.cpp:120 onError | 18446744072462798196(127.0.0.1:40313) session timeouted
在我的业务程序LOG是
[34m2020-07-19 20:26:26.716 T LiveSrvCtrl[26997] HttpSession.cpp:30 HttpSession | 18446744072381008452(58.220.112.189:54054) [0m
[34m2020-07-19 20:26:26.716 T LiveSrvCtrl[26997] HttpSession.cpp:30 HttpSession | 18446744072412465748(58.220.112.189:54055) [0m
[33m2020-07-19 20:26:26.718 W LiveSrvCtrl[26997] SSLUtil.cpp:98 loadPublicKey | error:02001002:system library:fopen:No such file or directory[0m
[33m2020-07-19 20:26:26.718 W LiveSrvCtrl[26997] SSLUtil.cpp:126 loadPrivateKey | error:2006D080:BIO routines:BIO_new_file:no such file[0m
[33m2020-07-19 20:26:26.718 W LiveSrvCtrl[26997] SSLUtil.cpp:98 loadPublicKey | error:02001002:system library:fopen:No such file or directory[0m
[33m2020-07-19 20:26:29.180 W LiveSrvCtrl[26997] util.cpp:324 operator() | Stamp expired is not abnormal:2437133[0m
[33m2020-07-19 20:26:44.823 W LiveSrvCtrl[26997] HttpSession.cpp:120 onError | 18446744072412465748(58.220.112.189:54055) session timeouted[0m
[34m2020-07-19 20:26:44.823 T LiveSrvCtrl[26997] HttpSession.cpp:38 ~HttpSession | 18446744072412465748(58.220.112.189:54055) [0m
```
我发现在HttpRequester使用时需要一个static semaphore sem.     会不会问题出在这上面？是不是内部信号量死锁了？

**Comment by suisou** [comment]
用test_httpclient和Wget访问MEdiaServer,   相同的链接   WGET就能成功，
test_httpclient访问时Medaiserver的日志：
# args:
app : proxy
enable_hls : 1
enable_mp4 : 1
enable_rtmp : 1
enable_rtsp : 1
stream : 1
url : rtsp://admin:admin@192.168.0.109
vhost : __defaultVhost__
# response:
{
   "code" : -1,
   "msg" : "play rtsp timeout"
}
wget访问时Medaiserver的日志：
# args:
app : proxy
enable_hls : 1
enable_mp4 : 1
enable_rtmp : 1
enable_rtsp : 1
stream : 1
url : rtsp://admin:admin@192.168.0.109
vhost : __defaultVhost__
# response:
{
   "code" : 0,
   "data" : {
      "key" : "__defaultVhost__/proxy/1"
   }
}

**Comment by urmyfaith** [comment]
HttpRequester 使用的时候，并不需要 semaphore，只需要保证HttpRequester在回调函数调用前不被释放就可以了。

1）可以保存为属性。
2）可以加信号量阻塞（例子就是增加信号量，保持了HttpRequester不被释放。）
3）可以在callback中引用自己，就会在调用callback后自动释放。

**Comment by suisou** [comment]
我的现在加信号量阻塞，MediaServer和httprequestor都报Timeout，是不是发生了死锁了。

**Comment by urmyfaith** [comment]
贴下一示意代码。

信号量会阻塞当前线程。,添加信号量后需要在callbcack完成后 post。

**Comment by suisou** [comment]
int HttpGet(string url,mediakit::HttpRequester::HttpRequesterResult onResult)
{
    static semaphore sem;
    signal(SIGINT, [](int) { sem.post(); });// 设置退出信号
    Logger::Instance().add(std::make_shared<ConsoleChannel>());
    Logger::Instance().setWriter(std::make_shared<AsyncLogWriter>());

    //加载证书，证书包含公钥和私钥
    SSL_Initor::Instance().loadCertificate((exeDir() + "ssl.p12").data());
    //信任某个自签名证书
    SSL_Initor::Instance().trustCertificate((exeDir() + "ssl.p12").data());
    //不忽略无效证书证书(例如自签名或过期证书)
    SSL_Initor::Instance().ignoreInvalidCertificate(false);

    ///////////////////////////////http get///////////////////////
//创建一个Http请求器
    HttpRequester::Ptr requesterGet(new HttpRequester());
    //使用GET方式请求
    requesterGet->setMethod("GET");
    //设置http请求头，我们假设设置cookie，当然你也可以设置其他http头
    //requesterGet->addHeader("Cookie", "SESSIONID=e1aa89b3-f79f-4ac6-8ae2-0cea9ae8e2d7");
    //开启请求，该api会返回当前主机外网ip等信息
    requesterGet->startRequester(url,//url地址
        [](const SockException& ex,                                 //网络相关的失败信息，如果为空就代表成功
            const string& status,                                    //http回复的状态码，比如说200/404
            const HttpClient::HttpHeader& header,                    //http回复头
            const string& strRecvBody) {                              //http回复body
                DebugL << "=====================HttpRequester GET===========================";
                if (ex) {
                    //网络相关的错误
                    WarnL << "network err:" << ex.getErrCode() << " " << ex.what();
                }
                else {
                    //打印http回复信息
                    _StrPrinter printer;
                    for (auto& pr : header) {
                        printer << pr.first << ":" << pr.second << "\r\n";
                    }
                    InfoL << "status:" << status << "\r\n"
                        << "header:\r\n" << (printer << endl)
                        << "\r\nbody:" << strRecvBody;
                }
                sem.post();
        },0

    );
   sem.wait();
    return 0;
}

**Comment by suisou** [comment]
namespace mediakit {
	////////////HTTP配置///////////
	namespace Http {
#define HTTP_FIELD "http."
#define HTTP_PORT 80
		const char kPort[] = HTTP_FIELD"port";
#define HTTPS_PORT 443
		extern const char kSSLPort[] = HTTP_FIELD"sslport";
		onceToken token1([]() {
			mINI::Instance()[kPort] = HTTP_PORT;
			mINI::Instance()[kSSLPort] = HTTPS_PORT;
			}, nullptr);
	}//namespace Http
}  // namespace mediakit




void Listener(BroadcastHttpRequestArgs) {

	//const Parser &parser,HttpSession::HttpResponseInvoker &invoker,bool &consumed
	if (strstr(parser.Url().data(), URLPREFIX) != parser.Url().data()) {
		return;
	}
	//url以"/api/起始，说明是http api"
	consumed = true;//该http请求已被消费

	_StrPrinter printer;
	////////////////method////////////////////
	printer << "\r\nmethod:\r\n\t" << parser.Method();
	////////////////url/////////////////
	printer << "\r\nurl:\r\n\t" << parser.Url();
	////////////////protocol/////////////////
	printer << "\r\nprotocol:\r\n\t" << parser.Tail();
	///////////////args//////////////////
	printer << "\r\nargs:\r\n";
	for (auto& pr : parser.getUrlArgs()) {
		printer << "\t" << pr.first << " : " << pr.second << "\r\n";
	}
	///////////////header//////////////////
	printer << "\r\nheader:\r\n";
	for (auto& pr : parser.getHeader()) {
		printer << "\t" << pr.first << " : " << pr.second << "\r\n";
	}
	////////////////content/////////////////
	printer << "\r\ncontent:\r\n" << parser.Content();
	auto contentOut = printer << endl;


	string apitype = parser.Url().substr(strlen(URLPREFIX));
	//const char VHOST[] = "vhost=__defaultVhost__&app=proxy&stream=0";
	string VHOST="vhost=";
	VHOST += (*lconf.begin())->strVhost;
	VHOST += "&app=";
	VHOST += (*lconf.begin())->strApp;
	VHOST += "&stream=";
	VHOST += (*lconf.begin())->strId;
	string url = MEDIASERVERURL;


	if (!apitype.compare("StartRecord/"))
	{
		url += "/index/api/startRecord?";
		url += VHOST;
		url += "&type=1";
		url += "&secret=" + mINI::Instance()["api.secret"];
		HttpGet(url, nullptr);

	}
	else if (!apitype.compare("StopRecord/"))
	{
		url += "/index/api/stopRecord?";
		url += VHOST;
		url += "&type=1";
		url += "&secret=" + mINI::Instance()["api.secret"];
		HttpGet(url, nullptr);

	}
	else if (!apitype.compare("StartRtsp/"))
	{
		url += "/index/api/addStreamProxy?";
		url += VHOST;
		url += "&enable_rtsp=";
		url += to_string((*lconf.begin())->bEanbleRtsp);
		url += "&enable_rtmp=";
		url += to_string((*lconf.begin())->bEanbleRtmp);
		url += "&enable_mp4=";
		url += to_string((*lconf.begin())->bEnableMp4);
		url += "&enable_hls=";
		url += to_string((*lconf.begin())->bEanbleHls);

		//url += "&secret=" + mINI::Instance()["api.secret"];
		//url += "&url=rtsp://admin:wangjile0@192.168.0.109";
		url += "&url=rtsp://";
		url += (*lconf.begin())->sUserName;
		url += ":";
		url += (*lconf.begin())->sPassword;
		url += "@";
		url += (*lconf.begin())->sDeviceAddress;
		HttpGet(url, nullptr);
	}
	else if (!apitype.compare("StopRtsp/"))
	{
		url += "/index/api/close_streams?";
		url += VHOST;
		url += "&force=1";
		url += "&secret=" + mINI::Instance()["api.secret"];
		HttpGet(url, nullptr);

	}
	else if (!apitype.compare("StartRecord/"))
	{

	}
	else if (!apitype.compare("StartRecord/"))
	{

	}
	else if (!apitype.compare("StartRecord/"))
	{

	}
	else if (!apitype.compare("StartRecord/"))
	{

	}
	else
	{
		return;
	}


	////////////////我们测算异步回复，当然你也可以同步回复/////////////////
	EventPollerPool::Instance().getPoller()->async([invoker, contentOut]() {
		HttpSession::KeyValue headerOut;
		//你可以自定义header,如果跟默认header重名，则会覆盖之
		//默认header有:Server,Connection,Date,Content-Type,Content-Length
		//请勿覆盖Connection、Content-Length键
		//键名覆盖时不区分大小写
		headerOut["TestHeader"] = "HeaderValue";
		invoker("200 OK", headerOut, contentOut);
		}
	);
}

void initEventListener() {
	static onceToken s_token([]() {
		NoticeCenter::Instance().addListener(nullptr, Broadcast::kBroadcastHttpRequest,
			Listener
		);
		}, nullptr);
}

void* Webmain(void* sharedptr_conf) {
	//设置退出信号处理函数
	static semaphore sem;
	signal(SIGINT, [](int) { sem.post(); });// 设置退出信号

	//设置日志
	Logger::Instance().add(std::make_shared<ConsoleChannel>());
	Logger::Instance().setWriter(std::make_shared<AsyncLogWriter>());

	//加载配置文件，如果配置文件不存在就创建一个
	loadIniConfig();
	initEventListener();

	//加载证书，证书包含公钥和私钥
	SSL_Initor::Instance().loadCertificate((exeDir() + "ssl.p12").data());
	//信任某个自签名证书
	SSL_Initor::Instance().trustCertificate((exeDir() + "ssl.p12").data());
	//不忽略无效证书证书(例如自签名或过期证书)
	SSL_Initor::Instance().ignoreInvalidCertificate(false);


	//开启http服务器
	TcpServer::Ptr httpSrv(new TcpServer());
	httpSrv->start<HttpSession>(mINI::Instance()[Http::kPort]);//默认80

	//如果支持ssl，还可以开启https服务器
	TcpServer::Ptr httpsSrv(new TcpServer());
	httpsSrv->start<HttpsSession>(mINI::Instance()[Http::kSSLPort]);//默认443

	InfoL << "你可以在浏览器输入:http://127.0.0.1/api/my_api?key0=val0&key1=参数1" << endl;

	sem.wait();
	return 0;
}

**Comment by suisou** [comment]
死锁是不是与httpSrv运行的机制相关？

**Comment by xiongziliang** [comment]
你的使用方法是错误的，ZLMediaKit是全异步的模式，你不能在ZLMediaKit的线程里面做注释操作。
现在你在ZLMediaKit事件触发线程里面做阻塞操作，那当然会影响后面的网络和定时器事件。

你要转变思想，不要阻塞编程模式

**Comment by xiongziliang** [comment]
ZLMediaKit/server/WebHook.cpp里面不是有全异步http客户端范例吗？为什么不参考？

**Comment by xiongziliang** [comment]
https://github.com/xiongziliang/ZLMediaKit/blob/master/server/WebHook.cpp#L142

**Comment by xiongziliang** [comment]
zlmediakit在测试程序里面用信号量阻塞main函数是为了防止main函数退出，从而程序退出。而且ZLMediaKit的main函数线程不做任何事情，也不是ZLMediaKit内部创建的事件线程，所以可以那么做

**Comment by urmyfaith** [comment]
> ```c++
>   requester->startRequester(url,[url,fun,bodyStr,requester,pTicker](const SockException &ex,
>                                                     const string &status,
>                                                     const HttpClient::HttpHeader &header,
>                                                     const string &strRecvBody){
>         onceToken token(nullptr,[&](){
>            //此处确保消除循环引用，回调结束后，HttpRequester可以销毁释放
>             const_cast<HttpRequester::Ptr &>(requester).reset();
>         });
>         parse_http_response(ex,status,header,strRecvBody,[&](const Value &obj,const string &err){
>             if(fun){
>                 fun(obj,err);
>             }
>             if(!err.empty()) {
>                 WarnL << "hook " << url << " " <<pTicker->elapsedTime() << "ms,failed" << err << ":" << bodyStr;
>             }else if(pTicker->elapsedTime() > 500){
>                 DebugL << "hook " << url << " " <<pTicker->elapsedTime() << "ms,success:" << bodyStr;
>             }
>         });
>     },hook_timeoutSec);
> ```

webhook里的关键点在于，HttpRequesterResult中引用了自己 `[url,fun,bodyStr,**requester**,pTicker]`
保持了对象在callback完成前不被释放。

同时，使用 onceToken保证在callback生命周期结束后，通过reset确保释放requester对象。

**Comment by suisou** [comment]
谢谢两位，终于理解了，跑起来了。

**Comment by suisou** [comment]
static void do_http_get(const string& url, const function<void(const Value&, const string&)>& fun) {
	//GET_CONFIG(float, hook_timeoutSec, Hook::kTimeoutSec);
	static float hook_timeoutSec = 10.0f;
	HttpRequester::Ptr requester(new HttpRequester);
	requester->setMethod("GET");
	//auto bodyStr = to_string(body);
	//requester->setBody(bodyStr);
	//requester->addHeader("Content-Type", getContentType(body));
	std::shared_ptr<Ticker> pTicker(new Ticker);
	requester->startRequester(url, [url, fun,  requester, pTicker](const SockException& ex,
		const string& status,
		const HttpClient::HttpHeader& header,
		const string& strRecvBody) {
			onceToken token(nullptr, [&]() {
				const_cast<HttpRequester::Ptr&>(requester).reset();
				});
			parse_http_response(ex, status, header, strRecvBody, [&](const Value& obj, const string& err) {
				if (fun) {
					fun(obj, err);
				}
				if (!err.empty()) {
					WarnL << "api " << url << " " << pTicker->elapsedTime() << "ms,failed" << err << ":" << url;
				}
				else if (pTicker->elapsedTime() > 500) {
					DebugL << "api " << url << " " << pTicker->elapsedTime() << "ms,success:" << url;
				}
				});
		}, hook_timeoutSec);
}



		
do_http_get(url, [&](const Json::Value v, const string err) {
			contentOut = "test string";//  v.toStyledString();
			});

我现在又发现问题，参考hook访问 MediaServer，但是对它的返回值处理却有问题，这个contentOut 在以上的代码中，会出现segment failt，感觉他已被销毁了。
如何 让这个代码在这个地方暂停，等待服务器返回后并处理完后，再向下走？

**Comment by suisou** [comment]
do_http_get(url, [contentOut,invoker](const Json::Value v, const string err) {

			//contentOut = "test string";//  v.toStyledString();
			string servermsg = contentOut + err+"test string";
				////////////////我们测算异步回复，当然你也可以同步回复/////////////////
			EventPollerPool::Instance().getPoller()->async([invoker, servermsg]() {
				HttpSession::KeyValue headerOut;
				//你可以自定义header,如果跟默认header重名，则会覆盖之
				//默认header有:Server,Connection,Date,Content-Type,Content-Length
				//请勿覆盖Connection、Content-Length键
				//键名覆盖时不区分大小写
				headerOut["TestHeader"] = "HeaderValue";
				invoker("200 OK", headerOut, servermsg);
				}
			);

			});

已解决。
