### ISSUE TITLE
如何实现定时对直播流进行快照截图的功能

### ISSUE THREAD

**Issue by chenxiaolei** [xiongziliang/ZLMediaKit#43]
目前是自己外部用ffmpeg定时来做这个功能, 希望内置.

**Comment by xiongziliang** [comment]
目前ZLMediaKit有rtsp、rtmp流互相转换的机制；
在转换途中会提取出相应的帧，包括H264/H265；
你可以对提取出的H264、H265的关键帧进行截屏快照。

但是这样有他的局限性，虽然ZLMediaKit可以接受任意编码格式的推流，
但是只能转换H265/H264的视频，所以并不是所有的编码格式都能提取出关键帧。

加入你的视频流都是H264编码，你可以通过截取关键帧的方式来保存截图，
但是如果是很多种类型的编码，那么建议还是采用外挂FFmpeg方式来截屏。

外挂FFmpeg方式虽然性能不怎么好，截屏速度也慢，但是好处是灵活，
跟你的程序解耦，并且就是FFmpeg崩溃了也不影响你流媒体服务器的稳定性。

综合考虑，还是建议你采用目前这种方案。
