### ISSUE TITLE
rtsp推到rtmp

### ISSUE THREAD

**Issue by jyy1082** [xiongziliang/ZLMediaKit#5]
看着很强大！请问有没有基于这个项目，能在linux下，将rtsp推到rtmp的脚本执行文件呢？谢谢！

**Comment by xiongziliang** [comment]
目前不支持rtsp推流协议 只支持rtmp推流

**Comment by xiongziliang** [comment]
你可以拉个rtsp的流然后把他用rtmp的方式推流到你的服务器上

**Comment by zhanjx1314** [comment]
rtsp 推模式没有实现?

**Comment by commshare** [comment]
请问  test_server.cpp 支持拉rtsp转rtmp么？

**Comment by xiongziliang** [comment]
@zhanjx1314 目前不支持rtsp推流

**Comment by xiongziliang** [comment]
@commshare 支持

**Comment by xiongziliang** [comment]
现在已经支持rtsp推流了
