### ISSUE TITLE
您好,有几个问题需要咨询下

### ISSUE THREAD

**Issue by alexliyu7352** [xiongziliang/ZLMediaKit#6]
1. 使用test_server测试,发现无论使用输出的hls还是rtmp还是rtsp都会一卡一卡的, 并且声音会爆音.这是我这里的问题还是程序的问题呢?
2. 如何做vod呢?我看示例里面并没有vod, 但是代码里面应该是支持的.可否给个例子呢?
3. 代码里面打开了UDP服务器, 应该是支持rtp的, 但是我发现没办法访问rtp呢.
4. 如何设置proxy的缓冲时间?, 比如预先缓冲30秒的内容这样客户端播放不会卡.
5. 如何进行录制呢?
6. 文档有写配置文件热更新, 可是我发现我修改配置文件后并不会触发热更新.代码我还没有仔细看.
应该是监控文件读写是么?当发现文件读了就进行更新?

**Comment by xiongziliang** [comment]
1. 你是否用的最新的代码?最新的代码在处理rtmp推流和拉流代理时会直接覆盖时间戳(也就是根据服务器接受到数据时的系统时间戳生成一个平滑处理过的时间戳).从我实践经验来看,这个生成的时间戳是可以保证平滑播放的,如果你那里播放卡顿,有可能是你推流时丢失了部分音频数据,因为音频播放速度是匀速的,时间戳不平滑并不会导致声音卡顿或者爆音.

2.你说的vod是点播还是录像?目前ZLMediaKit支持录制为MP4,同时也支持了rtmp/rtsp方式点播MP4文件.

3.通过RTSP over UDP的方式访问,VLC默认此方式.

4.ZLMediaKit接收数据是异步的,能以最快的速度接收数据并写入环形缓冲,环形缓冲大小为一个GOP数据长度,如果客户端在播放ZLMediaKit的流时网速很慢,那么ZLMediaKit将会最多缓存5秒的数据,当然你可以设置这个时间长度.

5.目前ZLMediaKit默认关闭录制功能,你可以通过修改代码来实现,如果你确实想这么做我会告诉你一个最简单的实现方式.

6.修改配置文件后请执行 killall -1 pid 来让ZLMediaKit重新加载配置文件.

**Comment by alexliyu7352** [comment]
感谢回复.
1. 我用的是最新的代码, 并且只是测试了下你写的test server, 输出不论是hls还是rtmp或者rtsp都会一顿一顿的, 声音会爆音
2. 我说的vod是指的可以加载本地或者远程的mp4文件, 好像rtsp的点播mp4不起作用啊,
比如rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov这个你的示例的应该是vod, 但是使用proxyplayer拉流过来,仍旧是当作直播处理了
4. 请告知下如何的设置这个时间长度, 因为客户端网络使用移动网络的话那么速度肯定是追不上的, 所以需要服务器缓存时间长一些.
5. 请告知如何实现录制功能, 因为有这个需要可以按照条件录制
6. 感谢, 这个reload的方式看起来和srs是一样的.

**Comment by xiongziliang** [comment]
1.经证实这个问题可能是你那边环境的问题
2.目前拉流代理都是生成直播流
3.你可以修改ZLToolKit/src/Network/Socket.h,里面的宏SEND_BUF_MAX_SEC来实现，或者你修改ZLMediaKit的代码，调用Socket::setSendBufSecond方法
4.拉流录制，你可以修改PlayerProxy构造函数的bEnableMp4参数来实现，Rtmp推流录制你可以修改RtmpToRtspMediaSource的构造参数实现

**Comment by alexliyu7352** [comment]
如何修改拉流代理生成VOD点播流?主要是切成hls是vod的.
