### ISSUE TITLE
您好，如果用vidoejs播放要如何配置？

### ISSUE THREAD

**Issue by hqsam** [xiongziliang/ZLMediaKit#7]
现在我rtmp推流上去，用vlc potplayer播放没有问题，不过我在网页端播放，可以一直没成功，我把videojs播放的html放在了httpRoot\__defaultVhost__目录下，能打开页面但是看不了流,要怎么配置才能在网页端看rtmp直播？ 谢谢

**Comment by xiongziliang** [comment]
你是用videojs播放rtmp吗? 你编译ZLMediaKit时有没有开启openssl? flash播放rtmp使用的是所谓的复杂握手,如果你没开启openssl,那么ZLMediaKit会采用简单握手的处理方式处理flash的请求,这样flash就没法播放了

**Comment by xiongziliang** [comment]
请查看次issue： #16
