### ISSUE TITLE
您好，如果用vidoejs播放要如何配置

### ISSUE THREAD

**Issue by hqsam** [xiongziliang/ZLMediaKit#8]
您好，根据您的指导 这次我打开了openssl 现在flash在网页端是可以播放的，不过videojs还是播放不了？这个还要怎么修改吗

**Comment by xiongziliang** [comment]
能把无法播放的服务器log发给我看看吗?另外抓个包让我分析下.
你可以加入qq技术群 我们方便沟通

**Comment by hqsam** [comment]
感觉是服务器没有响应浏览器刷新，他不知道浏览器刷新后要重传。具体情况是这样的，用videojs 在edge和ie都不能播放，但是在chrome上开始报这样的错VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. MediaError {code: 4, message: "No compatible source was found for this media."}
后来通过设置此网站始终允许flash后，第一次能看到画面，可是刷新页面，则画面没有了，直到关闭浏览器后再次打开浏览器和播放页面又能看。刷新后还是不行。  所以对于videojs播放，怀疑是服务器没有响应浏览器刷新，他不知道浏览器刷新后要重传。另外，videojs在edge 和ie下这种方式也不能播放。 但是用nginx-rtmp 服务器videojs 在chrome edge ie下没有任务问题。

服务器log如下：
[33m2018-06-26 10:09:40 [warn] async wake up main thread take time:18[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:10:25 [warn] async wake up main thread take time:18[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:11:16 [warn] async wake up main thread take time:6[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:11:16 [warn] async wake up main thread take time:6[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:11:21 [warn] async wake up main thread take time:7[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:11:21 [warn] async wake up main thread take time:7[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 54
[32m2018-06-26 10:12:07 [debug] onError end of file[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 50
[32m2018-06-26 10:12:07 [debug] ~RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 46
[32m2018-06-26 10:12:07 [debug] RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 396
[36m2018-06-26 10:12:07 [info] check_C1_Digest check rtmp complex handshark success![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 340
[36m2018-06-26 10:12:07 [info] handle_C1_complex schema0[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 672
[34m2018-06-26 10:12:07 [trace] handle_rtmpChunk MSG_WIN_SIZE:5000000[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 406
[34m2018-06-26 10:12:07 [trace] onProcessCmd can not support cmd:FCSubscribe[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\tests\test_server.cpp 121
[36m2018-06-26 10:12:07 [info] operator() rtmp __defaultVhost__ live 0 [0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 54
[32m2018-06-26 10:12:13 [debug] onError end of file[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 50
[32m2018-06-26 10:12:13 [debug] ~RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:12:13 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:12:13 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 46
[32m2018-06-26 10:12:14 [debug] RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 396
[36m2018-06-26 10:12:14 [info] check_C1_Digest check rtmp complex handshark success![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 340
[36m2018-06-26 10:12:14 [info] handle_C1_complex schema0[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 672
[34m2018-06-26 10:12:14 [trace] handle_rtmpChunk MSG_WIN_SIZE:5000000[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 406
[34m2018-06-26 10:12:14 [trace] onProcessCmd can not support cmd:FCSubscribe[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\tests\test_server.cpp 121
[36m2018-06-26 10:12:14 [info] operator() rtmp __defaultVhost__ live 0 [0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:12:17 [warn] async wake up main thread take time:18[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:12:17 [warn] async wake up main thread take time:18[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:12:17 [warn] async wake up main thread take time:18[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:12:17 [warn] async wake up main thread take time:22[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:12:17 [warn] async wake up main thread take time:24[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:12:19 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:12:19 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:12:19 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 54
[32m2018-06-26 10:12:21 [debug] onError end of file[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 50
[32m2018-06-26 10:12:21 [debug] ~RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:12:27 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:12:27 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:12:27 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:12:27 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:12:27 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:12:46 [warn] async wake up main thread take time:10[0m





[33m2018-06-26 10:18:24 [warn] async wake up main thread take time:6[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:18:24 [warn] async wake up main thread take time:6[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:18:24 [warn] async wake up main thread take time:6[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:18:24 [warn] async wake up main thread take time:12[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:18:55 [warn] async wake up main thread take time:22[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:19:11 [warn] async wake up main thread take time:22[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:19:42 [warn] async wake up main thread take time:9[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 46
[32m2018-06-26 10:20:31 [debug] RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 396
[36m2018-06-26 10:20:31 [info] check_C1_Digest check rtmp complex handshark success![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 340
[36m2018-06-26 10:20:31 [info] handle_C1_complex schema0[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 672
[34m2018-06-26 10:20:31 [trace] handle_rtmpChunk MSG_WIN_SIZE:5000000[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 406
[34m2018-06-26 10:20:31 [trace] onProcessCmd can not support cmd:FCSubscribe[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\tests\test_server.cpp 121
[36m2018-06-26 10:20:31 [info] operator() rtmp __defaultVhost__ live 0 [0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:20:37 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:20:37 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:20:37 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:20:37 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:20:37 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 54
[32m2018-06-26 10:20:43 [debug] onError unknown error[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 50
[32m2018-06-26 10:20:43 [debug] ~RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 46
[32m2018-06-26 10:20:43 [debug] RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 396
[36m2018-06-26 10:20:43 [info] check_C1_Digest check rtmp complex handshark success![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 340
[36m2018-06-26 10:20:43 [info] handle_C1_complex schema0[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 672
[34m2018-06-26 10:20:43 [trace] handle_rtmpChunk MSG_WIN_SIZE:5000000[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 406
[34m2018-06-26 10:20:43 [trace] onProcessCmd can not support cmd:FCSubscribe[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\tests\test_server.cpp 121
[36m2018-06-26 10:20:43 [info] operator() rtmp __defaultVhost__ live 0 [0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 54
[32m2018-06-26 10:20:44 [debug] onError end of file[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 50
[32m2018-06-26 10:20:44 [debug] ~RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 46
[32m2018-06-26 10:20:45 [debug] RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 396
[36m2018-06-26 10:20:45 [info] check_C1_Digest check rtmp complex handshark success![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 340
[36m2018-06-26 10:20:45 [info] handle_C1_complex schema0[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 672
[34m2018-06-26 10:20:45 [trace] handle_rtmpChunk MSG_WIN_SIZE:5000000[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 406
[34m2018-06-26 10:20:45 [trace] onProcessCmd can not support cmd:FCSubscribe[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\tests\test_server.cpp 121
[36m2018-06-26 10:20:45 [info] operator() rtmp __defaultVhost__ live 0 [0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:20:49 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:20:49 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:20:49 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:20:49 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:20:49 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:20:51 [warn] async wake up main thread take time:7[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\ZLToolKit\src\Poller\EventPoller.cpp 220
[33m2018-06-26 10:20:53 [warn] async wake up main thread take time:10[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 54
[32m2018-06-26 10:20:57 [debug] onError end of file[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 50
[32m2018-06-26 10:20:57 [debug] ~RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 46
[32m2018-06-26 10:20:58 [debug] RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 396
[36m2018-06-26 10:20:58 [info] check_C1_Digest check rtmp complex handshark success![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 340
[36m2018-06-26 10:20:58 [info] handle_C1_complex schema0[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 672
[34m2018-06-26 10:20:58 [trace] handle_rtmpChunk MSG_WIN_SIZE:5000000[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 406
[34m2018-06-26 10:20:58 [trace] onProcessCmd can not support cmd:FCSubscribe[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\tests\test_server.cpp 121
[36m2018-06-26 10:20:58 [info] operator() rtmp __defaultVhost__ live 0 [0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 54
[32m2018-06-26 10:20:58 [debug] onError end of file[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 50
[32m2018-06-26 10:20:58 [debug] ~RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 46
[32m2018-06-26 10:20:59 [debug] RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 396
[36m2018-06-26 10:20:59 [info] check_C1_Digest check rtmp complex handshark success![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 340
[36m2018-06-26 10:20:59 [info] handle_C1_complex schema0[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 672
[34m2018-06-26 10:20:59 [trace] handle_rtmpChunk MSG_WIN_SIZE:5000000[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 406
[34m2018-06-26 10:20:59 [trace] onProcessCmd can not support cmd:FCSubscribe[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\tests\test_server.cpp 121
[36m2018-06-26 10:20:59 [info] operator() rtmp __defaultVhost__ live 0 [0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 54
[32m2018-06-26 10:20:59 [debug] onError end of file[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 50
[32m2018-06-26 10:20:59 [debug] ~RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 46
[32m2018-06-26 10:20:59 [debug] RtmpSession 192.168.1.117[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 396
[36m2018-06-26 10:20:59 [info] check_C1_Digest check rtmp complex handshark success![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 340
[36m2018-06-26 10:20:59 [info] handle_C1_complex schema0[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpProtocol.cpp 672
[34m2018-06-26 10:20:59 [trace] handle_rtmpChunk MSG_WIN_SIZE:5000000[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Rtmp\RtmpSession.cpp 406
[34m2018-06-26 10:20:59 [trace] onProcessCmd can not support cmd:FCSubscribe[0m
test_server.exe(17284) D:\project\git\ZLMediaKit\tests\test_server.cpp 121
[36m2018-06-26 10:20:59 [info] operator() rtmp __defaultVhost__ live 0 [0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:21:03 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:21:03 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:21:05 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:21:05 [warn] onManager HttpSession timeouted![0m
test_server.exe(17284) D:\project\git\ZLMediaKit\src\Http\HttpSession.cpp 181
[33m2018-06-26 10:21:05 [warn] onManager HttpSession timeouted![0m

**Comment by xiongziliang** [comment]
#16
